### ISSUE TITLE
Attempted import error: 'MapControl' is not exported from 'react-leaflet'

### ISSUE THREAD

**Issue by sahin52** [PaulLeCam/react-leaflet#1000]
Hey, I am trying to upgrade react-leaflet from 2.5.0 to 4.0, and I am getting this error. Is there a new name for MapControl? Is there a workaround to use this. I don't want to change everything in the project.  
And there is a stackoverflow question about this: https://stackoverflow.com/questions/64678752/attempted-import-error-mapcontrol-is-not-exported-from-react-leaflet

**Comment by PaulLeCam** [comment]
No new name but different APIs, hence the major version changes.
See https://react-leaflet.js.org/docs/core-introduction/ for guidelines on creating custom components.
