### ISSUE TITLE
createControlComponent() has no updateInstance argument

### ISSUE THREAD

**Issue by superelitist** [PaulLeCam/react-leaflet#1002]
One of [Leaflet's own tutorials](https://leafletjs.com/examples/choropleth/) details how to extend a custom control to display information on a map, with positioning handled by Leaflet. Updating a control thus seems like functionality that should be supported by `createControlComponent()`.

**Comment by PaulLeCam** [comment]
There's no update method on Leaflet's `Control` class, the tutorial adds custom methods to the control that are specific to the example.
