### ISSUE TITLE
vite: Module 'react-leaflet' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.ts(1471)

### ISSUE THREAD

**Issue by mikeimrsv** [PaulLeCam/react-leaflet#1003]
## Bug report in v4

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

It appears the latest version of react leaflet (as of this ticket, that's v4.0.1) doesn't support interfacing with Typescript's "NodeNext" moduleResolutions strategy.

### Expected  behavior

Typescript should compile and recognize react-leaflet

### Actual behavior

Typescript returns the following error:

```
src/App.tsx:2:30 - error TS1471: Module 'react-leaflet/MapContainer' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.

2 import { MapContainer } from 'react-leaflet/MapContainer';
...same error for the other imports
```

### Steps to reproduce

System:
node v.16.13.1
yarn 1.22.10

1.  ```git clone https://github.com/mikeimrsv/react-leaflet-vite-problem.git```
2. ```cd react-leaflet-vite-problem```
3. ```yarn install && yarn tsc```

The quick fix is to change `tsconfig.json`'s `moduleResolution` from `NodeNext` to `Node`, and then change the imports to
```jsx
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
```
But as per [this announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs) we should probably move to support NodeNext as it improves the module resolution speed of various frameworks such as vite.

What confuses me is that the latest react-leaflet source code appears to adhere to proper ES module definition. In fact, not too long ago UMD and CommonJS was removed.  So I'm unsure exactly what is required to support NodeNext.  I attempted to load modules asynchronously too (like `const MapContainer = await import(...`) but then typescript cannot infer anything from those modules.  Not sure if this is the import syntax I'm supposed to be changing, but this is based on the bug report template.

**Comment by CarlosBalladares** [comment]
your probably need to add this to your package.json
```
"type": "module"
```

**Comment by loanburger** [comment]
I have a similar issue when running my tests for any component that uses the MapContainer:

```
    C:\GIT\strava-react-app\project\node_modules\react-leaflet\lib\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { useMap, useMapEvent, useMapEvents } from './hooks.js';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | /* eslint-disable camelcase */
      2 | /* eslint-disable @typescript-eslint/naming-convention */
    > 3 | import { MapContainer } from 'react-leaflet';
        | ^
      4 | import 'leaflet/dist/leaflet.css';
      5 | import { useEffect } from 'react';
      6 | import { IStravaActivity } from 'src/models';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
```

**Comment by PaulLeCam** [comment]
The TypeScript configuration is up to your setup, React Leaflet's `package.json` contains `"type": "module"` which signals how compilers/bundlers should treat the code.

**Comment by alioune-badara-fam** [comment]
Remove `"type": "module"` from `package.json`

**Comment by albjeremias** [comment]
I don't get this.. i never had such problem with any package... what do I have to do?
