### ISSUE TITLE
Map resets its zoom after closing the marker popup

### ISSUE THREAD

**Issue by Glebka** [PaulLeCam/react-leaflet#1006]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

When closing popup with X button - the map doesn't reset zoom

### Actual behavior

When closing popup with X button - the map does reset zoom

### Steps to reproduce

1. Open https://react-leaflet.js.org/
2. Scroll down the page to the map example
3. Zoom in or zoom out several times
4. Click on marker
5. Click on X button on the popup
6. Observe that map did reset zoom

**Comment by pyrozhok** [comment]
Same here. It redirects to #close and cause a rerender. This bug is really annoying.

<img width="537" alt="leaflet-marker-close" src="https://user-images.githubusercontent.com/5194872/178540100-f2f87b8c-40fb-4fa2-add2-c92f941c0f15.png">
.

**Comment by PaulLeCam** [comment]
This is Leaflet's behavior, not something caused by React Leaflet.
