### ISSUE TITLE
Support custom control containers

### ISSUE THREAD

**Issue by davetapley** [PaulLeCam/react-leaflet#1008]
This issue would be more compelling if ⬇️ was merged, but I wanted to document while it's in my head.

- https://github.com/Leaflet/Leaflet/pull/4518

Per the comment there:
> This update allows a control to be added to the map even if it does not fall into one of the 4 control corner containers.
When a control is added without a defined corner container, the map will now append the control after the existing corner containers allowing for custom containers to be added to the map.

This is actually already 'supported' if you are prepared to just attach a portal to `.leaflet-control-container`, but as https://github.com/Leaflet/Leaflet/pull/4518 proposes it would probably be nicer if it was 'officially' supported.

---

For `react-leaflet` specifically we already use [`type ControlOptions`](https://github.com/PaulLeCam/react-leaflet/blob/1b6846de786c19ce70d8514c174b9bd020fd647f/packages/core/src/control.ts#L1-L14),
that gives a `position` which [can already be `undefined`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80633f89f944975e99a53821251685f4d94a0530/types/leaflet/index.d.ts#L1423-L1425).

So from a type signature perspective the use case in https://github.com/Leaflet/Leaflet/pull/4518 already 'appears' to be be supported,
but AFAICT isn't supported by `react-leaflet` yet.

Is that assumption correct? And if so is it something which could be supported?

**Comment by PaulLeCam** [comment]
Once it's supported by Leaflet it can be added to React Leaflet, please fell free to open a PR when it's the case.
