### ISSUE TITLE
React v18 executes useMap() hook twice, causing double loading of controls in MapContainer

### ISSUE THREAD

**Issue by manuelpoelzl** [PaulLeCam/react-leaflet#1011]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

The hook should be called once, and components in the MapContainer should be rendered once.

### Actual behavior
The GeoCoder control is rendered twice, according to react devtools because the map is initialized twice.

This problem does not occur in the fully deployed production version.

### Steps to reproduce
StackBlitz didn't work for me, so I cloned the sample in Codesandbox:
https://codesandbox.io/s/xenodochial-water-bfc7gp?file=/src/App.js

Additionally, here is a picture of the duplicate geocoders as reproduced in the sample above.
![Screenshot_1](https://user-images.githubusercontent.com/46539758/180847358-93326d94-97c9-4a78-bd4f-d9dbd6e4811a.png)

**Comment by manuelpoelzl** [comment]
This can be fixed by storing the geocoder control inside a ref, and removing the control in the cleanup function inside the useEffect hook which adds the control to the map.

**Comment by plamenh** [comment]
Would you share directions on how exactly to fix this? I can see your explanation, but it speaks nothing to me, as I am not quite versed in the internal workings of react-leaflet.
