### ISSUE TITLE
Type '{ type: "Point"; coordinates: number[]; }' is not assignable to type 'GeoJsonObject'.

### ISSUE THREAD

**Issue by asamad-hitachi** [PaulLeCam/react-leaflet#1015]
HI
I am trying to implement geojson with react-leaflet in a react app with typescript.

Following are the version details

leaflet@1.7.1
react-leaflet@3.2.2 
react@16.14.0
typescript@3.9.9

Created a map component in react source code.

Sample code for reference 

import { MapContainer, GeoJSON } from "react-leaflet";

const MapComponent  = (props) => {
return (
<MapContainer
                
                id="map"
                center={props.mapCenter}
                zoom={7}
            >
            <TileLayer
                    attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                    url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                />
                
                <GeoJSON
                    data={{
                        "type": "Point",
                        "coordinates": [30.0, 10.0]
                    }}
                    onEachFeature={(feature)=>console.log(feature)}
                />
                
 </MapContainer>
)
}

export default MapComponent;

**Output**: 
TypeScript error in ~/src/components/Map/index.tsx(837,25):
Type '{ type: "Point"; coordinates: number[]; }' is not assignable to type 'GeoJsonObject'.
  Object literal may only specify known properties, and '"coordinates"' does not exist in type 'GeoJsonObject'.  TS2322

                     data={{
                            "type": "Point",
                                "coordinates": [30.0, 10.0]
                                ^
                   }}
                       onEachFeature={onEachGeoJSONFeature}
                 />
                 
                 
Please provide me any suggestions to what I can do to implement correct GeoJsonObject structure.
Thanks in advance

**Comment by PaulLeCam** [comment]
These are types defined by `@types/leaflet`, you should open an issue in the relevant repository if you think they are incorrect.
