### ISSUE TITLE
Marker icon property cant be undefined

### ISSUE THREAD

**Issue by neronim1141** [PaulLeCam/react-leaflet#1016]
## Bug report in v4

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Marker icon property if set to undefined should have the same bahaviour as not setting that property.

### Actual behavior

It is throwing "TypeError: Cannot read properties of undefined (reading 'createIcon')"

### Steps to reproduce

https://stackblitz.com/edit/react-leaflet-v4-jdvixf?file=src%2FApp.js

**Comment by PaulLeCam** [comment]
This is Leaflet's behavior, you should open an issue in the relevant repository if you think it's a bug.
