### ISSUE TITLE
Core-Api: removing a layer with conditional rendering doesn't work

### ISSUE THREAD

**Issue by ffischer1984** [PaulLeCam/react-leaflet#1018]
I've used the [core-api-guide](https://react-leaflet.js.org/docs/core-introduction/) to write a layer.
I've this structure:

```
const selectedIds = useState([2])
<MapComponent>
   {
                            selectedIds.length > 0 &&
                            selectedIds.map(id => {
                                return <ProjectLayer key={id} id={id}/>
                            })
                        }
</MapContainer>


```
adding a second Layer works perfectly fine on runtime but removing will not be displayed on the map. Have anyone an idea what i could possibly made wrong or is it a bug. The array is also refreshing. That was my first idea.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
