### ISSUE TITLE
How to set the AttributionControl's prefix?

### ISSUE THREAD

**Issue by mojodna** [PaulLeCam/react-leaflet#102]
In raw Leaflet, this would look like:

```javascript
this.map.attributionControl.setPrefix("");
```

(It hides the "Leaflet |" prefix when displaying attribution.)

**Comment by PaulLeCam** [comment]
https://github.com/PaulLeCam/react-leaflet#components

**Comment by mojodna** [comment]
For straight-up attribution changes, passing options as props works great. However, for the attribution prefix, it's not enough to set `options.attributionControl.prefix: ""` (which would need to be passed as `<Map ... {...{"attributionControl.prefix": ""}} />`, if I'm understanding things right). ([`attributionControl` is a boolean](http://leafletjs.com/reference.html#map-attributioncontrol) and is a bit too much of a hammer.)

**Comment by PaulLeCam** [comment]
No you can't set nested options like this in the properties, but as stated in the documentation, you can access Leaflet's map instance using `getLeafletElement()` on the Map component.

**Comment by derwaldgeist** [comment]
How exactly does this work?

**Comment by MattSidor** [comment]
I'm struggling with this. My `<TileLayer>` element has an `attribution` value, but I want to hide the default "Leaflet" prefix. I can create an `<AttributionControl>` element with `prefix={false}`, but that just creates a duplicate attribution.

Example:

    render() {
      const position = [this.state.lat, this.state.lng];
      return (
        <ReactLeafletMap
          center={position}
          zoom={this.state.zoom}
          zoomControl={false}
        >
          <TileLayer
            attribution="[attribution text]"
            url="[tile url]"
          />
          <AttributionControl position="bottomright" prefix={false} />
        </ReactLeafletMap>
      );
    }

Screenshot (two attributions, one without the "Leaflet" prefix):

![screen shot 2018-02-05 at 1 35 44 pm](https://user-images.githubusercontent.com/6138182/35827508-85254a84-0a79-11e8-8387-fbf57f5a47bf.png)

@mojodna, I am curious, were you able to find a good solution for removing the prefix via these React components?

**Comment by mojodna** [comment]
@MattSidor no, i end up embedding Leaflet directly in my own components instead since I'm not doing anything complicated (or if I am, it's a weird fit with this plugin).

**Comment by MattSidor** [comment]
I figured it out!

Declare `attributionControl={false}` in the parent `<ReactLeafletMap>` component to disable to default attribution, then create a new `<AttributionControl>` component with `prefix={false}`, like so:

    render() {
      const position = [this.state.lat, this.state.lng];
      return (
        <ReactLeafletMap
          center={position}
          zoom={this.state.zoom}
          zoomControl={false}
          attributionControl={false}
        >
          <TileLayer
            attribution="[attribution text]"
            url="[tile url]"
          />
          <AttributionControl position="bottomright" prefix={false} />
        </ReactLeafletMap>
      );
    }

The actual attribution text, minus the prefix, is still declared in the `attribution` property of the `<TileLayer>` component.

**Comment by StephanGeorg** [comment]
Should be 
```
<AttributionControl position="bottomright" prefix=""} />
```
otherwise

> Failed prop type: Invalid prop `prefix` of type `boolean` supplied to `AttributionControl`, expected `string`.

**Comment by jmlord** [comment]
If leaflet is in an iframe, and you want to set the attribution `_blank` or `_top`, the `AttributionControl` part of @MattSidor  's answer can be adapted like this:

``` js
      <AttributionControl position="bottomright" prefix='
        <a href="https://leafletjs.com" title="A JavaScript library for interactive maps" target="_blank" rel="noopener noreferrer">
          <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="12" height="8" viewBox="0 0 12 8" class="leaflet-attribution-flag"><path fill="#4C7BE1" d="M0 0h12v4H0z"></path><path fill="#FFD500" d="M0 4h12v3H0z"></path><path fill="#E0BC00" d="M0 7h12v1H0z"></path></svg> Leaflet
        </a>'
      />
```
