### ISSUE TITLE
Suggestion to Improve documentation on the marker problem

### ISSUE THREAD

**Issue by ndrean** [PaulLeCam/react-leaflet#1021]
I spend quite some time searching. Maybe just append the following to the documentation?

```js
import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';

let DefaultIcon = L.icon({
    iconUrl: icon,
    shadowUrl: iconShadow
});

L.Marker.prototype.options.icon = DefaultIcon;
```

**Comment by fdemir** [comment]
i think it's not a react-leaflet concern. you can look up the leaflet's documentation for this type of things.

**Comment by ndrean** [comment]
Ok. I don't know one person who started using react-leaflet who didn't bump into this problem so indeed, you are absolutely right, they should just start using directly Leaflet to save time.
