### ISSUE TITLE
typescript failed to compile on nextjs

### ISSUE THREAD

**Issue by juandans01** [PaulLeCam/react-leaflet#1025]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using the latest version of React and ReactDOM v18.
- [X] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

On nextjs build should finish as expected

### Actual behavior
Getting this log from nextjs build process

this are the versions i'm working with
react: 18.2.0
react-leaflet: 4.0.2
react-dom: 18.2.0
leaflet: 1.8.0

any help is appreciated,
thanks

`
info  - Checking validity of types ...Failed to compile.

./node_modules/@react-leaflet/core/lib/component.d.ts:1:22
Type error: ',' expected.

> 1 | import React, { type MutableRefObject, type ReactNode } from 'react';
    |                      ^
  2 | import type { DivOverlay, DivOverlayHook } from './div-overlay.js';
  3 | import type { LeafletElement } from './element.js';
  4 | declare type ElementHook<E, P> = (props: P) => MutableRefObject<LeafletElement<E>>;

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/juan/code/tellaweb-frontend/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/home/juan/code/tellaweb-frontend/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}

`
Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this StackBlitz](https://stackblitz.com/edit/react-leaflet-v4?file=src/App.js).

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
