### ISSUE TITLE
Using eventhandlers with WMSTileLayer adds a bad param to request URLs

### ISSUE THREAD

**Issue by joeberkovitz** [PaulLeCam/react-leaflet#1029]
## Bug report in v4

(Issue checklist passed in full.)

### Expected behavior

Loading a WMSTileLayer with an `eventHandlers` property should not result in a different WMS request URL than would have been issued without the event handlers map.

### Actual behavior

When an event handler map is supplied to a WMSTileLayer component, WMS request URLs include this key/value pair:
`eventHandlers=%5Bobject%20Object%5D`

### Steps to reproduce

The following example illustrates the problem: the map displayed is grayed out because no tiles can be loaded due to the extra param included in the URL. Delete the `eventHandlers` property and the map will appear properly.

```js
import React, { StrictMode } from 'react';
import { MapContainer } from 'react-leaflet/MapContainer';
import { Marker } from 'react-leaflet/Marker';
import { Popup } from 'react-leaflet/Popup';
import { WMSTileLayer } from 'react-leaflet/WMSTileLayer';

function SimpleExample(props) {
  return (
    <StrictMode>
      <MapContainer center={props.position} zoom={9}>
      <WMSTileLayer 
          eventHandlers={{add: () => console.log('added')}}
          attribution="&copy; Copyright NOAA."
          url="https://devgis.charttools.noaa.gov/arcgis/rest/services/POD/NCC_1081/MapServer/exts/MaritimeChartService/WMSServer"
          minZoom={9}
          maxZoom={15}
        />

        <Marker position={props.position}>
          <Popup>
            A pretty CSS3 popup. <br /> Easily customizable.
          </Popup>
        </Marker>
      </MapContainer>
    </StrictMode>
  );
}

export default function App() {
  return <SimpleExample position={{ lat: 42., lng: -70.0 }} />;
}
```

This appears to be similar in spirit to the now-closed https://github.com/PaulLeCam/react-leaflet/issues/373

**Comment by PaulLeCam** [comment]
Thanks for reporting this, it should be fixed in v4.1.0, please try it out!
