### ISSUE TITLE
How to use ref in Class Component

### ISSUE THREAD

**Issue by rcaner** [PaulLeCam/react-leaflet#1030]
### Expected behavior

Hey Paul,

I've a question about the migration to v4 from v3. We are using whenCreated callback to get map instance. 
In v4, we couldn't find a callback to get a map instance. We have ref object but  in whenReady callback event ref object is null.
Which I need is a callback when the ref is set to L.Map instance.

### Actual behavior
ref.current is null.
Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this StackBlitz](https://stackblitz.com/edit/react-leaflet-v4?file=src/App.js).
          <MapContainer
            id="map"
            bounds={bounds as LatLngBoundsExpression}
            maxZoom={25}
            minZoom={5}
            zoomControl={false}
            zoom={10}
            zoomDelta={1}
            zoomSnap={0.25}
            crs={L.CRS.EPSG3857}
            wheelPxPerZoomLevel={300}
            wheelDebounceTime={100}
            fadeAnimation={false}
            doubleClickZoom={false}
            ref={this.mapRef}
            whenReady={() => {
              if(this.mapRef.current) {
                this.setState(
                  {
                    mapContext: {
                      map: this.mapRef.current,
                      mapType: "leaflet",
                      addEditPolygon: this.addEditPolygon,
                      clearEditPolygons: this.clearEditPolygons,
                      changeBaseLayer: this.changeBaseLayer,
                      editPolygonStart: this.editPolygonStart,
                      editPolygonsStart: this.editPolygonsStart,
                      tileload: tileload,
                      undoDraw: this.undoDraw,
                    },
                  },
                  () => {
                    this.mapLoaded();
                  }
                );
              }
            }}
          />

**Comment by rcaner** [comment]
I solved it by state. variable. But I'm not sure is it the best way or not.

In when ready callback, a flag sets true. And In render method, this flag checks and map context sets the state variable after that flag should be set to null. (Not needed to update again )

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
