### ISSUE TITLE
Racecondition mouseover and mouseout

### ISSUE THREAD

**Issue by ludvikbrodl** [PaulLeCam/react-leaflet#1031]
Perhaps I am doing something wrong but it's possible to end up in a state where a Polylines mouseout does not get triggered when moving the mouse quickly around the map.

This also happens when the mouse is static but the map is moving around with a flyTo call.

Sandbox where it can be reproduced
https://codesandbox.io/s/react-18-playground-forked-c45o38?file=/src/App.tsx

Video of it happening 
[screen-capture (1).webm](https://user-images.githubusercontent.com/3493658/191008658-a7392219-7055-4183-8630-e191d1e622fb.webm)

My best guess is that when moving the mouse quickly the mouse leaves the polygon as it's being rerenderd thus not registering the mouseout event?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
