### ISSUE TITLE
Circle component has no prop `radius` in >=4.1.0

### ISSUE THREAD

**Issue by Audiopolis** [PaulLeCam/react-leaflet#1034]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Using TypeScript...

```jsx
<Circle radius={radius} center={center}>Hello</Circle>
```

should work.

### Actual behavior

```
Type '{ children: Element; radius: number; center: LatLngLiteral; }' is not assignable to type 'IntrinsicAttributes & CircleProps & RefAttributes<Circle<any>>'.
  Property 'radius' does not exist on type 'IntrinsicAttributes & CircleProps & RefAttributes<Circle<any>>'.
```

`radius` is no longer recognized as an attribute in 4.1.0 and later.

### Steps to reproduce

1. Start a project using TypeScript and following dependencies:

```
    "leaflet": "^1.8.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-leaflet": "4.1.0",
```

2. Render ```<Circle radius={radius} center={center}>Hello</Circle>```
3. See TypeScript error on `radius`
4. Downgrade `react-leaflet` to `<4.1.0`
5. Error disappears

**Comment by Audiopolis** [comment]
Should also point out that the issue persists with leaflet 1.9.2.

**Comment by argo1** [comment]
@types/leaflet must be at least 1.8.0. For me it helped to remove lock file and reinstall.
