### ISSUE TITLE
Provide guidelines about migrating from v2 to v4 (or 3) in the documentation

### ISSUE THREAD

**Issue by januszm** [PaulLeCam/react-leaflet#1035]
Other issue/Feature request related to this project (not plugins).

It'd be incredibly helpful to include in the documentation tips on how to replace elements that were used in version 2, e.g. `Path`, that were removed in most recent versions. Currently I am adapting to v4 a project built in v2 which used a very useful plugin (geojson-patterns). Unfortunately, that plugin has not been developed for a long time. However, it seems to be relatively easy to adapt to v4, in fact the last thing missing is replacing import `Path`.

Probably in a few other cases, either people's projects or plugins, documentation on migration from v2 to modern ReactLeaflet v3 and v4 would be useful. Especially that many commonly used programming libraries include such guidelines, whether on the Github Wiki pages or on the project's web site.

**Comment by MrPoint1400** [comment]
+1
