### ISSUE TITLE
Tooltip throws Cannot set properties of null (setting '_source') 

### ISSUE THREAD

**Issue by ndavidson-manticore** [PaulLeCam/react-leaflet#1036]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [✔️  ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [✔️  ] Using the latest version of React and ReactDOM v18.
- [✔️ ] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [✔️  ] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [✔️  ] The issue has not already been reported.
- [✔️  ] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [✔️  ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

The leaflet tooltip should not throw errors when being conditionally rendered

### Actual behavior

After leaving clicking on another browser tab and then clicking back into the application the error below is thrown

leaflet-src.js?af6a:10904 Uncaught TypeError: Cannot set properties of null (setting '_source')
    at NewClass.eval (leaflet-src.js?af6a:10904:1)
    at HTMLDivElement.handler (leaflet-src.js?af6a:2798:1)
eval @ leaflet-src.js?af6a:10904
handler @ leaflet-src.js?af6a:2798

### Steps to reproduce
Render marker with tooltip children
```
    <Marker position={...}
    	 eventHandlers={{
              mouseover: () => setShowTooltip(true),
              mouseout: () => setShowTooltip(false),
            }}
    >
      {showTooltip && (<Tooltip key={myKey} direction='right' offset={[16, 0]}>
        hello
      </Tooltip>)}
    </Marker>
```

After hovering the marker, click on another tab and then click back into tab running application. The error will be thrown

**Comment by trinhvuduc** [comment]
I have same issues, how can u fix it?
