### ISSUE TITLE
The updateLeafletElement method is not called react-leaflet v2.8

### ISSUE THREAD

**Issue by LLStudent83** [PaulLeCam/react-leaflet#1037]
Good afternoon. I ask for help in solving the problem. There is a RoutingMashin component:
`class RoutingMachine extends MapLayer {`
 ` createLeafletElement() {`
    `const { map, constructionCoord, projectCoord, dataIconsForMap, color, removeRoute } = this.props;`
   ` this.leafletElement = L.Routing.control({.........})`

`updateLeafletElement(fromProps, toProps) {`
    `if (toProps.action === 'dell') {`
    `  this.control.setWaypoints([]);`
   `   toProps.map.leafletElement.removeControl(this.control);`
  `  }`
 ` }`
when trying to delete a route, the updateLeafletElement method is not called.
I call Routing Machine something like this:
`return routesToBuild!.map(({ pointA, pointB, color, action }: BlankRoute & { action?: string }) => {`
   ` }`
    `return (`
     ` <RoutingMachine`
      `  // @ts-ignore`
       ` map={map}`
        `color={color}`
        `constructionCoord={pointA.coord}`
        `projectCoord={pointB.coord}`
        `key={uniqid()}`
        `action={action}`
      `/>`
    `);`
 ` });`

Tell me what could be the problem, why updateLeafletElement is not called when called again with changed props

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
