### ISSUE TITLE
Tiles are unloading still when using maxNativeZoom

### ISSUE THREAD

**Issue by MarshMello0** [PaulLeCam/react-leaflet#1038]
## Bug report in v4
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

The tiles last loaded should stay visiable.

### Actual behavior

The tiles unload.

### Steps to reproduce

Using OSM for this.
1. Set `maxZoom` to `22`
2. Set `maxNativeZoom` to `19`
3. Zoom in to max and see the tiles unload
[Stackblitz Example](https://stackblitz.com/edit/react-leaflet-v4-kunalm?file=src/App.js)

**Comment by aricooperdavis** [comment]
Can confirm this is still a bug.

**Comment by sundisc** [comment]
Using the maxZoom and maxNativeZoom props on the TileLayer instead of the MapContainer fixes the problem.
