### ISSUE TITLE
Path Layer losing style when rerender Marker

### ISSUE THREAD

**Issue by RobertChaw** [PaulLeCam/react-leaflet#1058]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).

### Expected behavior

Path Layer not losing style when rerender Marker.

### Actual behavior

When the mouse was moved over a Path Layer, the path Layer will fill blue.
but the style of the Path Layer was reset, after the marker appear.

### Steps to reproduce

https://stackblitz.com/edit/react-leaflet-v4-zttbra?file=src/App.js

**Comment by AhXianGL** [comment]
the problem is not <GeoJSON>-specific,
see the (stackblitz code)[https://stackblitz.com/edit/react-leaflet-v4-zttbra?file=src/App.js] line 76, you set a "style" prop to the <GeoJSON>.Each time you call setMarkerCenter() or setShowMarker() the component rerender,then the GeoJSON Layer rerender with the "style" prop you set,this is the key, you create the “const style = { ... }” literally so that whenever the component render the style prop's value is totally 'new' for the GeoJSON component, then the codes inside the component run some effect to set the 'new' style to its inner geojson layer,
So the right way to set the default style of GeoJSON layer is make the style props controlled or set the 'style' const outside the RFC to avoiding difference reference of 'style' of the style props.
see the right way to resolve the problem tackling you.
```javascript
import React, { StrictMode, useState } from 'react';
import { MapContainer } from 'react-leaflet/MapContainer';
import { Marker } from 'react-leaflet/Marker';
import { GeoJSON } from 'react-leaflet/GeoJSON';
import { Popup } from 'react-leaflet/Popup';
import { TileLayer } from 'react-leaflet/TileLayer';
import data from './china.js';

/** Solution A: set the const outside */
const defaultStyle = {
  stroke: true,
    color: '#aeafaf',
    opacity: 0.2,
    fill: true,
    fillColor: '#c4c5c6',
    fillOpacity: 0.4,
}

function SimpleExample(props) {
  /**wrong way to declare */
  /* const style = {
    stroke: true,
    color: '#aeafaf',
    opacity: 0.2,
    fill: true,
    fillColor: '#c4c5c6',
    fillOpacity: 0.4,
  }; */

  const selectedStyle = {
    stroke: true,
    color: '#aeafaf',
    opacity: 0.1,
    fill: true,
    fillColor: '#3b7efc',
    fillOpacity: 0.8,
  };

  /** Solution B: make the default style controlled,then the react shallow compare decide wether rerender */
  // const [defaultStyle,] = useState(
  //   {
  //     stroke: true,
  //       color: '#aeafaf',
  //       opacity: 0.2,
  //       fill: true,
  //       fillColor: '#c4c5c6',
  //       fillOpacity: 0.4,
  //   }
  // );
  const [showMarker, setShowMarker] = useState(false);
  const [markerCenter, setMarkerCenter] = useState([0, 0]);
  const marker = (
    <Marker
      position={markerCenter}
      icon={
        new L.DivIcon({
          className: showMarker ? 'block' : 'hidden',
          html: `<p>losing style</p>`,
        })
      }
    />
  );

  const onEachFeature = (feature, layer) => {
    layer.on({
      mouseout: (e) => {
        e.target.setStyle(defaultStyle);
        setShowMarker(false);
        console.log('鼠标移除');
      },
      mouseover: (e) => {
        e.target.setStyle(selectedStyle);
        const center = feature.properties.center;
        setMarkerCenter([center[1], center[0]]);
        setShowMarker(true);
        console.log('鼠标进入');
      },
      click: (e) => {
        console.log(`点击了: ${feature.properties.name}`);
      },
    });
  };

  return (
    <StrictMode>
      <MapContainer
        center={[34.167, 108.89]}
        zoom={5}
        scrollWheelZoom={true}
        className="h-[64rem] w-[64rem]"
      >
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          url="https://api.tiles.mapbox.com/styles/v1/{id}/tiles/{tileSize}/{z}/{x}/{y}?access_token={accessToken}"
          id="chaw1213/cl32dvwpm009c15mxtmcbmax4"
          accessToken="pk.eyJ1IjoiY2hhdzEyMTMiLCJhIjoiY2xjdnI4dzRwMDFtazNucDdtdHJwMmRiMSJ9.uPGWtxwSSwpxdSVVpHyJ_A"
        />
        {/* <GeoJSON style={style} data={data} onEachFeature={onEachFeature} /> */}
        <GeoJSON style={defaultStyle} data={data} onEachFeature={onEachFeature} />
        {/* {marker} */}
      </MapContainer>
    </StrictMode>
  );
}

export default function App() {
  return <SimpleExample position={{ lat: 51.505, lng: -0.09 }} />;
}

```

**Comment by RobertChaw** [comment]
Thank you for your detailed reply! It was my problem.😂😂
