### ISSUE TITLE
plugin request: smooth zoom

### ISSUE THREAD

**Issue by ambuehll** [PaulLeCam/react-leaflet#1059]
Hi there, 
great work. 
another plugin that I'd love to see supported is https://github.com/mutsuyuki/Leaflet.SmoothWheelZoom
Many thanks!
Lukas

**Comment by takada-masaya** [comment]
I also need this plugin.
Thank you!

**Comment by TrifectaKS** [comment]
This would be great if implemented.

**Comment by simonprovost** [comment]
Still not @PaulLeCam  ?
