### ISSUE TITLE
Support for react `ref`

### ISSUE THREAD

**Issue by colllin** [PaulLeCam/react-leaflet#106]
How could we support React's `ref` prop to give us access to the underlying Leaflet layer?

For example:

    <GeoJson data={myData}
        ref={(ref) => this.geoJsonFeature = ref}
    />

Then in componentDidMount:

    componentDidMount() {
        console.log(this.feature);
    }

I'm trying to animate the style of the GeoJson element.  I think I need to either create a JS animation or CSS animation and apply it to the feature.  This would give us access to the underlying Leaflet element so I could create a JS animation or apply a CSS class to trigger an animation.  Does this seem possible?  Is there a better way to achieve my goal?  I'm willing to implement it if you can point me in the right direction.

**Comment by PaulLeCam** [comment]
`ref` is supported as it is default React's behavior, nothing specific to it.
As written in [the documentation](https://github.com/PaulLeCam/react-leaflet#components) you can already access the created instance for the Leaflet element.

Regarding animations, I think the best option is to refer to Leaflet's documentation as the DOM manipulations are handled by Leaflet, not React.

**Comment by colllin** [comment]
Do you think it could be an issue specific to ES6?

I tried `ref='thing'` and `this.refs.thing` is `undefined`. I also tried `ref={(ref) => this.thing = ref}` as in the example above, and that `ref` handler never gets called, so, as you would expect, `this.thing` is `undefined`.

**Comment by PaulLeCam** [comment]
The rendering happens in different steps:

1. The `<Map>` component renders an empty `<div>` that will contain the map. At this point the children are completely ignored (so it's expected no ref would be bound).
2. The Map `componentDidMount()` handler creates the Leaflet map instance.
3. The Map renders its children, injecting the map instance as their `map` property.
4. Children components instantiate their Leaflet instance using the provided `map`, that usually renders them (this is purely Leaflet rendering, React only provides the abstraction).

So if you are trying to access a ref of a layer in the `componentDidMount()` handler of a component rendering the `Map`, it would be undefined as only the empty `<div>` would be rendered at the time `componentDidMount()` is called.

A very ugly workaround would be to use a `setTimeout()` in `componentDidMount()` to defer the access to the ref, but a better solution is to create a custom component to handle the specific logic you want around this component, ex:

```js
class MyCustomFeature extends React.Component {
  componentDidMount() {
    const el = this.refs.feature.getLeafletElement();
    // Your custom logic interacting with Leaflet
  }

  render() {
    return <GeoJson ref='feature' {...this.props} />;
  }
}
```

**Comment by colllin** [comment]
@PaulLeCam Thank you for the detailed and patient response.

I see now that the `ref` handler **is** being called, but after `componentDidMount` has already been called.

Either way, I think I was caught in an old (non-react) way of thinking about leaflet, and the approach you suggested sounds better.  I'm going to extend the GeoJson component to create a custom GeoJsonAnimated component.

**Comment by PaulLeCam** [comment]
Glad it helps!

I haven't tried anything related to animations, but I think the best options is to use Leaflet APIs directly as they are the ones interacting with the DOM. Using a custom component would give you the most flexibility.

**Comment by Smallmelo** [comment]
@colllin can you share a sample of the solution you came up with?  i'm having trouble animating the entering of geojson.  for simplicity sake, i'm using a MyPolygon component that renders a react-leaflet GeoJson component.  do i need to setStyle in the componentDidMount method? i've tried wrapping the component in the ReactCSSTransition group, but doesn't work.

**Comment by colllin** [comment]
@Smallmelo Looking back at my code, all I can see is that I performed my `componentDidMount` logic also in `componentWillReceiveProps`:

    componentDidMount
        this.updateGeomLayer(this.props);
    }
    componentWillReceiveProps(nextProps) {
        this.updateGeomLayer(nextProps);
    }
    updateGeomLayer(props) {
        // ...
    }

**Comment by christianhaller** [comment]
Can you provide a demo or some hints for an animated marker?

**Comment by TPABHuKOB** [comment]
I solved this problem in this way
```
<FeatureGroup onAdd={(e)=> {this.zones=e.target}}>
```
