### ISSUE TITLE
In production mode typescript returns   TS1005: ',' expected. error

### ISSUE THREAD

**Issue by aohayk** [PaulLeCam/react-leaflet#1061]
I have using react 17 and typescript 4.9.4
So when I run npm run prod I have TS1005: ',' expected. error in node_modules`
node_modules/react-leaflet/lib/WMSTileLayer.d.ts(3,43)
![image](https://user-images.githubusercontent.com/88877787/215450063-40d90f70-f63d-43e9-b251-43a813f53cbf.png)

This issue related import { type... } from '....'

**Comment by EugenIlchenko** [comment]
same problem

**Comment by damiangolojuch** [comment]
You have to bump typescript version in your project, at least to 4.5.
