### ISSUE TITLE
I would like to ask for help on how to fix the white lines that appear after loading a tile map using the TileLayer component

### ISSUE THREAD

**Issue by lhs1478** [PaulLeCam/react-leaflet#1065]
![image](https://user-images.githubusercontent.com/93760705/223633055-816ae1f4-4cdf-4e16-9c7a-33890c89ce80.png)

When I load the tile map using the TileLayer component, there is a serious white line problem between the tiles, is there any way to solve this white line problem?

**Comment by AhXianGL** [comment]
This is not [react-leaflet](https://github.com/PaulLeCam/react-leaflet)-specific behavior; it is a part of leaflet itself,see [leaflet whiteline issue](https://github.com/Leaflet/Leaflet/issues/3575).

**Comment by lhs1478** [comment]
> 

Yes, I understand it's not react-leaflet's problem, I would like to ask me is there any solution for this using react-leaflet

**Comment by AhXianGL** [comment]
It depends on whether the developer will add a plugin in the next version to solve this problem~~

**Comment by lhs1478** [comment]
> 就看开发者下个版本会不会加插件来解决这个问题了~~

Ok thank you for your advice
