### ISSUE TITLE
Leaflet.divIcon & Leaflet.icon

### ISSUE THREAD

**Issue by alex3165** [PaulLeCam/react-leaflet#107]
It would be nice to have a component to create Icon and divIcon instead of having to use leaflet instance.
Then we can pass the icon component as a property to the Marker like so:

```

const icon = (
  <mapIcon iconUrl="image.png" iconAnchor={[20, 30]}/>
)

render() {
  return (
    <Marker
     icon={icon}/>
  )
}
```

**Comment by PaulLeCam** [comment]
`Icon` and `DivIcon` are types, not layers, they would not provide any value as components, only overhead.
