### ISSUE TITLE
Clicking on polyline with sticky tooltip cause tooltip to jump to the polyline center

### ISSUE THREAD

**Issue by krivoruchkoND** [PaulLeCam/react-leaflet#1072]
### Expected behavior

Sticky tooltip do nothing when parent element is clicked

### Actual behavior

Sticky tooltip jump to parent center when parent element is clicked

### Steps to reproduce

Can be reproduced in [documentation](https://react-leaflet.js.org/docs/example-tooltips/). Try to click at diferent possitions inside left or right triangle at example. Tooltip will jump to the left triangle center

upd: reproduced only in Chrome v 112.0.5615.49, can't reproduc in Safari and Firefox

**Comment by Rounak-Dwary** [comment]
any help on this.

**Comment by DaryaHaprova** [comment]
If someone looking for the work around, you can find it there - https://stackoverflow.com/questions/77777776/react-leaflet-geojson-tooltip-appears-in-two-places-how-to-fix
