### ISSUE TITLE
[docs] React control example doesn't really work

### ISSUE THREAD

**Issue by hooch** [PaulLeCam/react-leaflet#1089]
Bug report in v4 (docs)

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

The provided [documentation](https://react-leaflet.js.org/docs/example-react-control/) for creating a React component-based leaflet-style control don't properly insert the control into Leaflet's control hierarchy.

```
<div className={positionClass}>
  <div className="leaflet-control leaflet-bar">{minimap}</div>
</div>
```

### Expected behavior

The control stacks with other controls within the same `positionClass`.

### Actual behavior

The control sits on top of other controls in the same `positionClass` making them inaccessible and effectively invisible.

### Steps to reproduce

An example of the `ZoomControl` being hidden behind the example React control is available [here](https://stackblitz.com/edit/react-leaflet-v4-vsgrfa?file=src%2FApp.js)

I'm interested to see if the React control example can be updated in such a way to make this work as expected.

Alternatively, for what it's worth, I was able to resolve my problem by using a [third party package](https://www.npmjs.com/package/react-leaflet-custom-control)

**Comment by PaulLeCam** [comment]
This is an example of what is possible to do, not a complete integration into what Leaflet does, for this you can implement the logic you need.
