### ISSUE TITLE
Using Google maps tiles

### ISSUE THREAD

**Issue by adanielyan** [PaulLeCam/react-leaflet#109]
I tried to use this component with Google maps API for rendering Google maps tiles layer over the map (since you can't just use Google tiles directly bypassing their API), but couldn't make it work. Does anyone have a working example of using this component with Google maps' tiles? Any advice is appreciated.

**Comment by PaulLeCam** [comment]
Hi,

This is out of the scope of this library, as it only provides React bindings to Leaflet, not additional features.

I hope you'll have more luck with Leaflet documentation / plugins.

**Comment by stephanedaviet** [comment]
For those interesting in setting up react-leaflet with Google maps (or other), you can write your custom component inspired by the one described below, based on [leaflet-plugin](https://github.com/shramov/leaflet-plugins) by @shramov and [google-maps](https://github.com/Carrooi/Js-GoogleMapsLoader) by @Carrooi:

```javascript
import 'leaflet-plugins/layer/tile/Google';

import L from 'leaflet';
import MapLayer from 'react-leaflet/lib/MapLayer';
import GoogleMapsLoader from 'google-maps';

export default class GoogleLayer extends MapLayer {

  componentWillMount() {
    super.componentWillMount();

    this.state = {
      googleLoaded: false
    };

    this.leafletElement = L.tileLayer('');

    GoogleMapsLoader.LANGUAGE = 'fr';
    GoogleMapsLoader.LANGUAGE = 'FR';
    GoogleMapsLoader.KEY = '<your-google-api-key>';

    GoogleMapsLoader.load(() => {
      const GoogleLayer = new L.Google('ROADMAP');
      this.props.layerContainer.removeLayer(this.leafletElement);
      this.leafletElement = GoogleLayer;
      this.props.layerContainer.addLayer(this.leafletElement);
      this.setState({
        googleLoaded: true
      });
    });
  }

  componentWillUnmount() {
    super.componentWillMount();

    GoogleMapsLoader.release(() => {
      this.setState = {
        googleLoaded: false
      };
    });
  }

  shouldComponentUpdate() {
    return super.shouldComponentUpdate()
        && this.state.googleLoaded;
  }

  render() {
    return null;
  }
}
```
