### ISSUE TITLE
Change the map of India and add entire Kashmir in it 

### ISSUE THREAD

**Issue by vishu1301** [PaulLeCam/react-leaflet#1134]
Please change the map of India and add entire Kashmir as part of India As soon as possible.
#BoycottReactLeafLet or else face consequences.

**Comment by victor-bts** [comment]
> Please change the map of India and add entire Kashmir as part of India As soon as possible. #BoycottReactLeafLet or else face consequences.

You do realize that `react-leaflet` doesn't generate maps, right? It merely accepts and visualizes mapping data.
