### ISSUE TITLE
Cannot read properties of undefined (reading '_leaflet_pos')

### ISSUE THREAD

**Issue by iqbalhassan-7654** [PaulLeCam/react-leaflet#1136]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this StackBlitz](https://stackblitz.com/edit/react-leaflet-v4?file=src/App.js).

**Comment by iqbalhassan-7654** [comment]
![image](https://github.com/PaulLeCam/react-leaflet/assets/170302501/cb30799e-bbca-466d-8e91-cbc9e992f8a1)

**Comment by piotr-cz** [comment]
I think this may happen when you access native leaflet methods at the time when map container is unmounted.

For example I'm attempting to store map bounds in a state when user navigates to another page.
At the same time I'm unmounting map container

**Comment by marcoangelo** [comment]
@piotr-cz How are you unmounting the map container? I am getting a similar issue as in this bug report; I try to use the remove() method on the map instance (when using the useMap hook), but get a [Map container is already initialized] error.

**Comment by piotr-cz** [comment]
@marcoangelo 
Now I'm using external state, so it's updates don't trigger leaflet methods after component has been unmounted

**Comment by iqbalhassan-7654** [comment]
Still i have that issue and don't resolve yet how can i resolve it any suggestion @piotr-cz

**Comment by iqbalhassan-7654** [comment]
@marcoangelo can you resolve it ?

**Comment by iqbalhassan-7654** [comment]
@PaulLeCam the issue is when come to component of map and zoom in zoom out repeatedly after that immediate go to next component they give me this error why ?

**Comment by piotr-cz** [comment]
@iqbalhassan-7654 It's probably because of this: https://github.com/PaulLeCam/react-leaflet/issues/1136#issuecomment-2203908894

**Comment by iqbalhassan-7654** [comment]
`  const position = [state.lat || 0, state.lng || 0]
  const displayMap = (
    <MapContainer
    key={props.mapLayer?.id}
      center={position}
      id='mapContainer'
      zoom={state.zoom}
      style={{ height: props.height, width: props.width }}
      maxZoom={props.mapLayer.maxZoom}
      onBaselayerchange={changeBaseLayer}
      whenReady={(map)=>{
        if(isMapMounted.current){
        setMapInstance(map.target)
        setIsMapReady(true)
        if (map.target) {
          map.target.scrollWheelZoom?.enable();
        }
      }
      }}
      scrollWheelZoom={false}
  

    // ref={setMap}
    >
      {/* <MapInitializer setMap={setMap} /> */}
      {
        mapInstance&&isMapMounted.current&&isMapReady&&<>

      <DrawControl
        onDrawControlReady={_onDrawControlReady}
        drawSettings={drawSettings}
        onDrawStop={_onDrawStop}
        onDrawStart={_onDrawStart}
      />

      <ClusteredMarkers
        clustersEnabled={props.logInUser?.attributes?.clusters}
        markers={state.markers}
      />

      {props.geoFence?.map((obj) => (
        <ChidlGeofences
          key={obj.id}
          obj={obj}
          settings={settings}
          onFeatureGroupAdd={onFeatureGroupAdd}
          _onEditControlReady={_onEditControlReady}
          _onEditPath={_onEditPath}
          _onEditStart={_onEditStart}
        />
      ))}

      <LayersControl position="bottomright">
          {MapTileLayers?.map(layer => <LayersControl.BaseLayer id={layer.id} checked={layer.id === props.mapLayer.id} key={layer.id} name={layer.name}>
            <TileLayer {...layer} minZoom={state.minZoom} />
          </LayersControl.BaseLayer>)}
        </LayersControl>
      <ZoomControl position={'bottomright'} />
      </>
      }
    </MapContainer>
  )
  return (
    <div className='no-map-controls no-widgets'>
      {state.geofenceModal && state.resourceList !== 'tracks' && (
        <GeofenceModal
          geofence={state.geofenceModalData}
          {...state.geofenceModalMaoData}
          onClose={closeGeofenceModal}
          resourceList={state.resourceList}
          translate={props.translate}
          logInUser={props.logInUser}
        />
      )}
      {state.geofenceModal && state.resourceList === 'tracks' && (
        <TrackModal
          enableEdit={state.enableEdit}
          geofence={state.geofenceModalData}
          {...state.geofenceModalMaoData}
          onClose={closeGeofenceModal}
          resourceList={state.resourceList}
          kmlFileUpload={upload}
          kmlDataForm={state.kmlDataForm}
          onChange={handleChange}
          disableSubmit={state.disableSubmit}
          submitKMLForm={submitKMLForm}
          translate={props.translate}
        />
      )}
      <Layout
        {...props}
        kmlFileUpload={upload}
        enableEdit={state.enableEdit}
        geofenceData={{ ...state, updateVisible, save, enableEditMap, cancelMapChanges, cancelDrawing, saveDrawing, undoDrawing, toggleGeofences }}
        toggleGeofences={toggleGeofences}
        fetchMoreItems={fetchMoreItems}
        itemPagination={{ ...state.itemPagination, endMessage }}
        searchItems={searchItems}
        openGeofenceModal={openGeofenceModal}
        onDelete={onDelete}
        showResources={showResources}
        onEditResource={onEditResource}
        onLinkResource={onLinkResource}
        addResource={addResource}
        resourceList={state.resourceList}
        getAllGeofences={getAllGeofences}
        handleScrollGeofencesIndex={handleScrollGeofencesIndex}
      >
        {!['addResource', 'editResource'].includes(state.activeOperation) && (
          <>
            {props.mapLayer && [
              'osm', '', 'carto', 'googleTerrain',
              'googleSatellite', 'googleHybrid',
              'googleRoad', 'baidu', 'yandexMap', 'yandexSat'
            ].includes(props.mapLayer.id) && displayMap}
          </>
        )}
        <button
          style={{
            position: 'absolute',
            left: '-10000px',
            top: '-10000px'
          }}
          onClick={() => addShape('circle')}
          id='addCircle'
        ></button>
        <button
          style={{
            position: 'absolute',
            left: '-10000px',
            top: '-10000px'
          }}
          onClick={() => addShape('polygon')}
          id='addPolygon'
        ></button>
        <button
          style={{
            position: 'absolute',
            left: '-10000px',
            top: '-10000px'
          }}
          onClick={() => addShape('polyline')}
          id='addPolyline'
        ></button>


        <div className="has-padding">
          <ResourceModal
            changeResource={props.changeResource}
            selectedResourse={state.selecteditem}
            activeOperation={state.activeOperation}
            onCloseResource={onCloseResource}
            itemPagination={state.itemPagination && state.itemPagination.items}
            assignItem={props.assignItem}
            unassignItem={props.unassignItem}
            fetchNestedItems={props.fetchNestedItems}
            nestedResources={props.nestedResources}
            translate={props.translate}
            editResource={state.editResource}
            linkResource={state.linkResource}
            themecolors={props.themecolors}
            itemType='Geofence'
          />
        </div>
      </Layout>
    </div>
  )`

**Comment by iqbalhassan-7654** [comment]
@piotr-cz  check the above code if not understand any thing my code i will tell ask me kindly resolve my issue

**Comment by val3ntin** [comment]
I think it is an edge case.
Looks like the reason is when you re-init the map ( e.g. re-render it or cancel rendering the popup with this map) , and use `setView` or `fitBounds()` , these methods are called with animation by default, leaflet uses `requestAnimationFrame` under the hood:

https://github.com/Leaflet/Leaflet/blob/9931f73bc2c508c1e7de4ff645fa5d7d5c9048a4/src/map/Map.js#L1675C1-L1680C12

the Util returns `rAFId` but it is not saved to any of the variables, and once map is removed from DOM, leaflet still tries to access it.

I think this could be solved on `_remove()` method here:
https://github.com/Leaflet/Leaflet/blob/9931f73bc2c508c1e7de4ff645fa5d7d5c9048a4/src/map/Map.js#L741
