### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by gane5h** [PaulLeCam/react-leaflet#114]
Has anybody using this library with Typescript? Curious what your experience has been.

**Comment by PaulLeCam** [comment]
No feedback... I'm closing it but feel free to comment / reopen if relevant.

**Comment by stroborobo** [comment]
Just for the record, using it and works well. There's just no typing information, so you'll have to use `require` instead of `import`:

```typescript
declare var require: any
const { Map, TileLayer } = require('../../node_modules/react-leaflet')
```

**Comment by danzel** [comment]
FYI, I've created typescript definitions and submitted them to DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13922
