### ISSUE TITLE
Labels for Vectors

### ISSUE THREAD

**Issue by thynan** [PaulLeCam/react-leaflet#115]
Hi!
I'm relatively new to React and Leaflet, so I'm having a hard time wrapping my head around this. Maybe some of you can give me some pointers:

I have a map with some rectangles (polygons) drawn on it. I want to write some text into those polygons.
There is a Plugin which does exactly what i need: https://github.com/Leaflet/Leaflet.label

However, I have no idea how i can use this with the react-leaflet library. So if I have a polygon like this:
```
<Polygon color='black' key={person.person.name} positions={positionArray}>
```

.. how should I extend the "Polygon" component to accept a label? Any help would be really appreciated. Thanks!

**Comment by PaulLeCam** [comment]
Hi,
As stated in the [documentation](https://github.com/PaulLeCam/react-leaflet#creating-custom-components), one way to achieve this is to extend the relevant components to add the handlers you need.

I haven't used Leaflet.label or tested the code below so it may not work, but it should give you the general idea.
For example let's take the [Polygon](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Polygon.js#L18) source, as you can see the `Leaflet.polygon` instance is created in `componentWillMount()`, using the provided props.
It seems with Leaflet.label you need to call the `bindLabel()` function on this instance:

```js
// Use the same code as Polygon, just customise componentWillMount()
class PolygonWithLabel extends Path {
   // Add the relevant prop types for Leaflet.label
   static propTypes = {
    label: PropTypes.string.isRequired,
    labelOptions: PropTypes.object,
    positions: PropTypes.oneOfType([
      latlngListType,
      PropTypes.arrayOf(latlngListType),
    ]).isRequired,
  };

  componentWillMount() {
    super.componentWillMount();
    // Extract label and labelOptions from props
    const { label, labelOptions, map, positions, ...props } = this.props;
    // Call bindLabel() as documented in Leaflet.label
    this.leafletElement = polygon(positions, props).bindLabel(label, labelOptions);
  }

  componentDidUpdate(prevProps) {
    if (this.props.positions !== prevProps.positions) {
      this.leafletElement.setLatLngs(this.props.positions);
    }
    this.setStyleIfChanged(prevProps, this.props);
    // Eventually handle specific logic if props change
  }
}
```
Depending on your usage, you may also want to customise the `componentDidUpdate()` handler to update the label accordingly when the props change.

**Comment by thynan** [comment]
Hi,

thanks a lot, you just made my day! :) That was exactly what I needed.

**Comment by SunyoungKim508** [comment]
@thynan did it work? It says that bindLabel doesn't exist.

**Comment by abdurrehman1998** [comment]
> Hi, As stated in the [documentation](https://github.com/PaulLeCam/react-leaflet#creating-custom-components), one way to achieve this is to extend the relevant components to add the handlers you need.
> 
> I haven't used Leaflet.label or tested the code below so it may not work, but it should give you the general idea. For example let's take the [Polygon](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Polygon.js#L18) source, as you can see the `Leaflet.polygon` instance is created in `componentWillMount()`, using the provided props. It seems with Leaflet.label you need to call the `bindLabel()` function on this instance:
> 
> ```js
> // Use the same code as Polygon, just customise componentWillMount()
> class PolygonWithLabel extends Path {
>    // Add the relevant prop types for Leaflet.label
>    static propTypes = {
>     label: PropTypes.string.isRequired,
>     labelOptions: PropTypes.object,
>     positions: PropTypes.oneOfType([
>       latlngListType,
>       PropTypes.arrayOf(latlngListType),
>     ]).isRequired,
>   };
> 
>   componentWillMount() {
>     super.componentWillMount();
>     // Extract label and labelOptions from props
>     const { label, labelOptions, map, positions, ...props } = this.props;
>     // Call bindLabel() as documented in Leaflet.label
>     this.leafletElement = polygon(positions, props).bindLabel(label, labelOptions);
>   }
> 
>   componentDidUpdate(prevProps) {
>     if (this.props.positions !== prevProps.positions) {
>       this.leafletElement.setLatLngs(this.props.positions);
>     }
>     this.setStyleIfChanged(prevProps, this.props);
>     // Eventually handle specific logic if props change
>   }
> }
> ```
> 
> Depending on your usage, you may also want to customise the `componentDidUpdate()` handler to update the label accordingly when the props change.

I am getting following error 
**Uncaught TypeError: Class constructor PolygonWithLabel cannot be invoked without 'new'.**
Any help will be appreciated.
