### ISSUE TITLE
True MultiPolyline implementation

### ISSUE THREAD

**Issue by L0key** [PaulLeCam/react-leaflet#118]
Paul,

Love the react-leaflet library.  Any thought towards implementing the MultiPolyline layer closer to leaflet's implementation, i.e. something more than an array of an array of lat/lng? This would allow the use of different color polylines and/or other options?

**Comment by PaulLeCam** [comment]
Hi,

If you are referring to the [Path options](http://leafletjs.com/reference.html#path-options)? They [should be supported on all vector layers](https://github.com/PaulLeCam/react-leaflet#vector-layers), please let me know if this is not the case.
