### ISSUE TITLE
Error when including into a web pack built app

### ISSUE THREAD

**Issue by chriswiggins** [PaulLeCam/react-leaflet#119]
Hi all,

Loving the library and how easy it looks to extend leaflet components - I was going to try and do a similar thing myself but why bother when there's already a good library out there that you can extend and contribute to!

Anyway, I have webpack building my app, but I'm hitting an error whenever I include react-leaflet:
```
ERROR in ./~/react-leaflet/lib/index.js
Module build failed: ReferenceError: Unknown plugin "syntax-class-properties" specified in "/Users/chris/Documents/web/node_modules/react-leaflet/.babelrc" at 1, attempted to resolve relative to "/Users/chris/Documents/web/node_modules/react-leaflet"
```

If I install the syntax-export-extension babel plugin as a dependancy to my own app, I then hit the same error with `syntax-export-extensions`. It seems to be that I need all the plugins listed in react-leaflet's `.babelrc` installed in my own app dir for this to compile.

Is this expected behaviour? I'm not entirely sure if this is a web pack issue or not, however if these are required at my app's node_modules root, then should they be listed as peerDependencies? 

Interested to see what I'm doing wrong and if anyone can help!

Thanks
Chris

**Comment by PaulLeCam** [comment]
Hi,

It's probably an issue with your Webpack configuration, make sure babel loader ignores the files in `node_modules`. Ex: https://github.com/PaulLeCam/react-leaflet/blob/master/example/webpack.config.js#L14
