### ISSUE TITLE
react-leaflet marker-cluster support

### ISSUE THREAD

**Issue by GalitTugi** [PaulLeCam/react-leaflet#121]
hello,
I'm using react-leaflet with MarkerCluster, using the example in the previous issues (https://github.com/PaulLeCam/react-leaflet/issues/42).

Everytime a cluster changes (opens up, for example), the click event is removed from the listeners. That means, the click event on the map I subscribed to, is no longer fired.
Has anybody ran into that problem \ have a reasonable solution?

I'm using versions: 
leaflet: 0.7.7
react-leaflet: 0.9.0
leaflet.markercluster: 0.7

I figured out the source to the problem, it happens when the markerCluster component calls "removeLayer", which calls L.Path.onRemove.
In this function it literally removes the click event listener (line 5052 in leaflet-src.js).

Thanks.

**Comment by c0cky** [comment]
+1

**Comment by PaulLeCam** [comment]
Hi,

Seems your issue is with MarkerCluster, how is it related to this lib?
