### ISSUE TITLE
Please update to leaflet 0.7.7

### ISSUE THREAD

**Issue by pke** [PaulLeCam/react-leaflet#125]
get `DomUtil.getPosition()` is broken in 0.7 and can return `null`

**Comment by PaulLeCam** [comment]
Leaflet is a peer dependency set to `^0.7.0`, so matching all `0.7.x` releases.

**Comment by pke** [comment]
Hmm installing `react-leaflet` brings 0.7.0 into the bundle. And has this bug from 0.7.0. How can I force npm to install the newest leaflet bundle with react-leaflet?

**Comment by PaulLeCam** [comment]
`npm install leaflet`?

**Comment by pke** [comment]
hmmm. Of course I did that. I have 0.7.7 in my package. react-leaflet uses 0.7.0 thats bundled with it. Using npm 2, mind you. Do I need to de-dup or something to fix that?

**Comment by PaulLeCam** [comment]
I just installed it with the following results:
```
> npm -v
2.14.20
> npm install react-leaflet
react-dom@0.14.7 node_modules/react-dom

leaflet@0.7.7 node_modules/leaflet

react@0.14.7 node_modules/react
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
└── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.1.0, promise@7.1.1, core-js@1.2.6)

react-leaflet@0.10.1 node_modules/react-leaflet
└── lodash@4.6.1
```
Whatever your issue is, it's most likely your environment, not this lib.

**Comment by pke** [comment]
Something is wrong with my node_modules. Sorry for bothering. Will check.
