### ISSUE TITLE
Remove zoom controls

### ISSUE THREAD

**Issue by kachkaev** [PaulLeCam/react-leaflet#128]
This might be just an issue with the documentation, but I haven't found a way to switch off zoom controls (+ / – icons in the top-left corner). What prop do I need to pass to the Map component in order to remove them?

**Comment by PaulLeCam** [comment]
From the `Map` documentation:
> Refer to Leaflet documentation for more information about the properties.

**Comment by Spaxe** [comment]
Just in case someone stumbles on this, and needs more help:

      <Map zoomControl={false} > is what @PaulLeCam is referring to in http://leafletjs.com/reference.html#map-constructor

**Comment by HSN-Studio** [comment]
> Just in case someone stumbles on this, and needs more help:
> 
> ```
>   <Map zoomControl={false} > 
> ```
> 
> is what @PaulLeCam is referring to in http://leafletjs.com/reference.html#map-constructor

Thanks Dude!
