### ISSUE TITLE
Rendering on load

### ISSUE THREAD

**Issue by ballwood** [PaulLeCam/react-leaflet#129]
![screengrab](https://cloud.githubusercontent.com/assets/4639337/13915139/ad0d327e-ef4a-11e5-8a86-1c81f274da68.png)

Hi, really like the react-leaflet library. Great work! 

I'm having a little issue with rendering on load, because react is so quick it seems that the DOM isn't fully loaded before its inserting the leaflet component and causing the attached rendering issue. Do you know any way to work around this?

**Comment by estaub** [comment]
I'm not an expert, but my first guess would be that you're maybe misdiagnosing the problem.  Does it sometimes display a different shape?  If not, I'd look first  (using Chrome Dev Tools or similar) at the map elements to make sure they're sized correctly.

**Comment by bigsassy** [comment]
I also ran into a similar problem.  Try and inline the height of the map real quick and see if it helps:

    <Map style={{height: "300px"}}> // plus whatever other props
        // stuff
    </Map>

**Comment by ballwood** [comment]
cheers @bigsassy that fixed it

**Comment by HeyHugo** [comment]
Hi, just a tip for anyone who like me don't want to set a fixed height for the map. 
```
componentDidMount() {
    this.mapApi = this.refs.map.leafletElement;
    setTimeout(() => {
      this.mapApi.invalidateSize();
    }, 100);
}
```

**Comment by canda** [comment]
I have the same issue, I can't have the height fixed, and I don't want to use the setTimeout, it's kind of hackish. Any suggestions?

**Comment by estaub** [comment]
@canda In a similar situation, I've used [react-measure](https://github.com/souporserious/react-measure) to get the dimensions I have to work with , and set the "fixed" dimensions from that.  I haven't tried it with react-leaflet, though.
