### ISSUE TITLE
Add New Control

### ISSUE THREAD

**Issue by LucasAlumni** [PaulLeCam/react-leaflet#130]
Hi everybody,

I would like to create a new control with a button for recenter the map in marker.
I don't see how do..

Example : 
![capture d ecran 2016-03-24 a 11 28 55](https://cloud.githubusercontent.com/assets/7590678/14014571/bf0384e0-f1b3-11e5-877e-7e8f837fce07.png)

**Comment by bigsassy** [comment]
Hey Lucas,

You want to do something like this:

```
import React from 'react';
import ReactDOM from 'react-dom';
import L from 'leaflet';
import { MapControl } from 'react-leaflet';

export default class CenterControl extends MapControl {  // note we're extending MapControl

  componentWillMount() {
    const centerControl = L.control({position: 'bottomright'});  // see http://leafletjs.com/reference.html#control-positions for other positions
    const jsx = (
      // PUT YOUR JSX FOR THE COMPONENT HERE:
      <div {...this.props}>
        // add your JSX 
      </div>
    );

    legend.onAdd = function (map) {
      let div = L.DomUtil.create('div', '');
      ReactDOM.render(jsx, div);
      return div;
    };

    this.leafletElement = centerControl;
  }
}
```
Then use it like this:
```
// import / require your component and the react-leaflet Map component
<Map className="map" center={center} zoom={13}>
    <CenterControl/>
</Map>
```

**Comment by LucasAlumni** [comment]
Thanks bigsassy ! 

Just a little question, what's the legend for you ? : legend.onAdd = function (map).

Best regards,

**Comment by bigsassy** [comment]
Oh, sorry!  It should be `centerControl.onAdd = function (map) {`.  I updated the code above.

**Comment by LucasAlumni** [comment]
Thank you very much bigsassy !

**Comment by alexanderfrey** [comment]
Hello ! @bigsassy Thanks for the excellent example. Everything works so far except that I don't seem to be able to refresh my custom control when changing its properties. My custom control displays different information according to the selected marker on the map. 

Problem is that the content in the custom control does not update when selecting a marker. This mus t be because of the fact the react render function is not implemented / is able to rerender the component on prop change.

Did anyone come across this problem before ?

Thanks for help

**Comment by jgimbel** [comment]
This component only renders it's children on mount, not on render or update. If you would like a custom  control component that updates, I created [react-leaflet-control](https://github.com/liveby/react-leaflet-control). If your not a fan of installing more external components, you can always copy the ~45 lines of source.

**Comment by alexanderfrey** [comment]
@jgimbel Thanks so much ! I will go and check it out.

**Comment by alexanderfrey** [comment]
Looks good. I will go and use that one for my custom control. Do you have a suggestion to block panning the map when the mouse is over your react-leaflet-control container ? This is the reason why I was trying to create a custom leaflet control in the first place...

**Comment by alex1kirch** [comment]
You can use the component https://github.com/alex1kirch/react-leaflet-portal. The component allows to use the leaflet control panel like a normal React child. Features like context are availble because the component child still exists in the React tree.
Demo: https://react-leaflet-portal.herokuapp.com/#portal

**Comment by yuliakal** [comment]
Does anyone have solution for latest version of `react-leaflet`?

**Comment by clementallen** [comment]
@yuliakal Use this plugin: https://github.com/liveby/react-leaflet-control

**Comment by yuliakal** [comment]
Yeah, unfortunately it doesn't work for current version.

**Comment by yuliakal** [comment]
Solved using https://github.com/alex1kirch/react-leaflet-portal as @alex1kirch's comment.

**Comment by lidiasm** [comment]
Hi everyone! I installed that plugin but when I try to import it with this line `import Control from 'react-leaflet-control';
` I got this error: `TypeError: Super expression must either be null or a function, not undefined`. Does anyone know why it is or how can I fix this?? Thank you in advance!

**Comment by guillaume-gc** [comment]
> Hi everyone! I installed that plugin but when I try to import it with this line `import Control from 'react-leaflet-control'` I got this error: `TypeError: Super expression must either be null or a function, not undefined`. Does anyone know why it is or how can I fix this?? Thank you in advance!
> 
> I'm using react-leaflet 3 and react-leaflet-control 2.1.2

Unfortunately it seems the latest version of `react-leaflet-control` is not compatible with `react-leaftlet 3`. More info here: https://github.com/LiveBy/react-leaflet-control/issues/44
