### ISSUE TITLE
Extending MapControl

### ISSUE THREAD

**Issue by per-frojdh** [PaulLeCam/react-leaflet#134]
Maybe I've misunderstood the way I'm intended to use the BaseComponents and extending from them but when I attempt to wrap MapControl in a wrapper of my own, extending the MapControl component, I don't seem to get access to the this.leafletElement object which results in errors. (In this case I've used one of the /example files in order to eliminate any other errors)

```
import React, { Component } from 'react';
import { MapControl } from '../../src';

export default class ControlWrapper extends MapControl {
  render() {
    return (
        <h1>Hello world!</h1>
    );
  }
}
```

Doing it like this, I receive the following error:
```
MapControl.js:35 Uncaught TypeError: Cannot read property 'addTo' of undefined
```

Which makes it seem like the component lifecycles at least seem to be inheriting, but the access to the leafletElement does not. Is this the intended way of using these BaseComponents?

**Comment by PaulLeCam** [comment]
It's up to you to add the `this.leafletElement`, the base classes contain utilities and lifecycle handlers, but the point of extending them is to provide the relevant element.
For example as you can see in the [`ZoomControl` component](https://github.com/PaulLeCam/react-leaflet/blob/master/src/ZoomControl.js#L15), the `this.leafletElement` is set in the `componentWillMount()` lifecycle handler, and then used by [the `componentDidMount()` handler of `MapControl`](https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapControl.js#L12) to add it the map, making the actual `ZoomControl` code dead simple.

**Comment by per-frojdh** [comment]
Ah, this makes a lot of sense suddenly.  

So, if I understand this correctly, if I would want to add a container to the map, capable of rendering React components inside, I'd have to extend the base ```L.control``` with a new class, use that for my ```leafletElement``` and render the appropriate children to the container through the ```React-DOM```.  
Or is there some shortcut here I could use?

**Comment by PaulLeCam** [comment]
Yes, basically the components provided by this library are bindings to Leaflet elements, all the rendering is performed by Leaflet so if you want to render DOM elements as you would otherwise do with React, you need to do it explicitly and provide the resulting HTML to your Leaflet component.

The [`Popup` component](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Popup.js) should be a good start as it's implementing this logic to render the popup contents.

**Comment by per-frojdh** [comment]
The ```Popup``` component was a great find, it helped me a lot.
Thanks a lot for the help and clarification!
