### ISSUE TITLE
How to use LayersControl

### ISSUE THREAD

**Issue by jumpinjackie** [PaulLeCam/react-leaflet#137]
Is there an example of how to use the LayersControl component? From looking at the source, it appears that the props this component wants are the underlying leaflet layer objects. But how would you get access from these layer objects from their respective layer components at rendering time?

Suppose I had a fragment to render like this

    <Map ...>
        <TileLayer ref='osm-layer' url='http://{s}.tile.osm.org/{z}/{x}/{y}.png' attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors' />
        <GeoJson ref='geojson-layer' ... />
        <LayersControl  ??? />
    </Map>

What do you pass in to LayersControl?

**Comment by PaulLeCam** [comment]
Hi,
I just released a new version (0.11) that makes the `LayersControl` API more "React-friendly", you can check the [new documentation](https://github.com/PaulLeCam/react-leaflet#layerscontrol) and a [more advanced example](https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/layers-control.js) of this new behavior that should make it much easier to manipulate `LayersControl`.

**Comment by jumpinjackie** [comment]
Excellent!
