### ISSUE TITLE
Error with leaflet event listeners

### ISSUE THREAD

**Issue by per-frojdh** [PaulLeCam/react-leaflet#138]
I'm having a small issue with calling events from the Map, using the code below.

```
invalidateMap = () => {
      if (this.refs.map) {
          this.refs.map.leafletElement.invalidateSize();
      }
  }
```

```
<Map ...
    ref="map"
    onResize={this.invalidateMap()}>
    <TileLayer ... />
</Map>
```

I'm getting the expected behaviour here, because ```invalidateSize()``` is successfully called, but I also receive a leaflet error:

```
leaflet-src.js:461 Uncaught TypeError: Cannot read property 'call' of undefined
```

Looking closer at the error, it appears that the ```'resize'``` event is being fired, but the listener in charge of it is missing it's ```action``` property. Worth noting is that this also happens for other events, like ```onDragEnd```. Similarly, I changed the method to ```stopLocate()``` from ```invalidateSize()``` and same error occurred.

Any ideas why this might be happening?

**Comment by PaulLeCam** [comment]
Hi,
Can you provide a jsfiddle or similar to reproduce the issue please?
You can find a simple one here: https://jsfiddle.net/paul_lecam/q2v7t59h/

**Comment by per-frojdh** [comment]
Try this: https://jsfiddle.net/fa7hd0ko/
In this case I switched out the onResize to onDragEnd to produce the error in an easier fashion.

**Comment by PaulLeCam** [comment]
Looks like your event listener is not properly bound to the instance:
```
<Map ...
    ref="map"
    onResize={this.invalidateMap()}>
    <TileLayer ... />
</Map>
```
is calling `this.invalidateMap()` on every render, not when the event is triggered, it should probably be:
```
<Map ...
    ref="map"
    onResize={this.invalidateMap.bind(this)}>
    <TileLayer ... />
</Map>
```
