### ISSUE TITLE
How to use polyline encoding with this library?

### ISSUE THREAD

**Issue by opensourcegeek** [PaulLeCam/react-leaflet#139]
First of all this is a brilliant library, really intuitive to use. Thanks for that.

I was wondering if I could somehow use https://github.com/jieter/Leaflet.encoded for encoding/decoding polylines. I can possibly use standalone version of the algorithm outside leaflet to encode/decode but it would be nicer if I could use that plugin with react-leaflet itself. Any hints or pointers please?

**Comment by PaulLeCam** [comment]
Thanks for using it, glad it's intuitive to use!

Creating custom components implementing plugins is usually pretty easy, just a matter of interacting with the plugin in React lifecycle methods.
You can have a look at [the documentation](https://github.com/PaulLeCam/react-leaflet#creating-custom-components) and possibly [this similar issue](https://github.com/PaulLeCam/react-leaflet/issues/37) for more information.
