### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by wuyong201006** [PaulLeCam/react-leaflet#141]
Hi PauLeCan,Use example error：react-leaflet.min.js-Uncaught TypeError:Cannot read property 'PropTypes' of undefined;Drag the map out of the container.Can provide a more simple example,thank you!!

**Comment by PaulLeCam** [comment]
Hi,
You are probably missing dependencies (React as it looks like), make sure to load React, ReactDOM and Leaflet **before** this library.
You can have a look at the **External Resources** section in the sidebar of [this example jsfiddle](https://jsfiddle.net/paul_lecam/q2v7t59h/) to see the dependencies included.
