### ISSUE TITLE
Error in navigating away from Map with multiple layers

### ISSUE THREAD

**Issue by jpkeyw** [PaulLeCam/react-leaflet#145]
I have a Map on page. The Map has one or more BaseLayers. (I'm not even sure the utility of a map without a BaseLayer, but....) The Map also has a single Overlay layer. I can navigate to all of the routes in my application without issue until I get to the one that displays the Map. Though the Map works correctly, trying to navigate to another route in my app after hitting the Map gives errors. It appears the initial error is `Uncaught TypeError: Cannot read property 'hasLayer' of null`. The beginning of the trace:

    L.Control.Layers.L.Control.extend._addItem	@	VM6284:8515
    L.Control.Layers.L.Control.extend._update	@	VM6284:8471
    L.Control.Layers.L.Control.extend.removeLayer	@	VM6284:8385
    removeLayer	@	VM6445:220
    removeLayer

My component is simply a repackaging of the render function from the layers-control example inside my own component, so I'm not including any code snippets.

Further testing seems to indicate that this only happens when there are more than one layer within the LayersControl element. If the LayersControl contains only a single layer -- whether it's a BaseLayer or an Overlay containing any number of  Markers, Circles, etc -- then navigation away works fine.

**Comment by jeffshaver** [comment]
In `MapControl.jsx`s componentWillUnmount, you run `this.leafletElement.removeFrom(this.props.map)`. However, in `componentWillUnmount`, while `this.leafletElement` is defined, `this.leafletElement.removeFrom` is undefined. I am not why or how to fix this though.

**Comment by PaulLeCam** [comment]
Hi,
It should be fixed in v0.11.2, please let me know if you have any problem using this new release.

**Comment by jpkeyw** [comment]
Excellent. It appears that this issue has been fixed. Thanks.
