### ISSUE TITLE
Dynamic props not translating to view after state change with redux

### ISSUE THREAD

**Issue by nickyromeijn** [PaulLeCam/react-leaflet#149]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior
Dynamic props automatically updating path

### Actual behavior
They're not being updated at all. Props are actually being updated by redux but Leaflet dynamic prop changes aren't being displayed. (New multiPolyLine isn't being drawn when polylines prop changes.

```
getLatLngarray(GmapDirectionData){
 //pseudo code (works properly)
 return { rootList: array(withLatLngObjects) }
}

getMap() {
                var obj = this.getLatLngarray(this.props.dashboard);
                const position = obj.start;
                console.log("GETTING MAP", "RE-RENDER");
                return (<Map ref="map" style={style.map} center={position} zoom={13}>
                    <TileLayer
                        url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
                        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                    />
                    <Marker position={position}>
                        <Popup>
                            <span>A pretty CSS3 popup.<br/>Easily customizable.</span>
                        </Popup>
                    </Marker>
                    {this.getMarkers(obj.endLocations)}
                    <Path fill={true}>
                        <MultiPolyline polylines={obj.rootList}></MultiPolyline>
                    </Path>
                </Map>)
    }

retrieveDirectionDataFor(){
 //REDUX ACTION (Triggers state change)
 this.props.getDirections(this.refs.driverId.value);
}

render(){
<select ref="driverId" onChange={this.retrieveDirectionDataFor.bind(this)}>
        <option value="">Select a driver...</option>
        {Drivers.map(function (e) {
                return (<option value={e.driver_number}>{e.name}</option>)
        })}
</select>
  this.getMap()
}
```

So as seen in above code there's a simple dropdown which changes the component state when changed. All the props get updated properly (tested) and It also triggers the render method accordingly; but it doesn't reflect on the leaflet map.

--Editted (Added code samples)

Redux, React-leaflet

**Comment by PaulLeCam** [comment]
Steps to reproduce?

**Comment by nickyromeijn** [comment]
Added code samples

**Comment by PaulLeCam** [comment]
Hard to say what could be the issue looking at your code, but here is a working example of dynamic polylines and color: http://jsfiddle.net/mf9z320t/
Unless there is a very particular edge case, I expect the issue is likely with your application not injecting the needed data to the components.
