### ISSUE TITLE
`opacity` of `TileLayer` isn't updated

### ISSUE THREAD

**Issue by mdebbar** [PaulLeCam/react-leaflet#151]
From a quick look at the code: `BaseTileLayer` handles updating the opacity but `TileLayer`'s `componentDidUpdate` isn't calling `super.componentDidUpdate`.

**Comment by PaulLeCam** [comment]
Thanks for reporting this issue, it's been fixed in v0.11.4.

**Comment by mdebbar** [comment]
Thanks for the quick fix @PaulLeCam. That definitely increases my confidence in the library 😄 
Keep up the good work!
