### ISSUE TITLE
Map won't fitBounds when options change

### ISSUE THREAD

**Issue by SereznoKot** [PaulLeCam/react-leaflet#157]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior
fitBounds is called when boundsOptions changed

### Actual behavior
fitBounds is called only when bounds change
That means that changes in Map padding or maxZoom will not affect rendering, unless you change bounds as well

**Comment by PaulLeCam** [comment]
Hi,
Thanks for reporting this, it should be fixed in v0.11.5.
