### ISSUE TITLE
How can I use CanvasTileLayer inside a <Map>?

### ISSUE THREAD

**Issue by Charmatzis** [PaulLeCam/react-leaflet#161]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this jsfiddle](https://jsfiddle.net/paul_lecam/q2v7t59h/).

Could you provide a simple example with CanvasTileLayer ?
THX and great job!!!

**Comment by PaulLeCam** [comment]
Hi,
The CanvasTileLayer simply passes its props to Leaflet `tileLayer.canvas()` function, please refer to [its documentation from Leaflet](http://leafletjs.com/reference.html#tilelayer-canvas).
