### ISSUE TITLE
LayerControl does not work correctly

### ISSUE THREAD

**Issue by fschimandl** [PaulLeCam/react-leaflet#163]
Hey ... thx for this awesome lib!

Currently I'm having issues with the LayerControl-Component. Even the simplest example does not work correctly for me.

When using the following within my render() method:
```
<Map id="map" ref="map" center={position} zoom={8} onContextMenu={this.handleClick}>
        <ZoomControl position="topright" />
        <LayersControl position="topright" >
          <BaseLayer checked name="Karte">
            <TileLayer
            url='http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png'
            attribution='&nbsp;&nbsp;&nbsp;<table style="display:inline-block; vertical-align: middle; text-align: right;"><tr><td style="vertical-align: bottom;">Map imagery/data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy;, <a href="http://cartodb.com/attributions">CartoDB</a>.</td><td rowspan=2>&nbsp;&nbsp;&nbsp;</td></tr><tr><td style="vertical-align: top;" ><td></tr></table>'
            unloadInvisibleTiles={true}
            updateWhenIdle={true}
            reuseTiles={true}
            />
          </BaseLayer>
        </LayersControl>
      </Map>
```
I get the following error messages: 
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `...`.`

When working without the LayersControl everything is working fine. Maybe you can just help me out with that.

Thanks a lot,
Flo

**Comment by PaulLeCam** [comment]
Hi,
This is a pretty self-explanatory error from React: one of the components you are trying to use is not valid, please make sure you are correctly importing the components you are trying to use.

**Comment by fschimandl** [comment]
My import looks like this:
```
import React from 'react';
import ReactDOM from 'react-dom';
import L from 'leaflet';
import $ from 'jquery';
import _ from 'underscore';
import { Map, Marker, CircleMarker, Polyline, TileLayer, Popup, ZoomControl, GeoJson, LayerGroup, LayersControl, FeatureGroup }  from 'react-leaflet';
const { BaseLayer, Overlay } = LayersControl;
```
Anything wrong with it?

Thx for help!

**Comment by PaulLeCam** [comment]
Hard to say just from the imports, I suppose if you `console.log()` each component you would find one is undefined.
