### ISSUE TITLE
Obtaining Leaflet element in stateless functional component

### ISSUE THREAD

**Issue by evenfrost** [PaulLeCam/react-leaflet#164]
Hello Paul, thanks for the job you've done on this lib.
I'm using stateless components in my project, and  it seems there is no way to access Leaflet element (`getLeafletElement()` can't be called as there is no `ref`). E.g. 'onMoveend' event listener gets `event` argument which `target` prop doesn't have reference to Leaflet element to operate with map methods. [Example here.](https://jsfiddle.net/q2v7t59h/17/)

My code is:
```jsx
// map.jsx
import React, { PropTypes } from 'react';
import { Map, Marker, Popup, TileLayer } from 'react-leaflet';
import { mapbox } from './config.json';

const tiles = `${mapbox.tiles}?access_token=${mapbox.token}`;
const RootMap = ({ pos, position, handleMoveend }) => (
  <div>
    <Map center={position} zoom={13} className="root map" style={{ height: '100vh' }} onMoveend={handleMoveend}>
      <TileLayer url={tiles} />
      {pos.map(item => (
        <Marker position={[item.location.lat, item.location.lng]} key={item.id}>
          <Popup>
            <span>{item.name}</span>
          </Popup>
        </Marker>
      ))}
    </Map>
  </div>
);

RootMap.propTypes = {
  pos: PropTypes.array,
  position: PropTypes.array,
  onMoveend: PropTypes.func,
};

export default RootMap;
```
```jsx
// container.jsx
import { connect } from 'react-redux';
import RootMap from './map';

const mapStateToProps = state => ({
  pos: state.pos,
  position: state.position,
});

const mapDispatchToProps = dispatch => ({
  handleMoveend: event => {
    const map = event.target;
    console.log('map', map); // neither leafletElement prop nor getLeafletElement() method here
  },
});

export default connect(mapStateToProps, mapDispatchToProps)(RootMap);
```

**Comment by evenfrost** [comment]
Well, it seems `event.target` itself is a Leaflet element. Don't know how I couldn't have it managed before, but now it works flawlessly.

**Comment by TylerGriffin99** [comment]
How did you end up solving this @evenfrost ?

**Comment by jketcham** [comment]
I had an issue not directly related to this, but where I was trying to render the Map within a stateless component and it created some odd issues. Sometimes when the component was loaded, an exception would be thrown complaining about the element being undefined when it was trying to get its position. Eventually I just rendered the Map in a class based component and all the issues went away.

**Comment by evenfrost** [comment]
@evenfrost Sorry, don't remember, it was literally years ago. :sweat_smile:
