### ISSUE TITLE
Changing position of ZoomControl?

### ISSUE THREAD

**Issue by bduffany** [PaulLeCam/react-leaflet#165]
I am not sure how to change the position of the default `ZoomControl`, even after reading through the docs. If I simply add a new element like `<ZoomControl position="topright" />`, then I get two zoom controls.

Is there a preferred way of doing this? Or is this functionality not supported?

**Comment by bduffany** [comment]
Nevermind, I think the way to do this is

`<Map zoomControl={false}>`

then add my own `ZoomControl`. Please let me know if there is a better way!

**Comment by rhewitt22** [comment]
This is the same way you do this with the core Leaflet library, too. (i.e. there's no better way).
