### ISSUE TITLE
Control map as a classic input field

### ISSUE THREAD

**Issue by benzen** [PaulLeCam/react-leaflet#168]
### Expected behavior
Using this kind of code

````jsx
<Map bounds={bounds} onMapmove={handleMapMove}>
`````

and

`````
  const handleMapMove = (event) => {
    const bounds = event.target.getBounds() 
    const topLeft = bounds.getNorthWest()
    const bottomRight = bounds.getSouthEast()
    const customBounds = {
      topLeft:{
        lat: topLeft.lat,
        lng: topLeft.lng
      },
      bottomRight: {
        lat: bottomRight.lat,
        lng: bottomRight.lng
      }
    }
    onMapMove(customBounds)
  }
`````
I expect to be able to control the map just like i can control an input field

### Actual behavior

What happens is that sometimes when zooming in the map will jump back and forth.

Is there a better way to solve this ?

**Comment by PaulLeCam** [comment]
Hi,
Leaflet maintains its own state of the map, and this lib simply uses components and props as an abstraction on top of Leaflet, so it's up to your application to work around Leaflet's model.

**Comment by shackbarth** [comment]
FWIW, I've found the best way to strongarm the leaflet events into a more declarative pattern is something like the following:


```
  render() {
    const bounds = SOME_INITIAL_BOUNDS;

    ...

    <Map
      bounds={this.state.zoom ? undefined : bounds}
      center={this.state.zoom ? { lat: this.state.lat, lng: this.state.lng} : undefined}
      zoom={this.state.zoom}
      onMoveEnd={this.mapEvent}
      onZoomEnd={this.mapEvent}
    >

    ...

  }
  mapEvent(event) {
    const { lat, lng } = event.target.getCenter();
    this.setState({ lat, lng, zoom: event.target.getZoom() });
  }
```

Basically, as soon as we use the leaflet events to change the map state we stop using bounds to drive the map, and instead use our reacty state, which follows the leaflet state.
