### ISSUE TITLE
Make TileLayer subdomains dynamic

### ISSUE THREAD

**Issue by moimael** [PaulLeCam/react-leaflet#17]
Hi,

I need to be able to switch tilelayers in my app. It works fine if all tilelayers have the same subdomains. But if I mix tilelayers with different subdomains, it does not work because subdomains option is static.

Sample code : 

```JavaScript
    if (this.props.mapState.baseLayer === 'road') {
      baseLayer = <TileLayer
          url="http://{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.png" subdomains={['otile1', 'otile2', 'otile3', 'otile4']} />;
    } else if (this.props.mapState.baseLayer === 'satellite') {
      baseLayer = <TileLayer
          url="http://{s}.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.png" subdomains={['otile1', 'otile2', 'otile3', 'otile4']} />;
    } else if (this.props.mapState.baseLayer === 'cycle') {
      baseLayer = <TileLayer
          url="http://{s}.tile.opencyclemap.org/cycle/{z}/{x}/{y}.png" subdomains={['a', 'b', 'c']} />;
    }
```

**Comment by PaulLeCam** [comment]
Hi,

There is no subdomains setter in Leaflet TileLayers so it can't be made dynamic here, see http://leafletjs.com/reference.html#tilelayer

I suppose a solution is to set the `key` property on each TileLayer component so that React would add/remove them accordingly.

**Comment by moimael** [comment]
key property works fine, thx !
