### ISSUE TITLE
Help with pattern for async load and creation of component and adding to Map when data is ready

### ISSUE THREAD

**Issue by MichaelMarkieta** [PaulLeCam/react-leaflet#171]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

Hi all, what is the pattern for adding new components like `<GeoJson />` to my `<Map />` after `<Map />` has already been rendered on the DOM.

I have a large GeoJson coming from postgresql which I want to load onto the map after its rendered, instead of blocking the map rendering until its load has completed:

```
import React, {Component, PropTypes} from 'react';
import Promise from 'bluebird';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Map.scss';

class LeafletMap extends Component {

  constructor(props, context) {
    super(props, context);

    this.state = {
      buildingsgeojson: []
    };
  };

  fetchBuildingsGeoJSON = () => {
    var scope = this;
    return new Promise(function (resolve) {
      fetch('http://localhost:8000/buildingsgeojson/?format=json')
        .then(function (res) {
          return res.json();
        }).then(function (json) {
        scope.setState({buildingsgeojson: json});
        resolve();
      });
    })
  }

  componentDidMount() {
    var scope = this;

    const {render} = require('react-dom');
    const {Map, TileLayer, GeoJson} = require('react-leaflet');
    const position = [52.2522514, 5.2122977];
    var tileserver = 'http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png';

    if (window.devicePixelRatio >= 2) {
      tileserver = tileserver.replace('.png', '@2x.png');
    }

    this.fetchBuildingsGeoJSON().then(function () {
      const map = (
        <Map className={s.map} id='map' center={position} zoom={7}>
          <TileLayer
            url={tileserver}
            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            opacity={0.75}
          />
          <GeoJson data={scope.state.buildingsgeojson}/>
        </Map>
      );
      render(map, document.getElementById('map-container'));
    })
  }

  render() {
    return (
      <div className={s.root} id='map-container'>
      </div>
    );
  }

}

export default withStyles(LeafletMap, s);

```

Please provide the simplest example possible to reproduce the issue, based on [this jsfiddle](https://jsfiddle.net/paul_lecam/q2v7t59h/).

**Comment by PaulLeCam** [comment]
Hi,
I'm closing this issue as it's not directly related to this lib but a broader question about asynchronous data management and rendering with React. There are different resources on this subject but it mostly depends on your application needs and the stack you are using.
