### ISSUE TITLE
Change a Control based on state

### ISSUE THREAD

**Issue by njbarrett** [PaulLeCam/react-leaflet#173]
Hey there,

Firstly, great work with this implementation of leaflet in react.
I'm having a hard time wrapping my head around how to change a control based on the react state. Here's my FreeDrawControl component:

```
import React from 'react';
import ReactDOM from 'react-dom';
import L from 'leaflet';
import {MapControl} from 'react-leaflet';

export default class FreeDrawControl extends MapControl {

    componentWillMount() {
        const freeDrawControl = L.control({position: 'topright'});

        var freeDrawButtonText;
        if (this.props.freeDraw.mode === L.FreeDraw.MODES.CREATE) {
            freeDrawButtonText = 'Drawing Search';
        }
        else {
            freeDrawButtonText = 'Draw Search';
        }

        const jsx = (
            <div {...this.props}>
                {freeDrawButtonText}
            </div>
        );

        freeDrawControl.onAdd = function (map) {
            let div = L.DomUtil.create('div', '');
            ReactDOM.render(jsx, div);
            return div;
        };

        this.leafletElement = freeDrawControl;
    }
}
```

Now all this code is in `componentWillMount` so only runs once. How can I make it so the `freeDrawButtonText` changes when the state changes? Because all of the rendering is done in the `componentWillMount` I cant figure out how to change the control afterwards.

Thanks in advance for any help.

**Comment by jgimbel** [comment]
If you are willing to use an outside component I created `react-leaflet-control` for this kind of thing.

```js
import React from 'react';
import ReactDOM from 'react-dom';
import L from 'leaflet';
import Control from 'react-leaflet-control';

export default (props) => (
  <Control 
    map={this.props.map}
    layerContainer={this.props.layerContainer}
    position='topright'
  >
    {
      (props.freeDraw.mode === L.FreeDraw.MODES.CREATE)
        ? 'Drawing Search'
        : 'Draw Search'
    }
  </Control>
)

```

**Comment by PaulLeCam** [comment]
Hi,
You probably want to use React's [lifecycle methods](https://facebook.github.io/react/docs/component-specs.html#lifecycle-methods) to update the Leaflet element when the props change, this is pretty much how this entire lib works.
The [MapControl component](https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapControl.js) should be a good example to reproduce or directly extend depending on your needs.

**Comment by njbarrett** [comment]
Thanks @jgimbel I think your component will help achieve what I need.

**Comment by banisirohi** [comment]
I'm also having tough time integrating leaflet freedraw with react-leaflet. And to make it behave consistent with react-leaflet-draw. Did you able to achieve any solution through react-leaflet-control. I'm clueless how to make it work that way. Thanks.

**Comment by elangobharathi** [comment]
@banisirohi I have created a plugin [react-leaflet-freedraw](https://github.com/elangobharathi/react-leaflet-freedraw) for leaflet freedraw integration. Please take a look at it and let me know if you encounter any issues.

**Comment by ChaitanyaKrishnaPappala** [comment]
thanks @jgimbel, your package is a real help to avoid dealing with state handling in react when using with leaflet
