### ISSUE TITLE
Support for zoomend on Map component?

### ISSUE THREAD

**Issue by thenickcox** [PaulLeCam/react-leaflet#174]
Thanks a lot for this library. It's making my life easier.

I need to attach some logic to the `zoom` property of the `<Map />` component. You can pass it in, but I don't see a way to attach an event to zooming. I tried to add a `scroll` event listener to `window` on `componentDidMount`, but scroll wheel zooming doesn't fire window scroll. I can't quite figure out how to access leaflet's `getZoom`. It [appears in the tests](https://github.com/PaulLeCam/react-leaflet/blob/74659d90d30ad106ba45fb67fde02b9aca30a645/__tests__/Map.js#L37), but it's not clear to me how to access that, or attach a handler to zooming.

It looks like Leaflet has a `zoomend` event, but I can't figure out how to attach that to the `<Map />` component. It seems like [it's in the `props` of the Map](https://github.com/PaulLeCam/react-leaflet/blob/master/lib/Map.js#L87). But can I access that?

**Comment by thenickcox** [comment]
I tried something along these lines

```javascript
import { Map } from 'react-leaflet';
import { map } from 'leaflet';

export default class MapWithZoom extends Map {
  componentWillMount() {
    super.componentWillMount();
    this.leafletElement = map(this.props);
  }

  componentDidUpdate(newProps) {
    console.log(newProps.zoom);
  }
}
```

That wasn't working. I'm sure I did something wrong.

**Comment by thenickcox** [comment]
Sorry, I promise I read the docs and tried things before filing this issue! If anyone else looks here, this is referenced in the [Events API docs](https://github.com/PaulLeCam/react-leaflet#events).

**Comment by arusahni** [comment]
For those of you who tried clicking the now-broken link in the previous comment, the solution is to add the `onZoomend` property to your `Map` component declaration.

e.g.:
```js
<Map onZoomend={this.onZoomEvent}>
</Map>
```

**Comment by thenickcox** [comment]
Thanks, @arusahni. I think the take-away is that the `<Map />` component supports all the events in the [official leaflet event docs](http://leafletjs.com/reference.html#map-events), simply prefixed with `on`, e.g., `zoomEnd` -> `onZoomEnd`.

**Comment by peteruithoven** [comment]
How to do this these days? 
`MapContainer` instead of `Map` seems to be used in all examples, but `MapContainer` has no onZoom etc. 
> Property 'onZoom' does not exist on type 'IntrinsicAttributes & MapContainerProps & RefAttributes<Map>'. Did you mean 'zoom'?
