### ISSUE TITLE
Load geojson data

### ISSUE THREAD

**Issue by calivet** [PaulLeCam/react-leaflet#176]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x ] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Check that you are using a supported version of React (v0.14 or v15).
- [x ] Check that you are using a supported version of Leaflet (v.0.7)
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

Hello,

I'm trying to load GeoJson data with appropriate marked (geojson tag with geojson object in data options).
I think the syntax is good because reactjs doesn't return error. But nothing is display on map.
I tried in an other project with leaflet only, and the data appears well.

Is this feature has been tested ? Is it possible to have an example ? 

Thank you

**Comment by jgimbel** [comment]
[Here](https://jsfiddle.net/e3zh51fp/7/) is a jsfiddle exmaple of using geojson.

**Comment by calivet** [comment]
Thank you very much !
