### ISSUE TITLE
Leaflet-fullscreen with react-leaflet?

### ISSUE THREAD

**Issue by jpkeyw** [PaulLeCam/react-leaflet#179]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

I'd like to incorporate the [Leaflet.fullscreen](https://github.com/Leaflet/Leaflet.fullscreen) plugin. Without react, it's as simple as linking the js and css and adding `fullscreenControl: true` to the MapOptions. Unfortunately, it doesn't seem so straightforward with react-leaflet. If you link the javascript file, you get an error (due to it trying to load leaflet-fullscreen before leaflet itself).

How would you recommend using both this module and the fullscreen plugin? Perhaps the fullscreen module could be incorporated directly into react-leaflet?

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://github.com/PaulLeCam/react-leaflet#creating-custom-components) section of the documentation.

**Comment by jeffshaver** [comment]
@PaulLeCam I have read that section of the README.md, but I am still not 100% of how this should be implemented. Are there any examples of implementations for other plugins?

**Comment by PaulLeCam** [comment]
It really depends on your needs and the plugin you want to implement, but it's usually about implementing React's lifecycle handlers. You can have a look at the [Rectangle](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Rectangle.js) component for a very simple example.

**Comment by elangobharathi** [comment]
I have created a plugin to integrate [leaflet.fullscreen](https://github.com/brunob/leaflet.fullscreen). Please check this out - https://github.com/elangobharathi/react-leaflet-fullscreen-plugin and provide me your feedback. Thanks.
