### ISSUE TITLE
New features to react-leaflet

### ISSUE THREAD

**Issue by Charmatzis** [PaulLeCam/react-leaflet#186]
Hi, I have been working with your react-leaflet and I have created some more features for your project.

Please, take a look and if you want you can merge them to your.

-  [react-leaflet-google ](https://github.com/Charmatzis/react-leaflet-google)
- [react-leaflet-bing ](https://github.com/Charmatzis/react-leaflet-bing)
- [react-leaflet-shapefile ](https://github.com/Charmatzis/react-leaflet-shapefile)

Also, it would be a great idea to start combine all this extensions to your project.

Yours truly,
X.

**Comment by PaulLeCam** [comment]
Hi,

I want to keep this project as a simple interface for Leaflet and not its entire ecosystem, so I find having plugins as other npm modules a good solution.
I added a [plugins](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Plugins.md) section to the documentation, please feel free to send PRs to update this list!

**Comment by jakehm** [comment]
Can you put a link to the plugins in the root readme rather than just the readme in the docs?
