### ISSUE TITLE
Using child component attributes

### ISSUE THREAD

**Issue by heeton** [PaulLeCam/react-leaflet#188]
- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

Consider a component like this: 

```
<Map bounds={bounds}>
  <TileLayer />
  <GeoJson data={featureJson} />
</Map>
```

There's an issue If you need to set the map bounds according to the bounds of the GeoJson layer. In plain leaflet this would be accessed as `geoJson.getBounds()`. 

I'm struggling to find a clean way to do this. Any advice on an idiomatic approach?

**Comment by jgimbel** [comment]
The [events](https://github.com/PaulLeCam/react-leaflet/blob/0b88c1896692823532fffe5f9971cf8a83e0b95d/example/components/events.js) example shows how you can use refs to be able to get the raw leaflet element from a child component. From there you can do ...
```js
componentDidMount(){
  const { map, geojson } = this.refs
  map.leafletElement.setBounds(geojson.leafletElement.getBounds())
}

```

**Comment by heeton** [comment]
@jgimbel I tried a nastier version of this, but your example is good, thanks.
