### ISSUE TITLE
What sort of array is the FeatureGroup expecting?

### ISSUE THREAD

**Issue by ktmn** [PaulLeCam/react-leaflet#19]
I was expecting to do:

    <Map...>
        <TileLayer ... />
        <FeatureGroup ref="features">
            <Marker position={[0, 0]}></Marker>
            <Marker position={[1, 1]}></Marker>
            <Marker position={[2, 2]}></Marker>
        </FeatureGroup>
    </Map>

But I get a warning:
    Failed propType: Required prop `layers` was not specified in `FeatureGroup`. Check the render method of `AsdComponent`.

What should I pass as layers? I was under the impression that markers *are* the layers.

Also this Error appears for every other Marker I nest in FeatureGroup. If it's only 1 marker it's fine.

    Danger: Discarding unexpected node: <noscript data-reactid=".0.$=11:0.$=11:0"></noscript>

Ultimately what I'm trying to do is pass a FeatureGroup to [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) so I can edit features using this plugin.

**Comment by PaulLeCam** [comment]
Hi,

`<FeatureGroup>` only passes its `layers` property to [`Leaflet.featureGroup()`](http://leafletjs.com/reference.html#featuregroup), the only child that can be set is a `<Popup>`.
