### ISSUE TITLE
Centralize all markers automatically

### ISSUE THREAD

**Issue by tiagocedrim** [PaulLeCam/react-leaflet#190]
Hello everybody.

I have two markers , one in the United States and the other in Brazil , I can not center the map with all the markers automatically.

### Expected behavior

<img src="https://monosnap.com/file/CKca7xFaskbYMg3JrmX1xosofgtFLi.png">

### Actual behavior

<img src="https://monosnap.com/file/Ky0RNmokugCZShYfxbNkvcmPGjOTCg.png">

Here is an example of code

https://jsfiddle.net/hqjv5utx/

**Comment by PaulLeCam** [comment]
Hi,
The map's `center` is applied as expected, there is no "automatic" center, it's up to your application to set it.
You probably want to use something like [Leaflet's latLngBounds()](http://leafletjs.com/reference.html#latlngbounds-l.latlngbounds) to create the bounds to inject to the map.

**Comment by tiagocedrim** [comment]
@PaulLeCam What would be the best way to achieve this with the code below ?

https://jsfiddle.net/hqjv5utx/

**Comment by nguyendh2601** [comment]
Hi @tiagocedrim,
As your code above, you could you *bounds* to achieve your expectation. 
FYI

> bounds: bounds (optional): A rectangle for the map to contain. It will be centered, and the map will zoom in as close as it can while still showing the full bounds. This property is dynamic, if you change it it will be reflected on the map.

**Comment by tiagocedrim** [comment]
@PaulLeCam Thanks, worked perfectly :metal:

**Comment by ihor-doroschenko** [comment]
Thanks, works great!

**Comment by QauseenMZ** [comment]
THANKS A LOT!!!

**Comment by atefBB** [comment]
@nguyendh2601 Thx! Save my day!
