### ISSUE TITLE
[question] Possibility to use it with custom Marker ? What about performance ?

### ISSUE THREAD

**Issue by TimoRuetten** [PaulLeCam/react-leaflet#191]
I am sorry if this is the wrong place for this kind of question.

Currently I am using leaflet for our Map but I am using it with this plugin:
https://github.com/SINTEF-9012/PruneCluster

Now I have 2 questions.

1. Is it possible to use this plugin with the included <Marker /> Component ?
2. What about performance ? We are using this Plugin because in a few views of the Map it could be possible that there are about 100.000 Markers (or even more) - is it really a good idea to use 100.000 <Marker /> components ?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.

**Comment by TimoRuetten** [comment]
You're absolutly right. I will post to Stackoverflow! Thanks
