### ISSUE TITLE
add support for divicon

### ISSUE THREAD

**Issue by benzen** [PaulLeCam/react-leaflet#193]
Leaflet api now has divicon support can we add it to react-leaflet.
Or it's trivial to add, and we can do it outside of this library

**Comment by PaulLeCam** [comment]
Hi, you can already use `DivIcon`s, you simply need to generate them from Leaflet, ex:
```js
import { divIcon } from 'leaflet'
import { Marker } from 'react-leaflet'

const icon = divIcon({className: 'my-div-icon'})
const marker = <Marker icon={icon} ... />
```

**Comment by benzen** [comment]
Really nice thanks

**Comment by cherouvim** [comment]
The example you provided is nice, but it doesn't use any custom HTML. Is it possible to have react generated HTML (JSX) into that leaflet `divIcon`?

**Comment by wmertens** [comment]
@cherouvim https://stackoverflow.com/questions/37079847/is-it-ok-to-use-reactdomserver-rendertostring-in-the-browser-in-areas-where-reac
