### ISSUE TITLE
v1 release plan

### ISSUE THREAD

**Issue by PaulLeCam** [PaulLeCam/react-leaflet#197]
Now that Leaflet v1 is well under way and React started to use major versions, React-Leaflet will move to [semantic versioning](http://semver.org/) as well, which means:
- Only Leaflet v1+ will be supported, v0.12 of React-Leaflet will be the last version compatible with Leaflet v0.7.
- Only React v15+ will be supported. It's likely React v0.14 would still work fine but v15 has been released for a while so most apps should already be using it anyways.
- React follows semantic versioning and until now has also made new releases supporting the previous release API with eventual warnings, so in theory React v16 should not need a new major version of React-Leaflet. Hopefully Leaflet will also be strict in respecting semantic versioning, but otherwise React-Leaflet will apply it anyways, meaning if Leaflet v1.1 has a breaking API change affecting React-Leaflet, it would be supported in React-Leaflet v2.0.
- Until Leaflet v1 final is released, React-Leaflet v1 will only have beta releases (available on npm with the `next` tag) for as long as there bugfixes and features to add. Once Leaflet v1 is finally released and if there is no pending issue with React-Leaflet, a first release candidate will be made, with other ones if necessary until the library is stable enough for a final v1 release.

Changes can be tracked in [this pull request](https://github.com/PaulLeCam/react-leaflet/pull/196) and the [v1.0 milestone](https://github.com/PaulLeCam/react-leaflet/milestone/2).
Once beta releases are published, please try them as much as possible to make sure most issues get reported and fixed before the stable release!

If you have any question or suggestion regarding this release plan, please feel free to comment below.

**Comment by Dahlgren** [comment]
Leaflet 1.0 was just released, http://leafletjs.com/2016/09/27/leaflet-1.0-final.html 🎉

**Comment by mbritton** [comment]
Thanks for the excellent work. Is there an ETA on the rc for react-leaflet that supports the complete Leaflet v1 feature set?

**Comment by zavan** [comment]
I upgraded from leaflet rc3 to final and now i'm getting: 
```
GET http://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.0-rc.3/imagesmarker-icon.png 404 (Not Found)
GET http://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.0-rc.3/imagesmarker-shadow.png 404 (Not Found)
```
When rendering markers:
```html
<div class="leaflet-pane leaflet-marker-pane">
  <img src="//cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.0-rc.3/imagesmarker-icon.png" class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" tabindex="0" style="margin-left: -12px; margin-top: -41px; width: 25px; height: 41px; transform: translate3d(605px, 190px, 0px); z-index: 190; outline: none;">
</div>
```

Downgrading to rc3 works.
The url is different: `http://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.0-rc.3/images/marker-icon.png`

**Comment by Dahlgren** [comment]
See #229

**Comment by PaulLeCam** [comment]
v1.0.0 RC 1 released, still under the "next" tag.

**Comment by PaulLeCam** [comment]
v1.0.0 RC 2 released, please try it out!

**Comment by tconroy** [comment]
Hey there! great work on these components, they're pretty amazing. Was wondering if you had an ETA on the v1 release? I noticed there's an open PR regarding it ( but appears to be a WIP? ). Going to be using this guy in a production app within a few weeks and would love to use 1.0.

**Comment by prewk** [comment]
Hi, where do you want the RC2 bugs reported? In the PR?

**Comment by PaulLeCam** [comment]
Preferably as new issues please, make sure to indicate the versions of the libraries you are using, thanks!

**Comment by PaulLeCam** [comment]
v1 is here! https://github.com/PaulLeCam/react-leaflet/releases/tag/v1.0.0

**Comment by tconroy** [comment]
awesome work, @PaulLeCam! 👏 👏
