### ISSUE TITLE
Polyline's method "bringToBack" raises error when polyline is nested within a LayerGroup

### ISSUE THREAD

**Issue by evansiroky** [PaulLeCam/react-leaflet#199]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x ] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Check that you are using a supported version of React (v0.14 or v15).
- [ x] Check that you are using a supported version of Leaflet (v.0.7)
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

When a Polyline that is nested within a LayerGroup has its method "bringToBack" invoked, it should move the polyline to the back of the map.

### Actual behavior

The error `Uncaught TypeError: Cannot read property '_pathRoot' of undefined` is raised.

### Steps to reproduce

It does work if the polyline is not within a LayerGroup (see https://jsfiddle.net/m5gatktz/2/).  However, it does cause an error if the polyline is within a LayerGroup (see https://jsfiddle.net/m5gatktz/3/).  I'm a bit new to leaflet, so I'm not sure if I'm doing it right by putting a Polyline within a LayerGroup.

**Comment by PaulLeCam** [comment]
Hi,
Thanks for the detailed explanation.

I think the issue comes from the fact you are calling `bringToBack()` in the `ref` handler of `Polyline` instead of the `componentDidMount()` handler of your containing component, so the Map is not initialised yet, see https://jsfiddle.net/m5gatktz/4/
