### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by gneutzling** [PaulLeCam/react-leaflet#20]
Hi,

I am trying to use react-leaflet in a isomorphic js project with webpack and leaflet its returning `window is not defined`. Is there any reason to use window object in the server side?

**Comment by PaulLeCam** [comment]
Hi,

This lib doesn't use window or other DOM APIs directly, but Leaflet, which is a dependency, does.

**Comment by revolunet** [comment]
try this solution : https://github.com/etalab/adresse.data.gouv.fr/blob/0bc6dd7/pages/map.js#L5-L12
