### ISSUE TITLE
Popup always open

### ISSUE THREAD

**Issue by tiagocedrim** [PaulLeCam/react-leaflet#200]
Hello guys, is there any way popup always stay open ? Not having the need to click on it to open.

### Expected behavior
<img src="https://monosnap.com/file/mPkuSTmPAfwxTxY99YQVA5m96Zolow.png">

### Actual behavior
<img src="https://monosnap.com/file/frmxaG3C7ow9DSB2cF6XucvL0JTn2i.png">

**Comment by jgimbel** [comment]
Hi, we try to answer how-to questions on StackOverflow, and use issues for bugs in the library. You can use the react-leaflet tag in StackOverflow for how-to questions. They usually get answered with examples in 24 hours.

**Comment by tiagocedrim** [comment]
Hi @jgimbel thks for the tip :metal:
