### ISSUE TITLE
updating center state of map resets entire UI

### ISSUE THREAD

**Issue by lifeiscontent** [PaulLeCam/react-leaflet#203]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

setting center state on map does not reset entire state of map.

### Actual behavior

setting center state on map resets entire state of map.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this jsfiddle](https://jsfiddle.net/paul_lecam/q2v7t59h/).

https://jsfiddle.net/q2v7t59h/83/

1. watch map position update.
2. change zoom level, watch zoom state revert back to default.

**Comment by PaulLeCam** [comment]
This is working exactly as expected, you are setting the `zoom` property in your `render()` method so it's up to you to handle zoom changes events if you want to keep its value updated.

**Comment by lifeiscontent** [comment]
@PaulLeCam so, how exactly would I keep track of the zoom value? It seems the `Map` component already adds a zoom control by default. How do I hook into the value after its been modified by the UI?

**Comment by drwelby** [comment]
What is the best way to set the options for initializing the map? Could some initialization properties be added? In my case I don't need zoom to be dynamic, but it would be nice to specify the initial zoom as a property such as `initZoom={13}`, or maybe an entire `initOptions` object that is only used when first creating the Leaflet element.
