### ISSUE TITLE
[Solved][markercluster] How to addLayer() to the react-leaflet <Map> component. Layer generated by leaflet plugin.

### ISSUE THREAD

**Issue by YUzhva** [PaulLeCam/react-leaflet#209]
### Actual behavior

> map.addLayer is not a function

or 

> Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {options, _featureGroup, _leaflet_id, _nonPointGroup, _inZoomAnimation, _needsClustering, _needsRemoving, _currentShownBounds, _queue, _animationStart, _animationZoomIn, _animationZoomOut, _animationAddLayer, _markerCluster, _initHooksCalled}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `LayerGroup`.

### Steps to reproduce
```
import React from 'react';

import {Map, Marker, LayerGroup, LayerGroup} from 'react-leaflet';
import L from 'leaflet';
import markerClusterGroup from 'leaflet.markercluster';

export default class Content extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      toggle: false,
      markers: [
         [45.5225581, -122.673447],
         [44.5225581, -122.673447]
       ]
    };
  }

  var markers = L.markerClusterGroup();
  markers.addLayer(L.marker(this.state.marker[0]));
  markers.addLayer(L.marker(this.state.marker[1]));

// FROM Leaflet.markercluster DOCUMENTATION:
// map.addLayer(markers);

  render() {
    return (
   <Map center={[39.50, -98.35]} zoom={3} style={{height: '400px'}}>
      <TileLayer
        url="MY_URL"
        maxZoom={25}
        id="MY_ID"
        accessToken="MY_TOKEN"/>
      <LayerGroup>
      
      </LayerGroup>
    </Map>
    );
  }
}
```

### Expected behavior

How to addLayer of leaflet Plugin to react-leaflet <Map>...</Map>.

Let's say I need make clustering of Markers:

```
var markers = L.markerClusterGroup();
markers.addLayer(L.marker(getRandomLatLng(map)));
```

And add Clustered by leaflet plugin library custom Markers to react-leaflet <LayerGroup>{ClusteredMarkers}</LayerGroup>.

**Comment by mbritton** [comment]
Try giving Map a ref attribute:

```
<Map ref="foo"></Map>
```

Then reference in componentDidMount():
```
const map = this.refs['foo'].leafletElement
```

**Comment by YUzhva** [comment]
@mbritton Thank you, it works well.

Also I improved implementation, by extending react-leaflet LayerGroup:

MyCustomMap => my React Component that using react-leaflet:
```
import React from 'react';
import { Map, TileLayer } from 'react-leaflet';
import ClusteredMapMarkers from './ClusteredMapMarkers';

export default class MyCustomMap extends React.Component {

  constructor(props){
    super(props);
    this.state = {
      position: [],
      zoom: 0
    };
  }

  componentDidMount() {
    this.setState({position: [51.30, 0.7], zoom: 2});
  }

  render() {
    let position = this.props.position || this.state.position;
    let zoom = this.props.zoom || this.state.zoom;
    let maxZoom = this.props.maxZoom || 17;

    const mapStyle = {
      height: ~~this.props.height || 310 + 'px'
    };

    let map = null;
    if (position && position.length) {
      map = (
        <Map center={position} zoom={zoom} style={mapStyle} attributionControl={false}>
          <TileLayer
            url='https://api.mapbox.com/styles/v1/buddymap/{id}/tiles/256/{z}/{x}/{y}?access_token={accessToken}'
            maxZoom={maxZoom}
            id='cirgwba540000h2nx1a7y13y1'
            accessToken='pk.eyJ1IjoiYnVkZHltYXAiLCJhIjoiY2locXQ5dmdnMDAxdXY3a3NjNmw2enYwayJ9.BF8CSctNG-7Q-0unvEJ99g'
          />
          <ClusteredMapMarkers markers={this.props.marks}/>
        </Map>

      );
    }

    return (
      <div className="my-custom-map">
        {map}
      </div>
    );
  }
}

```

ClusteredMapMarkers => Component, that extends LayerGroup of react-reaflet and makes .addLayer() of Clustered by [Leaflet.markercluster Plugin](https://github.com/Leaflet/Leaflet.markercluster) to the react-leaflet <Map> ...

```
import {LayerGroup} from 'react-leaflet';
import L from 'leaflet';
import markerClusterGroup from 'leaflet.markercluster';

export default class ClusteredMapMarkers extends LayerGroup {
  componentWillReceiveProps(nextProps) {

    if(nextProps.markers && nextProps.markers.length) {
      var pinkMarker = L.icon({
        iconUrl: 'custom_marker.png',
        iconSize: [25, 41]
      });
      var clusteredMapMarkers = L.markerClusterGroup();

      nextProps.markers.forEach((marker) => {
        clusteredMapMarkers.addLayer(
          L.marker([marker.Latitude , marker.Longitude], {icon: pinkMarker})
        );
      });
    }

    nextProps.map.addLayer(clusteredMapMarkers);
  }
}
```

.forEach iteration in that component I user, because I receiving specific .json from back-end.

**Comment by mbritton** [comment]
I did something similar, extended FeatureGroup to send map bounds back through the app with an Action. Not sure if this is a best practice, but it works. Wish I knew how to bubble events up the chain in Redux. :D

**Comment by YUzhva** [comment]
Solution:

There is a new package for clustering markers with react-leaflet:
https://www.npmjs.com/package/react-leaflet-markercluster

ES6 Source here:
https://github.com/YUzhva/react-leaflet-markercluster/blob/master/src/react-leaflet-markercluster.jsx
