### ISSUE TITLE
Obtaining the leafletElement

### ISSUE THREAD

**Issue by Frikki** [PaulLeCam/react-leaflet#21]
Say I have a React Component that creates a Map

    render() {
      return (
        <Map ... />
      );
    }

How do I get a handle to the leafletElement?

**Comment by PaulLeCam** [comment]
Hi,

You can use the `getLeafletElement()` function on the `Map` component to get the created Leaflet instance *after* the component is mounted.

Ex:
```js
componentDidMount() {
  this.element = this.refs.map.getLeafletElement();
}

render() {
  return <Map ref='map' .../>;
}
```

**Comment by Frikki** [comment]
Thank you! This works. Btw., is there any reason why the `onLeafletLoad` isn’t implemented?

I was able to get the `load` event to fire by modifying the `Map` component by adding

    render() {
      …
      if ( map )
        map.on( 'load', this.fireLeafletEvent( 'load', this ) );
      …
    }

**Comment by PaulLeCam** [comment]
I have never tried to use the `load` event, it should be implemented as all Leaflet events are simply passed to the Leaflet instance, but it's possible this event is fired just before the event handlers are actually attached.

I assume any logic you would put in a `load` handler could be set in the `componentDidMount` of the containing component, but it really depends on your use case.

**Comment by Frikki** [comment]
Yes. I added the code to obtain the `leafletElement` before you answered 
how to get a hold of it.

**Comment by mikefab** [comment]
I'm trying to pass a reference to a leaflet map as a prop in a nested custom component. It's not working.

In MyMap.jsx I have:

    return (
        <Map ref='map'
          ref={m => {
            this.leafletMap = m;  // Set reference here
          }
          }
          center={[0,0]}
          <TileLayer
            url={this.state.url}
            attribution={this.state.attribution}
          />
          <MyCustomComponent
            leafletMap={this.leafletMap}
            points={geojson}
          />
        </Map>
    )

in MyCustomComponent.jsx

    componentDidMount() {
      console.log(this.props.leafletMap) // undefined
    }

Tried to follow advice from https://github.com/PaulLeCam/react-leaflet/issues/106#issuecomment-161594328, however,  this.refs is an empty object when inspected from componentDidMount in both MyMap.jsx and MyCustomComponent.jsx.

Any advice appreciated. Thank you.
