### ISSUE TITLE
Fix Marker size with custom icon when zooming map

### ISSUE THREAD

**Issue by alexanderfrey** [PaulLeCam/react-leaflet#212]
Hi, 

I'm really having difficult times to fix the size if one marker on my map. 
I already tried to get a reference of the marker in the maps onZoomend callback and adjust the icon size of that marker in relation to the map zoom value. The problem was that I could not get a marker reference that would allow me to change the markers size dynamically. Am I missing some api to fix size of markers ?

Any ideas very much appreciated !

Best,
Alexander

**Comment by PaulLeCam** [comment]
Hi,
You can access the instance of the created Leaflet element for any component after it is mounted using the component's `leafletElement` property.
