### ISSUE TITLE
Popup does not unmount its children if rendered multiple times with different child components

### ISSUE THREAD

**Issue by hannesj** [PaulLeCam/react-leaflet#213]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

ReactDOM.unmountComponentAtNode should be called if the child component is not of the same type as the previously rendered.

### Actual behavior

ReactDOM.unmountComponentAtNode is only called for the last component to be mounted. The documentation states:

`If the ReactElement was previously rendered into container, this will perform an update on it and only mutate the DOM as necessary to reflect the latest React component.`

The reactElement needs to be the same in order for this to be true, if they differ, the new ReactElement is rendered, but the old one is not discarded of.

### Steps to reproduce

https://jsfiddle.net/6vcze6fv/

- Open popup
- Click on span below the popup
- Close popup
- First popup is still visible in React developer tools

**Comment by PaulLeCam** [comment]
Sorry I don't get your issue, the behavior you expect is not the one of this library and it's not supposed to be.
If you want to implement additional logic for rendering popup contents, you should create a custom component.

**Comment by hannesj** [comment]
@PaulLeCam It already calls [`unmountComponentAtNode`](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Popup.js#L83). But only for the last component that has been rendered last in the popup. Now if I change the contents of the popup while it is open, I get memory leaks, as the old render trees are never purged for the components that have been mounted before the last. Do you mean that this is intentional behaviour?

**Comment by PaulLeCam** [comment]
As long as the DOM container is the same, `ReactDOM.render()` handles the diffing and unmounts any previously rendered component so if you get any memory leak, I'd assume it's more likely coming from you app. This library only calls `ReactDOM.render()` for the contents of the Popup, there is no extra logic around it.
