### ISSUE TITLE
Why Marker.js doesn't include a shouldComponentUpdate()?

### ISSUE THREAD

**Issue by MrOutis** [PaulLeCam/react-leaflet#214]
I was just wondering why not include something like:

```js
shouldComponentUpdate(nextProps, nextState) {                                 
  return nextProps.position[0] !== this.props.position[0] &&
         nextProps.position[1] !== this.props.position[1];
}

```
Inside [Marker.js](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Marker.js).

I think people will render Markers as dynamic children, something like:
```js
myMarkersCollection = (latLngList) => (
  latLngList.map(p => <Marker key={p.id} position={p} />)
);
```

The problem here, is that changing one entry of `myPositions` will update all the markers.

Here is a quick example that demonstrate the updates: https://jsfiddle.net/q2v7t59h/97/
_just open your web console and click the button below the map_

*EDIT*:
I don't know if all the `if`s here: https://github.com/PaulLeCam/react-leaflet/blob/0b88c1896692823532fffe5f9971cf8a83e0b95d/src/Marker.js#L34-L53 could be in `shouldComponentUpdate()` or if it's useful to do such thing

**Comment by PaulLeCam** [comment]
The DOM rendering is performed by Leaflet, not React, so it's necessary to call the relevant Leaflet setters when the props change.
This library does not make assumptions or rendering optimizations itself, it only acts as an interface for Leaflet.

**Comment by MrOutis** [comment]
Ok, thanks, @PaulLeCam :ok_hand:
