### ISSUE TITLE
 The library is not working with IE10 , v0.12.1 , but v0.11.7 is fine

### ISSUE THREAD

**Issue by aparij** [PaulLeCam/react-leaflet#215]
Looks like the changes in v.0.12.0 moving from props to context broke it on IE10. 
It works fine with v0.11.7

The map is not initialized

The error message is :
 ReactCompositeComponent.getChildContext(): childContextTypes must be defined in order to use getChildContext(). 

You can run the react-leaflet examples locally and see that none are working .

Not sure why the thing is not working. Babel should properly transpile from the ES7 static childContextTypes

**Comment by PaulLeCam** [comment]
Apparently [IE <= 10 does not support __proto__](https://babeljs.io/docs/usage/caveats/) so IE <= 10 isn't be supported by React-Leaflet from v0.12

**Comment by aparij** [comment]
Or you can add babel-polyfill to thedependencies.

**Comment by PaulLeCam** [comment]
If it works with babel-polyfill, why don't you add it to your app?

**Comment by aparij** [comment]
Well, the thing is I have it and it still doesn't work. Anyways I don't think adding babel-polyfill will help in this case, it's something else.

**Comment by dettier** [comment]
This is the reason it doesn't work in IE <= 10: https://babeljs.io/docs/usage/caveats/
You can just add `protoToAssign` and `loose` options in babel configuration to fix this.

**Comment by webcarrot** [comment]
Version 2.0 work in IE >= 9 with https://www.npmjs.com/package/proto-polyfill
