### ISSUE TITLE
Popup component does not render the popup content

### ISSUE THREAD

**Issue by stoil** [PaulLeCam/react-leaflet#220]
Hi there,

Thanks for bringing this nice library to the public!
I am trying to do some local tests in order to see how everything works and I am encountering a very weird issue which I can not manage to resolve.
The Popup component does not want to render the popup content and instead it renders null (if you look at the react dev tool or empty div if you look in the DOM inspector). I have tried to run the same code (the one from your [jsbin ](https://jsfiddle.net/hu0Lewuz/1/)) both on my local environment and on [codepen](http://codepen.io/kostadinovstoil/pen/YGwabx) and it is all the same. I have also tried with the example code from the get it started section 
```
import React from 'react';
import { render } from 'react-dom';
import { Map, Marker, Popup, TileLayer } from 'react-leaflet';

const position = [51.505, -0.09];
const map = (
  <Map center={position} zoom={13}>
    <TileLayer
      url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
      attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    />
    <Marker position={position}>
      <Popup>
        <span>A pretty CSS3 popup.<br/>Easily customizable.</span>
      </Popup>
    </Marker>
  </Map>
);

render(map, document.getElementById('map-container'));
```
The same problem still occurs. The Popup is empty. 
I have checked and all the requirements and dependencies are installed and included.
Could you please help me with that problem?

Thanks in advance!

**Comment by PaulLeCam** [comment]
Hi,
As your jsfiddle is working it's most likely an issue with your environment, make sure you've followed all the installation steps.

**Comment by rusffer** [comment]
Hi all, 
I had the same issue.
*stoil*, it is because you are using styles from newest version of leaflet
Try to use same version as in example:
`https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css`

**Comment by stoil** [comment]
First of all, I am sorry for my late answer. 
Thank you very much **rusffer**, your solution worked and now the popup works fine.
