### ISSUE TITLE
On-click event handler broken in pre-built JS after 0.11.6

### ISSUE THREAD

**Issue by Deraen** [PaulLeCam/react-leaflet#223]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

Marker onClick handler is called.

### Actual behavior

After 0.11.6 onClick handler is not called.

### Steps to reproduce

Clicking on the marker should open a alert.

0.11.5: https://jsfiddle.net/sd2nv96o/
0.11.6: https://jsfiddle.net/ep4szn38/

I didn't test other events, but based on implementation I guess it is possible that other events are also broken.

**Comment by PaulLeCam** [comment]
Hi,
Thanks for reporting this issue and the code samples, it should be fixed in v0.12.3.

**Comment by Deraen** [comment]
Tested and I can confirm that fix works.
