### ISSUE TITLE
GeoJson object methods don't work.

### ISSUE THREAD

**Issue by felixtan** [PaulLeCam/react-leaflet#225]
Hi, I am following leafletjs's [interactive choropleth map](http://leafletjs.com/examples/choropleth.html) example and I am trying to add interaction by using the GeoJson object's resetStyle method and the Map object's fitBounds method. In leaflet, these methods are called via a reference to the respective objects:

```
var map = L.map('map');

function zoomToFeature(e) {
    map.fitBounds(e.target.getBounds());
}

var geojson;
// ... our listeners
geojson = L.geoJson(...);

function resetHighlight(e) {
    geojson.resetStyle(e.target);
}
```

How can I access these methods in react-leaflet? The methods don't exist in the objects returned from user interaction. I also tried exporting them from react-leaflet but that doesn't work either.

Here is my [jsfiddle](https://jsfiddle.net/photon/thbh99nu/1/).

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.
