### ISSUE TITLE
Triggering PopUp of a Marker Inside a Custom MapLayer

### ISSUE THREAD

**Issue by mbritton** [PaulLeCam/react-leaflet#231]
My Redux application needs to be able to trigger Marker PopUps in a situation where each Marker is inside a MapLayer. I’ve added these MapLayers to an Array in order for my Redux application to have the ability to reference the Markers:

```
// ATLBikeMarker is a MapLayer containing a Marker
muiMapLayer = <ATLBikeMarker {...this.props} key={i} position={position} icon={this.props.trailheadIcon} content={toolTipStr} />
muiMarkers.push(muiMapLayer)
// Send the Array of MapLayers off to the store…
```

Markers are rendered in the MapLayers like this:

```
render() {
	return (
		<Marker ref="marker" onClick={this.onClick} position={this.props.position} icon={this.props.icon}>
			<Popup>
            	<div></div>
        	</Popup>
		</Marker>
	)
}
```

So…a person clicks a button labeled “Select Marker”, and this dispatches Actions that create a selectedMarker variable. My Map component receives the selectedMarker prop, and retrieves its MapLayer as a variable from the Array of MapLayers in the Store.

From the same Component (containing the Map), I’m later detecting that this ATLBikeMarker, which contains a Marker, should be “selected”. This means that the Marker contained in the MapLayer should inflate its PopUp.

From my main component, I loop through the prop containing the MapLayers like this:

```
for (var i = 0; i < this.props.markers.length; i++) {
    const latlng = new L.LatLng(this.props.markers[i]['lat'], this.props.markers[i]['lon'])
    if (latlng.lat === this.props.selectedMarker.lat && latlng.lng === this.props.selectedMarker.lon) {
        console.log('this.props.atlBikeMarkers[i]', this.props.atlBikeMarkers[i])       
        // So how do I get the Marker contained in the MapLayer, and inflate its PopUp??
	// FAILS: this.props.atlBikeMarkers[i].openPopUp()
    }
}
```

Desired: MapLayer contains ref of marker, and it's possible to expand its PopUp.

**Comment by rjdestigter** [comment]
```

**Comment by rjdestigter** [comment]
```
class FixedPopup extends Popup {
  render () {
    setTimeout(() => {
      this.context.popupContainer.fire('click')
    }, 150)
    return null
  }
}```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.

**Comment by Stophface** [comment]
I wonder how that is done too....
