### ISSUE TITLE
GeoJSON pointToLayer marker customisation not working: t.onAdd not defined

### ISSUE THREAD

**Issue by sirwoetang** [PaulLeCam/react-leaflet#234]
### Expected behavior

Adding pointToLayer function to a GeoJSON react component should allow me to customise the normal marker to CircleMarker.

### Actual behavior

It insists that the object is not a Leaflet Layer, and that the t.onAdd is not available. 

### Steps to reproduce

Refer to this fiddle: https://jsfiddle.net/9ppbmr7n/ 
by removing the line 
`pointToLayer={this.onPointToLayer}` or line 48, one can see that the object is displayed with normal markers.

**Comment by rjdestigter** [comment]
The `pointToLayer` callback is directly passed to leaflet.  `L.geoJSON(..., { pointToLayer }`. However your callback is returning `React.createElement(CircleMarker, ..)`. Use Leaflet's API instead by returning `L.circleMarker(..)`

**Comment by frafra** [comment]
Wouldn't it be better to allow the usage of React elements with `pointToLayer`?

**Comment by flodaniel** [comment]
@frafra just stumbled across this and was hopeing that you (4 years ago) found a solution to how to just return a react element in the pointToLayer function?

**Comment by frafra** [comment]
@flodaniel you can have a look at my project: https://github.com/frafra/is-osm-uptodate/blob/2467a4be4ff10a93fb0e5103716d798c9a546dc2/web/src/map.js#L206

**Comment by frafra** [comment]
I see. I found a lot of issues with react-leaflet and how the project is maintained. This is one of the reason I switched to Maplibre and react-map-gl. I would have a hard time recommending Leaflet over Maplibre nowadays.
