### ISSUE TITLE
Leaflet v1 Google Map Support

### ISSUE THREAD

**Issue by inDream** [PaulLeCam/react-leaflet#236]
As [react-leaflet-google](https://github.com/Charmatzis/react-leaflet-google) is not yet updated for Leaflet v1,
I would like to use [Leaflet.GridLayer.GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant) with react-leaflet.
I extended `MapLayer` based on the example.

### Expected behavior
The map shown correctly.

### Actual behavior
The map is empty.

### Steps to reproduce
Demo: https://jsfiddle.net/indream/w6a1tzok/

Am I extend `MapLayer` correctly?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.

**Comment by Charmatzis** [comment]
I have updated with the new version [react-leaflet-google v2.1.0](https://www.npmjs.com/package/react-leaflet-google).
Now it uses: 
- "react-leaflet": "^1.0.1"
- "leaflet": "^1.0.2"
- "react": "^15.4.1"
- Leaflet.GridLayer.GoogleMutant
