### ISSUE TITLE
Add option to refresh WMS tile layer

### ISSUE THREAD

**Issue by themre** [PaulLeCam/react-leaflet#237]
Hi, this is a feature request. Currently I do not see the option to update WMS parameters with current API. Leaflet has method `layer.setParams({...})` which updates WMS layer with new options. Could this be implemented? Thanks!

**Comment by mdfischer** [comment]
I am having an issue which is perhaps the same thing.  The render function is being called with new props for the WMSTileLayer component:

`  
render: function () {
    var params = this.getWMSParams();
    return (
      <div>
        <WMSTileLayer
          className={styles.overlay}
          url={NCWMS_URL}
          format={params.format}
          transparent={params.transparent}
          opacity={params.opacity}
          styles={params.styles}
          version={params.version}
          srs={params.srs}
          logscale={params.logscale}
          origin={params.origin}
          layers={params.layers}
          time={params.time}
        />
      </div>
    );
  },
`
and I have confirmed in the debugging console that params are being correctly set to their updated values by `getWMSParams()`, however, no WMS request is sent to the `url`. Thus, the WMS tile layer is not updated on the map and the old layer is left in place.

**Comment by PaulLeCam** [comment]
Good idea, added to v1.0.0-rc.2.

**Comment by hzburki** [comment]
```
<WMSTileLayer
                                url="http://18.212.81.189:8080/geoserver/Texas/wms?service=WMS"
                                version='1.1.0'
                                opacity={1}
                                transparent
                                layers="Texas:intelligence"
                                srs="EPSG:4326"
                                format="image/png"
                                cql_filter={cql_filter ? cql_filter : "INCLUDE;NAME='Texas'"}
                            />
```

I'm using the above code-snippet. When I updated the cql_filter string. The map is cleared of the existing WMSLayer, I can the request being sent out and executing successfully with 200 status. The params are present in the request sent out but nothing renders on the map
