### ISSUE TITLE
Have problem with native events

### ISSUE THREAD

**Issue by Becherman** [PaulLeCam/react-leaflet#239]
Sory by offtop, but i don't find right answer for my questions on stackoverflow. Can someone tell me, where i may put native Leaflet methods in react-leaflet? I mean methods like getRadius() or getLatLng(). In my case i try to create my instance of geofences, and actual questions is how i can log current coordinates of circle by click, for exemple. Thank you!

**Comment by PaulLeCam** [comment]
This is documented in the [components section](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md)

**Comment by Becherman** [comment]
Thank you for this solution! Everything works correctly!
