### ISSUE TITLE
feature request: WMSTileLayer make url prop dynamic, replace vs extend params

### ISSUE THREAD

**Issue by sunny-g** [PaulLeCam/react-leaflet#247]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

------------

First, thanks for writing such a convenient library!

I want to recommend changing the `url` prop of a `WMSTileLayer` to be dynamic - currently, the layer won't update the url used to fetch the WMS layer, causing the new params to be sent to the wrong tile URL.

Unless I'm mistaken, the ability to change the URL dynamically would allow for declaratively rendering a map or set of maps without having to use the Leaflet Controls or having to resort to the imperative Leaflet API for adding and removing layers. Here's a potential implementation: https://github.com/PaulLeCam/react-leaflet/pull/196#discussion_r86277521

In addition, in the interest of staying in alignment with React's declarative nature (though this contradicts the library's purpose of only "supporting features provided by Leaflet"), within `componentWillUpdate`, it would make sense to clear from the layer's params any params that do not exist in the newly received props before setting the params to the new props (of course, assuming they are distinct), along the lines of the solution provided here: https://github.com/Leaflet/Leaflet/issues/3441#issuecomment-206507663

Let me know what you think (more about the first recommendation than the second, though I think they both would be useful and are more intuitive than current behavior).

**Comment by PaulLeCam** [comment]
Yes, good idea. I added support for dynamic `url` prop in v1.0.0-rc.3.
Regarding the issue with unsetting other parameters, I think that should be handled by Leaflet directly so I'd rather not implement custom logic here. If you need to clear the layer you can always give it a different `key`.
