### ISSUE TITLE
Allow HTML Icon

### ISSUE THREAD

**Issue by obetomuniz** [PaulLeCam/react-leaflet#248]
Allow insert HTML Icon. It'll provide more customization and control of the icon behavior.

**Comment by PaulLeCam** [comment]
There is nothing preventing you from using whatever icon you want.

**Comment by obetomuniz** [comment]
Hey @PaulLeCam 

I mean, use something like `<Marker icon={<MyCustomIcon />}> ... </Marker>`...It's possible this type of declaration?

**Comment by dkrichards86** [comment]
According to [the docs](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Plugins.md), there is a third party plugin for div icons.

[React Leaflet Div Icon](https://www.npmjs.com/package/react-leaflet-div-icon)

Or, you could just pass in the div icon yourself:
```js
var myIcon = L.divIcon({className: 'my-div-icon'});
<Marker icon={myIcon} />
```

**Comment by obetomuniz** [comment]
Awesome @dkrichards86, do you guys have any idea about include it as a built-in feature? it's a good thing to have in terms of customization. Anyway, thank you for sharing the approach, will be useful for me. Maybe it can be added as a tip in the docs. Thoughts?

**Comment by PaulLeCam** [comment]
`<Marker icon={<MyCustomIcon />}> ... </Marker>` can't work as `<MyCustomIcon />` would return a React Element, not a Leaflet Icon class, so please use the alternative that suits you the most.
