### ISSUE TITLE
v1 RC3: Re-render due to prop change issues

### ISSUE THREAD

**Issue by prewk** [PaulLeCam/react-leaflet#252]
# Using

* `react-leaflet@1.0.0-rc.3`
* `leaflet@1.0.1`

# Behavior:

* When I re-render `<TileLayer />` with a new `attribution` value it doesn't re-render.
* When I re-render `<Map />` with a new `zoomControl` value it doesn't re-render.

# Expected behavior:

For the components to re-render when the props are changed.

# Possible problem source:

Lifecycle methods such as `shouldComponentUpdate` not taking into account all of its props correctly.

# Workaround:

Currently solving it by coupling keys with some props to force React to re-render:

```jsx
<Map
    { ...mapProps }
    key={ zoomControls }
>
  <TileLayer { ...tileProps } key={ attribution } />
</Map>
```

**Comment by PaulLeCam** [comment]
These are not dynamic props, it's expected they don't get updated.

**Comment by prewk** [comment]
I wasn't aware there was a distinction between dynamic and non-dynamic props? Doesn't sound very Reacty IMHO, but I'm sure you have your reasons when wrapping a complex library such as Leaflet.

Is this documented somehow?

**Comment by PaulLeCam** [comment]
It is documented here: https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#component-properties

**Comment by prewk** [comment]
Ah, you're absolutely right. Sorry for wasting your time and thanks you for a great lib!

**Comment by dostuffthatmatters** [comment]
The up-to-date docs link is https://react-leaflet.js.org/docs/example-external-state/
