### ISSUE TITLE
Empty divs with display:none in leaflet-container

### ISSUE THREAD

**Issue by lorem--ipsum** [PaulLeCam/react-leaflet#253]
Hi ! First of all, congrats on this great project, it saved me quite a bit of time :-)
Now, I'm facing something weird and I was hoping you could point me in the right direction to find out what I'm doing wrong.

Here's a screenshot of my DOM structure :
![image](https://cloud.githubusercontent.com/assets/1224709/20178389/2d1d6da8-a751-11e6-8f19-871c3ce8e5e3.png)

What could possibly cause so many empty divs being generated ? It's not a problem per se, but it's probably not helping performance to have so many empty divs.

Thanks ! I hope my question is clear enough :-)

**Comment by PaulLeCam** [comment]
Hi!
It is used to handle nesting of layers, as the components created do not alter the DOM themselves (they pass props to Leaflet, that handles the DOM manipulations). You can see it used in [this component](https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapLayer.js#L36), extended by most others.
I don't know about the performance cost of these empty divs, but if you have any idea/data I'm interested. One simple solution to reduce the number of divs would be to check if the children of a component are in an Array or not, and only wrap in a div in that case, but that means extra work in `render()` for things that are not displayed anyways so I don't know what is best.

**Comment by lorem--ipsum** [comment]
That's interesting. Off the top of my head, I'd say it's better to check something that to generate unnecessary divs, especially when those are empty. So checking whether `this.props.children` is an array is one thing, but simply checking if there _are_ children is an other.

Maybe something like this :
```
const { children } = this.props;
return Array.isArray(children) ? <div style={{display: 'none'}}>{children}</div> : (children || null);
```

?

**Comment by PaulLeCam** [comment]
Yes that's what I was thinking, I'll update this for the next release if I don't find any edge case.

**Comment by lorem--ipsum** [comment]
Awesome, thanks a lot !
