### ISSUE TITLE
GeoJson component name change?

### ISSUE THREAD

**Issue by IGlautier** [PaulLeCam/react-leaflet#254]
In previous versions of react-leaflet the GeoJson component was imported:

import { GeoJson } from "react-leaflet";

However in rc.3 this will produce an error ( Element type is invalid ). This issue can be resolved by using:

import { GeoJSON } from "react-leaflet";

Please could you update the docs to reflect this?

**Comment by IGlautier** [comment]
Additionally it appears that the onEachFeature prop is broken.

**Comment by PaulLeCam** [comment]
Yes, `GeoJson` becomes `GeoJSON` in v1 to mirror Leaflet's change, this is indicated in the release notes: https://github.com/PaulLeCam/react-leaflet/releases/tag/v1.0.0-beta.1
Regarding `onEachFeature`, please post a new issue following the template and provide an example jsfiddle or similar.
