### ISSUE TITLE
layer.on not functioning correctly in onEachFeature

### ISSUE THREAD

**Issue by IGlautier** [PaulLeCam/react-leaflet#257]
### Expected behavior

Function bound to click event should be called when the corresponding part of the geojson is clicked.

The code used for onEachFeature was functioning in previous versions (leaflet 0.7.7).

### Actual behavior

Function bound to click event is not called when geojson is clicked.

### Steps to reproduce

https://jsfiddle.net/n7jmqg1s/2/

**Comment by IGlautier** [comment]
Appears that this was actually nothing to do with react-leaflet. For anyone experiencing similar issues check the zIndex of other html elements, even if not positioned above the leaflet map they seem to interfere.

**Comment by minhlucvan** [comment]
or maybe just check your ``leaflet.css`` version, it's took me hours actually :sweat_smile:

**Comment by 1Paint** [comment]
Took a while for me to find out why my onEachFeature function was not binding a tooltip and onClick function.

The tooltips and onClick functions were being binded, but my GeoJSON layers were being rendered in Panes. Panes were layered over each other in order of declaration and only the most recent Pane's GeoJSON layer was interactive.
