### ISSUE TITLE
react-native support ? 

### ISSUE THREAD

**Issue by mydearxym** [PaulLeCam/react-leaflet#26]
amazing work!

Can i use it in my react-native project ?

**Comment by PaulLeCam** [comment]
Thanks!

No it doesn't support react-native.
Leaflet needs to access the DOM so I assume the only way to use it is in a WebView.

**Comment by mydearxym** [comment]
is this saying that all the third part component write by react.js can not be use in the react-native project? that's so sad ..

**Comment by PaulLeCam** [comment]
Well it's the purpose of react-native to render native components, not a DOM :)

**Comment by vvavepacket** [comment]
Is it possible to load react-leaflet into ReactNative's WebView?

**Comment by filipef101** [comment]
bump

**Comment by incarnateTheGreat** [comment]
> Is it possible to load react-leaflet into ReactNative's WebView?

https://github.com/reggie3/react-native-webview-leaflet

**Comment by dokselblackbit** [comment]
It works for me [react-native-leaflet-view](https://www.npmjs.com/package/react-native-leaflet-view/v/1.0.5)
