### ISSUE TITLE
CircleMarker is not displayed

### ISSUE THREAD

**Issue by kevinSuttle** [PaulLeCam/react-leaflet#261]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
**15.3.2  for both**
- [x] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded. 
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior

Please describe.
`CircleMarker` to be displayed. 

### Actual behavior
CircleMarker is constructed, but without content. 

Please describe.

```jsx
import React, { Component } from 'react'
import update from 'react-addons-update'

import L from 'leaflet';
import { Map, CircleMarker, Popup, TileLayer } from 'react-leaflet';

import locationData from '../data/locations.json';

// inside of render method
const markers = this.state.markers.map(m => (
      <CircleMarker
        center={L.latLng(m.position.lat, m.position.lng)}
        key={m.DEVICENAME}
        radius={25}
        fill="true"
        color="red"
      >
        <Popup>
          <span>{m.DEVICENAME}</span><br />
        </Popup>
      </CircleMarker>
    ))
```
### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this jsfiddle](https://jsfiddle.net/paul_lecam/q2v7t59h/).

This fiddle can't be used to reproduce, because it's handled outside of a client-side HTML file. 
I have used [create-react-app](https://github.com/facebookincubator/create-react-app) for structure.

I have the following in my head tag inside index.html:
```html
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
 <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>
```

The components have data, but they appear empty, and have no width or height. I added `fill` and `color` to debug, but to no avail.

<img width="1440" alt="screen shot 2016-12-08 at 12 43 45 pm" src="https://cloud.githubusercontent.com/assets/95672/21021926/b51d8140-bd48-11e6-86b5-8d6679e95c36.png">

No errors exist in the console. Please let me know what I can provide further.

**Comment by PaulLeCam** [comment]
Hi,
The `center` prop should not be a `Leaflet.LatLng` but a plain array of object, as defined in the [PropTypes documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/API.md#proptypes), please check if the problem persists when using one of these formats.

**Comment by kevinSuttle** [comment]
Will do. Thanks.

**Comment by shivika** [comment]
I am having this same issue using the [number,number] prop format for an array of locations 
`center={[marker[0], marker[1]]}`

Was your issue resolved?

**Comment by thomasr96** [comment]
Ran into this problem and found the solution at the end of [this issue](https://github.com/PaulLeCam/react-leaflet/issues/68).
