### ISSUE TITLE
FeatureGroup onClick handler does not fire

### ISSUE THREAD

**Issue by Flo890** [PaulLeCam/react-leaflet#263]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x ] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
- [x ] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded.
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior

According to Leaflet [docs](http://leafletjs.com/reference-1.0.2.html#featuregroup) , events occuring in child layers of a FeatureGroup should be propagated to the parent FeatureGroup. So a onClick handler added to a FeatureGroup should fire if i click a child element of this FeatureGroup

### Actual behavior

The onClick handler of a FeatureGroup does not fire if I click on its child element(s)

### Steps to reproduce
Run this JsFiddle and click on the Marker. A alert should open, but it doesn't.
https://jsfiddle.net/dedv6xgh/1/

**Comment by PaulLeCam** [comment]
Thanks for reporting this, should be fixed in v1.0.2
