### ISSUE TITLE
Context is not preserved through ReactDOM.render (eg in Popup, Tooltip etc)

### ISSUE THREAD

**Issue by sgentle** [PaulLeCam/react-leaflet#264]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
- [x] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior

When you put an element that uses `this.context` inside a `Popup`, it works because `ReactDOM.render` doesn't preserve the context, but the context is transferred to the child using a context-transferring higher-order component or `unstable_renderSubtreeIntoContainer`.

### Actual behavior

When you put an element that uses `this.context` inside a `Popup`, it doesn't work because `ReactDOM.render` doesn't preserve the context, and the context isn't transferred to the child using a context-transferring higher-order component or `unstable_renderSubtreeIntoContainer`.

### Steps to reproduce

1. Look at the code: https://github.com/PaulLeCam/react-leaflet/blob/d7ba0947b8fda95c1cdc54f1c5022cfd38306647/src/Popup.js#L87
2. Read this StackOverflow question: https://stackoverflow.com/questions/38212174/is-it-possible-to-pass-context-into-a-component-instantiated-with-reactdom-rende
3. Read this Github issue: https://github.com/facebook/react/issues/4706

**Comment by PaulLeCam** [comment]
Not preserving the context is the behavior of `ReactDOM.render()`, so this is expected behavior.
`unstable_renderSubtreeIntoContainer()` is very explicitly labelled as "unstable" so I don't think it should be used in this library.

**Comment by rsolomon** [comment]
Context could be preserved using an HOC without resorting to `unstable_renderSubtreeIntoContainer`, as mentioned in the OP. I don't have time to take this on today, but if someone else comes across this and feels a more immediate need, it should be very possible without using dubiously-named hidden functionality.
