### ISSUE TITLE
wherReady callback call error with leaflet-routing-machine

### ISSUE THREAD

**Issue by grigory-leonenko** [PaulLeCam/react-leaflet#265]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [X] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
- [X] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior

Route built, there are no errors.

### Actual behavior

Route built, but the error appears and application breaks.

![image](https://cloud.githubusercontent.com/assets/5756341/21499659/a76a0648-cc59-11e6-9a68-394459539964.png)

### Steps to reproduce
1. Open fiddle
2. Open dev tools console
3. Press run button

[Example on fiddle](https://jsfiddle.net/b6bLd5L2/1/)

**Comment by PaulLeCam** [comment]
Please refer to the documentation about [creating custom components](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Extending.md#creating-custom-components).
