### ISSUE TITLE
Uncaught Error: Could not find "store" in either the context or props 

### ISSUE THREAD

**Issue by rowdyroad** [PaulLeCam/react-leaflet#266]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
- [x] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior
Use in Tooltip redux-wrapped children.

### Actual behavior
When I add redux-wrapped element (by connect) function to Tooltip body, I've got an error:

> Uncaught Error: Could not find "store" in either the context or props of "Connect(MyElement)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(MyElement)".

### Steps to reproduce
import React from 'react'
import {connect} from 'react-redux'
import {Map, TileLayer, Marker, CircleMarker, Tooltip} from 'react-leaflet'

const MyElement = connect((state)=> {
	return  {name: state.get('name')}
})((props) => < div>{props.name}</div>)

const Map = (props) => (
< Map scrollWheelZoom={false} {...props}>
   < TileLayer url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'/>
      < CircleMarker radius={0} color="transparent" center={props.position}>
		< Tooltip {...props} interactive={true} direction="top" permanent={true}>
			< MyElement/>
		</ Tooltip>
	</ CircleMarker>
</ Map>
)

**Comment by PaulLeCam** [comment]
As written in [the documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#tooltip), the `<Tooltip>` contents are rendered using `ReactDOM.render()`, which does not propagate the context from its container.

**Comment by jgimbel** [comment]
You can use [this HoC](http://stackoverflow.com/questions/38212174/is-it-possible-to-pass-context-into-a-component-instantiated-with-reactdom-rende) to pass context. I would suggest using it to continue the store.
An example would look like...
`<ContwextWrapper> <MyElement/> </ContextWrapper>`
