### ISSUE TITLE
Possible to use with offline maps with tiles stored locally?

### ISSUE THREAD

**Issue by anandgeorge** [PaulLeCam/react-leaflet#267]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [ ] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [ ] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
- [ ] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded.
- [ ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ ] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this jsfiddle](https://jsfiddle.net/paul_lecam/q2v7t59h/).

**Comment by anandgeorge** [comment]
Is it possible to serve tiles locally, offline?

**Comment by PaulLeCam** [comment]
It's not supported out of the box, but you could investigate Leaflet plugins.

**Comment by anandgeorge** [comment]
Thanks

**Comment by reggie3** [comment]
@anandgeorge did you have any luck getting offline support working?

**Comment by anandgeorge** [comment]
No

**Comment by Tmfwang** [comment]
I've gotten offline support to work with react-leaflet using the leaflet.offline plugin. Posted a short guide here:
https://stackoverflow.com/questions/69091797/using-leaflet-offline-with-react/69153168#69153168
