### ISSUE TITLE
<Map> className attribute does not respect leaflet-generated classes

### ISSUE THREAD

**Issue by noblebright** [PaulLeCam/react-leaflet#269]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [X] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Check that you are using a supported version of React and ReactDOM (v15.0.0+).
- [X] Check that you are using the supported version of Leaflet (v.1.0.0) and its corresponding CSS file is loaded.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/next/docs/How%20it%20works.md#limitations).

### Expected behavior

It would be nice if setting className on Map respected the stuff that leaflet does to the container div afterwards. For example, setting className={visible ? 'map' : 'hide'} should result in either 
`class="map leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" 
`
or 
`class="hide leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom"
`

### Actual behavior

I have a map with className={visible ? 'map' : 'hide'}  This works fine the first time (because leaflet hasn't done anything yet), but when I change the props afterwards, the div loses all leaflet-generated classes and blows up. (ie, renders to just class="map" instead of class="map leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom")

### Steps to reproduce

https://jsfiddle.net/29xmLn2k/1/

**Comment by PaulLeCam** [comment]
Yes it's an issue that it's not working like this already, thanks for reporting it.
I just published v1.0.3 that should address the problem, please try it out and let me know if it works as expected in your case.

**Comment by noblebright** [comment]
Looks good to me.  Thanks for the quick turnaround!
