### ISSUE TITLE
When I add a Popup to a Marker then call setState I get `Invariant Violation`

### ISSUE THREAD

**Issue by vjpr** [PaulLeCam/react-leaflet#27]
If I remove the Popup element it doesn't happen.

```
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.1.0.1.0.$=11=20:0.$=10:0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

---

I am using the `Map` component inside another component.

**Comment by vjpr** [comment]
After some investigation it seems to be related to this bug in Chrome -> [Child elements of <noscript> tags not always rendered](https://code.google.com/p/chromium/issues/detail?id=232410).

Children of `noscript` are rendered as string literals. 

Workaround: Change `noscript` in `PopupContainer` to `return <div style="display:none;">{children}</div>;`

**Comment by Frikki** [comment]
Apparently, @PaulLeCam is not in favor of changing it to a `DIV` element. See discussion here https://github.com/PaulLeCam/react-leaflet/issues/18

**Comment by PaulLeCam** [comment]
Hi,

Removing a Popup is not supported, you need to update the entire layer, see https://github.com/PaulLeCam/react-leaflet/issues/18#issuecomment-99013617

**Comment by vjpr** [comment]
Hi Paul,

You might have misread the issue. It's not about removing a Popup.

There is a bug in Chrome which is causing this where noscript children are turning into string literals. Not sure how you want to handle this but a div is a simple fix. Otherwise people trying your library will struggle to get a simple example working.

**Comment by PaulLeCam** [comment]
Sorry I misread about the Popup deletion.

I'm not so up for using a `<div>` as a workaround because the rendering is made by Leaflet, not React, so the `null`/`<noscript>` rendered by the components are only there because React needs to render something.
My main concern is that rendering `<div>`s could affect the expected layout, but `display: none` should avoid that issue, I'll try that!

**Comment by Frikki** [comment]
Please let the style be a `React.Component.prop` so we have some chance 
of overriding it.

**Comment by troutowicz** [comment]
@Frikki, I will try later tonight but I'm pretty sure that is already possible... while definitely limited due to Leaflet handling the rendering.

```js
<Popup maxWidth='300' minWidth='50' >
  some text
</Popup>
```

https://github.com/PaulLeCam/react-leaflet/blob/master/src/Popup.js#L15
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L11

**Comment by PaulLeCam** [comment]
The style would only apply to the PopupContainer component, that should be invisible anyways, not the Popup that would be rendered by Leaflet.

**Comment by troutowicz** [comment]
Hmm, I would think those props would be getting passed through the `bindPopup` method which would be used in Leaflet when creating the popup. I may submit a PR to Leaflet eventually that would allow passing more styling to popups. Wouldn't be a big change, just create a styling option, and make their popup module aware of it.

```js
L.popup({ style: { ... } });
```
```js
popupContainer.bindPopup(content, { style: {...} });
```

**Comment by PaulLeCam** [comment]
It should work properly now in v0.6 using a div with `display: none`, I didn't find any issue using it.
Please reopen if the bug appears again after updating.
