### ISSUE TITLE
createLeafletElement

### ISSUE THREAD

**Issue by ekatzenstein** [PaulLeCam/react-leaflet#275]
This new functionality breaks compatibility with react-leaflet-heatmap-layer

**Comment by Spaxe** [comment]
Why throw an error where as before it was fine?

**Comment by PaulLeCam** [comment]
I am not the author of react-leaflet-heatmap-layer, so this is something you should report in the relevant bug tracker, not here.
The added `createLeafletElement()` does not break any public API, but requires changes if you are using internal ones, as documented in the [upgrade guide](https://github.com/PaulLeCam/react-leaflet/blob/master/UPGRADING.md#v11).

**Comment by jetaix** [comment]
@Spaxe What do you mean by `in my subclass` ?

**Comment by Spaxe** [comment]
@jetaix See code excerpt:

```
// React-Leaflet addition
// See https://github.com/PaulLeCam/react-leaflet/blob/master/src%2FImageOverlay.js
//
// Given a Hyrax endpoint URL, this layer adds an ImageOverlay layer on Leaflet
// and refreshes its image content based on the Hyrax service endpoint.
// Unlike WMS services, images are constructed client-side, and it offers
// flexibility of changing colour maps and thresholds without re-querying the
// server.
export default class HyraxMapLayer extends MapLayer {

  // See https://github.com/PaulLeCam/react-leaflet/issues/275
  createLeafletElement () {}
```
