### ISSUE TITLE
How to custom popup style?

### ISSUE THREAD

**Issue by mcj010** [PaulLeCam/react-leaflet#276]
Hi everybody,

I would like to create a new style for recenter the map in popup.
I don't see how do.. 

Example :

![image](https://cloud.githubusercontent.com/assets/6703918/22239772/ff31b5ba-e252-11e6-96e1-a7cd83aad5ac.png)

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.
