### ISSUE TITLE
Map throws Invalid LatLng object: (NaN, NaN) error on initial page load with `bounds` property

### ISSUE THREAD

**Issue by caddac** [PaulLeCam/react-leaflet#277]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Using a supported version of React and ReactDOM (v15.0.0+).
- [ x] Using the supported version of Leaflet (v1.0.0) and its corresponding CSS file is loaded.
- [x ] Using the latest version of React-Leaflet.
- [x ] The issue has not already been reported.
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Map should load to the bounds given on initial load

### Actual behavior

Map does not load on initial page load, requires re-render before loading. On initial page load gives error `Uncaught Error: Invalid LatLng object: (NaN, NaN)`

### Steps to reproduce

see fiddle here that reproduces the problem: https://jsfiddle.net/ernwfLhv/

Direct fork of the example fiddle, removed the `center` prop and added the `bounds` and `boundOptions` props. This prevents the map from loading on initial page load
Clicking the "re-render" button will re-render the component and load the map (but it doesn't change anything else like state).
 

Note, I've tried this with all leaflets 1.0.0 to 1.0.3 and react-leaflet 1.0.0 & 1.1. It does not happen with leaflet 0.7 and react-leaflet 0.12

**Comment by caddac** [comment]
I don't know how but I fixed this. I'm not really doing anything differently...

**Comment by jgimbel** [comment]
Your bounds are the same value. When i run this version it loads the first time for me.
https://jsfiddle.net/31r878b8/

----- Reply message -----

**Comment by caddac** [comment]
That explains why it started working all the sudden when I refactored it. I made the bounds points different. That seems like a weird error for having the bounds be the same value. 

Thanks!

**Comment by diegoarcega** [comment]
imo it shouldn't throw that error, it wasnt in the previous version

**Comment by kylehotchkiss** [comment]
+1 i am also getting this error.

**Comment by getanwar** [comment]
Two and a half years past and still the same error!

**Comment by AndrejGajdos** [comment]
+1 I came across the same issue

**Comment by AliRezaDavuodi** [comment]
+1 still no way to fix that ?
