### ISSUE TITLE
Error in LayersControl example

### ISSUE THREAD

**Issue by vietnugent** [PaulLeCam/react-leaflet#279]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [ ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ ] Using a supported version of React and ReactDOM (v15.0.0+).
- [ ] Using the supported version of Leaflet (v1.0.0) and its corresponding CSS file is loaded.
- [ ] Using the latest version of React-Leaflet.
- [ ] The issue has not already been reported.
- [ ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ ] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior
LayersControl example not working due to invalid component name
https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/layers-control.js#L26

According to the latest [docs](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#layerscontrol)  children of `LayersControl` should be `LayersControl.BaseLayer` not `BaseLayer`

**Comment by PaulLeCam** [comment]
They are, [these components are extracted from `LayersControl`](https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/layers-control.js#L13).
