### ISSUE TITLE
Map is out of  Bounds

### ISSUE THREAD

**Issue by CusProjects** [PaulLeCam/react-leaflet#281]
![screen shot 2017-02-17 at 12 35 52 pm](https://cloud.githubusercontent.com/assets/14632593/23078295/bdfc943e-f50d-11e6-99ea-265ca98b7706.png)

**Comment by CusProjects** [comment]
componentDidMount(){
		var map = L.map('mapid').fitWorld();
		L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
		}).addTo(map);

		//http://{s}.tile.osm.org/{z}/{x}/{y}.png
	}

<Row>
					 <Col md={12}>
					 	<div id="mapid" style={{border: '3px solid', width: '100%', height: '200px'}}></div>
					 </Col>
				</Row>

**Comment by CusProjects** [comment]
`
componentDidMount(){
		var map = L.map('mapid').fitWorld();
		L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
		}).addTo(map);
	}

<Row>
					 <Col md={12}>
					 	<div id="mapid" style={{border: '3px solid', width: '100%', height: '200px'}}></div>
					 </Col>
				</Row>
`

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
