### ISSUE TITLE
Animate Polyline

### ISSUE THREAD

**Issue by Shadowman4205** [PaulLeCam/react-leaflet#285]
Hello, is there any suggestion how animate polyline so it will connect two (more) positions smoothly and like half ellipsis (not line)?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.
