### ISSUE TITLE
React Plugin For Leaflet.curve

### ISSUE THREAD

**Issue by Shadowman4205** [PaulLeCam/react-leaflet#286]
Is anyone  who can create this component, if it is easy?

**Comment by PaulLeCam** [comment]
I'd suggest looking for existing [npm packages](https://www.npmjs.com/search?q=react-leaflet) or [creating it yourself](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Extending.md#extending) if you do not find an existing plugin.

**Comment by Shadowman4205** [comment]
Thanks for answering, but it s hard for me to implement this  plugin leaflet.curve to react, it is similar to polyline but still i do not understand how reactify it or write plugin.
