### ISSUE TITLE
Events zoomlevelschange

### ISSUE THREAD

**Issue by rolfdalhaug** [PaulLeCam/react-leaflet#288]
Hi

Is it possible to get events using react-leaflet?.. specifically want to show / hide Markers based on zoom level.

Thanks

**Comment by PaulLeCam** [comment]
Hi, please refer to the [relevant section of the documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/API.md#events).

**Comment by Shadowman4205** [comment]
Which is the relevant section you refer to? I need this fuctionality too

**Comment by dy2288** [comment]
Basically just prefix Leaflet events with 'on', so zoom, becomes onZoom. I believe
`<Map onZoomlevelschange={(e) => { console.log(e); }}> ... </Map>` should work.

That's what I've been doing with the 'zoom' event.
