### ISSUE TITLE
Standalone build?

### ISSUE THREAD

**Issue by mbajur** [PaulLeCam/react-leaflet#29]
Hello!
I would really love to use react-leaflet in my project but i don't have a require.js there and i can't have it installed for various reasons. I just can't. 

I can't see any standalone build of react-leaflet in the repo but i've seen a lot or react (and js in generall) libs made in two version - for AMD and standalone so i assume that's doable. I'm not really good in JS and i don't know require.js so i'm totally not sure if that's possible but - is that possible for you to add a standalone version ? Or can i somehow build such thing myself?

Thanks!

**Comment by PaulLeCam** [comment]
Hi,

You could use Browserify or Webpack to build the library the way you want, I may provide a standalone build at some point but that would likely be part of a larger refactoring.

**Comment by PaulLeCam** [comment]
Hi,

Sorry for the delay, UMD builds are now available in https://github.com/PaulLeCam/react-leaflet/tree/master/dist
This makes them also available on npmcdn: https://npmcdn.com/react-leaflet/dist/react-leaflet.js and https://npmcdn.com/react-leaflet/dist/react-leaflet.min.js

I'll update the documentation with these links.

**Comment by eelcocramer** [comment]
Hi, I just tried these builds but they seem to fail for me.

```
var _react = __webpack_require__(4)
```

In the above line (and lines like these) the var `_react` is always undefined.

**Comment by PaulLeCam** [comment]
Hi, are you including the dependencies before loading react-leaflet? It requires `React`, `ReactDOM` and `Leaflet` to be defined on `window`.

**Comment by eelcocramer** [comment]
Thanks for the response but I switched to the npm / browsify build. It could very well be that I did not load all the dependencies.

**Comment by PaulLeCam** [comment]
Added to the Readme.
