### ISSUE TITLE
Example of creating a customer MapControl

### ISSUE THREAD

**Issue by anvk** [PaulLeCam/react-leaflet#294]
It would be amazing if someone would provide an example on how to create custom component http://leafletjs.com/examples/extending/extending-3-controls.html but using react-leaflet. 
This tiny basic mirror example would be so much helpful for users.

Thank you in advance.

**Comment by PaulLeCam** [comment]
You can refer to the [documentation regarding creating custom components](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Extending.md#creating-custom-components), it should work as documented.
Assuming you've added the `L.control.watermark` presented in Leaflet's documentation, porting it to this lib would work the same way as other controls implementations, such as the [`ZoomControl`](https://github.com/PaulLeCam/react-leaflet/blob/master/src/ZoomControl.js), ex:

```js
import L from 'leaflet'
import { MapControl, PropTypes as LeafletPropTypes } from 'react-leaflet'

export default class WatermarkControl extends MapControl {
  static propTypes = {
    position:  LeafletPropTypes.controlPosition,
  }

  createLeafletElement (props: Object): Object {
    return L.control.watermark(props)
  }
}
```

**Comment by anvk** [comment]
@PaulLeCam thanks a lot for your reply! I tried what you suggested and it worked like a charm. Also I just wanted to mention that you did an outstanding job porting LeafLet to React. Your component works so smooth.

I have few other questions about the example. I assume that I would need to extend `L` for any new custom control I want to create (e.g. `L.control.myOtherGreatControl`). Or I can put all this logic into `createLeafletElement()` ?

Also noticed that code `<WatermarkControl position="bottomleft" />` would work. But then `controlPosition` would not (according to https://github.com/PaulLeCam/react-leaflet/blob/master/docs/API.md#proptypes)

Do I need to extend componentUnmount() for every component or react-leaflet will take care of that? (once again reading doc here https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#lifecycle-process but not sure if map removes layer for custom components)



To be honest I find documentation very dry and cryptic. I re-read it multiple times and tried few different things until wrote a message here. Maybe it is just me, but a separate page even with this example, possibly another very simple example of some custom control counter (or other dynamic changing property on a map) could be so beneficial for anyone who wants to use react-leaflet.

**Comment by PaulLeCam** [comment]
> @PaulLeCam thanks a lot for your reply! I tried what you suggested and it worked like a charm. Also I just wanted to mention that you did an outstanding job porting LeafLet to React. Your component works so smooth.

Thanks!

> I have few other questions about the example. I assume that I would need to extend `L` for any new custom control I want to create (e.g. `L.control.myOtherGreatControl`). Or I can put all this logic into `createLeafletElement()` ?

You can have the logic you want in `createLeafletElement()`, as long as it returns a Leaflet instance having the expected APIs for the element type (ex don't use a layer as a control).

> Also noticed that code `<WatermarkControl position="bottomleft" />` would work. But then `controlPosition` would not (according to https://github.com/PaulLeCam/react-leaflet/blob/master/docs/API.md#proptypes)

What do you mean by `controlPosition` not working?

> Do I need to extend componentUnmount() for every component or react-leaflet will take care of that? (once again reading doc here https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#lifecycle-process but not sure if map removes layer for custom components)

You only need to extend it if you have additional logic, for example if you added custom event listeners that need to be removed.

> To be honest I find documentation very dry and cryptic. I re-read it multiple times and tried few different things until wrote a message here. Maybe it is just me, but a separate page even with this example, possibly another very simple example of some custom control counter (or other dynamic changing property on a map) could be so beneficial for anyone who wants to use react-leaflet.

Please don't hesitate to send PRs for anything you feel could be improved!

**Comment by anvk** [comment]
Amazing! Thanks a lot for all your help.
Once have some extra time will try to submit my ideas for some documentation if they make sense in a PR
