### ISSUE TITLE
Improve documentation for accessing leafletElement

### ISSUE THREAD

**Issue by anderspitman** [PaulLeCam/react-leaflet#295]
It took me a while digging through the examples to figure out you need to create your components with something like `ref='map'` and then access them via `this.refs.map`. It would be nice to have this documented somewhere.

**Comment by PaulLeCam** [comment]
Please don't hesitate to send a PR for any change you feel would make it more explicit.
Also, please note this documentation assumes the reader is already familiar with React and Leaflet, both libraries have relatively large APIs and different concepts that are specific to them, not React-Leaflet.
