### ISSUE TITLE
maxZoom > 19 renders gray tiles on max zoom

### ISSUE THREAD

**Issue by Eightyplus** [PaulLeCam/react-leaflet#296]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v15.0.0+).
- [X] Using the supported version of Leaflet (v1.0.0) and its corresponding CSS file is loaded.
- [X] Using the latest version of React-Leaflet.
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior
I want to change the zoom level on "<LeafletMap ..." to let the user zoom even more. I confirmed the leaflet map support zoom beyond zoom level 19 (which is default) and the tiles are delivered appropriately. 

### Actual behavior
When I set maxZoom beyond zoom level 19 the tiles are not fetched from the leaflet map/tile server. And the Leafletmap component renders gray tiles (because the tiles are not fetched). 

### Steps to reproduce
1. set maxZoom={20} or more on <LeafletMap
2. zoom in to the map cannot be zoom more
3. map turns gray

Demo: https://jsfiddle.net/vfa15L8c/8/

**Comment by PaulLeCam** [comment]
Hi,
Could you provide the similar demo with Leaflet only please to compare the behavior?

**Comment by Eightyplus** [comment]
Oh, the same thing occurs with leaflet.

http://jsfiddle.net/friesgaard/d9q9wzwf/

**Comment by Eightyplus** [comment]
But here I get an 404, which I didn't see when using react-leaflet.

<img width="888" alt="screen shot 2017-03-09 at 09 06 04" src="https://cloud.githubusercontent.com/assets/15194982/23741228/ad78c818-04a7-11e7-931c-edad2a797e4a.png">

**Comment by Eightyplus** [comment]
After updating the map server on our behalf to a higher zoom level, I must conclude it works in leaflet and not in react-leaflet.

React-leaflet
https://jsfiddle.net/friesgaard/vfa15L8c/10/

leaflet
http://jsfiddle.net/vk2m5hha/

**Comment by Eightyplus** [comment]
_layersMaxZoom is not set eventough maxZoom is set.

![screen shot 2017-03-09 at 11 37 57](https://cloud.githubusercontent.com/assets/15194982/23746611/decb4200-04bc-11e7-8f17-c40984049139.png)

**Comment by Eightyplus** [comment]
It work when maxZoom={20} is also set on <TileLayer

https://jsfiddle.net/friesgaard/vfa15L8c/11/

According leaflet documentation, setting maxZoom on map "overrides any maxZoom set on map layers"...
http://leafletjs.com/reference.html#map-maxzoom

**Comment by PaulLeCam** [comment]
Hi, thanks for all the details, it helped a lot!
I don't know what's the exact cause of the issue, as there is no logic trying to alter Leaflet's one, but I pushed a workaround to master that makes all tile layers inherit the `maxZoom` and `minZoom` properties from the map.
Could you please try the code from the latest master and check if it solves your issue?

**Comment by Eightyplus** [comment]
Great it helped, took some debugging and guesswork. Your fix has solved the issue.

**Comment by PaulLeCam** [comment]
Now published in v1.1.2.

**Comment by ayozebarrera** [comment]
Hi, still happening to me with ^1.9.1 and I'm ussing maxZoom property.

Btw, just checked v2 example on codesandbox and updating it with maxZoom={19} will break too!
What I missing?

Thanks!

**Comment by NeoLegends** [comment]
I'm also facing this issue here, I'm using react-leaflet v2.1.2. As soon as I zoom to max zoom level the tiles disappear and the `img` DOM nodes are unmounted. It doesn't matter where I set the max zoom level to, as soon as I hit it, the tiles disappear.

Any ideas?

**Comment by XGManuelJager** [comment]
Still happening on v3.2.1.
Setting maxZoom on the tileLayer works
