### ISSUE TITLE
LayerGroup.Collision

### ISSUE THREAD

**Issue by Shadowman4205** [PaulLeCam/react-leaflet#297]
I tried using plugin LayerGroup.Collision but i am getting error 
Uncaught TypeError: Cannot read property 'call' of undefined

```
import React, { PropTypes } from 'react';
import { MapLayer } from 'react-leaflet';
import L from 'leaflet';
import './collision.js';

export default class LayerGroupCollision extends MapLayer {
  static childContextTypes = {
    layerContainer: PropTypes.shape({
      addLayer: PropTypes.func.isRequired,
      removeLayer: PropTypes.func.isRequired,
    })
  }

  getChildContext() {
    return {
      layerContainer: this.leafletElement,
    }
  }
  createLeafletElement() {
    var t = L.layerGroup.collision({ margin: 20 }, this.getOptions());
    this.layerContainer.addLayer(t);
    return t;
  }

  componentDidMount() {
    const {map} = this.context;
    map.on("zoomend", this._onZoomEnd);
  }

  componentWillUnmount() {
    const {map} = this.context;
    map.off("zoomend", this._onZoomEnd);
  }
}
```

Any help with this [React-Leaflet-LayegroupCollision](http://stackoverflow.com/questions/42798222/react-leaflet-layergroup-collision-plugin)

**Comment by Shadowman4205** [comment]
Any help with this [React-Leaflet-LayegroupCollision](http://stackoverflow.com/questions/42643844/react-leaflet-collision)

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Extending.md#creating-custom-components) section of the documentation.
