### ISSUE TITLE
Issue with scrolling introduced in version 1.1.2

### ISSUE THREAD

**Issue by HeeL** [PaulLeCam/react-leaflet#298]
Starting from version 1.1.2 we have a weird behaviour:
Open map in lightbox, close it: as a result scrolling completely disabled (the user can't literally scroll the page anymore)

This issue is not there in version 1.1.1

**Comment by PaulLeCam** [comment]
Please try upgrading to v1.1.3 to see if it fixes the issue.

**Comment by HeeL** [comment]
@PaulLeCam yes, thank you, now it's been fixed
