### ISSUE TITLE
babel-plugin-lodash not used for transpiling 'lib'

### ISSUE THREAD

**Issue by larpo** [PaulLeCam/react-leaflet#299]
Seems that the babel plugin to map/shrink lodash imports is not used on 'build:lib', and thus using react-leaflet from npm causes the whole lodash to be included in webpack bundles.

I did quick test by manually transpiling the library code with  'lodash' plugin added to .babelrc, and sure enough, the bundle size dropped by about 40k.

Is there a reason why the plugin is not used for the code going to npm? I guess webpack/uglify should be able to slash off the dead code, but unfortunately that doesn't seem to be the reality...

**Comment by larpo** [comment]
Seems like 70cd9f32bb6 moved the plugin from .babelrc to webpack conf.

**Comment by PaulLeCam** [comment]
Yes good catch, I updated the config in v1.1.3 so it should be back to smaller imports.
