### ISSUE TITLE
Lib compile error

### ISSUE THREAD

**Issue by troutowicz** [PaulLeCam/react-leaflet#30]
@PaulLeCam In my PR #28, I forgot to include the babelfied equivalent. I went and ran the compile command last night, and it ran successfully... but upon trying to use those files, I was greeted with:

`Couldn't autodetect L.Icon.Default.imagePath, set it manually`

Mind investigating? From the little time I spent debugging I could not find an obvious reason for the error.

**Comment by PaulLeCam** [comment]
Hi,

The default path is set in the main file: https://github.com/PaulLeCam/react-leaflet/blob/master/src/index.js#L30 so maybe you tried to load a component directly instead of using the entry file?

**Comment by troutowicz** [comment]
@PaulLeCam I load components using the index file.

Example:
```js
const LeafletMap = require('react-leaflet').Map;
```
This works fine using the existing pre-compiled lib directory. Recompiling generates the error.

**Comment by PaulLeCam** [comment]
It's an issue with Leaflet I had originally developing this lib, that's why it's set by default in the entry file.

I just compiled the lib again without any problem, how are your trying to compile it?

**Comment by troutowicz** [comment]
I used `npm install; npm run compile`

**Comment by troutowicz** [comment]
@PaulLeCam It would be great if you could recompile in your build environment and update the repo. This repo is broken for me when I compile in my environment, I am developing on OSX. Whenever I compile, the default image path set in `index.js` never makes it to my components. I end up having to explicitly set the image path in my component.

**Comment by PaulLeCam** [comment]
Hi,

I could never reproduce the error compiling the lib, and Travis doesn't complain when running the tests, so it really seems like a runtime issue.
Could you please post a running example of the failing code in a jsbin or something like this?

**Comment by troutowicz** [comment]
This is strange. Yeah, I'll try to get you an example soon.

**Comment by troutowicz** [comment]
@PaulLeCam I do not experience the errors after installing v0.6.... I must have been building the source incorrectly.
