### ISSUE TITLE
Uncaught TypeError in the example fiddle

### ISSUE THREAD

**Issue by ResidentMario** [PaulLeCam/react-leaflet#301]
Open console on [this page](https://jsfiddle.net/paul_lecam/q2v7t59h/) (liked to from the docs) to see it.

Workaround (per [here](http://stackoverflow.com/questions/36672007/reactjs-cannot-read-property-keys-of-undefined)) is to load `babel-core@5.8.24` instead of using version 6, as this fiddle does.

**Comment by PaulLeCam** [comment]
Thanks for reporting this, should be fixed now in the jsfiddle.
