### ISSUE TITLE
Identify existing marker

### ISSUE THREAD

**Issue by shubham0892** [PaulLeCam/react-leaflet#302]
How can I identify if a marker is already present at a particular lat,lng. I have a JSON array of location along with names. Some of the locations are duplicate in that array. I want to identify whether a particular array value has already been used for the marker popup or not. Based on that result I can trigger some actions. How do I check if a marker is already rendered or not at a particular lat,lng?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.
