### ISSUE TITLE
could not get map and LayerContainer props in child component in version higher than 1.1.0

### ISSUE THREAD

**Issue by taozhi8833998** [PaulLeCam/react-leaflet#305]
I build an simple app, with the following code

```
const map = (
  <Map center={center} zoom={13}>
    <Marker position={center}>
      <Popup>
        <span>Using marker </span>
      </Popup>
    </Marker>
    <TaoZhiLayer  />
  </Map>
)
```

`TaoZhiLayer` is a simple compent as below shows

```
class TaoZhiLayer extends Component {
  render() {
    console.log('this.props====', this.props)
    return  <div>taozhi</div>
  }
}
```
 in `TaoZhiLayer` I could not get `map` and `layerContanier` properties in props, while I can get them in version `1.1.0`, anyone has met this issue??? if it not issue, how could I get them in my component when I installed react-leaflet version higher than `1.1.0`

**Comment by PaulLeCam** [comment]
These values are provided by the `context`, not the `props`, see [this section of the documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#component-context)

**Comment by taozhi8833998** [comment]
ok, thx, it works.
Further more, I have seen this from react official website
> If you want your application to be stable, don't use context. It is an experimental API and it is likely to break in future releases of React.
Thanks for ur help!

**Comment by mikew** [comment]
Quite shifty changing this in a bugfix release
