### ISSUE TITLE
Marker moves coordinates when I zoom in/out

### ISSUE THREAD

**Issue by rcwestlake** [PaulLeCam/react-leaflet#306]
### Expected behavior
I expect my marker to stay in the same position at all times. 

### Actual behavior
The marker moves coordinates. Very odd behavior. You'll notice in this gif that the popup stays in the same place even though the marker moves. http://g.recordit.co/KHcgInURpH.gif

### Steps to reproduce
I don't have specific steps. I have the Basemap and the marker nested inside of it as a separate component. My versions: 

React - ^15.4.2
ReactDOM - ^15.4.2
ReactLeaflet - 1.1.4
Leaflet - ^1.0.3

I have the react leaflet css file loaded. My code: https://github.com/rcwestlake/sports-map

**Comment by PaulLeCam** [comment]
Please provide steps to reproduce, with a jsfiddle or similar (you can use [this one](https://jsfiddle.net/paul_lecam/q2v7t59h/) to get started), not a complete project.

**Comment by YUzhva** [comment]
@rcwestlake I had the same issue when I configured marker with incorrect iconAnchor.

Let's say you would like to set a custom icon for a map with a size `iconSize: [28, 40]`, so you need to provide also iconAnchor like `iconAnchor: [14, 20]`.

**Comment by rcwestlake** [comment]
@YUzhva. Thanks for this. I'll give it a shot later today or tomorrow.

**Comment by rcwestlake** [comment]
This resolved the issue. I needed to add an explicit `iconSize` and `iconAnchor`. Thanks @YUzhva. I'll close this issue.
