### ISSUE TITLE
Passing props freely

### ISSUE THREAD

**Issue by jebarjonet** [PaulLeCam/react-leaflet#31]
Hi,

- It was a pain to give the Map the shape and size I wanted (using CSS class). It is nice somebody else did a merge request adding the *style* attribute to a Map component, but why do not you use the [ES6 destructuring assignment](https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx) to make it a lot easier and flexible to pass props to components ?

- Could you please upload the last version of compiled files here on Github ? (even after merge requests as it is the case right now) Depending on the computer I work on I can't compile it myself to keep it updated from your last **src** modified files.

*PS : I had some issues while showing a map but it was my bad, I edit this text + title issue*

Thanks !

**Comment by PaulLeCam** [comment]
Hi,

You can't allow all props to be passed the `Map` because the events are handled by Leaflet, not React. I'll make a new release with the added `style` prop on `Map` in the next few days.

**Comment by PaulLeCam** [comment]
Updated in v0.6.
