### ISSUE TITLE
`CircleMarker.center` not documented

### ISSUE THREAD

**Issue by dchambers** [PaulLeCam/react-leaflet#312]
Hi, I'm using a `CircleMarker`, and the only relevant documentation (for `Marker`) says that `position` is a required prop (to provide the LatLng), but after debugging it turned out that the prop name needs to be called `center`.

It would be great to update the docs here, but It would also be really helpful in general if type checking was used everywhere so you don't have to debug through the code each time you use the API incorrectly.

**Comment by PaulLeCam** [comment]
I don't know what doc you're referring to, because `CircleMarker` is documented as such: https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#circlemarker

**Comment by dchambers** [comment]
Ah, yes, so I was looking at this:

https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#marker
