### ISSUE TITLE
Feature request: add support for VectorGrid

### ISSUE THREAD

**Issue by stereobooster** [PaulLeCam/react-leaflet#313]
Trying to get [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid) support. Not successful so far.

Maybe you can give me some advices and I will do PR.

Related: https://github.com/Leaflet/Leaflet.VectorGrid/issues/37

**Comment by stereobooster** [comment]
Found solution

```js
// @flow

import L from 'leaflet';
import {} from 'leaflet.vectorgrid/dist/Leaflet.VectorGrid.bundled.js'

import PropTypes from 'prop-types';

import { default as childrenType } from './propTypesChildren';

import { GridLayer } from 'react-leaflet';

export default class VectorgridLayer extends GridLayer {
  static propTypes = {
    children: childrenType,
    opacity: PropTypes.number,
    url: PropTypes.string.isRequired,
    zIndex: PropTypes.number,
  };

  createLeafletElement(props: Object): Object {
    const { url, ...options } = props;

    return L.vectorGrid.protobuf(url, options);
  }

  updateLeafletElement(fromProps: Object, toProps: Object) {
    super.updateLeafletElement(fromProps, toProps);
    if (toProps.url !== fromProps.url) {
      this.leafletElement.vectorGrid.protobuf(toProps.url);
    }
  }
}
```

example of tiles URL `var mapboxUrl = "https://{s}.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/{z}/{x}/{y}.vector.pbf?access_token={token}";`

**Comment by stereobooster** [comment]
Also if anybody needs MapBoxGL integration:

```js
// @flow

import L from 'leaflet'
import {} from 'mapbox-gl-leaflet'
import PropTypes from 'prop-types'
import { childrenType, GridLayer } from 'react-leaflet'

export default class MapBoxGLLayer extends GridLayer {
  static propTypes = {
    children: childrenType,
    opacity: PropTypes.number,
    accessToken: PropTypes.string.isRequired,
    style: PropTypes.string,
    zIndex: PropTypes.number,
  }

  createLeafletElement(props: Object): Object {
    return L.mapboxGL(props)
  }
}
```

depends on:

```html
<script src='https://api.mapbox.com/mapbox-gl-js/v0.35.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.35.1/mapbox-gl.css' rel='stylesheet' />
```

```
yarn add mapbox-gl-leaflet
```

Compared [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid), [OpenLayers and MapBoxGL](https://osm2vectortiles.tileserver.com/#v3/mapboxgl). Only MapBoxGL feels fast.

**Comment by bardiaombre** [comment]
@stereobooster on your mapbox-gl, i cannot access childrenType  as of react-leaflet 1.1. any solution to how to fix it.

![screen shot 2018-11-14 at 1 35 05 pm](https://user-images.githubusercontent.com/43398867/48462176-24d82300-e812-11e8-80e5-ac8ce5faafcb.png)

**Comment by JensC** [comment]
@bardiaombre yes, I have the same problem. I can not update to react-leaflet v2 since it depends on React 16.x. Any solution would be great.

**Comment by Naseer-Ahmad** [comment]
Getting error in V3.1.0 "Attempted import error: 'GridLayer' is not exported from 'react-leaflet'."
