### ISSUE TITLE
Draggable Polygons

### ISSUE THREAD

**Issue by ranleung** [PaulLeCam/react-leaflet#314]
Hi,

Is there was a way to create draggable polygons?

Thanks for the library!

**Comment by PaulLeCam** [comment]
Hi,
If it's not supported by Leaflet directly, it won't be by this library either, but you can easily [create custom components](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Extending.md#creating-custom-components) to extend it, as it is notably done by [plugins](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Plugins.md#third-party-plugins).
