### ISSUE TITLE
Map component should handle changes to multiple class names

### ISSUE THREAD

**Issue by mikeldking** [PaulLeCam/react-leaflet#316]
### Expected behavior
The ```Map``` component should respect changes to multiple class names. For example, if class names are being used to change cartography using class names that follow BEM, you may have something like
```javascript
<Map className={`my-map my-map--${cartography}`}>
   ...
</Map>
```

### Actual behavior
The ```Map``` component assumes only a single class. 
```javascript
if (fromProps.className) {
   Leaflet.DomUtil.removeClass(this.container, fromProps.className);
}
```
If ```className``` is changed from "my-map my-map--dark" to "my-map my-map--light" for example, ```Leaflet.DomUtil``` throws an error when trying to remove the class with a space in it.

### Steps to reproduce
https://jsfiddle.net/vfa15L8c/13/

**Comment by PaulLeCam** [comment]
If it's not supported by Leaflet I don't plan on supporting it in this library either. You can always wrap the `<Map>` in a containing `<div>` is you need extra CSS rules.
