### ISSUE TITLE
Feature request: isVisible for Popup

### ISSUE THREAD

**Issue by stereobooster** [PaulLeCam/react-leaflet#317]
I have list of places. For each place I want to have marker. If I click on a place in a list I want to show popup for correspondent marker for correspondent place, to achieve this I will set state of parent component to selected place and then rerender marker with one of the Popups opened. Is this the way it should be done? If yes I can do simple PR with isVisible property Popup

**Comment by PaulLeCam** [comment]
Please refer to Leaflet's documentation, there is the [`isOpen()` method](http://leafletjs.com/reference-1.0.3.html#popup-isopen) that seem to provide what you need.

**Comment by stereobooster** [comment]
it is not. I do not want to check visibility - I want to control visibility in declarative manner, like this:

```js
<Popup isOpen={true}>
<Popup isOpen={false}>
```

I know that this lib integrates with third-party, so not all React paradigms are feasible, that's why I'm asking if this is good idea or not

**Comment by stereobooster** [comment]
As of now Marker-Popup pair works as [uncontrolled component](https://facebook.github.io/react/docs/uncontrolled-components.html) e.g. it maintain it's own internal state and this state updated directly with user interaction, not through react setState.

What I'm suggesting is to implement  [controlled component](https://facebook.github.io/react/docs/forms.htmll) e.g. Popup will open if you set state or property externally.

**Comment by PaulLeCam** [comment]
As far as I know It's not something supported by Leaflet itself so it won't be implemented in this library either, but you can always create a custom component to implement the logic you need.

**Comment by stereobooster** [comment]
This is not concern of Leaflet, this is concern of React implementation. Html input does not support this behaviour out of the box too, instead React component use event handler and e.preventDefault to achieve Reactive way to do it.

**Comment by PaulLeCam** [comment]
I understand what you're asking but this is out of the scope of this library.
One important thing to consider is that Leaflet maintains its own state and handles the interactions with the DOM, React only provides the component abstraction, see the ["how it works" section of the documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md) for more information.

**Comment by stereobooster** [comment]
I get your point, way to do this is to implement "plugin". Just one note

> One important thing to consider is that Leaflet maintains its own state and handles the interactions with the DOM

html `<Input>` maintains its own state too, but React folks take step further and wrote wrapper to adapt it to React workflow. This is not a general stopper, this is just a choice.

**Comment by draganSm** [comment]
@stereobooster I've managed to open the popup with the following code (just the prototype):

~~~
const targets = targetList.map(target => (
      <Marker position={[target.lat, target.lng]} key={target.id}>
        <Popup ref={ref => !target.valid && setTimeout(() => x(ref, [target.lat, target.lng]))}>
          <Target target={target} />
        </Popup>
      </Marker>));
~~~
~~~
function x(ref, pos) {
  ref.context.map.openPopup(ref.leafletElement, pos);
}
~~~
I know ... setTimeout in reder... Didn't find a better implementation yet.

**Comment by pvhieuit** [comment]
I found this in [jsfiddle](https://jsfiddle.net/jrcoq72t/)
```javascript
// Create your own class, extending from the Marker class.
class ExtendedMarker extends Marker {
  // "Hijack" the component lifecycle.
  componentDidMount() {
    // Call the Marker class componentDidMount (to make sure everything behaves as normal)
    super.componentDidMount();
    
    // Access the marker element and open the popup.
    this.leafletElement.openPopup();
  }
}
`````

```javascript
  render() {
    const position = [this.state.lat, this.state.lng];
    return (
      <Map center={position} zoom={this.state.zoom}>
        <TileLayer
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
        />
        <ExtendedMarker position={position}>
          <Popup>
            <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
          </Popup>
        </ExtendedMarker>
      </Map>
    );
  }
```

**Comment by mikedeng** [comment]
I agree with @pvhieuit, but it will report an error in  react-leaflet `v2`, this error will appear: 
```
TypeError: Super expression must either be null or a function, not object
```
and the solution goes [here](https://github.com/verdie-g/react-leaflet-rotatedmarker/issues/1)

**Comment by phanirithvij** [comment]
My workaround using accessing the dom (horrible but works).

Using hooks and functional components, and programmatically clicking on the marker to open/close it.

```jsx
  const togglePopup = () => {
    document.querySelectorAll(".marker-x")?.[1].click();
  };

  const openPopup = () => {
    if (document.querySelector(".popupcl")) {
      // popup is already open because the popup div exists
      // that div i.e. the popup, will be removed from dom by leaflet when we close the popup
      // already open so return
      return;
    }
    // I'm using shadow and react-leaflet assigns the className to both the marker and the shadow
    // might need to use [0] or just document.querySelector(".marker-x") if not using shadow (untested)
    document.querySelectorAll(".marker-x")?.[1].click();
  };

  const [position, setPos] = useState(null);
  useEffect(() => {
    if (position !== null) openPopup();
  }, [position]);

    <Marker
      draggable={true}
      .....
      // Need to use this icon to specify a class to act as an identifier for the marker image
      icon={
        new Icon({
          iconUrl: icon,
          shadowUrl: shadow,
          // Add a custom classname so we can query it
          className: "marker-x",
        })
      }
      position={position}
    >
      {/*  Using a custom classname here to query this as well  */}
      <Popup ... className="popupcl">
         ...
       </Popup>
     </Marker>

```

Leaflet provides these functions openpopup, closepopup, [etc.](https://leafletjs.com/reference-1.7.1.html#map-openpopup) so would be great if this library also provides those methods at the top level.

**Comment by danielvandermaas** [comment]
Maybe in many cases it could be better to use the Tooltip component instead of automatically opening the popup component.

https://stackoverflow.com/questions/65345016/react-leaflet-add-label-popup-next-to-marker

**Comment by yonycalsin** [comment]
using the latest versions of the libraries, it works as follows using the `openPopup` method of `leaflet`.

```jsx
        <Marker
          position={[51.505, -0.09]}
          ref={ref => {
            setTimeout(() => ref?.openPopup(), 500)
          }}
        >
          <Popup>A pretty CSS3 popup. Easily customizable.</Popup>
        </Marker>
```

**Comment by raven-wing** [comment]
If like me you'd like to use Popup like `{isMarkerClicked && Popup}` instead of using:

```
export const AutoOpenPopup = ({ children }) => {
    const popupRef = useRef(null);

    useEffect(() => {
        if (popupRef.current) {
            const marker = popupRef.current._source;
            if (marker) {
                marker.openPopup();
            }
        }
    }, []);

    return <Popup ref={popupRef}>{children}</Popup>;
};
```
