### ISSUE TITLE
Issue in map loading, its getting loaded in disarranged tiles out of which some tiles are blank. 

### ISSUE THREAD

**Issue by neeraj022** [PaulLeCam/react-leaflet#322]
Node version: 6.10.2
react-leaflet version: 1.1.6
leaflet version: 1.0.3
![screenshot from 2017-05-11 15 12 26](https://cloud.githubusercontent.com/assets/8348573/25943118/6f3cd4cc-365c-11e7-8e81-e29a9fb7b23d.png)

**Comment by PaulLeCam** [comment]
Please follow the issue template.

**Comment by stunningpixels** [comment]
Getting this too

**Comment by stunningpixels** [comment]
@neeraj022 make sure you include the leaflet CSS file and give the map height, `<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css">` fixed it for me

**Comment by neeraj022** [comment]
Thanks...working for me now.. Didn't include leaflet.css in the css file.

**Comment by Roconda** [comment]
How did you fix this @neeraj022 ?

**Comment by ggwc82** [comment]
@Roconda you need to add that link rel to your index.html, and also make sure you have this in your index.css:

```
.leaflet-container {
    height: 400px;
    width: 100%;
}
```

I spent the better half of a day trying to figure out what my issue was, @PaulLeCam the instructions need to be clearer to make sure you include the leaflet.css file.

**Comment by hqzh** [comment]
import 'leaflet/dist/leaflet.css';
