### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by diegoarcega** [PaulLeCam/react-leaflet#327]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Using a supported version of React and ReactDOM (v15.0.0+).
- [x ] Using the supported version of Leaflet (v1.0.0) and its corresponding CSS file is loaded.
- [x ] Using the latest version of React-Leaflet.
- [x ] The issue has not already been reported.
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Not fail in CI

### Actual behavior

```
+-- UNMET PEER DEPENDENCY leaflet@1.0.3
+-- UNMET PEER DEPENDENCY react@15.5.4
+-- UNMET PEER DEPENDENCY react-dom@15.5.4
`-- UNMET PEER DEPENDENCY react-leaflet@1.1.6
```

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue

`npm install` in CI
Locally I dont get this issue

**Comment by PaulLeCam** [comment]
You need to add these dependencies to your `package.json`, cf https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Getting%20started.md#using-npm-or-yarn

**Comment by diegoarcega** [comment]
Those are already installed @PaulLeCam

**Comment by diegoarcega** [comment]
@PaulLeCam  all good, sorry it was a problem with cache in CI... thanks!!
