### ISSUE TITLE
console.log in Polygon updateLeafletElement function

### ISSUE THREAD

**Issue by bchelkow** [PaulLeCam/react-leaflet#334]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.0.0+).
- [x] Using the supported version of Leaflet (v1.0.0) and its corresponding CSS file is loaded.
- [x] Using the latest version of React-Leaflet.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

No `console.log` in Polygon **updateLeafletElement** function.

### Actual behavior

`console.log` in Polygon **updateLeafletElement** function.

### Steps to reproduce

console.log:
https://github.com/PaulLeCam/react-leaflet/blob/master/src/Polygon.js#L30

**Comment by PaulLeCam** [comment]
Fixed in v1.2.1
