### ISSUE TITLE
auto-pan is re-triggered for an open popup when markers are added or removed on the map

### ISSUE THREAD

**Issue by qrohlf** [PaulLeCam/react-leaflet#336]
### Expected behavior

When a marker popup is opened, the auto-pan should be triggered. Afterwards, auto-pan should NOT be triggered and the user should be able to pan away from the popup (provided `keepInView=false`), even if updates are made to the map while the popup is open.

### Actual behavior

While a marker popup is opened, auto-pan will be triggered each time a different marker is added or removed on the map.

### Steps to reproduce

https://www.webpackbin.com/bins/-Kle4Bvy078Jnxxr1QhZ

1. click the marker in the center of the map to open the popup
2. pan the map such that the popup is off the screen
3. wait for the second marker to be added/removed

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for general questions about it.

**Comment by qrohlf** [comment]
@PaulLeCam I'm not sure how this isn't a bug in the library - leaflet itself doesn't exhibit this behavior, I've included reproduction steps, and it seems like a pretty clear mechanic that one of the methods that `<Popup />` or `<Marker />` is calling in componentDidUpdate is causing Leaflet to re-do the map layout stuff when it shouldn't. 

I can investigate this myself if you don't have time, but I'm not sure why you closed the issue without explaining why this isn't a bug in react-leaflet.

**Comment by qrohlf** [comment]
@PaulLeCam I have confirmed that vanilla Leaflet dos not exhibit this behavior, meaning this is a possible bug in the library. I'd appreciate it if you could re-open this issue.

**Comment by mjclawar** [comment]
@qrohlf Looks like the actual argument that prevents it from panning for your example is [`autoPan`](http://leafletjs.com/reference-1.1.0.html#popup-autopan). This defaults to true.

[`keepInView`](http://leafletjs.com/reference-1.1.0.html#popup-keepinview) just forces the popup to stay in the map view.

If you add `autoPan={false}` to the first `Popup` component in your example, you'll get the intended behavior.
If you set `keepInView={true}` with no `autoPan` argument in the first `Popup` component in your example, you won't be able to move the map.

**Comment by qrohlf** [comment]
@mjclawar That makes sense, it looks like this is an issue with leaflet itself: https://github.com/Leaflet/Leaflet/issues/2937. My mistake.

I'm opening an issue with leaflet since I believe this is undesired behavior (the popup should auto-pan when opened, but adding or removing sibling markers shouldn't re-trigger a popup to pan into view when the user isn't interacting with it at all).

**Comment by ko80** [comment]
@qrohlf Quick question: were you able to solve the issue?

I have the same problem with `<Popup>` in react-leaflet. There are some markers with popups on the map. When I click a marker, a popup opens, and Leaflet automatically does some panning to show the whole content of the popup. Then I pan to another location, and the popup (still open) gets off the visible area. In a moment, a periodic fetch operation completes, the contents on that popup are updated with the fetched data, and Leaflet automatically pans to the opened popup again. And that confuses the user significantly.

Any ideas on how to prevent Leaflet from re-panning to the opened popup when its contents are updated are highly appreciated.

**Comment by qrohlf** [comment]
We migrated off react-leaflet entirely, I don’t believe I wound up solving
this issue before that happened.

**Comment by ko80** [comment]
I think I've found a simple solution for the issue. It is based on react-leaflet hooks.

By default, in `<Popup>` the option `autoPan` is set to `true`. I've left it as it is, and added some processing for map events to manipulate the `autoPan` option. The deferred timeout function is a workaround to avoid incorrect panning when the popup is opened for the first time. Without the timeout, the panning is adjusted to the initial empty popup measurements, with no respect to the contents put in that popup.

```
const map = useMap();
useMapEvents({
  popupopen: (e) => setTimeout(() => e.popup.options.autoPan = false, 100),
  popupclose: (e) => e.popup.options.autoPan = true,
});
```

I hope it will help someone avoid that confusing behavior.
