### ISSUE TITLE
onEachFeature for GeoJSON data does not work

### ISSUE THREAD

**Issue by mohitnatoo** [PaulLeCam/react-leaflet#338]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.x) and its corresponding CSS file is loaded.
- [x] Using the latest version of React-Leaflet.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

I have added code to jsfiddle to test on click events for each feature of GeoJSON data.
https://jsfiddle.net/ojofr4v2/1/
The click events work as expected.

I have then written exact same code in my app with only change from the jsfiddle code being importing components from libraries instead of window.
https://gist.github.com/mohitnatoo/99e88a3f897a7a951eb6d29c25a30497

Expected is the output of this code should behave similar to that in jsfiddle.

### Actual behavior

The output of the code present in the gist does not respond to clicks.

Used exactly the same versions of React, ReactDOM, Leaflet and ReactLeaflet as those present in the jsfiddle code.

I've gone through the source code and couldn't find any example of the use of `onEachFeature`. Would be helpful if a working example of the same could be provided in the codebase for GeoJSON component.

**Comment by PaulLeCam** [comment]
You seem to be using an old jsfiddle as reference with outdated dependencies, the code from your gist works as expected in webpackbin: https://www.webpackbin.com/bins/-KmT3ODX5UKFZuZ6ehVt
