### ISSUE TITLE
Best way to interact with layers

### ISSUE THREAD

**Issue by hokkos** [PaulLeCam/react-leaflet#34]
Hi,
thanks for your lib,
I wonder what is the best way to to interact with vector layers, for now I use ref in the component that contains the map on the layers to access leafletElement to be able to do :
````javascript
this.map.getLeafletElement().fitBounds(this.refs.circle.leafletElement.getBounds())
````
I could compute the bounds but it would duplicate the complexity already handled by leaflet.
Or maybe should I subclass the Circle component, and make it a ["connected component"](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) that handle it himself.
Any idea ?
Thanks.

**Comment by PaulLeCam** [comment]
It really depends on your use case, if you're using Flux you would likely have the properties of your circle set in a store, so it would make sense to update the map based on these values as well.
If your map layers are your sources of truth, your solution seems good.
