### ISSUE TITLE
Leaflet Popup Autopan doesn't always move whole popup into view when clicking marker

### ISSUE THREAD

**Issue by andersodt** [PaulLeCam/react-leaflet#342]
### Expected behavior

When clicking on a marker near the edge of the map view, the map should pan to show the entire contents of the popup.

### Actual behavior

When clicking on a marker near the edge of the map view, the map pans slightly, only showing the very bottom of the popup. 

### Steps to reproduce

Go to [the default WebpackBin](https://www.webpackbin.com/bins/-Kl_ZeUx4I05ETYoT26O).
Move the map so the marker is near the top of the screen.
Click the marker.

Compare this result with:
Go to [LeafletJS.com](http://leafletjs.com)
Move the map so the marker is near the top of the screen.
Click the marker.

When going on LeafletJS.com, the marker's popup moves into view. When doing this using react-leaftlet, the popup does not move into view. 

Here are some images of this in practice:

## React-leaflet:
<img width="494" alt="screen shot 2017-06-20 at 12 38 15 pm" src="https://user-images.githubusercontent.com/1243035/27347360-efe83634-55b5-11e7-8b40-b73529a8681c.png">
<img width="474" alt="screen shot 2017-06-20 at 12 38 36 pm" src="https://user-images.githubusercontent.com/1243035/27347365-f314aae0-55b5-11e7-8dcc-76fb235f2df5.png">

## LeafleatJS.com:
<img width="886" alt="screen shot 2017-06-20 at 12 38 26 pm" src="https://user-images.githubusercontent.com/1243035/27347373-f6345afe-55b5-11e7-8444-96a332694819.png">
<img width="882" alt="screen shot 2017-06-20 at 12 38 42 pm" src="https://user-images.githubusercontent.com/1243035/27347377-f806f30a-55b5-11e7-86c0-c1618bbc35f0.png">

**Comment by PaulLeCam** [comment]
Thanks for the detailed report, should be fixed in v1.3.1.

**Comment by andersodt** [comment]
Great! Looks like it's working well for me. Thank you for fixing this so quickly, and thank you for your work on this project.

**Comment by PaulLeCam** [comment]
Thanks!

**Comment by mhyassin** [comment]
This isn't working again for some reason!
