### ISSUE TITLE
Lodash in final bundle

### ISSUE THREAD

**Issue by gmarcos87** [PaulLeCam/react-leaflet#343]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior
Import only required lodash parts

### Actual behavior
Lodash is importing integer when I visualize the dependencies of my project. The only dependence that uses it is react-leaflet. This increases many kb the final bundle.

![webpack-visualizer](https://preview.ibb.co/nEr0nk/Captura_de_pantalla_de_2017_06_27_14_24_58.png)

**Comment by gmarcos87** [comment]
It's not all lodash but it's a lot, you can see in [this repository](https://github.com/gmarcos87/lodash-on-react-leaflet) a replica of the dependencies. The total weight of the bundle is 36kb.

**Comment by PaulLeCam** [comment]
Only the required Lodash functions as loaded, as you can see in the generated files.
