### ISSUE TITLE
No support for map state change events?

### ISSUE THREAD

**Issue by anthonyshull** [PaulLeCam/react-leaflet#344]
### Expected behavior

I am trying to detect when a map has been zoomed via touch. I added zoomend={} to the Map element. I would expect it to trigger my listener at the end of a series of zoom actions.

### Actual behavior

The listener is never fired.

### Steps to reproduce

https://www.webpackbin.com/bins/-KoDG0D_U4C4Ge5uijVd

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
