### ISSUE TITLE
Map dynamic property useFlyTo not working (or I am unable to use it)

### ISSUE THREAD

**Issue by corneliusgdahling** [PaulLeCam/react-leaflet#347]
I have created a simple codepen [React-leaflet useFlyTo not working](https://codepen.io/corneliusgdahling/pen/eRXZbY), where I just have a Map and a button below it. When I click the button I change the state which manipulates the center position from London to New York. I have included `useFlyTo={true}` as a prop in the `Map` component, however this does not create the `map.flyTo` animation as explained in the [leaflet documentation for flyTo](http://leafletjs.com/reference-1.0.0.html#map-flyto). Instead the default `map.setView` is used.

Am I missing something else to enable it? Looking at the [react-leaflet API for useFlyTo](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#map), it seems that `useFlyTo` is just a `boolean` value that you add to the Map and that is all you need.

## Workaround
By creating an instance of the leaflet map explained by @PaulLeCam [here](https://github.com/PaulLeCam/react-leaflet/issues/256), I was able to utilize the `map.flyTo([lat, long], zoom)` to create the desired flyTo effect. You can see the codepen at [react-leaflet flyTo working with leaflet map instance](https://codepen.io/corneliusgdahling/pen/ZyPOYG)

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
