### ISSUE TITLE
Map dynamic property useFlyTo not working (or I am unable to use it)

### ISSUE THREAD

**Issue by corneliusgdahling** [PaulLeCam/react-leaflet#348]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet. 
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.x) and its corresponding CSS file is loaded.
- [x] Using the latest version of React-Leaflet.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start/) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/API.md) and that you understand the [technical considerations.](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations)

## Steps to reproduce
I have created a simple codepen [React-leaflet useFlyTo not working](https://codepen.io/corneliusgdahling/pen/eRXZbY), where I just have a Map and a button below it.

## Expected behavior
When I click the button I change the state which manipulates the center position from London to New York. I have included `useFlyTo={true}` as a prop in the `Map` component, which should create the `map.flyTo` animation as explained in the [leaflet documentation for flyTo](http://leafletjs.com/reference-1.0.0.html#map-flyto).

## Actual behavior
The `flyTo` animation is not used at all and instead the default `map.setView` is used.

## Verdict
Am I missing something else to enable it? Looking at the [react-leaflet API for useFlyTo](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#map), it seems that `useFlyTo` is just a `boolean` value that you add to the Map and that is all you need.

## Workaround (if someone googling finds this)
By creating an instance of the leaflet map (explanation on how to do that by @PaulLeCam [here](https://github.com/PaulLeCam/react-leaflet/issues/256)), I was able to utilize the `map.flyTo([lat, long], zoom)` to create the desired flyTo effect. You can see the codepen at [react-leaflet flyTo working with leaflet map instance](https://codepen.io/corneliusgdahling/pen/ZyPOYG)

**Comment by PaulLeCam** [comment]
This is the expected behavior, please refer to [Leaflet's documentation](http://leafletjs.com/reference-1.1.0.html#zoom/pan-options-animate)

**Comment by corneliusgdahling** [comment]
Did you even read the issue? `flyTo `from leaflet works just as expected. `useFlyTo` prop from react-leaflet however does not use the [leaflet `flyTo` animation](http://leafletjs.com/reference-1.1.0.html#map-flyto). That is the whole point. [Working implementation](https://codepen.io/corneliusgdahling/pen/ZyPOYG) where I use `.flyTo` directly on an instance of the leaflet map. However, when I try something similar but just using the `useFlyTo` prop in react-leaflet it does not work, as you can see [here](https://codepen.io/corneliusgdahling/pen/eRXZbY).

**Comment by SleipRecx** [comment]
@corneliusgdahling Yo go girl !!
