### ISSUE TITLE
maxZoom and minZoom update not work on Map

### ISSUE THREAD

**Issue by willkan** [PaulLeCam/react-leaflet#350]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.1.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior
map component should update max zoom properly when max zoom update .

### Actual behavior
map component did not update max zoom properly when max zoom update .

### Steps to reproduce

example code refer to  <https://www.webpackbin.com/bins/-KpPQllgV40qn3E7hrxq>

**Comment by PaulLeCam** [comment]
Please only check the boxes if you have actually done what they say... this is the expected behavior, [as documented](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#component-properties).

**Comment by willkan** [comment]
@PaulLeCam I have actually done all the boxes, but the problem still exist. Could you try the the example I mentioned above?

**Comment by willkan** [comment]
@PaulLeCam Did you mean if I want to properly update the `maxZoom` , I should directly write some code such as `this.refs.map.leafletElement.setMaxZoom(max)`?

**Comment by PaulLeCam** [comment]
Yes, it's not supported as a "dynamic property" as documented in the link above, so there is no logic to update the value from the Map's props to the Leaflet element.

**Comment by willkan** [comment]
uhh...okay, thanks.

**Comment by valstu** [comment]
If I would like to make some property dynamic lets say `minNativeZoom` on `TileLayer` dynamic what would be the best approach to that?

**Comment by jahed** [comment]
@valstu extend the component and implement it yourself by overriding `updateLeafletElement` or fork the project and apply the fix directly. I've taken the former approach, it's relatively straight forward. The difficult part is remembering which props are already dynamic and which aren't.

**Comment by ErnestBrandi** [comment]
If it can save you some time 
```
import L from 'leaflet';
import { Map, withLeaflet } from 'react-leaflet';

class CustZoomMap extends Map {
  constructor(props) {
    super(props)
  }

  componentDidUpdate(prevProps) {
    super.componentDidUpdate(prevProps)
    this.leafletElement.setMinZoom(this.props.minZoom)
  }
}

export default withLeaflet(CustZoomMap);
```
