### ISSUE TITLE
Marker images not loading with webpack

### ISSUE THREAD

**Issue by quesurifn** [PaulLeCam/react-leaflet#351]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [X ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ X] Using a supported version of React and ReactDOM (v15.x).
- [X] Using the supported version of Leaflet (v1.1.x) and its corresponding CSS file is loaded.
- [X] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Marker image loads

### Actual behavior

MArker image 404

### Steps to reproduce

WEbpack setup: 

```
var HtmlWebpackPlugin = require('html-webpack-plugin')
var HTMLWebpackPluginConfig = new HtmlWebpackPlugin({
  template: __dirname + '/app/index.html',
  filename: 'index.html',
  inject: 'body'
});
module.exports = {
  output: {
  publicPath: './public'  
  },
  entry: [
    'babel-polyfill',
    './app/index.js'
  ],
  module: {
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loader: "babel-loader"},
      { test: /\.css$/, loader: "style-loader!css-loader" },
      {test: /\.(jpe?g|png|gif|svg)$/i,loaders: [
            'file-loader?hash=sha512&digest=hex&name=[hash].[ext]',
            'image-webpack-loader?bypassOnDebug&optimizationLevel=7&interlaced=false'
        ]}
    ]
  },
  devServer: {
    historyApiFallback: true,
  }, 
  output: {
    filename: "index_bundle.js",
    path: __dirname + '/dist'
  },
  plugins: [HTMLWebpackPluginConfig]
};


```

**Comment by PaulLeCam** [comment]
Build systems are out of the scope of this library, it's more likely an issue with your configuration than anything to do with this library.

**Comment by aproberts01** [comment]
Any resolution? I am having the same issue.
