### ISSUE TITLE
Can't zoom to 0

### ISSUE THREAD

**Issue by gffuma** [PaulLeCam/react-leaflet#352]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.1.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

To zoom to 0.

### Actual behavior

Don't zoom to 0. 
I think the problem is here: 
https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L139

0 is falsy in js so when 0 in provided don't pass the if condition and the zoom didn't change. 

### Steps to reproduce

https://www.webpackbin.com/bins/-KpnwxVUx-EKWJX79Ned

**Comment by PaulLeCam** [comment]
Yes good catch, thanks for reporting this!
It should be fixed in v1.4.1, please give it a try.
