### ISSUE TITLE
maxBoundsViscosity property on Map element.

### ISSUE THREAD

**Issue by martsie** [PaulLeCam/react-leaflet#353]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.1.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior
Setting maxBoundsViscosity={1} on the map element will result in the map stopping abruptly when the user attempts to drag outside of the maxBounds.

### Actual behavior
Does nothing.

I can't find the maxBoundsViscosity property anywhere in the source for this project - is there a magic way that we can apply Leaflet properties to the Map element even if they aren't in the support propTypes for the component (ie if this project lags behind leaflet)?

**Comment by PaulLeCam** [comment]
There is nothing magic about it, the props are simply passed as options to the relevant Leaflet factory, ex https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L98
`maxBoundsViscosity` works as expected, whatever issue you're having is likely from your end, please make sure you have actually followed the steps of the issue template before checking the boxes, or at least use WebpackBin to provide an example.
