### ISSUE TITLE
BaseLayer -- Uncaught TypeError: addBaseLayer is not a function

### ISSUE THREAD

**Issue by 11samype** [PaulLeCam/react-leaflet#356]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.1.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

BaseLayer is added to LayerControl on Leaflet map in React

### Actual behavior

Map is blank and error in console: Uncaught TypeError: addBaseLayer is not a function

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this WebpackBin](https://www.webpackbin.com/bins/-Kl_ZeUx4I05ETYoT26O).

https://www.webpackbin.com/bins/-KrGeo-xgj73pzuZdDBU

**Comment by PaulLeCam** [comment]
There is no Map rendered in your example, please use the reference WebpackBin to reproduce your issue.

**Comment by 11samype** [comment]
Sorry about that. I have updated my comment.
https://www.webpackbin.com/bins/-KrBZ-3qiOr0SMun_B-K

**Comment by PaulLeCam** [comment]
You example is still breaking, whatever problem you're having doesn't seem related to this lib.

**Comment by 11samype** [comment]
I'll try one more time: https://www.webpackbin.com/bins/-KrGeo-xgj73pzuZdDBU

I really want to get this example to work. Even if it is an issue on my end I would appreciate a pointer. Would love to use this lib.

**Comment by 11samype** [comment]
Nevermind, found my issue.
