### ISSUE TITLE
Change pane on-the-fly

### ISSUE THREAD

**Issue by NekitoSP** [PaulLeCam/react-leaflet#357]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

I need to change pane for layer on-the-fly (by changing props).

### Actual behavior

Pane don't changed, because GridLayer.updateLeafletElement() don't handles pane prop changing.

### Steps to reproduce

https://www.webpackbin.com/bins/-KrFpAF4E-kYmc45AhAk

**Comment by PaulLeCam** [comment]
I don't know why you're expecting this behavior, as far as I know it's not documented anywhere.

**Comment by NekitoSP** [comment]
I expect this behavior because changing props is part of React lifecycle. And what this wrapper (react-leaflet) about.

Getting started.md
> It does not replace Leaflet, only leverages React's lifecycle methods to call the relevant Leaflet handlers.

**Comment by PaulLeCam** [comment]
As indicated part of the issue template checklist, make sure to read the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

**Comment by NekitoSP** [comment]
Thanks!
