### ISSUE TITLE
TileLayer 

### ISSUE THREAD

**Issue by diligiant** [PaulLeCam/react-leaflet#361]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Creating a `TileLayer` with `detectRetina=true` should enable retina maps on retina displays.

### Actual behavior

It does not… unless you set `maxZoom` in `<Map />` or in <TileLayer />` which is a deviation from Leaflet specs.

When [creating the LeafLetTileLayer](https://github.com/PaulLeCam/react-leaflet/blob/master/src/TileLayer.js#L22), you call `GridLayer.getOptions` which by default sets minZoom and maxZoom to `<Map />` values. This is where the problem lies:

While Leaflet Map [zoom defaults are undefined](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L59), Leaflet Tile [zoom defaults have values](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L50) that is uses later on to enable retina.

BTW, same issue for `<GridLayer />` as its zoom defaults are extracted from map too (undefined/undefined) where they are 1/undefined for Leaflet GridLayer.

If this was me, I'd leave options defaults handling to Leaflet but I don't have the whole picture.

**Comment by PaulLeCam** [comment]
I removed setting the `maxZoom` and `minZoom` from map in `GridLayer` in v1.6.1, could you please check if it solves your problem?

**Comment by diligiant** [comment]
it does. Thank you!
