### ISSUE TITLE
Popup contents are removed before fade transition ends

### ISSUE THREAD

**Issue by pbock** [PaulLeCam/react-leaflet#365]
### Expected behavior

Upon closing a `Popup`, the popup should fade out, including its contents.

### Actual behavior

The popup fades out, but its contents are removed before the transition has ended. The height shrinks to 0 + the popup's padding. The width remains unchanged.

### Steps to reproduce

Click the marker in https://www.webpackbin.com/bins/-Kl_ZeUx4I05ETYoT26O, then close it by clicking the <kbd>×</kbd> button. The popup should fade out during ~200ms whilst its contents have already been removed.

See also this screenshot taken milliseconds after clicking the close button:
<img width="490" src="https://user-images.githubusercontent.com/4964364/29590012-247622bc-8798-11e7-85d3-7a7a507ef09d.png">

**Comment by diligiant** [comment]
Does leaflet behave like you expect if you use it directly?

**Comment by pbock** [comment]
Yes, thanks, I should have mentioned: [Leaflet behaves as expected](https://codepen.io/pb/pen/NvzrVR), so this seems to be down to react-leaflet.

It looks like the exit transition was added in [Leaflet 1.0.0](https://codepen.io/pb/pen/BdVzXK). Playing around with the version numbers a bit, Leaflet also seems to have changed its mind on whether there should be an enter transition, an exit transition, or both.

**Comment by PaulLeCam** [comment]
This is the expected behavior for this library, the same way the React elements get rendered when the popup opens, they get unmounted when the popup closes. This is simply a trade-off of supporting React elements as popup contents.
If you want to avoid this behavior, you can create a [custom component](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Extending.md#creating-custom-components) implementing the logic you need.

**Comment by pbock** [comment]
I see, thanks for the explanation!

If disabling the transition is an option (or even desired), this can also be worked around by adding

```css
.leaflet-fade-anim .leaflet-popup {
  transition: none;
  /* … (browser prefixes as needed) */
}
```

to the page CSS.

**Comment by zeckdude** [comment]
That seems pretty lame to just say it's not possible to wait for the transition to finish before unmounting the React element. Is there no way to set a timeout to match the CSS transition time period that unmounts once the time period has passed?

My current solution will need to be to disable the animation but I refuse to believe that React is the new hotness and can't display the fancy animations.
