### ISSUE TITLE
Example/ideas about importing plugins

### ISSUE THREAD

**Issue by swennemans** [PaulLeCam/react-leaflet#37]
How hard/simple would it be to import existing plugins? For example the https://github.com/Leaflet/Leaflet.markercluster is a very nice plugin, but I don´t have any idea about how hard it will be to implement this in react. 

Are there any examples of ported plugins?

**Comment by troutowicz** [comment]
Hi @swennemans 
I came up with a [MarkerCluster](https://github.com/troutowicz/geoshare/blob/master/app/components/MarkerCluster.jsx) component for my project. It has some project specific logic in it at the moment, but it should give you an idea on what it takes to reactify leaflet plugins. In my project, I use the component [here](https://github.com/troutowicz/geoshare/blob/master/app/components/Map.jsx#L21).

**Comment by PaulLeCam** [comment]
Hi,
For plugins that provide additional layers, integration should be pretty easy by extending one of the [base components](https://github.com/PaulLeCam/react-leaflet#base-components) provided and implementing the relevant lifecycle handlers (most likely `componentWillMount` and `componentDidUpdate`) as it is done in the lib, ex with then [Rectangle component](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Rectangle.js).

**Comment by swennemans** [comment]
@troutowicz and @PaulLeCam thanks for your replies. And @troutowicz thanks for sharing, very useful :)

**Comment by swennemans** [comment]
@troutowicz cool app btw :) Works really nice. 
I'm also using alt + leaflet combo it's reassuring that it works smoothly :+1:
