### ISSUE TITLE
Missing Path options

### ISSUE THREAD

**Issue by northerneyes** [PaulLeCam/react-leaflet#374]
You didn't implement http://leafletjs.com/reference-1.2.0.html#interactive-layer options

they are absent in the code
https://github.com/PaulLeCam/react-leaflet/blob/master/src/types.js

Also, you should review these options:
https://github.com/PaulLeCam/react-leaflet/blob/master/src/Path.js#L11
with the current options:
http://leafletjs.com/reference-1.2.0.html#path

There is no 'clickable' or 'pointerEvents' options, for example

**Comment by PaulLeCam** [comment]
Should be fixed in v1.6.6, please try it out.
