### ISSUE TITLE
Creating a new MapLayer

### ISSUE THREAD

**Issue by lbrouckman** [PaulLeCam/react-leaflet#377]
`export default class RoutingMachine extends MapLayer<LeafletElement, Props>`
`{`
`  public render()`
` . {`
`    return null;`
`  }`
`  public createLeafletElement(props)`
`  {`
`   const { to, from } = props;`
 `    return L.Routing.control({`
`    position: 'topleft',`
`    waypoints: [`
`    L.latLng(from[0], from[1]),`
`    L.latLng(to[0], to[1]),`
`    ],`
`    router: L.Routing.mapbox('API_KEY'),`
`   });`
` }`

Using the above class as follows 
`       <RoutingMachine
            to={[37.4449002, -122.16174969999997]}
            from={[37.54554419999999, -122.29136640000002]}
          />
`

I get an error stating that: The provided object is not a Layer.
I followed the guidelines provided on how to create an extension to the react-leaflet elements, I'm not sure where I went wrong.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
