### ISSUE TITLE
Getting GeoJson data from the map

### ISSUE THREAD

**Issue by vinaykhade** [PaulLeCam/react-leaflet#379]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Hi guys, I'm trying to retrieve the GeoJson data of a circle with a certain fixed radius on the map. I'm not able understand how do I retrieve the GeoJson data object from the map.
Thanks in Advance !

**Comment by AlexVestin** [comment]
`<FeatureGroup ref={ (fGroup) => { this.fGroup=fGroup; } >`
 and then 

this.fGroup.getChildContext()["layerContainer"].toGeoJSON();

**Comment by vinaykhade** [comment]
Hi @AlexVestin , I tried implementing your solution in my code, it doesn't seem to work. Could please guide me on how to implement it inside this, on how to implement FeatureGroup in React? Thanks in Advance :)

`import React, {Component} from 'react';
import Geosuggest from 'react-geosuggest';
import { Map, Marker, Popup, TileLayer, Circle, FeatureGroup } from 'react-leaflet';
import Slider from 'react-rangeslider';

class App extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      lat: 18.572605,
      lng: 73.878208,
      zoom: 13,
      value: 500
    }
    this.onSuggestSelect = this.onSuggestSelect.bind(this);
  }

  componentDidMount() {
    // let x = this.fGroup.getChildContext()["layerContainer"].toGeoJSON();
    // console.log(x)
  }
  onSuggestSelect(suggest) {
    console.log(suggest)
    this.setState({
      lat: suggest.location.lat,
      lng: suggest.location.lng,
    })
  }

  handleChangeStart = () => {
    console.log('Change event started')
  };

  handleChange = value => {
    this.setState({
      value: value
    })
  };

  handleChangeComplete = () => {
    console.log('Change event completed')
  };

  render() {
    const position = [this.state.lat, this.state.lng];
    const { value } = this.state
    return (
      <div>
          <h1>Hello React :)</h1>
          <Geosuggest
          onSuggestSelect={this.onSuggestSelect}
          />
          <div >
            <Map style={{height: '600px', width: '500px'}} center={position} zoom={this.state.zoom}>
              <TileLayer
                attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
              />
              <Circle center={position} radius={value} color="#FF4E00" />
              <Marker position={position}>
                <Popup>
                  <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
                </Popup>
              </Marker>
            </Map>
          </div>
          <div className='slider'>
            <Slider
              min={0}
              max={1000}
              value={value}
              onChangeStart={this.handleChangeStart}
              onChange={this.handleChange}
              onChangeComplete={this.handleChangeComplete}
            />
            <div className='value'>{value}</div>
          </div>
      </div>

    );
  }
}
export default App;
`

**Comment by vinaykhade** [comment]
Hi @AlexVestin , I tried implementing your solution in my code, it doesn't seem to work. Could please guide me on how to implement it inside this, on how to implement FeatureGroup in React? Thanks in Advance :)

`import React, {Component} from 'react';
import Geosuggest from 'react-geosuggest';
import { Map, Marker, Popup, TileLayer, Circle, FeatureGroup } from 'react-leaflet';
import Slider from 'react-rangeslider';

class App extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      lat: 18.572605,
      lng: 73.878208,
      zoom: 13,
      value: 500
    }
    this.onSuggestSelect = this.onSuggestSelect.bind(this);
  }

  componentDidMount() {
    // let x = this.fGroup.getChildContext()["layerContainer"].toGeoJSON();
    // console.log(x)
  }
  onSuggestSelect(suggest) {
    console.log(suggest)
    this.setState({
      lat: suggest.location.lat,
      lng: suggest.location.lng,
    })
  }

  handleChangeStart = () => {
    console.log('Change event started')
  };

  handleChange = value => {
    this.setState({
      value: value
    })
  };

  handleChangeComplete = () => {
    console.log('Change event completed')
  };

  render() {
    const position = [this.state.lat, this.state.lng];
    const { value } = this.state
    return (
      <div>
          <h1>Hello React :)</h1>
          <Geosuggest
          onSuggestSelect={this.onSuggestSelect}
          />
          <div >
            <Map style={{height: '600px', width: '500px'}} center={position} zoom={this.state.zoom}>
              <TileLayer
                attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
              />
              <Circle center={position} radius={value} color="#FF4E00" />
              <Marker position={position}>
                <Popup>
                  <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
                </Popup>
              </Marker>
            </Map>
          </div>
          <div className='slider'>
            <Slider
              min={0}
              max={1000}
              value={value}
              onChangeStart={this.handleChangeStart}
              onChange={this.handleChange}
              onChangeComplete={this.handleChangeComplete}
            />
            <div className='value'>{value}</div>
          </div>
      </div>

    );
  }
}
export default App;
`

**Comment by AlexVestin** [comment]
Check out this webpackbin:
https://www.webpackbin.com/bins/-KtmfcJ1eZYVr_cJs7MT

**Comment by vinaykhade** [comment]
Hi @AlexVestin , thanks for sharing the webpackbin. 
RIght now, i'm getting the geometry type as point, after adding the <Circle /> inside feature group. 
Is there any way we can get the result where the geometry type is  polygon representing this circle in GeoJSON format. I've been going through the documentation, would getBounds be helpful in this scenario ?

**Comment by AlexVestin** [comment]
I should have read the original question better, sorry.
Yes, you can do a ref on the Circle and then use circle.leafletElement.getBounds() to get its bounds. After that you can check if the other layers are inside the circle by looping through the featuregroup, using bounds.contains(layer._latlng) to check if they're inside.

I would recommend putting the circle outside the feature group so you don't check it against itself.

**Comment by vinaykhade** [comment]
Hey @AlexVestin , thanks for sharing. I'm trying to implement it, seems circle.leafletElements is coming as undefined. Could you please guide me through this using the webpackbin, it's really helpful. Thanks a lot!

**Comment by AlexVestin** [comment]
updated the webbin a bit, it's a bit of a hack but it will probably do. getBounds() on a circle seems to return bounds for a square with the same proportions, so if you want geojson strictly in the circle you might have to write your own contains()

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
