### ISSUE TITLE
Accessing map instance from within leafletElement

### ISSUE THREAD

**Issue by adanielyan** [PaulLeCam/react-leaflet#38]
I need to access ```map``` from within my GeoJson layer. How can I do that?
It is not available through props. Providing ```map={this}``` (see below) doesn't work, because neither GeoJson nor any other component passes ```map``` to the props of created component.
```
<Map
    center={this.props.initialPosition}
    zoom={13}
    id='map'>              
    <GeoJson
        ...
        map={this}
        ...
    />
</Map>
```

Changing the code in GeoJson component from ```const {data, map, ...props} = this.props;``` to ```const {data, ...props} = this.props;``` fixes the issue as the map now is passed to the component and can be accessed through props.

Is there a better way to solve this issue?

**Comment by troutowicz** [comment]
`GeoJson` is a descendant of `MapLayer` which adds the `map` prop to all children [here](https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapLayer.js#L16). This means you have access to `map` via `this.props.map` inside the GeoJson component.

**Comment by adanielyan** [comment]
Ok, I think I wasn't clear enough, or maybe I am missing something.

I want to access the ```map``` from ```onEachFeature()``` function for my GeoJson layer. So I have this code:
```
<Map
    ...
    <GeoJson
        data={geoJSON}
        color='red'
        fillColor='green'
        map={this}
        onEachFeature={onEachFeature} />
</Map>
```
Now in onEachFeature() function I can access color and fillColor through ```this.color``` and ```this.fillColor``` respectively. But ```this.map``` is undefined even if I add it to &lt;GeoJson&gt; as ```map={this}``` along with ```color``` and ```fillColor```. 

What am I doing wrong?

**Comment by PaulLeCam** [comment]
I think in your case the best solution is to implement a custom `GeoJson` component pretty much the same way as it is done in https://github.com/PaulLeCam/react-leaflet/blob/master/src/GeoJson.js
All you need is to add the `onEachFeature` handler to the `props` variable in `componentWillMount`, it would have access to the `map` directly.

**Comment by troutowicz** [comment]
What about using refs?

```js
...

onEachFeature() {
  // let map = this.refs.map.leafletElement
}

render() {
  return (
    <Map
      ref='map'
    >
    ...
    <GeoJson
      data={geoJSON}
      color='red'
      fillColor='green'
      onEachFeature={onEachFeature.bind(this)} />
    </Map>
  )
}
```
Calling `bind` is only necessary with ES6 classes.

**Comment by adanielyan** [comment]
Thanks for responses. Using ```ref``` worked like a charm!

**Comment by troutowicz** [comment]
Great :)
