### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by wojtekmaj** [PaulLeCam/react-leaflet#380]
Hey there,
are you planning to officially support React 16?
I have tested this library with 16.0.0-rc.2 and so far, so good.

I'd appreciate feedback from other users how well react-leaflet behaves on their React 16-based environments.

If the feedback will be positive, updated react-leaflet stating React 16 compatibility would be great.

**Comment by PaulLeCam** [comment]
Yes it will be supported once React v16 is released.
