### ISSUE TITLE
Feature request: Delayed initialisation

### ISSUE THREAD

**Issue by derwaldgeist** [PaulLeCam/react-leaflet#381]
I would like to use Leaflet inside a Bootstrap modal dialog. This does not work, because Leaflet cannot calculate the correct map dimensions during initialisation, as described here: 

https://stackoverflow.com/questions/20400713/leaflet-map-not-showing-properly-in-bootstrap-3-0-modal

I guess this is due to the animation used when the modal is shown.  It works fine, however, if you delay map initialisation until the modal animation has finished. I did this using the whenReady() callback. It would be better if there was an option to delay initialisation by a given time.

**Comment by PaulLeCam** [comment]
Sorry but this is out of the scope of this library, you should implement the solution in your app.

**Comment by derwaldgeist** [comment]
Yep, I did :-)
