### ISSUE TITLE
GeoJson Dynamic Styles

### ISSUE THREAD

**Issue by kevinhughes27** [PaulLeCam/react-leaflet#382]
I'm building a map component that changes the style of some GeoJson components based on the value of a search input. However when I change the search the style of the GeoJson object it is not reflected in the browser. 

Here is how I am using this inside a `<Map>` component:

```javascript
function renderFields(fields, search) {
  return fields.map(field => {
    let style = {};
   
    if (field.name === search) {
      style = { color: 'white' };
    }

    return (
      <GeoJSON key={field.id} data={field.geoJson} style={style} />
    );
  });
}
```

I read the note in the `How it works` about dynamic fields and checked the documentation `style` is not a dynamic property for the GeoJson component. Is this a limitation or does it just need implementation? 

I am happy to help out here but want to make sure I am going in a worth while direction.

**Comment by PaulLeCam** [comment]
Please refer to Leaflet's docs, `style` should be a function, not an object.

**Comment by kevinhughes27** [comment]
That was it! Thanks :smile_cat:
