### ISSUE TITLE
Flow errors

### ISSUE THREAD

**Issue by buggy121** [PaulLeCam/react-leaflet#383]
flow outputs mass of errors from react-leaflet. 
File `node_modules/react-leaflet/lib/types.js` is almost clear, it has only 1 line:
`'use strict'`

### Expected behavior
no output of `npm run flow`

### Actual behavior

`Error: node_modules/react-leaflet/lib/MapComponent.js.flow:17
 17: > extends Component<Props> {
               ^^^^^^^^^ type application of identifier `Component`. Too few type arguments. Expected at least 3
 22: declare class React$Component<DefaultProps, Props, State> {
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ See type parameters of definition here. See lib: C:\Users\kulpa\AppData\Local\Temp\flow\flowlib_cca443b\react.js:22

Error: node_modules/react-leaflet/lib/MapControl.js.flow:10
 10: export default class MapControl<
                          ^^^^^^^^^^ undefined. Did you forget to declare some incompatible instantiation of `Props`?. This type is incompatible with
 10: export default class MapControl<
                          ^^^^^^^^^^ some incompatible instantiation of `Props`

... 86 more errors (only 50 out of 136 errors displayed)
`

and much more.

**Comment by PaulLeCam** [comment]
You're likely using a version of Flow older than the one supported (0.54).

**Comment by uwap** [comment]
@PaulLeCam Had the same problem. Updated flow to 0.54. Now it works, but I still get Redundant argument errors.

```
Error: node_modules/react-leaflet/es/Pane.js.flow:2
  2: // flowlint sketchy-null-string:off
                 ^^^^^^^^^^^^^^^^^^^^^^^ Redundant argument. This argument doesn't change any lint settings.
```

**Comment by PaulLeCam** [comment]
See https://github.com/PaulLeCam/react-leaflet/issues/364
