### ISSUE TITLE
Inconsistent behavior of the Map `bounds` option

### ISSUE THREAD

**Issue by bkon** [PaulLeCam/react-leaflet#387]
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

```
const boundsOptions: FitBoundsOptions = { padding: [50, 50] };

const TripOverviewContent: React.StatelessComponent<IProps> = props => (
  <Map
    center={initialPosition}
    zoom={13}
    style={{ height: "400px" }}
    bounds={bounds(props.route.waypoints)}
    boundsOptions={boundsOptions}
  >
  { ... some content ... }
  </Map>
)
```

and 

```
const TripOverviewContent: React.StatelessComponent<IProps> = props => (
  <Map
    center={initialPosition}
    zoom={13}
    style={{ height: "400px" }}
    bounds={bounds(props.route.waypoints)}
    boundsOptions={{ padding: [50, 50] }}
  >
  { ... some content ... }
  </Map>
)
```

should behave exactly the same

### Actual behavior

Second  code snippet forces user to the given bounds on every render; first code snippet keeps user position.

Note: renders are triggered by updates to the marker (children elements). 

### Reason

Note that https://github.com/PaulLeCam/react-leaflet/blob/f803889e05c28d48aedd20c2707fd4dec552b190/src/Map.js#L216 uses `===` to check that boundOptions hadn't changed. This does not work as expected if options are provided as a literal hash in JSX, as object identity changes on each render.

**Comment by PaulLeCam** [comment]
The expected behavior you describe is not the expected behavior for this library, you should provide the same object if you don't want to trigger a re-render.

**Comment by bkon** [comment]
@PaulLeCam I think I hadn't explained my point well enough; I'm sorry for being vague.

Re-render is perfectly fine and expected; in fact, we're explicitly triggering re-render as we need to animate the marker on the map. The problem I'm talking about is `flyTo` or `setView` triggered on that re-render even through the values of both bounds and boundsOptions are the same. 

Now, the above is still fine, but `flyTo` is triggered only by `boundsOptions` and it's inconsistent with the behavior of the `bounds` prop, which checks for equality by value instead of by reference (here: https://github.com/PaulLeCam/react-leaflet/blob/f803889e05c28d48aedd20c2707fd4dec552b190/src/Map.js#L287). This subtle difference is undocumented and confusing and the only way to triage this issue is to go through the library source.

Real-life cenario: we were using `bounds` for a while (passing a literal to the map) without any issues, and then we added `boundsOptions` with some padding, which resulted in map being re-centered on the initial position every time marker was animated.

It's up to you to decide on the solution; as a library consumer I'd suggest either:
- documenting the specifics of this behavior in the Map API section;
- making `bounds` use the same by-reference equality check as `boundsOptions`;
- making `boundsOptions` use the same by-value equality check as `bounds`.

**Comment by PaulLeCam** [comment]
Thanks for the detailed explanation, I agree I think it makes sense to be more explicit about how the props changes are compared, I updated the docs in the latest commit.
