### ISSUE TITLE
State changes cause LayersControl.Overlay to add additional Layer control checkbox

### ISSUE THREAD

**Issue by vietnugent** [PaulLeCam/react-leaflet#389]
Please make sure to check the following boxes before submitting an issue.  
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

Versions
- "react": "^15.6.2"
- "react-leaflet": "^1.7.0"

### Actual behavior
I'm seeing similar behavior as described in issue #175 
Additional Layer control check box appears when child component tree of `LayersControl.Overlay` changes 
 
In the snippet below `OSMClimbingDataLayer` component is initially a no-op.  When responding to a user request it renders addition geojson features on the map.

### Steps to reproduce
```
                  
                    <LayersControl.Overlay checked name='OSM data'>
                        <OSMClimbingDataLayer/>
                    </LayersControl.Overlay>
       
```

Before
![layercontrol_before](https://user-images.githubusercontent.com/19377299/31003788-584f0f74-a4a6-11e7-899a-8ba602695a5a.png)
------
After
![layercontrol_after](https://user-images.githubusercontent.com/19377299/31003787-5848a472-a4a6-11e7-813d-e963174a13e5.png)

**Comment by PaulLeCam** [comment]
Please provide a WebpackBin or similar example.

**Comment by vietnugent** [comment]
To reproduce click the first button -> second -> first.  Then check layer control.
https://www.webpackbin.com/bins/-KvBfuAhP4myQjGEpKs7

**Comment by PaulLeCam** [comment]
I think the issue in your example is your `MyLayer` component `render` method returning `null`. This is not supported, all layer controls must contain a layer to render.

**Comment by brianpchsu** [comment]
I have a similar question regarding the duplicate list. I need to iterate an array and push marker to it. Something similar to my code is:
https://www.webpackbin.com/bins/-Kvmu5PPSjeS4lY-qe_E

As you can see, there are duplicate `test` in the list which should be just one. Is there a different way I should call LayersControl.Overlay? Thanks. 

![screen shot 2017-10-06 at 1 20 27 pm](https://user-images.githubusercontent.com/8574617/31297108-a208e3d0-aa99-11e7-8a87-6e1e9cb3ce8d.png)

**Comment by brianpchsu** [comment]
Never mind. I figured it out. I should have wrap my marker in <LayerGroup>.

**Comment by antontranelis** [comment]
> Never mind. I figured it out. I should have wrapped my markers in .
> 
> ![screen shot 2017-10-06 at 2 31 36 pm](https://user-images.githubusercontent.com/8574617/31299410-1be79120-aaa3-11e7-9a6c-549ae6511bb1.png)

I dont't get it. How did you wrap your markers?
