### ISSUE TITLE
GeoJson Component not update data

### ISSUE THREAD

**Issue by jeans11** [PaulLeCam/react-leaflet#39]
Hey gays !

For my project, I use geojson layer. My project use Flux (with Fluxible). The problem is that the data transmited to GeoJson component are not update (when the store indicates that view must be updated). I don't understand why data doesn't update. If you have an idea...

**Comment by PaulLeCam** [comment]
It's not supported by the library, you can simply force the component recycling by changing is `key` property, but you should implement your own solution to efficiently diff the GeoJSON data.

**Comment by jeans11** [comment]
Hep, I found this solution:

```javascript
import React from "react";
import Leaflet from "leaflet";
import {GeoJson}  from "react-leaflet";

export default class MyGeojson extends GeoJson {

        componentWillReceiveProps(prevProps) {
                if (prevProps.data !== this.props.data) {
                        this.leafletElement.clearLayers();      
                }       
        }

        componentDidUpdate(prevProps) {
                if (prevProps.data !== this.props.data) {
                        this.leafletElement.addData(this.props.data);
                }
        }
}

MyGeojson.propTypes = {
  data: React.PropTypes.object.isRequired
};
```
