### ISSUE TITLE
Add map bounds to viewport

### ISSUE THREAD

**Issue by igorcalabria** [PaulLeCam/react-leaflet#391]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

Hi, I've noticed that viewport change events only include center and zoom. It may make sense to also include the map bounds from [getBounds](http://leafletjs.com/reference-1.2.0.html#map-getbounds). This is especially useful for applications that needs to fetch only visible data from some backend. 

To workaround this issue, I've created a component that gets the leaflet instance from the context and handles the `moveend` event on its own.  If you're interest I can provide a PR.

**Comment by PaulLeCam** [comment]
Hi,
I thought about that but the problem is that getting the bounds involves computations from Leaflet, so I don't think it's a good idea to do it when triggering this event.
Calling `getBounds()` on the map instance only when your app needs it is likely the best option.

**Comment by vcarl** [comment]
@igorcalabria I just published a component that makes bounds available as a render prop, if you're still hitting this problem. https://www.npmjs.com/package/react-leaflet-bounds

**Comment by austere-rm** [comment]
@vcarl any plans to publish a component to make the map centre available as a render prop (wishful thinking!)? I'm having a hard time implementing leaflet getCentre() into my react-leaflet map
