### ISSUE TITLE
All tiles are mis-positioned

### ISSUE THREAD

**Issue by codTango** [PaulLeCam/react-leaflet#392]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Render a nice map within my container

### Actual behavior

All tiles are mispositioned

### Steps to reproduce

https://jsfiddle.net/ctps4/bzbdtpuv/

The jsfiddle is a little messy, it's the structure of my map widget, and it looks like this now
![screen shot 2017-10-03 at 5 40 55 pm](https://user-images.githubusercontent.com/5359697/31151741-e2a21d60-a866-11e7-9e2a-94980a559d89.png)
I'm wondering if I miss anything or if any of my container's CSS would mess it up.... In general, it's in a react-grid-layout panel and it has a header and widget area; the upper containers are using column flex and has an auto overflow.

**Comment by Asher978** [comment]
I am encountering the same behavior. All depend are installed. I have even tried setting the height of the map container. Any ideas?

**Comment by PaulLeCam** [comment]
Use the code from https://www.webpackbin.com/bins/-Kl_ZeUx4I05ETYoT26O
Whatever issue you're having comes from your config, not this lib.

**Comment by Asher978** [comment]
Thanks for your help. All worked out!

**Comment by danielrasmuson** [comment]
I hit this problem. I was able to resolve it by adding the stylesheet to index.html

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css" />
```

**Comment by vire** [comment]
Had the same issue, it was because the import of `leaflet.css` has changed due to webpack setup changes... 

This is so hard to debug, you still see tiles but has no idea why it's distorted...

Maybe if `leaflet` would have some `cssStylePresence` check in development mode or, it would help...
