### ISSUE TITLE
The default tooltip/popup pane isn't used when adding an element to a custom pane.

### ISSUE THREAD

**Issue by RichardWithnell** [PaulLeCam/react-leaflet#393]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

When adding an element to a custom pane, any associated popup/tooltip should still be added to the default pane for that element, unless it is explicitly overwritten using the pane prop. 

This appears to be the default behaviour in Leaflet.

### Actual behavior

The popup is added to the same custom pane as the leaflet element. The popup won't display correctly, appearing behind the elements already in the pane. 

### Steps to reproduce

Clicking the yellow rectangle in the top map of the following bin:

https://www.webpackbin.com/bins/-Kw1QYT2vnFMlRLt8xGe

The bottom map recreates the same example with pure Leaflet, demonstrating the popup being added to the default instead of the custom panel.

**Comment by PaulLeCam** [comment]
Should be fixed in v1.7.1 thanks to your PR, please try it out.
