### ISSUE TITLE
HTMLVideoElement Mocha react-leaflet error

### ISSUE THREAD

**Issue by westandy** [PaulLeCam/react-leaflet#395]
My tests are unable to run in Mocha because Mocha does not know what an HTMLVideoElement is:  ReferenceError: HTMLVideoElement is not defined

The error is coming from Mocha not being able to understand the VideoOverlay.propTypes:

```
VideoOverlay.propTypes =  #{
  attribution: __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.string,
  bounds: __WEBPACK_IMPORTED_MODULE_3__propTypes_bounds__["a" /* default */].isRequired,
  opacity: __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.number,
  play: __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.bool,
  url: __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.oneOfType([__WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.string, __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.arrayOf(__WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.string), __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.instanceOf(HTMLVideoElement)]).isRequired,
  zIndex: __WEBPACK_IMPORTED_MODULE_1_prop_types___default.a.number
};
```

I am running with the following versions:
node 8.2.1
npm 5.5.1
mocha: 3.4.2
leaflet: 1.2.0
react-leaflet: 1.7.1
react-dom: 15.6.2
react: 15.6.2
webpack: 3.5.6

Let me know what further information you would need.  Thank you!

**Comment by PaulLeCam** [comment]
Only browsers are supported, if the DOM is not fully implemented by the environment you want you should open an issue in the relevant project.
