### ISSUE TITLE
map does not load tile layer and freezes when maxZoom > maxNativeZoom and zoom > (maxNativeZoom + 1)

### ISSUE THREAD

**Issue by barbalex** [PaulLeCam/react-leaflet#396]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

- When zooming past maxNativeZoom (hence with a maxZoom higher than maxNativeZoom), the map of version maxNativeZoom should be zoomed further in, without loading new tiles...
- ...and the map should stay responsive.

### Actual behavior

- When zooming past maxNativeZoom no map is shown.
- When zooming past maxNativeZoom + 1 the map freezes. In my actual app the entire browser tab freezes and I need to kill chrome

### Steps to reproduce

1. version using leaflet@1.2.0 not using react-leaflet, works as expected: https://plnkr.co/edit/3CszXfN7E1ZuSoJSdJog?p=preview
2. exact same version using react-leaflet, showing actual behaviour: https://www.webpackbin.com/bins/-Kw9UJYAi4QSSpXbqnFf
3. same version as 2. but using leaflet@1.0.3. This works as expected: https://www.webpackbin.com/bins/-Kw9blYnMqwuCVbhnx-7

To test:

1. The map opens at zoom 19 (= maxNativeZoom)
2. Zoom to 20. Check if map is still visible
3. Zoom to 21. Check if map can be zoomed in or out after this

### Possible cause

Leaflet moved min/maxNativeZoom from TileLayer into GridLayer for leaflet@1.1.0. See: https://github.com/Leaflet/Leaflet/issues/5833#issuecomment-335643581

**Comment by PaulLeCam** [comment]
Your example provides these values as strings where they should be numbers.

**Comment by barbalex** [comment]
facepalm

o.k., I guess I'd better rehearse the basics of react :-(

for any one who happens to make the same mistake: here is the working example: https://www.webpackbin.com/bins/-KwBpKAnTzjnCFepnsut

The difference is: (correct)

        <TileLayer
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
          maxNativeZoom={19}
          minZoom={0}
          maxZoom={22}
        />

versus: (me dreaming)

        <TileLayer
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
          maxNativeZoom="19"
          minZoom="0"
          maxZoom="22"
        />

**Comment by barrycarter** [comment]
https://github.com/Leaflet/Leaflet/issues/5895#issuecomment-486815449 may or may not be helpful re this closed issue.
