### ISSUE TITLE
Set viewport by props / state will cause in movement on map (2 up to 3 movements - but should be only 1)

### ISSUE THREAD

**Issue by TimoRuetten** [PaulLeCam/react-leaflet#398]
We have a redux store where we store our current Map View state. its very simple structered:

```
// initial store
lat: 52.516952093701605,
lng: 13.319377899169924,
zoom: 12,
```

We use this store to hold it as a current store which always shows the view in the map. Important here: Its only interesting for us how the map view is after a movement - so the `onViewportChanged` event.

This is how our component looks like.
```
<Map
  style={{
    height: '100%',
    width: '100%',
  }}
  onViewportChanged={(viewport) => {
    console.log('View port changed:', viewport.center);
   dispatch(setMapViewport(viewport));
  }}
  viewport={{
    center: [
      map.get('lat'),
      map.get('lng'),
    ],
    zoom: map.get('zoom'),
  }}
>
  // ...
</Map>
```

When I now scroll in the map (doesnt matter if its a drag&drop or a swipe or what ever) this is a console log example (we just changed the position once):

```
View port changed: (2) [52.516743172151706, 13.726558685302734]
Dispatch Map [52.516743172151706, 13.726558685302734]
View port changed: (2) [52.516952093701605, 13.726558685302734]
Dispatch Map [52.516952093701605, 13.726558685302734]
```

So you can see that after the view port changed we send the lat/lng to our store. In the log you can see that the data is the same. After this we send the data from the store to the `viewport` property of <Map />. So it should be absolutely the same like before. But it is not. After we set the "new" viewport the <Map /> fires again the onViewportChanged event with another viewport. This viewport will be dispatched - again - in our store and send back - again - as a viewport property of <Map />. And thats it. 

In this example it just run 2 times - but sometimes its running like 3 or maybe up to 4 times.

When we remove the `dispatch(setMapViewport(viewport));` its working fine. After moving once in the map this is our log:

```
View port changed: (2) [52.516743172151706, 13.726558685302734]
```

And thats it.

What do we expect ?

Of course - when moving the map once we only what to dispatch once to our store. Because the viewport we dispatch we are getting from <Map /> it should itself hold the same viewport but as far as we can see this is not.

What we would expect in reference to the example above it should be like this:

```
View port changed: (2) [52.516743172151706, 13.726558685302734]
Dispatch Map [52.516743172151706, 13.726558685302734]
```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by TimoRuetten** [comment]
Hm ? As far as I can see this is a bug. The bug seems to be that when I set 

[52.516743172151706, 13.726558685302734]

as center in your component the onViewportChanged get triggered and returns this as center: 

[52.516952093701605, 13.726558685302734]

This seems to be a bug for me.

**Comment by PaulLeCam** [comment]
Then please fill the issue template with a WebpackBin or similar showing the problem.

**Comment by torgeir** [comment]
I believe I fixed a similar issue by passing the reference to the same viewport object that got emitted in onViewportChanged, and not creating a new viewport object on each render. Might be worth a shot..
