### ISSUE TITLE
<ImageOverlay> className attribute does not insert space after leaflet-generated classes

### ISSUE THREAD

**Issue by sairus2k** [PaulLeCam/react-leaflet#399]
**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.  
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [*] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [*] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [*] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [*] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [*] The issue has not already been reported.
- [*] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [*] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

`<img class="leaflet-image-layer leaflet-zoom-animated custom-class">`

### Actual behavior

`<img class="leaflet-image-layer leaflet-zoom-animatedcustom-class">`

### Steps to reproduce
Insert ImageOverlay with className attribute.
`<ImageOverlay className="custom-class" />`

[https://jsfiddle.net/z2Lutn6y/](https://jsfiddle.net/z2Lutn6y/)

**Comment by PaulLeCam** [comment]
Please check the behavior using Leaflet directly to make sure it's an issue caused by this lib and not upstream.
