### ISSUE TITLE
<Popup /> does not proxy inherited events

### ISSUE THREAD

**Issue by qrohlf** [PaulLeCam/react-leaflet#401]
The `<Popup />` [component](https://github.com/PaulLeCam/react-leaflet/blob/a958e3a18caee783d893f3f308ae2d6ef1f5cd44/src/Popup.js) does not provide props for any events except `onOpen` and `onClose`. I need access to `onAdd/onRemove/onTooltipopen/onTooltipclose` for my usage scenario.

While I can get at these events using refs and `node.leafletElement.on({...}`, it seems like they would be worth building in as props.

![screen shot 2017-10-19 at 2 35 07 pm](https://user-images.githubusercontent.com/347189/31795461-b9d08f90-b4da-11e7-94fb-d66a9a2298ba.png)

**Comment by PaulLeCam** [comment]
Leaflet's docs are misleading, these events listeners shouldn't be attached to the Popup layer itself, you can check Leaflet's code for the actual implementation.
