### ISSUE TITLE
Use minified Leaflet version

### ISSUE THREAD

**Issue by schneck** [PaulLeCam/react-leaflet#402]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Should import minimized leaflet version.

### Actual behavior

Imports non-minimized leaflet version.

### Steps to reproduce

When inspecting my bundle size, I stumbled upon the leaflet-src.js file, which is not imported by my application. After digging through your codebase I found that you're importing directly from leaflet.
According to this comment, this could be the reason for a too large codebase: https://github.com/Leaflet/Leaflet/issues/5288#issuecomment-279397985

**Comment by PaulLeCam** [comment]
This is up to Leaflet defaults and your webpack config, not this lib.
