### ISSUE TITLE
Implementing a dynamic JSX element within a marker, using react-leaflet

### ISSUE THREAD

**Issue by nik-john** [PaulLeCam/react-leaflet#407]
_**Disclaimer:** This might be more related to the react-leaflet-markercluster plugin more than it is to the parent library, I am putting it out here to see if anyone here can provide any tips._

I have a React app in which I am using [Leaflet](http://leafletjs.com/) through [react-leaflet](https://github.com/PaulLeCam/react-leaflet), both super useful libraries.

In this app, I have a group of coordinates that need to be rendered as follows:

1. When zoomed out, cluster the coordinates into Marker Clusters like so
[![enter image description here][1]][1]

2. When zoomed in, each Marker needs to have 
  1. A dynamic countdown timer under it
  2. A dynamic SVG countdown clock around it like so
[![enter image description here][2]][2]

For the clustering, I am using the [react-leaflet-markercluster](https://www.npmjs.com/package/react-leaflet-markercluster) plugin, which works great for showing static content. 

But when I need to show any dynamic content within each marker, I have no option of sending in `JSX`, there's only provision for static HTML as can been seen from the example available [here](https://yuzhva.github.io/react-leaflet-markercluster/#marker-popup).

    // Template for getting popup html MarkerClusterGroup
    // IMPORTANT: that function returns string, not JSX
    function getStringPopup(name) {
      return (`
        <div>
          <b>Hello world!</b>
          <p>I am a ${name} popup.</p>
        </div>
      `);
    }
    
    // that function returns Leaflet.Popup
    function getLeafletPopup(name) {
      return L.popup({ minWidth: 200, closeButton: false })
        .setContent(`
          <div>
            <b>Hello world!</b>
            <p>I am a ${name} popup.</p>
          </div>
        `);
    }

Is there a way to handle this situation? How can I make a JSX marker instead of a static HTML marker?

TIA!!

### Expected behavior

JSX components aren't accepted as Markers

### Actual behavior

JSX components should be accepted as Markers

  [1]: https://i.stack.imgur.com/fY9he.png
  [2]: https://i.stack.imgur.com/m32Z2.png

### Steps to reproduce

Reproduction the issue,  [WebpackBin](https://www.webpackbin.com/bins/-KxhoIKcuQaFNyL7zivs).

**Comment by PaulLeCam** [comment]
Sorry but this has nothing to do with this library, a JSX tree is no a string, you need to convert it anyways.
