### ISSUE TITLE
Tooltip not unbound after "removing" it

### ISSUE THREAD

**Issue by errnesto** [PaulLeCam/react-leaflet#408]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

In the following example:
```
<Marker>
  { showTooltip &&
    <Tooltip>Hello</Tooltip>
  }
</Marker>
```

After `showTooltip`changes from `true` to `false` the Tooltip should be removed.

### Actual behavior

Only the content of the Tooltip is removed

### Steps to reproduce
https://www.webpackbin.com/bins/-Ky-GdJ8J0awEnIZ51ME

- See Tooltip on hover
- click button "remove tooltip"
-  See empty tooltip on hover

I solved this in my app with the following code (where `this.markers` are refs):
```
componentDidUpdate () {
    if (this.props.showTooltip) return
    this.markers.filter(m => m !== null).forEach(marker => {
      marker.leafletElement.unbindTooltip()
    })
  }
```

**Comment by PaulLeCam** [comment]
Thanks for reporting this, it should be fixed in v1.7.3.
