### ISSUE TITLE
<ImageOverlay bounds={is required?}/>

### ISSUE THREAD

**Issue by joefraley** [PaulLeCam/react-leaflet#409]
**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.  
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x ] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [ x ] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [ x ] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ x ] The issue has not already been reported.
- [ x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x ] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

[The `react-leaflet` documentation for the `<ImageOverlay/>` component says this](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#imageoverlay):
> ImageOverlay
> Leaflet reference
> Dynamic properties
> ...
> bounds: bounds (optional) <--------
> ...

### Actual behavior

[The `<ImageOverlay/>` prop-types say this](https://github.com/PaulLeCam/react-leaflet/blame/master/src/ImageOverlay.js#L24):
```js
export default class ImageOverlay extends MapLayer<LeafletElement, Props> {
  static propTypes = {
    ...
    bounds: bounds.isRequired, <------
    ...
  }
```
### Steps to reproduce

Which is it?
Please provide the simplest example possible to reproduce the issue, based on [this WebpackBin](https://www.webpackbin.com/bins/-Kl_ZeUx4I05ETYoT26O).

**Comment by joefraley** [comment]
Also the contributing guide link in the issue template is broken

**Comment by PaulLeCam** [comment]
Thanks, should be fixed in latest commit.
