### ISSUE TITLE
SmoothMarkerBouncing

### ISSUE THREAD

**Issue by FlorianBouron** [PaulLeCam/react-leaflet#411]
Hello,
Would it be possible to add the plugin Leaflet.SmoothMarkerBouncing to the library please?
https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing/blob/master/leaflet.smoothmarkerbouncing.js
Thank you in advance,
Florian.

**Comment by PaulLeCam** [comment]
Support for plugins is out of the scope of this library but you can refer to the documentation on implementing custom components.
