### ISSUE TITLE
Esri-leaflet?

### ISSUE THREAD

**Issue by maka-io** [PaulLeCam/react-leaflet#413]
Not an issue, more of a question.  Have you tried to add the esri-leaflet package? If not, do you have any advice as to the best approach? I'd like to simply point where ever you have "L." to "L.esri."

Thanks!

**Comment by maka-io** [comment]
Figured it out, so simple! Just... import the library.

**Comment by terranjp** [comment]
@maka-io Can you provide more details on how you made this work? I imported the library but I cant' load ESRI maps.  I am probably missing something simple...
