### ISSUE TITLE
Tooltip warnings on open / on close

### ISSUE THREAD

**Issue by FeNoMeNa** [PaulLeCam/react-leaflet#416]
**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.  
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

The leaflet tooltip should not display warnings when opening / closing.

### Actual behavior

If 'tooltipopen' event is fired I'm receiving this warning

```
Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.
```

If 'tooltipclose' event is fired I'm receiving this warning

```
Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.
```

### Steps to reproduce

https://www.webpackbin.com/bins/-KzThz6wE7J1dGGqVc6h - unfortunately webpackbin does not show the warnings

Environment:
- linux / osx
- react 16
- leaflet - 1.2.0
- react-leaflet 1.7.4

**Comment by PaulLeCam** [comment]
You'll probably need to make some changes to your `MarkerCluster` component to handle this logic there.
I don't know how `leaflet.markercluster` handles it but as it's a plugin and only displaying a warning, I'm not going to dig into this, sorry.
Please feel free to open a PR if you find a solution that can be implemented without hacks or side-effects.
