### ISSUE TITLE
Multiple Classes on Map Error

### ISSUE THREAD

**Issue by skipjack** [PaulLeCam/react-leaflet#417]
### Expected behavior

The `<Map>` component should be able to handle multiple classes the same way normal react components do. 

### Actual behavior

Multiple classes, e.g. passing `className="blah blah--something"`, work fine initially but as soon as you go to change the class an error is thrown:

> Uncaught InvalidCharacterError: Failed to execute 'remove' on 'DOMTokenList': The token
> provided ('blah blah--something') contains HTML space characters, which are not valid in 
> tokens.

### Steps to reproduce

Change the class name when multiple classes are applied. See the following contrived example:

https://www.webpackbin.com/bins/-KzUZppArtdgQoKcAlBG

I dug into this a bit and realized the issue is that [these lines](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L178-L185) and Leaflet's [`removeClass`](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomUtil.js#L128-L136) method simply don't handle multiple classes.

It seems that the `fromProps.className` and `className` strings would have to be split on one or more spaces, and then the resulting arrays should be iterated through to add and remove classes (assuming `addClass` doesn't handle multiple either).

> P.S. This library has been fantastic, thanks for all the hard work on it! I'm not sure if I'll have time to submit a PR, if we agree on the issue/resolution, but if that's desired I might be able to set aside some time to fix this.

**Comment by PaulLeCam** [comment]
Thanks for reporting this, as you suggested I made the change to split the `className` and call `addClass`/`removeClass` on each class.
It's pushed in v1.7.6, please try it out!

Thanks for the P.S., great to know this library is useful!

**Comment by skipjack** [comment]
> Thanks for the P.S., great to know this library is useful!

No problem, and fwiw I've dug into the code a bit and really like how things are laid out. Hoping I can find some time to contribute, whether it's via a plugin or to the main repo, at some point!

> It's pushed in v1.7.6, please try it out!

Tested it out and the core error is resolved but now I'm getting a different one:

> DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.

When you do the `.split(' ')`, I think multiple spaces and leading/trailing spaces need to be taken into account. This error is thrown when `className` is changed to something like `blah  blah--something` which can happen if you use template strings to apply classes, e.g. 

``` js
className={ `base-class ${modifier} ${className}` }
```

And only one of `modifier` or `className` exists. Originally I was thinking splitting on a regex would address this but maybe a simple `.filter` would be better, e.g.

``` js
fromProps.className.split(' ').filter(cls => !!cls)
```

What do you think?

**Comment by skipjack** [comment]
I tested the `.filter` and it does work. I'd be happy to submit a PR if you're ok with that approach.

**Comment by PaulLeCam** [comment]
I updated it in v1.7.7, it should be more permissive for this kind of case now.

**Comment by skipjack** [comment]
Great, thanks for your help on this!

**Comment by PaulLeCam** [comment]
You're welcome!
