### ISSUE TITLE
Leaflet.markercluster support

### ISSUE THREAD

**Issue by treydavis** [PaulLeCam/react-leaflet#42]
I'm interested in using https://github.com/Leaflet/Leaflet.markercluster with react-leaflet. What's the best way to go about this?

**Comment by troutowicz** [comment]
You can take a look at the version I created for my geoshare project [here](https://github.com/troutowicz/geoshare/blob/master/app/components/MarkerCluster.jsx).

**Comment by PaulLeCam** [comment]
@troutowicz's example is a good one, you can also have a look at this discussion: https://github.com/PaulLeCam/react-leaflet/issues/37 for more information

**Comment by YUzhva** [comment]
[react-leaflet-markercluster](https://www.npmjs.com/package/react-leaflet-markercluster) looks nice...

All you need to do, it's grab all react-leaflet Markers inside that plugin:
```javascript
<MarkerClusterGroup wrapperOptions={{enableDefaultStyle: true}}>
    <Marker position={[49.8397, 24.0297]} />
    <Marker position={[52.2297, 21.0122]} />
    <Marker position={[51.5074, -0.0901]} />
  </MarkerClusterGroup>
```

**Comment by isthakker** [comment]
@treydavis MarkerClusterGroup does have markers.refreshCluster() is the same functionality available for react?
