### ISSUE TITLE
Feature request: auto-open popup on marker

### ISSUE THREAD

**Issue by derwaldgeist** [PaulLeCam/react-leaflet#420]
I would like to place a marker on a map, alongside with a Popup containing info about the place that is being marked, just like it is shown on the Leaflet homepage: http://leafletjs.com/

I know that I can place a `<Popup>` inside a `<Marker>`. But this has popup will only show up if the user clicks on it. It would be great if the popup could be configured in a way that it shows up immediately.

I found this StackOverflow answer explaining how this can be achieved with a derived Marker class:
https://stackoverflow.com/questions/38730152/popup-always-open-in-the-marker

Yet I think this is such a common use case it would be great if the Marker element would support this directly, by providing a boolean property like `showPopup`. Or, alternatively, by adding a `show` property to the Popup element itself.

**Comment by PaulLeCam** [comment]
You can extend the `Popup` component to implement this behavior, but it won't be provided by this library itself.
