### ISSUE TITLE
Marker with custom icon dragging not working when using onDrag Event

### ISSUE THREAD

**Issue by ricxsar** [PaulLeCam/react-leaflet#429]
**Before** opening an issue, make sure to read the
[contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md)
and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good
reason not to follow this template.**

* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS
      file is loaded.
* [x] Using the
      [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [x] The issue has not already been reported.
* [x] Make sure you have followed the
      [quick start guide](http://leafletjs.com/examples/quick-start.html) for
      Leaflet.
* [x] Make sure you have fully read the
      [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md)
      and that you understand the
      [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Marker with custom icon should be following mouse cursor when dragging.

### Actual behavior

Marker dragging is not working. The dragging state somewhat halted.

### Steps to reproduce
See link below.
The blue marker is the default marker with default icon. 
The red marker is the marker with custom icon. 
Both markers have tooltip to show it's realtime coordinates.
Try to drag both markers to see the difference.
They have the same code except the red one has a custom icon.

[WebpackBin](https://www.webpackbin.com/bins/-L1gzCtLTvFl68qmuRPx)

**Comment by PaulLeCam** [comment]
It's likely caused by the fact you recreate the `customIcon` all the time in `render()`, so the icon effectively changes and likely the event handlers on the marker get replaced.

**Comment by ricxsar** [comment]
I see. Thank you for the response. I will now close the issue.
