### ISSUE TITLE
How to use "unproject"?

### ISSUE THREAD

**Issue by acpower7** [PaulLeCam/react-leaflet#431]
It's completely missing from the docs.

thanks!

**Comment by PaulLeCam** [comment]
It's unrelated to this library, as stated in the docs it uses Leaflet, it's not a replacement for it.

**Comment by acpower7** [comment]
Can you instruct how to use it with your library?
thx

**Comment by PaulLeCam** [comment]
Please refer to the documentation, anything I would explain here is already documented.

**Comment by acpower7** [comment]
you are the most useless project maintainer i've seen on github. i have read many of your comments on opened issues, every single one of them has a net value below zero. kill yourself.
