### ISSUE TITLE
Update to Leaflet 1.3.0

### ISSUE THREAD

**Issue by michael-p** [PaulLeCam/react-leaflet#432]
Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good
reason not to follow this template.**

* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x ] Using the supported version of Leaflet (v1.2.x) and its corresponding CSS
      file is loaded.
* [x] Using the
      [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [x] The issue has not already been reported.
* [x] Make sure you have followed the
      [quick start guide](http://leafletjs.com/examples/quick-start.html) for
      Leaflet.
* [x] Make sure you have fully read the
      [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md)
      and that you understand the
      [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

It would be nice if the library officially supported the most recent version of Leaflet, 1.3.0 (which was just released today, so sorry for the hurry :)

### Actual behavior

react-leaflet has Leaflet 1.2 as peer dependency but seems to work with 1.3 as well. Changelog of Leaflet is here: [Leaflet Changelog](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md)

### Steps to reproduce

Nothing

**Comment by PaulLeCam** [comment]
I just pushed v1.8.0 that changes the peer dependency. Apart from the added support for an image element in `ImageOverlay` I haven't spotted any required change in this library so hopefully everything should work as expected, but please open specific issues you may find.

**Comment by michael-p** [comment]
Thanks for the super-fast release! :)
One small thing might be the addition of `closeOnEscapeKey` for `Popup` - see #436.
