### ISSUE TITLE
closeOnEscapeKey prop for Popup does not work

### ISSUE THREAD

**Issue by michael-p** [PaulLeCam/react-leaflet#436]
Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good
reason not to follow this template.**

* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS
      file is loaded.
* [x] Using the
      [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [x] The issue has not already been reported.
* [x] Make sure you have followed the
      [quick start guide](http://leafletjs.com/examples/quick-start.html) for
      Leaflet.
* [x] Make sure you have fully read the
      [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md)
      and that you understand the
      [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior

Leaflet 1.3 supports a `closeOnEscapeKey` property for `Popup`. However, a quick test with react-leaflet seems to not work, i.e. the popup doesn't get closed on escape. I havent't yet tested this with Leaflet alone, so this could also be a Leaflet bug.

```
<Popup
  onOpen={onPopupOpen}
  onClose={onPopupClose}
  closeOnEscapeKey={true}
  maxWidth={400}>
  {popup}
</Popup>
```

### Actual behavior

Escape closes popup if `closeOnEscapeKey` is `true`.

**Comment by PaulLeCam** [comment]
I can't reproduce the issue, the value is `true` by default anyways, so there is likely something else happening in your code, please provide a running example.
