### ISSUE TITLE
"leaflet": "^1.3.0" + "react-leaflet": "^1.8.0" no Retina support

### ISSUE THREAD

**Issue by paulincai** [PaulLeCam/react-leaflet#437]
Hi @PaulLeCam,

I updated my project to the above versions from leaflet": "^1.2.0" + "react-leaflet": "^1.7.7" and I lost retina support. I downgrade back and everything is back to normal.

When on a retina device, I get invalid tiles with 404 error in browser console (as attached)
![screen shot 2018-01-18 at 00 51 46](https://user-images.githubusercontent.com/26188915/35076474-0c5a2bda-fc12-11e7-90d4-94d695b4e6bb.png)

Easiest way to test is indeed with the Chrome device simulator. The only device that looks truly bad is the Ipad Pro at the 3X density :).

Paul

**Comment by PaulLeCam** [comment]
Please follow the issue template.

**Comment by paulincai** [comment]
Confirmed by Leaflet: https://github.com/Leaflet/Leaflet/issues/6007
