### ISSUE TITLE
Issues building locally

### ISSUE THREAD

**Issue by jmfurlott** [PaulLeCam/react-leaflet#44]
Trying to help work on the project by adding layers control toggling.  There seems to be several problems setting up the environment correctly.

- The jest tests will not run entirely
- I believe you are missing eslint from the `package.json`
- Getting an error from babel when trying to use the package in the via `npm link`

```
ERROR in Loader /home/jmfurlott/work/misc/react-leaflet/node_modules/babel/index.js?optional=runtime&stage=0 didn't return a function
 @ ../misc/react-leaflet/lib/index.js 17:13-31
```

The Jest error I am getting on just `npm install`:

```
Using Jest CLI v0.4.13
Waiting on 5 tests...Could not find a `test` module while analyzing dependencies of `MapComponent`
 FAIL  lib/__tests__/Map.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:
```

Seen these problems before? Is it just my environment?

**Comment by PaulLeCam** [comment]
What version of node are you using? Jest is only compatible with v0.10.

There is no eslint in `package.json` but it's a good idea, I would add it eventually.

Regarding your error when using `npm link`, I suppose it's an issue with you configuration, seems to be an error with webpack loader and this library is not using webpack.

**Comment by PaulLeCam** [comment]
Closing due to lack of response, feel free to reopen if you need.
