### ISSUE TITLE
Uncaught Error: Couldn't autodetect L.Icon.Default.imagePath, set it manually

### ISSUE THREAD

**Issue by nahidmbstu** [PaulLeCam/react-leaflet#442]
i am using react leaftet and creating Marker Icon on map. But i am not seeing any image. it tells me that it does not getting the image path.

an working example in jsFiddle

https://jsfiddle.net/q2v7t59h/909/

it does not need any path. for icon.

but in my case it is asking me for Icon. why?

error

Uncaught Error: Couldn't autodetect L.Icon.Default.imagePath, set it 
manually.  at NewClass._getIconUrl 
///code

       {
              (typeof (this.state.startAnimationPoint) !== 'undefined' && (this.state.startAnimationPoint.length) 
       > 0) ? (

              <Marker 

              position={ this.state.startAnimationPoint } />
            ): null
          }

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
