### ISSUE TITLE
react-leaflet rendering issue in IE using Preact

### ISSUE THREAD

**Issue by SabirAmeen** [PaulLeCam/react-leaflet#445]
I used the following code in Preact.

https://codepen.io/anon/pen/aqYmmV

The zoom control repeat whenever the component rerenders. The issue unfortunately is present only in Internet Explorer.
Is this module compatible with Preact?

Here is the issue i got

![screenshot from 2018-02-20 13 21 56](https://user-images.githubusercontent.com/20511254/36412671-33a40c9e-1641-11e8-94c2-3c767f7a5b27.png)

**Comment by PaulLeCam** [comment]
No, it's not meant to be compatible with anything but the supported versions of React.
