### ISSUE TITLE
dragging with the Browse namespace

### ISSUE THREAD

**Issue by felixflow** [PaulLeCam/react-leaflet#451]
### Expected behavior

The dragging on dektops with one mouse-klick.
On MOBILE you need two fingers to zoom and drag

### Actual behavior

With `dragging={false}` the dragging won't work on desktops but on mobile.

### Steps to reproduce

set `dragging={false}`

The leaflet-documentation has the utility Browser. 
I think this is the solution -> http://leafletjs.com/reference-1.3.0.html#browser

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
