### ISSUE TITLE
Feature request: Ellipse in react-leaflet

### ISSUE THREAD

**Issue by shafiquejamal** [PaulLeCam/react-leaflet#456]
**Before** opening an issue, make sure to read the
[contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md)
and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good
reason not to follow this template.**

* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
* [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [x] The issue has not already been reported.
* [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
* [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

Hello, I would like to propose a new feature: adding an Ellipse to the library of shapes that can be plotted in React-Leaflet. 

An example of an ellipse in Leaflet is [here](https://github.com/jdfergason/Leaflet.Ellipse).

I tried to implement this myself, but I got stuck [(details are here)](https://stackoverflow.com/questions/49089011/how-can-one-make-an-ellipse-in-react-leaflet).

And [here](https://github.com/shafiquejamal/gis-util#circle-ellipse) is an example of an ellipse plotted using Leaflet. 

Thanks,

**Comment by PaulLeCam** [comment]
Hi, this library only aims to implement core Leaflet features, for plugins support you should check out [the plugins page of the documentation](https://react-leaflet.js.org/docs/en/plugins.html) or [how to implement your own](https://react-leaflet.js.org/docs/en/custom-components.html).
