### ISSUE TITLE
Popup not showing; Getting 'Cannot read property 'x' of null' error

### ISSUE THREAD

**Issue by mrinmoydas3011** [PaulLeCam/react-leaflet#457]
Hi,

Thank you for providing such a wonderful library to us. While working with it, I am unable to show pop-ups as expected. Here is my index.html and the component code

index.html - 
`<!doctype html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Fleet Connect</title>
        
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="https://unpkg.com/react-leaflet-markercluster/dist/styles.min.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://js.arcgis.com/4.6/esri/css/main.css">        
        <link rel="stylesheet" href="https://js.arcgis.com/4.6/esri/css/main.css">
        <link rel="stylesheet" href="https://js.arcgis.com/4.5/esri/css/main.css">
        <Link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css">
    </head>
    <body>
        <div id="app"></div>
    </body>`

and component code -
`<Map center={coordinates[0].coordinates} zoom={12} style={{height: 700}} zoomControl={false}>
      <Control position="topleft">
        <MapNavbar/>
      </Control>
      <TileLayer
        attribution='&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <MarkerClusterGroup>
      <Marker position={coordinates[0].coordinates} icon={iconIcon(coordinates[0].status).iconPerson}>
        <Popup>
          <span>
            A pretty CSS3 popup. <br /> Easily customizable.
          </span>
        </Popup>
      </Marker>
      <Marker position={coordinates[1].coordinates} icon={iconIcon(coordinates[1].status).iconPerson}>
        <Popup>
            <span>
              A pretty CSS3 popup. <br/> Easily customizable.
            </span>
        </Popup>
      </Marker>
    </MarkerClusterGroup>
    <Control position="bottomright"s>
      <MapCircularPieLegend vehicleCoordinates={coordinates}/>
    </Control>
    </Map>`

Any help will be appreciated. Thank you! :D

**Comment by yoloOnTheBattlefield** [comment]
try going back to  `"react-leaflet": "^1.7.8"`, i ad the same issue when installed the project with npm, then i used yarn and everything went fine.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by i-schuetz** [comment]
@mrinmoydas3011 Since I can't find this issue anywhere else, could you find a solution? Having the same problem (react-leaflet 2.4.0 and leaflet 1.5.1).

**Comment by i-schuetz** [comment]
@PaulLeCam Wouldn't this fall under "possible bug"? The popup works with the default (invisible) marker. Using a custom icon shouldn't break it.

**Comment by i-schuetz** [comment]
Just for the record, the solution when using custom icons is to set the popup anchor on the icon: e.g. `popupAnchor:  [-3, -76]`
