### ISSUE TITLE
Changing className on tooltip doesn't update style

### ISSUE THREAD

**Issue by sguergachi** [PaulLeCam/react-leaflet#458]
**Before** opening an issue, make sure to read the
[contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md)
and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good
reason not to follow this template.**

* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
* [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [x] The issue has not already been reported.
* [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
* [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

```
    <ReactLeaflet.Tooltip
          permanent={true}
          direction="center"
          className={
            this.props.zoom > 14
              ? styles.zone_tooltip_big
              : styles.zone_tooltip_small
          }
        >
```
Using a conditional className for a tooltip should update the tooltip's style. I've confirmed the conditional works by console logging it inside the render function, and that both classNames do produces the desired styles independent of the conditional, but in this case it seems when the condition switches (true to false, false to true) the style of the component doesn't update.

Not sure if this is a react-leaflet issue or a leaflet issue.

**Comment by PaulLeCam** [comment]
This functionality should now be supported with v1.9, please reopen this issue if it's not working after updating.

**Comment by sguergachi** [comment]
Thanks, I’ll try it!

**Comment by nuragic** [comment]
I'm using `v1.9.1` and this is still an issue apparently... 😕

**Comment by sabres207** [comment]
this still happens 4 years later :)
I'm using version 4.2.21

**Comment by gabsrl** [comment]
I've made a workaround for this. As we can not update  `className` dynamically. I've created  a css class called `.tooltip` where I did write convenient styles for my use case. With the Tooltip default styles reseted  I've made a "wrapper" where I could customize as much I needed.

My Solution: 

```
/* my css  file */
.tooltip {
    background-color: transparent;
    color: #fff;
    padding: 0px;
    border: none;
}

/* my tsx */
// others importings...
import './tooltip.css';

// some code...

<Tooltip
          className="tooltip"
        >
          <Box w="100%" h="100%" backgroundColor="#0CB966">
            My tooltip text
          </Box>
</Tooltip>

````
Hope it helps.
