### ISSUE TITLE
Cannot bind to onLoad event

### ISSUE THREAD

**Issue by dmitry** [PaulLeCam/react-leaflet#46]
Cannot bind to the `onLoad` event to invoke `invalidateSize()`. Looks like it loads before events are set: https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L34 (events are setting in `super.componentDidMount();`).

How to make it work: https://github.com/Leaflet/Leaflet/issues/3560

Lets discuss about the solutions, before I will try to push a PR.

**Comment by PaulLeCam** [comment]
Out of curiosity, why do you want to call `invalidateSize()` once the map is loaded? As far as I know, Leaflet sets its size when it's loaded anyways.

**Comment by dmitry** [comment]
Looks like my styles on development machine are loaded right after the map initialize (I haven't checked on production though...), and the container div is sized afterwards again once CSS styles are loaded.

**Comment by PaulLeCam** [comment]
OK so in your case I think it's a much better solution to load your styles before, just like Leaflet styles should be loaded before creating any map anyways.

**Comment by PaulLeCam** [comment]
Closing for now as it doesn't seem to be an immediate issue.

**Comment by evenfrost** [comment]
@PaulLeCam Is there any reason that `onLoad` event is not working/implemented? I have exactly same issue, and it seems to be webpack's `style-loader` is causing it. Currently there is no 'better solution to load your styles before', and `ExtractTextPlugin` is not an option (no hot styles reloading).

**Comment by PaulLeCam** [comment]
The `onLoad` handler is not called because it is fired by Leaflet before the events are attached, but you can use the `componentDidMount` in your container component to achieve the same purpose.

**Comment by evenfrost** [comment]
Seems this is dead end for functional components users as we don't have `componentDidMount` handler. Would appreciate to see a workaround if somebody had one.

**Comment by evenfrost** [comment]
Managed to implement workaround with the help of #105. I'm binding to `onLoad` event in `<Map>` children, i.e.
```jsx
<TileLayer url={tiles} onLoad={handleLeafletLoad} />
 ```
Then I get map element in `handleLeafletLoad` handler via `event.target._map` reference.

**Comment by jisaacks** [comment]
It would probable be good to add a caveat to the following events section in the docs:

>Leaflet exposes its own events, different from React. You can listen to them using React-Leaflet by adding a callback to a property prefixed by on. Ex: onMoveend.
Check Leaflet documentation for the events associated to each component.

Stating that `load/onLoad` is not supported.

-----

I wanted to use this to get the mapBounds after rendering, because I only know the center and zoom before rendering.

It looks like you can do it like so:

```javascript
<Map ref={comp => {
  console.log( comp && comp.leafletElement.getBounds() )
}} />
```

**Comment by kommander** [comment]
If anybody is still wondering how to get the map ref only once, like `componentDidUpdate` but in a functional component with hooks:

```js
function MyComponent() {
  const mapRef = createRef<Map>()
  useEffect(() => {
    // mapRef is now available and useEffect is only called once on component update
    const bounds = mapRef.current.leafletElement.getBounds();
  }, [])

  return (
    <Map ref={mapRef}>...</Map>
  )
}
```

Disclaimer: Snippet is pseudo code and untested, but in essence that's it

**Comment by aldipower** [comment]
Please state in the documentation what's going on with the `load/onLoad`.

**Comment by podsevalovAlex** [comment]
It's possible to use method whenReady():     
.......
`return (
    <Map ref={mapRef} whenReady={someActions}>...</Map>
  )`
.......
see https://leafletjs.com/reference-1.6.0.html#map-whenready

**Comment by frafra** [comment]
A different take: `<MapContainer whenCreated={map => {map.onload = someActions;}}>`

**Comment by bertho-zero** [comment]
In 2023 I need to do:

```jsx
<MapContainer
  bounds={bounds}
  whenReady={({ target: map }) => {
    setTimeout(() => {
      // can use `map.getBound()` without error here
    }, 1);
  }}
>
```
