### ISSUE TITLE
Can not pass map and layerContainer to children from map to ImageOverlay while using redux

### ISSUE THREAD

**Issue by betovelandia** [PaulLeCam/react-leaflet#460]
Hi guys, I have been using the following structure in my app:

![screen shot 2018-03-13 at 11 35 25 am](https://user-images.githubusercontent.com/440908/37362540-bae98a0e-26b2-11e8-946a-b8c3d79e3f4f.png)

Where TCCMap is a component that extends Map and I intend to see the ImageOverlay component being rendered, I was expecting to see the `map` and `layerContainer` being accessed by the context API or at least get them from the TCCMap component children to pass it to `ImageOverlay` but no luck I'm getting the following error when I render: 
` TypeError: Cannot read property 'addLayer' of undefined`

I have seen other posts and they all say I need to pass `map` and `layerContainer` but I haven't found how, any ideas?

Thanks!

**Comment by hoetmaaiers** [comment]
Care to share the solution?

**Comment by clementallen** [comment]
@betovelandia did you find a solution to this?  I seem to be struggling with the same issue
