### ISSUE TITLE
Custom Map Marker

### ISSUE THREAD

**Issue by Siyanda-Mzam** [PaulLeCam/react-leaflet#465]
Hello,

Is it possible to customise the map markers. That is, instead of them being images, ,maybe make them svg or pure html elements?

Thanks very much
Siya

**Comment by Siyanda-Mzam** [comment]
I am not sure how to use with react-leaflet. How would I go about doing the same thing with react-leaflet? Also, what is `L`?

**Comment by Pizdetss** [comment]
What are you trying to achieve?

**Comment by Pizdetss** [comment]
L is the leaflet object where you can assign the URL path to your custom marker.

`const customMarker = L.icon({
iconUrl: require('pathtoicon'),
})`
`return (
 <Marker icon={customMarker} >
 /*whatever inside marker */
 </Marker>
)`

**Comment by Siyanda-Mzam** [comment]
Great. It works. Thanks so much. Closing this...
