### ISSUE TITLE
How to add a TimeDimension layer/control to the map

### ISSUE THREAD

**Issue by krisaoe** [PaulLeCam/react-leaflet#467]
Hello and thank you for your hard work on this great package.

I need to add a TimeDimension layer and control to my map, do you have any examples or can you advise on the sensible way to add Leaflet plugins or similar functionality in a React-Leaflet project?

Thanks!

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/v1/custom-components.html) section of the documentation.
