### ISSUE TITLE
Return old logic with passing an empty array to a LayerGroup component

### ISSUE THREAD

**Issue by northerneyes** [PaulLeCam/react-leaflet#469]
### Expected behavior

Previously `MapLayer.js`  which uses `LayerGroup.js` supported passing an empty array, due to the logic
```
Array.isArray(this.props.children)
      ? <div style={{display: 'none'}}>{this.props.children}</div>
      : (this.props.children || null)
```

### Actual behavior

But now you are checking `Children.count(children) > 1`, but `children`  can be an empty array. 
```
if (Children.count(children) > 1) {
      return (
        <div style={{ display: 'none' }}>
          {children}
        </div>
      )
    }
    return children == null ? null : children
```

### Steps to reproduce
So this stuff is no longer worked, if `markers.length === 0` which is annoying 
```
<LayerGroup>
 {markers.map(marker => marker)}
</LayerGroup>
```

I need to wrap in `div`, but in this case when `markers.length > 0` we will get double `div`. 
Or passing `null`

Of course I can use `React.Fragment` to render arrays but it works only in React 16

**Comment by PaulLeCam** [comment]
`Array.isArray()` is not a good check, children could be other types of iterables.
This logic should be in your component, you shouldn't render an empty `LayerGroup`, could be as simple as `markers.length > 0 ? <LayerGroup>{markers}</LayerGroup> : null`.
