### ISSUE TITLE
support disabled prop

### ISSUE THREAD

**Issue by fyyyyy** [PaulLeCam/react-leaflet#47]
It would be nice if disabled={...} props would be supported in all relevant components.

Currently one has to manually unwrap the element and call the control functions as in:
```js

this.deactivateMap(
  this.refs.map.getLeafletElement()
);

  deactivateMap: function (map) {
    map.dragging.disable();
    map.touchZoom.disable();
    map.doubleClickZoom.disable();
    map.scrollWheelZoom.disable();
    map.boxZoom.disable();
    map.keyboard.disable();
    if (map.tap) map.tap.disable();

**Comment by PaulLeCam** [comment]
These interaction options are passed from the props when creating a Map, ex `<Map dragging={false}>`.

The purpose of this lib is not to add functionalities that are not supported by Leaflet, just provide an abstraction for it, so if you need this kind of features, the best option if to extend one of the components depending on your needs.

**Comment by fyyyyy** [comment]
My bad i thought leaflet supported it :)
In this case i will extend your base component
Thanks
