### ISSUE TITLE
ImageOverlay : Image not visible

### ISSUE THREAD

**Issue by gajju3588** [PaulLeCam/react-leaflet#472]
### Expected behavior
Image should show up
### Actual behavior
Screen is blank with div having leaflet as height and width as zero.
Using ImageOverlay inside Map, but image width and height is coming to be zero
### Steps to reproduce
      <div style={{opacity: '0.6', height: '100%', width: '100%'}}>
      <Map
        crs={CRS.Simple}
        zoomControl={false}
        attributionControl={false}
        editable
        onClick={(latlng) => console.log('onMapClick', latlng)}
        onMousemove={(latlng) => console.log('onMousemove', latlng)}
        zoomSnap={0.1}
      >
        <ImageOverlay interactive url={this.props.image} bounds={[[0, 0], [853, 256]]}/>
      </Map>

React & ReactDom version :  15.6.2
leaflet & react-leaflet are lates

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
