### ISSUE TITLE
Clicking a marker make the whole page scroll vertically

### ISSUE THREAD

**Issue by yzaroui** [PaulLeCam/react-leaflet#474]
**Before** opening an issue, make sure to read the
[contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md)
and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good
reason not to follow this template.**

* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
* [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
* [x] The issue has not already been reported.
* [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
* [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Clicking a marker should display the tooltip without scrolling the whole page.

### Actual behavior

When I click on a marker it tries to center the map component in the page by scrolling the whole page vertically and then the click event is triggered on another position on the map and not the clicked marker.

### Steps to reproduce

Create a map with one or more marker. Parts of the map should not be visible.
Click on the marker.

Please provide the simplest example possible to reproduce the issue, based on
[this CodePen](https://codepen.io/PaulLeCam/pen/XVPmmj).

**Comment by PaulLeCam** [comment]
This is Leaflet's expected behavior, not an issue with this library.

**Comment by henryornellas** [comment]
> This is Leaflet's expected behavior, not an issue with this library.

Well, then how to prevent it?
