### ISSUE TITLE
Help needed with react-leaflet-shapefile pomponet 

### ISSUE THREAD

**Issue by Charmatzis** [PaulLeCam/react-leaflet#477]
Hi, I have developed a year ago this https://github.com/Charmatzis/react-leaflet-shapefile and I finally found time to update it. 
But I have forgotten how to write react-leaflet component and now that I try to update the packages I run through bugs. 

Do you have any time to talk, to see how I can update it?

Thanks in advance. 

X.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
