### ISSUE TITLE
Popup rendering does not respect React expectations with regards to context

### ISSUE THREAD

**Issue by kroltan** [PaulLeCam/react-leaflet#478]
* [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
* [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
* [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
* [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v2 beta**.
* [x] The issue has not already been reported.
* [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
* [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/v1/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/v1/intro.html#limitations).

### Relevant issues
#310, #264, #266, but please see the comment below this bug report.

### Expected behavior

Rendering content within a `Popup` should follow the context stack.

### Actual behavior

`Popup`'s children are manually rendered with `ReactDOM.render`, creating a new context stack that does not inherit the current stack.

### Steps to reproduce

Use any component that depends on the `context` API (not the new `Provider`/`Consumer`-based API) within the contents of a popup. Example with `react-intl`, but happens with any context:

```jsx
ReactDOM.render(<IntlProvider /* ... */>
    <LeafletMap>
        <Marker>
            <Popup>
                <FormattedMessage id="example"/>
            </Popup>
        </Marker>
    </LeafletMap>
</IntlProvider>);
```

This will crash the application, because `FormattedMessage` expects the `intl` context, which is provided by `IntlProvider`. But `Popup` uses a separate `ReactDOM.render` call to get the element tree of the children and place it inside the actual popup, which creates a separate context which does  not have `intl`.

**Comment by kroltan** [comment]
Maybe this component was written before they existed, but nowadays we can use [Portals](https://reactjs.org/docs/portals.html) to easily achieve what the `ReactDOM.render` approach attempted to solve, which is placing elements in a location not matching the containing tree.

It will handle all peculiarities and work transparently for the library's user.

**Comment by kroltan** [comment]
This seems to be fixed in v2, but the documentation is outdated.

**Comment by suricactus** [comment]
Not sure if this is fixed, because when using redux's `connect` on component inside react-leaflet's `<Popup />` I continue to get the following error:
```browser.js:38 Uncaught Error: Could not find "store" in either the context or props of "Connect(LabelAirport)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(LabelAirport)".```

**Comment by kroltan** [comment]
@suricactus What version?
