### ISSUE TITLE
Support for React 16.3 Strict Mode

### ISSUE THREAD

**Issue by incarnateTheGreat** [PaulLeCam/react-leaflet#481]
Hello!

I'm really enjoying using react-leaflet. Thank you!

I have implemented **StrictMode** for my react-leaflet application, but am receiving errors regarding the React 16.3 soon-to-be deprecated lifecycle hooks' **componentWillMount** and **componentWillReceiveProps**. 

Are these hooks going to be replaced with their respective surviving hooks? 

Thanks again!

**Comment by PaulLeCam** [comment]
Hi, thanks!
What version of the library are you using please? v1 won't support React's strict mode but v2 should already be compatible, please provide more details if it's not.

**Comment by incarnateTheGreat** [comment]
@PaulLeCam : I'm on v1. Is V2 still in beta?

**Comment by PaulLeCam** [comment]
Yes v2 is in beta but unless you are using third-party plugins that haven't been updated to it, you should be able to upgrade from v1 without having to make any change.

**Comment by incarnateTheGreat** [comment]
`
"react-leaflet": "^1.9.1",
"react-leaflet-control": "^1.4.1",
"react-leaflet-markercluster": "^1.1.8",
react-leaflet-rotatedmarker": "^0.1.0",
`

These are the Leaflet third-party plugins that I'm using. I'm not sure if they'll break or not, but I'll give it a go. Thank you.

**Comment by kontrollanten** [comment]
I've created a PR to update those lifecycle methods https://github.com/PaulLeCam/react-leaflet/pull/485

**Comment by incarnateTheGreat** [comment]
@kontrollanten thank you. I had tested my leaflet dependencies and they were all cacking out. Hopefully those will be upgraded soon, but in the meantime, I hope your PR goes through. :)

**Comment by PaulLeCam** [comment]
Added in v2.

**Comment by incarnateTheGreat** [comment]
Thanks for looking in to this, guys.

I still try updating to v2 and the third-party plugins seem to be causing problems -- primarily RotatedMarker and MarkerClusterer. I'm assuming there's no real way to get around this unless the authors of these plugins solve their respective compatibility issues?
