### ISSUE TITLE
Map tiles missing in developer mode with custom-react-scripts

### ISSUE THREAD

**Issue by john-aws** [PaulLeCam/react-leaflet#487]
**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v2 RC**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/v1/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/v1/intro.html#limitations).

### Expected behavior

Maps renders correctly and fills container:

![react-leaflet-good](https://user-images.githubusercontent.com/3178883/41425756-aaf86e24-6fcf-11e8-8fa9-5b03ff6e66b5.jpg)

### Actual behavior

Only the top row of tiles renders. Nothing renders below the top row and all you see is the gray background:

![react-leaflet-bad](https://user-images.githubusercontent.com/3178883/41425734-9d309014-6fcf-11e8-9b16-52393bef161c.jpg)

### Steps to reproduce

* create minimal react app
* add minimal react-leaflet map to App.js/App.css
* test in dev mode, using `npm start` (it shows map **correctly**)
* switch to custom-react-scripts (npm uninstall --save react-scripts && npm install --save custom-react-scripts)
* test in dev mode, using `npm start` (it shows map **incorrectly**)
* test in prod mode, using `npm run build && serve -s build` (it shows map **correctly**)

The reason that I am switching from react-scripts to custom-react-scripts is in order to support Mobx decorators such as `@observer` and custom CSS modules.

Note that I can repro this on both Windows 10 and on Mac OS X.

**Comment by PaulLeCam** [comment]
From your description this is an issue with your setup, not this library.

**Comment by weyert** [comment]
@john-aws Have you ever been able to fix this problem? I am having a similar issue that the map is not correctly loading like this.

**Comment by john-aws** [comment]
@weyert Hi, I elected to stop using Mobx ES.next observer decorators and instead used observer functions instead, for example:

```
const MyMarker = observer(class MyMarker extends React.Component {
  static propTypes = {
    map: PropTypes.object,
    position: PropTypes.object,
    color: PropTypes.string,
  };
  render() {
    return (
      <React.Fragment>
        <Circle center={this.props.position} fillColor="blue" radius={200} />
        <CircleMarker center={this.props.position} color={this.props.color} radius={20}/>
      </React.Fragment>
    );
  }
});

export default MyMarker;
```
