### ISSUE TITLE
WMTS layer

### ISSUE THREAD

**Issue by PaulTodd** [PaulLeCam/react-leaflet#490]
Is there a way to use WMTS Tile Layers with this component?  There is a library here: https://github.com/mylen/leaflet.TileLayer.WMTS.  How would this be used to create a plugin for this component?

Thanks

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.

**Comment by matkoniecz** [comment]
https://react-leaflet.js.org/docs/en/custom-components.html link is broken

**Comment by matkoniecz** [comment]
It seems that nowadays it is available through https://github.com/PaulLeCam/react-leaflet/blob/master/packages/react-leaflet/src/WMSTileLayer.tsx

**Comment by PaulTodd** [comment]
They still don't have a built in option for WMTS though.  That is just for WMS.  A WMS is calculated on the server side and delivers one image per request. A WMTS delivers tiles that have been pre-rendered on the server side, and cached on the client side.
