### ISSUE TITLE
Module not found: Can't resolve 'leaflet'

### ISSUE THREAD

**Issue by behnamazimi** [PaulLeCam/react-leaflet#491]
When I do like I am currently facing this error, 

```
./node_modules/react-leaflet/es/Marker.js
Module not found: Can't resolve 'leaflet' in ...\node_modules\react-leaflet\es'
```

**Comment by hpierre74** [comment]
I ran into the same error, you need to add 'leaflet' to your depencies : 
```yarn add leaflet``` 
```npm i leaflet```

**Comment by behnamazimi** [comment]
I did it truely! 
still this error. even when I ctrl+click on the file names , it goes to the file inner!

**Comment by alexghinea-adswizz** [comment]
Facing the same issue here.
Using `Webpack 4.12` and `Typescript 2.9.2` with `react-leaflet 2.0.0-rc.2"`

**Comment by tarksin** [comment]
Does not work for me; same error. 
Using  "react-leaflet": "^2.0.0" in packages.json
Module not found: Can't resolve 'leaflet' in '/home/.../..../...../client/node_modules/react-leaflet/es'

**Comment by gitstephanie** [comment]
Still no solution? I'm getting the same error:
'Can't resolve 'leaflet' in '/home/.../..../...../client/node_modules/react-leaflet/es''

`yarn add leaflet //
npm i leaflet` --> didn't help

**Comment by idurant** [comment]
worked for me! 

`npm install react-leaftlet --save` then
`npm i leaflet`

**Comment by 747823** [comment]
To clarify for anyone reading, `react-leaflet` has `react`, `react-dom`, and `leaflet` as peerDependencies which means they have to be npm installed separately or you will get this error. This is in fact noted on the installation instructions in the docs: https://react-leaflet.js.org/docs/en/installation.html

I would recommend doing --save on all the dependencies too, but that may depend on your use case.

**Comment by rzubrycki** [comment]
Maybe it's time to add this to documentation?

**Comment by reinisg** [comment]
> 
> 
> worked for me!
> 
> `npm install react-leaftlet --save` then
> `npm i leaflet`

This order worked for me. Thanks.

**Comment by worldsayshi** [comment]
Make sure you install in the right folder.

// Someone who didn't install in the right folder.

**Comment by mtaba** [comment]
i have same error in nextjs with leaflet. 
package below are added
     "leaflet": "^1.6.0",   
    "react-leaflet": "^2.6.0",
    "react-leaflet-markercluster": "^1.1.8"

**Comment by herodrigues** [comment]
To avoid this issue, I think `leaflet` should be a peer of `react-leaflet`.

**Comment by jjsmclaughlin** [comment]
Can you use react-leaflet without leaflet? I am unclear why it is a peer dependency and not a dependency.

**Comment by herodrigues** [comment]
@jjsmclaughlin It's not a peer. You also have to install `leaflet` as a dependency to your project.

**Comment by herodrigues** [comment]
@jjsmclaughlin It's a peer. But you have to install it to your project.

From the docs: 
> React, ReactDOM and Leaflet are peer dependencies, if you haven't already installed them you can use:
>
> `npm install leaflet react react-dom # npm`
> `yarn add leaflet react react-dom # Yarn`

**Comment by ashik927** [comment]
I faced the problem. Then  this command solve my problem.. ###   
                         npm i leaflet

**Comment by balazsbotond** [comment]
I got the same error. I needed to install the leaflet package **[but also include the leaflet CSS file](https://leafletjs.com/examples/quick-start/)** from the CDN.

**Comment by viniciusSantosdev** [comment]
yarn add leaflet worked for me too!

**Comment by mn3m-cs** [comment]
> worked for me!
> 
> `npm install react-leaftlet --save` then
> `npm i leaflet`

worked for me thank you

**Comment by atifghaffar83** [comment]
> npm i leaflet

yes it worked for me also. So this is the solution for me

npm install react-leaftlet --save then
npm i leaflet

thanks

**Comment by polat-code** [comment]
I got the same error and I changed the version of dependency. It solved it. My dependencies are below :
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@reduxjs/toolkit": "^2.2.3",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.7.9",
    "bootstrap": "^5.3.3",
    "js-cookie": "^3.0.5",
    "leaflet": "^1.8.0",
    "react": "^18.3.1",
    "react-bootstrap": "^2.10.4",
    "react-dom": "^18.3.1",
    "react-leaflet": "^4.2.1",
    "react-redux": "^9.1.2",
    "react-router": "^6.24.1",
    "react-router-dom": "^6.24.1",
    "react-scripts": "5.0.1",
    "react-toastify": "^10.0.6",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": " react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/leaflet": "^1.9.15"
  }
}
