### ISSUE TITLE
Help porting standard Leaflet map to React

### ISSUE THREAD

**Issue by shardick** [PaulLeCam/react-leaflet#492]
Hi,
sorry for writing here, but i'm having big problems to port a map already realized and fully functional in standard LeafletJS in react.

That map use a lot of unproject and project and geo calculation to port map coordinates on real game coordinates (in this case Euro Truck Simulator 2 and American Truck Simulator)

The map is located here: https://api.truckyapp.com/map/ets2 and is controlled by this classic js class: https://api.truckyapp.com/mapobjects/mapManager.js 

Anyone could help with some hints?

Thanks

Regards

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
