### ISSUE TITLE
Collapse LayersControl programmatically

### ISSUE THREAD

**Issue by fullhdpixel** [PaulLeCam/react-leaflet#494]
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v2 RC**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/v1/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/v1/intro.html#limitations).

### Expected behavior

https://leafletjs.com/reference-1.3.0.html#control

There is a collapse method that is not supported here. I want to programmatically close the LayersControl. 

### Actual behavior

-

**Comment by PaulLeCam** [comment]
You can use the `collapsed` property of the `LayersControl` component in v2.
