### ISSUE TITLE
On Add event for circle, polygon

### ISSUE THREAD

**Issue by sruthisripathi** [PaulLeCam/react-leaflet#496]
Hi,

I saw in leaflet documentation that 'add' event is fired after the circle / polygon is added to the map.
I want to perform some actions like updating state after the circle / polygon is added to the map.
Is there a way to do it? I thought it would be convenient if there is a prop method to Circle / Polygon called onAdded which receives the leaflet id of the circular or polygonal layer added as a parameter.

**Comment by PaulLeCam** [comment]
Hi,
If I understand your request correctly this is already covered by the events support, you can read about it in the documentation: https://react-leaflet.js.org/docs/en/events.html

**Comment by jimmyhsie** [comment]
@PaulLeCam  you just save my day !! thx
