### ISSUE TITLE
Draggable Marker referencing incorrect Marker element

### ISSUE THREAD

**Issue by sneakycrow** [PaulLeCam/react-leaflet#497]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable v2 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

When I Drag a Marker, its `lattitude` and `longitude` are updated in my array of Markers

### Actual behavior

When the Marker is being picked up, React seems to know via the ID of the Marker being passed which marker to update, but the `refMarker` seems to think that we're still on the last created marker. Therefore, the lattitude and longitude positions that are being injected into the params are for the last marker created, not the marker being dragged.

### Steps to reproduce

https://codepen.io/sneakycrow/pen/gjwGzY

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/gzVmGw).

**Comment by PaulLeCam** [comment]
According to your example this is not an issue with this lib but rather the expected behavior considering you're using the same ref for all markers, it only gets applied to the last one in the loop.

**Comment by sneakycrow** [comment]
Ah, that does seem to be the problem. Alright, I had a misunderstanding of how ref's are applied. Thanks!
