### ISSUE TITLE
Unable to integrate ImageOverlay.Rotated plugin

### ISSUE THREAD

**Issue by mottab** [PaulLeCam/react-leaflet#500]
I am trying to integrate [ImageOveraly.rotated](https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated) but I am stuck in how I can integrate it and use with react-leaflet.

I tried to make a custom Map Class that integrates the ImageOverlay with the map, but it didn't work.

Any working examples or thoughts about how to integrate this library.

Here's what I am doing

    import React, { Component } from 'react'
    import { Map, TileLayer, ImageOverlay } from 'react-leaflet'
    import Leaflet from 'leaflet'
    import {imageOverlay} from 'leaflet-imageoverlay-rotated'
    
    class ImageOverlayRotated extends Map {
      createLeafletElement(props) {
        let LeafletMapElement = super.createLeafletElement(props);
        let topleft    = new Leaflet.latLng(25.19369224545977, 55.27024269104004);
        let topright   = new Leaflet.latLng(25.19369224545977, 55.27024269104004);
        let bottomleft = new Leaflet.latLng(25.192905875160584, 55.27065575122833);
        let overlay = new Leaflet.imageOverlay.rotated("./zoning.svg", topleft, topright, bottomleft, {
          opacity: 0.4,
          interactive: true
        });
        LeafletMapElement.ImageOverlay = overlay
        return LeafletMapElement;
      }
    }
    
    export default class ImageOverlayExample extends Component {
      state = {
        play: true,
      }
    
      onTogglePlay = () => {
        this.setState({ play: !this.state.play })
      }
    
      render() {
        return (
          <div className="map">
            <ImageOverlayRotated
            onClick={this.onTogglePlay}
            bounds={[[25.192905875160584,55.27024269104004,0],[25.19413882386311,55.27176082134247,0]]}
            style={{width: "858px", height: "650px"}}
            >
              <TileLayer
                noWrap={true}
                attribution="&amp;copy <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              />
              {
              <imageOverlay
                opacity={0.6}
                bounds={[[25.192905875160584,55.27024269104004,0],[25.19413882386311,55.27176082134247,0]]}
                play={this.state.play}
                url="./zoning.jpg"
                interactive={true}
                topRight = {{lat: 25.19413882386311, lng: 55.271347761154175}}
                topleft = {{lat: 25.19369224545977, lng: 55.27024269104004}}
                bottomleft = {{lat: 25.192905875160584, lng: 55.27065575122833}}
              />
              }
            </ImageOverlayRotated>
          </div>
        )
      }
    }

Thanks.

**Comment by mottab** [comment]
Thank you,

I solved it.

    import React, { Component } from 'react'
    import { Map, TileLayer, ImageOverlay} from 'react-leaflet'
    import Leaflet from 'leaflet'
    import 'leaflet-imageoverlay-rotated'
    
    class ImageOverlayRotated extends Map {
      createLeafletElement(props) {
        let LeafletMapElement = super.createLeafletElement(props);
        let topleft    = new Leaflet.latLng(25.19369224545977, 55.27024269104004);
        let topright   = new Leaflet.latLng(25.19413882386311, 55.271347761154175);
        let bottomleft = new Leaflet.latLng(25.192905875160584, 55.27065575122833);
        let overlay = new Leaflet.imageOverlay.rotated("./zoning.svg", topleft, topright, bottomleft, {
          opacity: 0.7,
          interactive: true
        }).addTo(LeafletMapElement)
        return LeafletMapElement;
      }
    }
    
    export default class ImageOverlayExample extends Component {
      state = {
        play: true,
      }
    
      onTogglePlay = () => {
        this.setState({ play: !this.state.play })
      }
    
      render() {
        return (
          <div className="map">
            <ImageOverlayRotated
            onClick={this.onTogglePlay}
            bounds={[[25.192905875160584,55.27024269104004,0],[25.19413882386311,55.27176082134247,0]]}
            style={{width: "858px", height: "650px"}}
            >
              <TileLayer
                noWrap={true}
                attribution="&amp;copy <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              />
            </ImageOverlayRotated>
          </div>
        )
      }
    }

**Comment by saadbinsaeed** [comment]
@mottab I copied and pasted the same code. Just changed the image URL. I can see my image on map but I am unable to rotate or transform it.

**Comment by mottab** [comment]
Make sure you changed both the bounds, topright, topleft and bottomleft variables to your own custom positions.
