### ISSUE TITLE
Supporting Offline

### ISSUE THREAD

**Issue by mkrishna2025** [PaulLeCam/react-leaflet#502]
How was we support offline maps completely. Assume that we can keep offline maps in some folder and consume them in app rather than online map.

**Comment by PaulLeCam** [comment]
This is something you should investigate with Leaflet and its plugins as it's out of the scope of this library.

**Comment by shierro** [comment]
Hi @PaulLeCam , can you help me with an issue regarding offline support? https://stackoverflow.com/questions/52810382/enable-react-leaflet-to-use-be-usable-offline

Thanks!
