### ISSUE TITLE
Pane component does not render children in correct Pane when using GeoJSON

### ISSUE THREAD

**Issue by chazsolo** [PaulLeCam/react-leaflet#503]
## Bug report in v1.9.1

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x or v16.x).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest v1 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/v1/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/v1/intro.html#limitations).

### Expected behavior

Components passed as children to a `<Pane>` component should be rendered as child elements within the DOM

### Actual behavior

When using `GeoJSON` (or other components like Marker, DivIcon, custom Icon components, etc), the markers generated end up inside the `leaflet-overlay-pane` and not the Pane that is wrapping the elements.

### Steps to reproduce

See [this CodePen for working example](https://codepen.io/chazsolo/pen/pZYYQd).

Note the empty "test-pane" at the bottom.

![elements](https://user-images.githubusercontent.com/5860950/44046434-70a6389c-9ef9-11e8-829e-8d38cdaaada2.png)

I believe this is due to the pane name not propagating to the marker properly; this means the marker gets added to the default pane instead of it's parent. If you add

```
pane: 'test-pane',
```

to the L.circleMarker options (pointToLayer function), the marker gets added to the correct pane (although not showing up on top of the map in this example)

### Workaround

I believe the name _should_ be propagated to the marker without the developer from having to bind it manually. Until then, I have this working by adding the pane name as a property to the Geo object before passing it into the `<GeoJSON>` component and ensuring the pane name is destructured into the marker:

A short example (real project is broken up into multiple panes each with their own styles and custom popups):

```typescript
const markers = data.map((feature: any) => {
  feature.properties.pane = 'test-pane'
  return feature
})

return (
  <Pane name="test-pane">
    <GeoJSON
      data={arrayToFeatureCollection(markers)}
      pointToLayer={this.pointToLayer}
      onEachFeature={this.onEachFeature}
    />
  </Pane>
  <Pane name="..."></Pane>
  <Pane name="..."></Pane>
)
```

pointToLayer method

```typescript
pointToLayer = (feature: Feature, latlng: LatLng) => {
  const { pane } = feature.properties

  return IconMarker({
    latlng,
    pane,
  })
}
```

in `IconMarker.tsx`

```typescript
function IconMarker(props: IProps) {
  const { latlng, pane } = props

  return L.marker(latlng, {
    pane,
    icon: L.divIcon({
      // ...
    })
  })
}
```

**Comment by PaulLeCam** [comment]
The `Pane` component will provide the `pane` option to its children components, but it is the expected behavior that it is not affecting Leaflet itself in any way.
As you presented in your code, providing the `pane` option to Leaflet factories is the way to go.

**Comment by chazsolo** [comment]
Thanks for the response, and happy to leave as is. I'd suggest to update the documentation for Pane to reflect this, at least - took me longer than I'd like to admit to narrow this one down.

**Comment by felixdrp** [comment]
Add next line to html header helped me a lot. (Change version if you need it)
   <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" />

Thanks for the check list :-)
