### ISSUE TITLE
Polyline component does rerender on state change

### ISSUE THREAD

**Issue by melvinchng** [PaulLeCam/react-leaflet#504]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable v2 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Overview

I am able to use the polyline component without any issue (lines are drawn and shown on the map). I tried to add or extend a polyline dynamically (by adding a set of coordinates to my state).

### Expected behavior

Polylines should extend the line and show on the map. Example: A -> B -> C -> D -> E, where A, B are the original polyline and C, D, E, are the new points added.

### Actual behavior

Polylines component does not update, showing the original state of data. Example: A -> B, where A, B are the original polyline.

### Steps to reproduce

Please refer to codepen: https://codepen.io/melvinchng/pen/djLpeM?editors=0110

**Comment by chazsolo** [comment]
Check this codepen: https://codepen.io/chazsolo/pen/NBmzPB?editors=0110

You weren't updating `positions` in state which is what the polyline was using for data.

**Comment by melvinchng** [comment]
Thanks for the response. From your codepen, the Polyline works the way you have your state updated. However, I found out that the way I have my state updated works for Circle components, but not Polyline.  

Codepen: https://codepen.io/melvinchng/pen/MBRqXP?editors=0110

**Comment by chazsolo** [comment]
I've not used setState functionally before, but that _seems_ to be your problem. Change

```
this.setState(prevState => {
  const newSample = [...prevState.sample];
  newSample[0].positions.push(newMarker);
  return {sample: newSample};
});
```

to

```
this.setState({
  sample: [{
    ...this.state.sample[0],
    positions: [
      ...this.state.sample[0].positions,
      newMarker
    ]
  }]
})
```

Your polyline will update correctly

**Comment by PaulLeCam** [comment]
This is the expected behavior as the changes to the `positions` prop are compared by reference, not by value, so you need to provide a different array of `positions` rather than mutating the existing one.
