### ISSUE TITLE
Question: Is <TileLayer> compatible with Mapquest?

### ISSUE THREAD

**Issue by RossKinsella** [PaulLeCam/react-leaflet#518]
Hi folks,

I love the library, it feels super powerful. I'd like to use mapquest and this together but looking at their documentation, its not clear to me if / how to make it work with the Tilelayer component. 
- Specifically, I am not seeing the `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` pattern

doc:
https://developer.mapquest.com/documentation/leaflet-plugins/maps/

Any help / suggestions are much appreciated

Thanks!

**Comment by PaulLeCam** [comment]
Hi,
Sorry I'm not familiar with MapQuest but you can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using this library.

**Comment by benneq** [comment]
@RossKinsella Did you get it working somehow?

**Comment by RossKinsella** [comment]
It's possible to specify the tileset leaflet is running. Check out their
API, I gave it a URL for Google's tiles in my app. I'd give you a snippet
but AFK

**Comment by benneq** [comment]
@RossKinsella It's not urgent, but it would be nice if you could provide some code for it eventually 😄 

It looks like MapQuest is now powered by MapBox. And MapBox is much cheaper 😮 

Would still be nice if you could provide some code to get MapQuest working with react-leaflet. 

Thank you!

**Comment by RossKinsella** [comment]
@benneq I got the google tileset running using: https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

under the hood, these tilesets are running the same protocal. Something similar should be possible if you dig into the source code

**Comment by benneq** [comment]
I already figured out a simple solution:
```
<Map>
  <TileLayer url="https://{s}.tiles.mapbox.com/v4/mapquest.streets-mb/{z}/{x}/{y}.png?access_token=...">
</Map>
```

I just used my legacy leaflet MapQuest map and opened Chrome's Network tab. There you can see where it loads the tiles from. Then I just copied the request URLs and added some variables: `{s}` and `{z}/{x}/{y}`.
