### ISSUE TITLE
Add ability to modify the leaflet-control-container

### ISSUE THREAD

**Issue by michaelryancaputo** [PaulLeCam/react-leaflet#52]
Leaflet automatically adds `leaflet-top leaflet-left` to the +/- buttons. I can't seem to figure out how to control the class' here.

**Comment by PaulLeCam** [comment]
If this is default Leaflet behavior, it's Leaflet's documentation you should refer to.

**Comment by michaelryancaputo** [comment]
Thanks, I am familiar with the Leaflet API, however, I don't quite understand how I can access `getLeafletElement()` to modify it.

**Comment by PaulLeCam** [comment]
You only need to add a `ref` to the `<Map />` component to access it from its parent, as you would for any other React component.
You can check [this example](https://github.com/PaulLeCam/react-leaflet/blob/master/example/events.js) that accesses the Map's `leafletElement`.
