### ISSUE TITLE
 marker Icon not showing

### ISSUE THREAD

**Issue by anujsinghwd** [PaulLeCam/react-leaflet#520]
#### Map is loading corrrectly but marker icon is not showing

```jsx
<Map center={position} zoom={this.state.zoom}>
        <TileLayer
                    url={url}
                    attribution="&amp;copy <a href=&quot;http://www.mapmyindia.com/about/privacy-policy&quot;>MapMyIndia</a> contributors"
                />
         <Marker position={position}>
             <Popup>A pretty CSS3 popup.<br />Easily customizable.</Popup>
       </Marker>
  </Map>
```
#### Error: 
`Failed to load resource: net::ERR_INVALID_URL`

**Comment by phdog** [comment]
Same here

**Comment by anujsinghwd** [comment]
@phdog 
i found the solution use custom marker. this resolve your issue.

**Comment by QauseenMZ** [comment]
This custom marker resolved problem for me (have to give right path for marker image):
https://stackoverflow.com/questions/47723812/custom-marker-icon-with-react-leaflet

**Comment by MendezBruno** [comment]
I found this solution in another page: 

`import React, { Component } from 'react';
import L from 'leaflet';
import {
    Map, TileLayer, Marker, Popup
} from 'react-leaflet'
import 'leaflet/dist/leaflet.css';
import './style.css';


import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';

let DefaultIcon = L.icon({
    iconUrl: icon,
    shadowUrl: iconShadow
});

L.Marker.prototype.options.icon = DefaultIcon;`

this work for react-leaflet

**Comment by Teewaii** [comment]
I had a similar problem when using leaflet on a react project but the following steps worked for me:

Step 1: I removed the import "leaflet/dist/leaflet.css" line of code from my index.js document.
Step 2: I copied and pasted  the link below to the CSS file for leaflet from  leafletjs.com and pasted it in the header section of my index.html document.

Leafletjs CSS link:  ( <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossorigin=""/>)
