### ISSUE TITLE
onMouseover marker popup

### ISSUE THREAD

**Issue by Fuad607** [PaulLeCam/react-leaflet#521]
hello 
I want to try onMouseover prop show Marker Popup but it is not working. The console log work when mouseover but popup did not show. I do not have any idea how to fix this. Can you help me to solve this problem?

Code:

```
const Markers = markers.map(marker => (
      <Marker position={marker.latlng} key={`marker_${marker.name}`}
     onMouseout={this.hidePopUpOfMarker.bind(this)}   onMouseover={this.showPopUpOfMarker.bind(this)} >
        <Popup   >
   <h1 style={{ fontSize: 20 }}> {marker.name}</h1>
     </div>
   <span><p>New York</p></span>
   </div>
        </Popup>
      </Marker>
    ));

```
```
 showPopUpOfMarker(marker){
        console.log("Mouse over")
        this.setState({markerPopUp:marker})
}
hidePopUpOfMarker(){
        console.log("Mouse out")
        this.setState({markerPopUp:false})
}
```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
