### ISSUE TITLE
missing leaflet peer

### ISSUE THREAD

**Issue by droganov** [PaulLeCam/react-leaflet#522]
react-leaflet doesn't work out of the box neither with `yarn add` nor with `npm install`.

the error is `Uncaught Error: Cannot find module "leaflet"`

Normally a module works out of the box, please fix the config or improve the `Leaflet setup` section

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.

**Comment by yanickrochon** [comment]
Right, so this is an issue, how was this resolved?
