### ISSUE TITLE
<Popup> doesn't fire leaflet events

### ISSUE THREAD

**Issue by nuragic** [PaulLeCam/react-leaflet#525]
### Expected behavior

From https://react-leaflet.js.org/docs/en/events.html:

> Leaflet exposes its own events, different from React. You can listen to them using React-Leaflet by adding a callback to a property prefixed by on. Ex: <Map onMoveend={this.handleMoveend}>...</Map>.
> Check 🍃 Leaflet's documentation for the events associated to each component.
> 

Cool, in fact I'm doing that with `Marker` and it works as expected (it logs the leaflet event data):

`<Marker draggable onMoveend={(eventData) => console.log(eventData)} />`

However, I'm trying to do the same with `Popup`:

`<Popup onPopupopen={(popupEventData) => console.log(popupEventData) } />`

That should log:

`{popup:{ … }, type: "popupopen", target: { … }, sourceTarget: { … }}`

### Actual behavior

It doesn't even enter the function. 😢 

### Steps to reproduce

https://codepen.io/nuragic/pen/MPePgW?editors=1111

Thanks in advance! I could make a PR to fix if you prefer. Cheers 😄

**Comment by PaulLeCam** [comment]
`popupopen` is an event emitted by the containing layer, not the popup itself.
You can use the `onOpen` prop on the `Popup` component to achieve what you're expecting.

**Comment by nuragic** [comment]
I need the event data so `onOpen` is useless in this case.

I know that Layer fires `popupopen`, but it's also fired by... obviously Popup.

Don't you think it's a bug?

**Comment by nuragic** [comment]
Nevermind... I figured it out as my Popup is wrapped in a FeatureGroup. Thanks for your time.
