### ISSUE TITLE
Add ability to use mapbox gl

### ISSUE THREAD

**Issue by michaelryancaputo** [PaulLeCam/react-leaflet#53]
Mapbox GL is so nice. Would be great to be able to add this to this component!

**Comment by PaulLeCam** [comment]
Have you tried [mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet)?

**Comment by simonv3** [comment]
@PaulLeCam any pointers for how to integrate mapbox-gl-leaflet with `react-leaflet`?
