### ISSUE TITLE
Issuetracker template: codepen external links are broken

### ISSUE THREAD

**Issue by ostrgard** [PaulLeCam/react-leaflet#530]
I'm sorry to byparse the bug submission template, but they're the issue. The `react` and `react-dom` external ressource links are broken in the [Codepen](https://codepen.io/PaulLeCam/pen/gzVmGw). Latest cdnjs `react` version is `16.4.2` and `react-dom` is `16.5.1`, though they ought to follow eachother.

This goes for the documentation codepen link as well, as they're the same.

**Comment by PaulLeCam** [comment]
Thanks for reporting this, I switched these dependencies to unpkg so this should work as expected now, please try it out and let me know if you still encounter the issue.
