### ISSUE TITLE
Changing Map className prop removes internally set classes

### ISSUE THREAD

**Issue by ostrgard** [PaulLeCam/react-leaflet#531]
## Bug report in v2

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable v2 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Classname can be provided and changed without overwriting the internally set classes.

### Actual behavior

Simple isolated reproduction: https://codepen.io/anon/pen/zmLbYb

In your browsers DOM inspector, observe that the class is initially set as:
`some-class leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom`

`some-class` comes from the `className` prop, while the rest is managed internally. Once the className is changed (click the button in the codepen), only the prop-provided class remains, while the internal classes are missing. [GIF showing the issue.](https://user-images.githubusercontent.com/1216866/47312635-2e200680-d63d-11e8-9e02-6d8250f5c604.gif)

**Comment by PaulLeCam** [comment]
Thanks for the example, this should be fixed in v2.1.1, please try it out.

**Comment by ostrgard** [comment]
> Thanks for the example, this should be fixed in v2.1.1, please try it out.

Thank you for the extremely quick fix. It is indeed fixed!
