### ISSUE TITLE
Leaflet Map events are not updated

### ISSUE THREAD

**Issue by fqborges** [PaulLeCam/react-leaflet#546]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x ] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x ] Using the [latest stable v2 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x ] The issue has not already been reported.
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Expected that when `Map` `onClick` prop changes it was propagated to Leaflet `Map` `click` event.

### Actual behavior

I debugged and noticed that MapEvented componentDidUpdated is not called from MapComponent componentDidUpdated.

### Steps to reproduce

I created a EditPathMapComponent receiving props `value` (an array of lat/lon) and `valueChanged` called when user clicks map with the previous lat/long plus the a new one on the clicked position. The value is accessed inside the onClick callback, and you can notice that the clousure is always the same, referencing the old value.

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/gzVmGw).

see: https://codepen.io/anon/pen/PXpBzm

**Comment by PaulLeCam** [comment]
Thanks for reporting this, indeed the issue was with the Map's `componentDidUpdate()` method.
It should be fixed now in v2.1.4, please try it out.

**Comment by fqborges** [comment]
Fixed! Thanks for your efforts, amazing work.
And sorry for the delay, I was off since xmas weekend.
