### ISSUE TITLE
@babel-runtime in dependencies: Is this normal?

### ISSUE THREAD

**Issue by popbee** [PaulLeCam/react-leaflet#547]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [ x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [ x] Using the [latest stable v2 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x ] The issue has not already been reported.
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

I believe, babel is used for building the library (devDependencies), not for runtime (dependencies)

### Actual behavior

@babel-runtime appears in dependencies

Now I have unmatched babel versions in my builds because I use a different version, it works, but I try to keep things clean when possible.

### Steps to reproduce

Just look at package.json  :)

**Comment by PaulLeCam** [comment]
Yes it's normal, `@babel/runtime` is a runtime dependency.
