### ISSUE TITLE
Error when unmounting TileLayer with minZoom set

### ISSUE THREAD

**Issue by bradcrawford** [PaulLeCam/react-leaflet#551]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.3.x) and its corresponding CSS file is loaded.
- [x] Using the [latest stable v2 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior
When using a TileLayer with minZoom set, it should be possible to zoom out beyond the minZoom setting and then selectively hide the map based on some state or route transition etc without it erroring.

### Actual behavior

Unmounting the map after zooming out beyond the minZoom setting of a TileLayer causes an error

Please describe.

### Steps to reproduce

https://codepen.io/anon/pen/zyjgEo
https://codesandbox.io/s/qz50lqnw14

- Zoom out to the point where the high res TileLayer (url set to cloudfront) disappears due to it's setting of `minZoom={18}`. Click the Hide button.
- Error
<img width="473" alt="screen shot 2019-01-08 at 6 31 12 am" src="https://user-images.githubusercontent.com/558730/50783205-06247300-130f-11e9-95ad-8e474310b53e.png">

- Remove `minZoom={18}`
- Repeat step above
- No error

**Comment by bradcrawford** [comment]
I will see what I can do @PaulLeCam

**Comment by bradcrawford** [comment]
https://codesandbox.io/s/ywn94996wj

@PaulLeCam, you're correct, it seems to be a leaflet bug so I will raise it on the leaflet github page.

**Comment by PaulLeCam** [comment]
Thanks for checking it it out.

**Comment by PaulLeCam** [comment]
Closing as it's an upstream issue in Leaflet.
