### ISSUE TITLE
Being able to customize the Leaflet component used

### ISSUE THREAD

**Issue by keul** [PaulLeCam/react-leaflet#562]
# Usecase

I need to use a custom `L.Control.Layers` implementation with slightly different behaviors.

At the moment I should provide also a new React wrapper as `LayersControl` implementation provided by react-leaflet uses the default Leaflet ones:

https://github.com/PaulLeCam/react-leaflet/blob/b8af25513f975617d3c1a9b584711c8c5ae43651/src/LayersControl.js#L138

This will work, but to be honest the react-leaflet wrapper is OK for me, I'm forced to customize it just to change few lines.

# Proposed change

I'm wondering if you will be interested in a new props like `leafletComponent=xxx` that, when provided, will change the leaflet element used inside `createLeafletElement`.
This should be probably done for every react component provided.

Do you find this too complex to be provided OOTB? I can work on a pull request in case (TypeScript is not my daily work, but should be simple enough).

**Comment by keul** [comment]
@PaulLeCam: any feedback on this?

**Comment by keul** [comment]
I found an alternative way that's requires less changes.

I tried fixing this need by simply relying on class inheritance, so just overriding the `createLeafletElement` method.:

```javascript

import { LayersControl as BaseLayersControl } from 'react-leaflet';

class LayersControl extends BaseLayersControl {
  createLeafletElement(props) {
    // my stuff
  }
}
```

However this is not working because the exported structure from the LayersControl module is the *decorated* version of `LayersControl`:

https://github.com/PaulLeCam/react-leaflet/blob/b8af25513f975617d3c1a9b584711c8c5ae43651/src/LayersControl.js#L193-L198

But with a very simple change this can work. It just need to exports also the non-decorated ones, putting an `export` keyword here:

https://github.com/PaulLeCam/react-leaflet/blob/b8af25513f975617d3c1a9b584711c8c5ae43651/src/LayersControl.js#L117

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.

**Comment by ZakRabe** [comment]
If you're publishing the package, why cant people extend your implementation of the LayersControl as @keul proposed?
