### ISSUE TITLE
Feature Request: WebGL support

### ISSUE THREAD

**Issue by Fiorello** [PaulLeCam/react-leaflet#573]
Hi,
it would be great if this component supported [leaflet plugin for webGL](https://gitlab.com/IvanSanchez/Leaflet.TileLayer.GL).

There is already a way to use webGL?

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.

**Comment by corydambach** [comment]
> Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.

that link is no longer valid, i tried to search for it but couldn't find it
