### ISSUE TITLE
Examples do not work in react 16.8.4

### ISSUE THREAD

**Issue by sknutsonsf** [PaulLeCam/react-leaflet#575]
## Bug report in v2,2,1

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [ x] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [ x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [x ] The issue has not already been reported.
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

I expect clone the project to be able to run the examples

### Actual behavior

The examples do not run.  It appears the example/webpack.config.js uses "webpack-server' that no longer works.

### Steps to reproduce

Clone the master branch to local disk

npm install 

npm run examples

When I open the browser for the port, I get a message "Upgrade needed".  This is because webpack-serve is deprecated and does not work.

**Comment by curiousPup** [comment]
+1

**Comment by PaulLeCam** [comment]
Thanks for reporting this, it should be fixed now.
