### ISSUE TITLE
How do you work with new react Context API with several map instances?

### ISSUE THREAD

**Issue by sayeko** [PaulLeCam/react-leaflet#578]
How do you work with new react Context API with several map instances?

**Comment by PaulLeCam** [comment]
Each `<Map>` component provides its own context.

**Comment by matth-c3** [comment]
Hello @PaulLeCam , 

Would it be possible to clarify please ? 

if in my app.js I have the following : 

```
import MapBase from './MapBase'

const MyComponent = () => {
    const [ lat, setLat ] = useState('xx')
    const [ lng, setLng ] = useState('yy')
    ...
    ...
  return (
   ....
    <MapBase lat={lat} lng={lng}/>
   ....
  )
}

export default MyComponent;
```

where `MapBase` is my react-leaflet component returning `<Map...../>`. 

How can I access the context ?  I trying to understand how to use "[Starting with version 2.3, the useLeaflet() hook can also be used to access the LeafletContext object](https://react-leaflet.js.org/docs/en/context.html)"

Thanks by advance.

**Comment by PaulLeCam** [comment]
Only components descendant of the `<Map>` component can access its context, not parent ones. The `useLeaflet()` hook is a consumer of the context.

**Comment by matth-c3** [comment]
Hello @PaulLeCam , 

You mean like the `L.Control` and `L.zoomControl`, etc ?

Thanks for you quick answer.

**Comment by PaulLeCam** [comment]
No, these are Leaflet classes and factories.
The `useLeaflet()` hook is only relevant for creating [custom components](https://react-leaflet.js.org/docs/en/custom-components.html).
