### ISSUE TITLE
Integration with leaflet.pm

### ISSUE THREAD

**Issue by BjoernRave** [PaulLeCam/react-leaflet#580]
Hey, I saw this plugin called [leaflet.pm](https://github.com/codeofsumit/leaflet.pm). Its a great way to create geoJson objects and I was wondering if someone managed to make it work with react-leaflet or with react in general?

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.
