### ISSUE TITLE
How to style map tile layer with custom JSON file?

### ISSUE THREAD

**Issue by keyeypee** [PaulLeCam/react-leaflet#581]
I don't want to use default styling that is coming from TileLayer attribute url. Is there any way to add custom styling using any JSON configuration?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
