### ISSUE TITLE
How to get an initial position

### ISSUE THREAD

**Issue by mbrucher** [PaulLeCam/react-leaflet#583]
## Bug report in v2

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

It seems that we always need an initial position for setting the map and there is no starting callback that can help me retrieving map information (or accessing the leaflet map object directly is not explained).

### Actual behavior

I need to get the browser geolocation callback, which gets me the position and then I can create the map. But there is no event that will help me retrieving information like current bounds, distance between points... without the user first doing something with the map.

I would be great to have an example that works without setting a random location (which I don't want) and then create the map or use callbacks like onLoad to get basic map information for computation.

**Comment by PaulLeCam** [comment]
This is how Leaflet works, you need to provide a position to render the map.
It's up to your application logic to define this position before rendering the map if it's the behavior you want.
