### ISSUE TITLE
Circle works and is correct size but CircleMarker huge and covers the entire map

### ISSUE THREAD

**Issue by r3wt** [PaulLeCam/react-leaflet#584]
I can't figure out what's wrong. when zooming out on the map the CircleMarker just keeps growing.

**Comment by clementallen** [comment]
It's because the circle marker size is measured in pixels so will stay the same size relative to your screen rather than the map

**Comment by r3wt** [comment]
@clementallen well shit. i don't suppose there's any option for me here if i want the marker and popup with my circle but also need to set the radius in meters?

**Comment by clementallen** [comment]
Perhaps something like this might help? https://stackoverflow.com/questions/27545098/leaflet-calculating-meters-per-pixel-at-zoom-level/27546312
