### ISSUE TITLE
ReactLeaflet in DotNetCore

### ISSUE THREAD

**Issue by swimhiking** [PaulLeCam/react-leaflet#585]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [ ] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/gzVmGw).

**Comment by swimhiking** [comment]
Hi jut wondering anyone tried React-Leaflet in .Net Core, basically I just copy the Simplest map code to create an React Component, get an error in library, see attached images,  I also tried several way want to make it work, no lucky. could you help me with this? Thank you very much.


![ReactLeafletInDotNetCoreError](https://user-images.githubusercontent.com/6053471/57498883-d8d6da00-729a-11e9-95c4-34164008c1f1.PNG)

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
If you haven't installed the peer dependencies, it's the most likely cause of your problem.
