### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by mbrucher** [PaulLeCam/react-leaflet#586]
Is there any plan to change the API to remove the deprecated API (like componentDidMount)?
They seem to be flagged in linter as they may remove in React 17 or 18 (or maybe I misread which API is deprecated).

**Comment by PaulLeCam** [comment]
No, there is no plan to make changes based on hypothetical future version changes and linter rules.
If React officially deprecates some APIs that are needed by this library, this would be evaluated accordingly.

**Comment by mbrucher** [comment]
They are officially deprecated and planned for removal in 17.

**Comment by PaulLeCam** [comment]
Any source about this information please?
I see no mention of it in the official React docs and no alpha release for v17.

**Comment by mbrucher** [comment]
For instance : https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

**Comment by clementallen** [comment]
Doesn't seem like `UNSAFE_componentWillUpdate()` or `UNSAFE_componentWillReceiveProps()` is used anywhere in react-leaflet?  Not sure what the issue is here.  The class based approach to creating components is going to stay around for a long time, even with Hooks now in stable release

**Comment by mbrucher** [comment]
That's the new name of the componentWillUpdate method.

**Comment by clementallen** [comment]
Which is not used in this library...

**Comment by mbrucher** [comment]
Which it does: https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapLayer.js#L51

**Comment by clementallen** [comment]
`componentWillUnmount` is not deprecated and isn't planned to be

**Comment by Frikki** [comment]
> `componentWillUnmount` is not deprecated and isn't planned to be

Uhm, yes it is:

> This lifecycle was previously named `componentWillUpdate`. That name will continue to work until version 17.
