### ISSUE TITLE
Map is needlessly updating bounds even if boundsOptions have not changed

### ISSUE THREAD

**Issue by kumikumi** [PaulLeCam/react-leaflet#587]
Map component is sometimes needlessly resetting bounds when boundsOptions prop is present, even though the actual options have not changed.

This is caused by a shallow comparison in updateLeafletElement function in Map.js

https://github.com/PaulLeCam/react-leaflet/blob/734973afc621c660dab4b3f44147e594ec15dd31/src/Map.js#L182

This bug can be fixed by changing it to a deep comparison.

Cheers

**Comment by PaulLeCam** [comment]
This is the expected behavior, it's up to your app to handle memoization or similar behavior as needed.
