### ISSUE TITLE
Problem with bounds and ajax loading

### ISSUE THREAD

**Issue by cekk** [PaulLeCam/react-leaflet#588]
I'm using react-leaflet in some CMS-generated pages and it works smoothly.

I have a simple component that shows some points in the map and i pass that list of points to the map as bounds:

`
<Map bounds={bounds}>
  <MarkersList markers={markers} />
</Map>
`

There is only a use-case where i can't draw the correct map boundaries: when in a page I have a js script where i get the html from another page and insert it into the current page (it's an ajax call with jquery "load" method).

The react app works correctly, i see the list of markers in the map, but boundaries seems not correctly calculated.

My suspect is that with that ajax call, the map can't calculate the map dimension and bounds corrrectly. Do you have any suggestions?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
