### ISSUE TITLE
using react-leaflet offline? 

### ISSUE THREAD

**Issue by bapHyv** [PaulLeCam/react-leaflet#589]
Is it possible to use locally stored tiles with react-leaflet? I've seen couple issues dated from 2 years ago and I'm wondering if react-leaflet now support the local url??

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by Tmfwang** [comment]
I've gotten the leaflet.offline plugin to work with react-leaflet. Posted a guide here:
https://stackoverflow.com/questions/69091797/using-leaflet-offline-with-react/69153168#69153168
