### ISSUE TITLE
Popup contents not appearing when inside a LayerControl.Overlay

### ISSUE THREAD

**Issue by damon02** [PaulLeCam/react-leaflet#590]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [X] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [X] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Layer shows a marker, when clicked on the marker it shows a popup and its contents.

### Actual behavior

Layer indeed shows the marker, but when clicked to activate the popup the window appears but no content is inside of the popup.

### Steps to reproduce

https://codepen.io/anon/pen/JqxwrY

**Comment by PaulLeCam** [comment]
Looks like your `MarkerLayer` component messes things up, when removing it from your example it works as expected: https://codepen.io/PaulLeCam/pen/OYKdEm
