### ISSUE TITLE
flow check error in GeoJSON.js since flow 0.99.0

### ISSUE THREAD

**Issue by cyrildurand** [PaulLeCam/react-leaflet#591]
Since flow 0.99.0 I have error in /lib/GeoJSON.js 

    > flow check --color always

    Error ----------------------------- node_modules/react-leaflet/lib/GeoJSON.js.flow:30:21

    Cannot call this.setStyle with toProps.style bound to options because:
     - property attribution is missing in statics of function type [1] but exists in PathOptions [2].
     - property bubblingMouseEvents is missing in statics of function type [1] but exists in PathOptions [2].
     - property className is missing in statics of function type [1] but exists in PathOptions [2].
     - property color is missing in statics of function type [1] but exists in PathOptions [2].
     - property dashArray is missing in statics of function type [1] but exists in PathOptions [2].
     - property dashOffset is missing in statics of function type [1] but exists in PathOptions [2].
     - property fill is missing in statics of function type [1] but exists in PathOptions [2].
     - property fillColor is missing in statics of function type [1] but exists in PathOptions [2].
     - property fillOpacity is missing in statics of function type [1] but exists in PathOptions [2].
     - property fillRule is missing in statics of function type [1] but exists in PathOptions [2].
     - property interactive is missing in statics of function type [1] but exists in PathOptions [2].
     - property lineCap is missing in statics of function type [1] but exists in PathOptions [2].
     - property lineJoin is missing in statics of function type [1] but exists in PathOptions [2].
     - property opacity is missing in statics of function type [1] but exists in PathOptions [2].
     - property pane is missing in statics of function type [1] but exists in PathOptions [2].
     - property renderer is missing in statics of function type [1] but exists in PathOptions [2].
     - property stroke is missing in statics of function type [1] but exists in PathOptions [2].
     - property weight is missing in statics of function type [1] but exists in PathOptions [2].

         node_modules/react-leaflet/lib/GeoJSON.js.flow
     [1] 17|   style?: (feature: GeoJSONdata) => Object,
           :
         27|
         28|   updateLeafletElement(fromProps: Props, toProps: Props) {
         29|     if (isFunction(toProps.style)) {
         30|       this.setStyle(toProps.style);
         31|     } else {
         32|       this.setStyleIfChanged(fromProps, toProps);
         33|     }

         node_modules/react-leaflet/lib/Path.js.flow
     [2] 56|   setStyle(options: PathOptions = {}) {

If I rollback flow to 0.98.1 the error disappear. 

Based on the [flow changelog](https://github.com/facebook/flow/blob/master/Changelog.md) this new feature can explain the error

> - The statics of function types used to be any but are now typed as an empty object.

I can reproduce the issue by forking this repo, update `flow-bin` to `0.99.0` and run `npm run flow`

**Comment by PaulLeCam** [comment]
Thanks for reporting this, it should be fixed in v2.4.0.

**Comment by achepukov** [comment]
Faced same issue, confirmed that upgrade to v2.4.0 fix it. Thanks @PaulLeCam!

**Comment by cyrildurand** [comment]
I confirmed that v2.4.0 fix the issue
