### ISSUE TITLE
State value change on LayersControl.Overlay

### ISSUE THREAD

**Issue by utkarsh447** [PaulLeCam/react-leaflet#597]
Hi, This issue is on asking information.
In [LayersControl.Overlay](https://react-leaflet.js.org/docs/en/components.html#layerscontrol) Documentation, 
At the usage of this snippet,
```
<LayersControl.Overlay name="Marker with popup">
    <Marker position={[51.51, -0.06]}>
      <Popup>
        <span>
          A pretty CSS3 popup. <br /> Easily customizable.
        </span>
      </Popup>
    </Marker>
  </LayersControl.Overlay>
```
This snippet generates the checkbox in `LayersControl` stackbox with name `Marker with popup`
On ticking the `Marker with popup` checkbox, it pops out the `marker` in the given position.

Here, I want to update a `boolean` in `state` on toggling the value of checkbox.
On removing the `Marker` code inside the snippet and adding a state change condition removes the checkbox from stackbox.

So, can you please tell how to place such condition inside this `Overlay` component without placing any marker or anything?

**Comment by utkarsh447** [comment]
Reply?

**Comment by utkarsh447** [comment]
Posted in [stackoverflow](https://stackoverflow.com/questions/56730623/variable-of-state-update-on-layerscontrol-overlay-checkbox-toggle)

**Comment by jeetdas** [comment]
Haven't tested this but I've done something like this before

```
<LayersControl.Overlay name="Marker with popup" checked>
    <Marker position={[51.51, -0.06]}>
      <Popup>
        <span>
          A pretty CSS3 popup. <br /> Easily customizable.
        </span>
      </Popup>
    </Marker>
  </LayersControl.Overlay>
```

I'm assuming you can swap that `checked` for `{this.state.isChecked}`

**Comment by utkarsh447** [comment]
Sorry, No, It didn't work, Instead it allotted the value of `{this.state.isChecked}` to the `checked`. 
What I require is feedback on click of `checked` checkbox.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by frafra** [comment]
> Sorry, No, It didn't work, Instead it allotted the value of `{this.state.isChecked}` to the `checked`. What I require is feedback on click of `checked` checkbox.

https://github.com/PaulLeCam/react-leaflet/issues/597
