### ISSUE TITLE
Defer requiring leaflet until inside componentDidMount

### ISSUE THREAD

**Issue by AndrewIngram** [PaulLeCam/react-leaflet#6]
I want to to try out this library, but one of my requirements is server-side rendering. This means that leaflet probably shouldn't be imported until componentDidMount is called, at which point the presence of a DOM is guaranteed.

Obviously I can't do server-side rendering of the map itself, but it should be possible to leave an empty container ready to be initialised on the client.

**Comment by nym** [comment]
I am also having this issue, trying to find a way around it.
