### ISSUE TITLE
`_updating` variable ignored when Leaflet centers popups

### ISSUE THREAD

**Issue by Empty2k12** [PaulLeCam/react-leaflet#600]
## Bug report in v2

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

The `_updating` variable is supposed to prevent needless state updates until the state stops changing. This works in most of the cases, however, we have identified an issue with Leaflet centering dialogs dialogs which circumvents this check.

https://github.com/PaulLeCam/react-leaflet/blob/164756820a60ccc136ffbd08ca1f9c5c609060de/src/Map.js#L294

When there is a marker that has a popup with large content or big amounts of text, Leaflet will try to center the popup inside the browser window, which would be clipping out of the window otherwise. This process does not set the `_updating` variable, which causes multiple state updates.

### Actual behavior

The popup scrolls into view, then the `onViewportChanged` callback is invocated.

### Steps to reproduce

1. Open the following pen: https://codepen.io/anon/pen/Zdmvby
2. Open developer console and follow instructions printed in Developer console.

**Comment by Empty2k12** [comment]
Our current workaround consists of rate limiting how often a `onViewportChanged` can call `setState`, but it would be nice if that would not be necessary.

**Comment by PaulLeCam** [comment]
The `_updating` flag is only meant to prevent updates when applying the props change, not for side-effects like this that are handled by Leaflet, so debouncing according to your apps logic is the best way to handle it.
