### ISSUE TITLE
Circle editable in not working

### ISSUE THREAD

**Issue by oshin23** [PaulLeCam/react-leaflet#601]
## Bug report in v2

Reactjs: 16.5.1
React-leaflet: 1.8.2
React-leaflet-draw: 0.18.0

### Expected behavior
When I use editable then circle should be editable.

### Actual behavior
When I use editable then page going black in my laptop. it's working fine with other laptop which have same npm version(v6.4.1) but in my system it throws below error.

![Screenshot 2019-07-10 at 12 07 15 PM](https://user-images.githubusercontent.com/43804079/61046644-48805700-a3fb-11e9-976f-df481674147f.png)

### Steps to reproduce

I use this circle editable code 
```
      <FeatureGroup>
        <EditControl>
     <Circle
            key={editFeatureGroup ? "circle1" : "circle2"}
            center={circleCoordinate}
            radius={geofenceRadius}
            editable
          />
  </FeatureGroup>
        </EditControl>
```
Macbook air OS version: 10.14.5

**Comment by hugobarragon** [comment]
Hello can you provide a link to check it out?
btw you have component the tags exchanged :  
```
<FeatureGroup>
        <EditControl>
            <Circle
            key={editFeatureGroup ? "circle1" : "circle2"}
            center={circleCoordinate}
            radius={geofenceRadius}
            editable
          />
        </EditControl> {/*  here */
</FeatureGroup>
```
