### ISSUE TITLE
Render order of CircleMarkers over Circle with large radius

### ISSUE THREAD

**Issue by ksdelacruz** [PaulLeCam/react-leaflet#602]
Hello. I can't find a solution to "send to back" a Circle component to make my smaller CircleMarkers  on top of it and enable their popups. Changing the order on how they are rendering on React doesn't work and I can't find any docs for ordering paths. Any help would be very help. Thanks!

**Comment by hugobarragon** [comment]
hello can you provide on codesandbox a url to check the problem? 
for me ordering the components its working just fine (Circle first and then CircleMarker), i can click the circle markers and open the popups jsut fine
check here : [![Edit react-leaflet-circle-marker](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-leaflet-1ifx3?fontsize=14)

**Comment by ksdelacruz** [comment]
@hugobarragon Hello. Thanks for answering. I created a sandbox using my code (tho the data is not dynamic) and yes, ordering components work. With that, I actually think the problem is handling and rendering dynamic data. As you can see, variable <eqEvents> is rendered first in order but it is has no data until an ajax request is finished in my original code, therefore <sites> are rendered first in the layer. Furthermore, <eqEvents> value changes depending on some user input. This is just my theory but it seems <sites> are not re-rendered because there are no changes in them. If my theory is correct, maybe the solution might be to force re-render the layer but I don't know how. I've read clearing the layer using <clearLayers()> force re-render the map but that is available on the original Leaflet library and don't know how to call such function on<react-leaflet>.

**Comment by PaulLeCam** [comment]
You can force re-rendering a layer by setting a new `key` value to it.
