### ISSUE TITLE
Customize Zoom Button aria-label ?

### ISSUE THREAD

**Issue by alexlabrioche** [PaulLeCam/react-leaflet#603]
Hello, 

I’d like to customize the aria-label of the ZoomIn/ZoomOut button, I know it’s possible with LeafLeft in Control, Zoom passing the options zoomInTitle, zoomOutTitle. 
Is that possible with React Leaflet ? i don’t find in the doc or online examples. 

Regards

**Comment by hugobarragon** [comment]
hi there, on react-leaflet you have a component called ZoomControl, 
[react-leaflet.](https://react-leaflet.js.org/docs/en/components#zoomcontrol)
as you can check here [ZoomControl](https://github.com/PaulLeCam/react-leaflet/blob/master/src/ZoomControl.js) the component supports the following props:
```  
zoomInText?: string,  
zoomInTitle?: string,  
zoomOutText?: string,  
zoomOutTitle?: string,  
```
and any prop you pass will be passed to `Control.Zoom(props)`, i will update this answer with a working example
