### ISSUE TITLE
MouseEvent.mozPressure is deprecated

### ISSUE THREAD

**Issue by rfdc** [PaulLeCam/react-leaflet#604]
After using onEachFeature at GeoJSON as following:
`
onEachFeature = (component, feature, layer) => {
      this.props.saveLayers(layer);
      layer.on({
        mouseover: this.mouseOverOnSuburb,
        click: this.clickedOnSuburb
      });
   }`

I get the following warning message:
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.

Using:
"react": "^16.6.3",
"react-leaflet": "^2.4.0",
"leaflet": "^1.5.1",

Not sure if it is due to react-leaflet or leaflet.

**Comment by Matthias-Hermsdorf** [comment]
I can confirm this bug but without react.
The devs over at tinymce had the same Problem and got it solved.
https://github.com/tinymce/tinymce/issues/5083#issuecomment-525649255

**Comment by PaulLeCam** [comment]
If this is caused by Leaflet please open an issue in the relevant repository.
I don't think there is any specific logic in this library that would affect this behavior so I won't spend time investigating it, please open a PR with a fix if there is some change that should be applied here.
