### ISSUE TITLE
Missing GeoJSON examples

### ISSUE THREAD

**Issue by kaitlynbrown** [PaulLeCam/react-leaflet#606]
There don't appear to be any examples for GeoJSON. The following would be extremely helpful:

- An example of how to use custom icons with GeoJSON
- An example of how to use Popups with GeoJSON

The first, I haven't been able to find any documentation or examples for anywhere.
The second, there seem to be a couple of issues in this repo with incomplete examples, but it isn't clear how to define the contents of the Popup

**Comment by hackleman** [comment]
I happen to have a working example for the second one.  

I’ve never contributed to an open source project before , hopefully this could be a good start!

**Comment by roata** [comment]
@hackleman, can you post your examples? I am dealing with the same thing now, it would surely be beneficial to have something to look at.

**Comment by Valerz** [comment]
It's all provided in the leaflet js website. 

I don't think this is an actual issue with the repository and this ticket should be closed.
