### ISSUE TITLE
Rectangle doesn't update Path options

### ISSUE THREAD

**Issue by blakestone95** [PaulLeCam/react-leaflet#609]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x ] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [ x ] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [ x ] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [ x ] The issue has not already been reported.
- [ x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

When inherited Path options are changed on a Rectangle component, the component should update.

### Actual behavior

Rectangle only updates its bounds.  

Looking at the source, it looks like `super.setStyleIfChanged` is needed instead of `this.setStyleIfChanged`.

### Steps to reproduce

When you click on the rectangle, it changes position, but it does not turn red because it does not react to the change in `className`.

https://codepen.io/blakestone/pen/PMeNaJ

**Comment by blakestone95** [comment]
I copied the source into my project and changed `this.setStyleIfChanged` to `super.setStyleIfChanged` and I can trace the functions being called correctly, but the rectangle element's `class` on the DOM still isn't changing.

**Comment by blakestone95** [comment]
For anyone else who runs into this, you can use `key` to force React to unmount and remount the component until this is fixed.

**Comment by hugobarragon** [comment]
hi there, instead of using the class name to paint the rectangle use the prop `color` i have made an example to you try:
[![Edit react-leaflet-retangle](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-leaflet-y6tr4?fontsize=14)

As you can see on source code of the rectangle:
```
return new LeafletRectangle(props.bounds, this.getOptions(props))
```
any prop will be passed to the LeafletRectangle original so, its the same as doing this:
Any porp implemented on original leaflet its supported [leaflet rectangle](https://leafletjs.com/reference-1.5.0.html#rectangle)
```
L.rectangle(bounds, {color: "#ff7800", weight: 1})
```
![image](https://user-images.githubusercontent.com/35630927/63542543-843d2f00-c518-11e9-9fdf-d7a8b0163894.png)

**Comment by blakestone95** [comment]
I appreciate the suggestion, but I'm not just talking about color.  That is a symptom, not the underlying problem.

**Comment by hugobarragon** [comment]
> I appreciate the suggestion, but I'm not just talking about color. That is a symptom, not the underlying problem.

me neither as leaflet docs say, the classname is only used on render maybe leaflet does not update
https://leafletjs.com/reference-1.5.0.html#rectangle-classname
everything on the react-leaflet code looks ok to me: (it calls the setStyle if element was updated)
```javascript
setStyle(options: PathOptions = {}) {
    this.leafletElement.setStyle(options)
  }

```

related to:https://github.com/leaflet/leaflet/issues/2662
