### ISSUE TITLE
Map is moved to some extent, and gets centred on changing screen size.

### ISSUE THREAD

**Issue by sahil-bansal-sb** [PaulLeCam/react-leaflet#613]
## Need Help in centering the Map

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Map to be centered as shown in examples

### Actual behavior

The map is moved to some extent, and when screen size gets changed, it then comes to the center

### Steps to reproduce

```javascript
import React, {Component} from 'react';
import {Map, TileLayer, Marker, Popup} from 'react-leaflet';
import {Icon} from 'leaflet';

Icon.Default.imagePath =
  '//cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.4/images/'

class MapComponentDash extends Component {
    constructor(props){
        super(props)
        this.state = {
            pos: [51.505, -0.09],
            zoom: 13,
        }

    }
    render() {
        return (
            <Map center={this.state.pos} zoom={this.state.zoom} >
                <TileLayer 
                    url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                />
                <Marker position={this.state.pos}>
                    <Popup>
                        A pretty CSS3 popup. <br /> Easily customizable.
                    </Popup>
                </Marker>
            </Map>
        )
    }
}

export default MapComponentDash;
```
just rendered this component in a container and then render that container in a route in react application,

**Comment by hugobarragon** [comment]
hi, i am sorry i could not understand you problem, i will have all the pleasure in help and check if its a bug or not
please provide a working example on [codesandbox](https://codesandbox.io) there you can add dependencies such as router

**Comment by sahil-bansal-sb** [comment]
I tried but was not able to replicate the issue,
i studied the examples and i found that i didn't used hot reoading,
so it loads the map, at some random center and when i resize the window, it then gets centered properly

**Comment by sahil-bansal-sb** [comment]
I believe that's the lack of using hot reloading, about which I don't know much.

**Comment by WaldemarEnns** [comment]
For me, this issue also appears, for the same setup.
Does anyone has an idea how to fix this?
