### ISSUE TITLE
Bad render for tile position

### ISSUE THREAD

**Issue by josesaranda** [PaulLeCam/react-leaflet#614]
Demo: https://recordit.co/9gGY06So1X

**Steps to reproduce**
Copy paste the example in https://leafletjs.com/

**Expected behavior**
See map correctly

**Current behavior**
Map works bad

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): 76.0.3809.87 (Official Build) (64-bit)
- OS/Platform (with version): MacOS Mojave 10.14.6

**Comment by QuentinChevance** [comment]
Try to add `<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" />` to your index.html file, I had the same issue and it worked for me.

**Comment by josesaranda** [comment]
Thanks. That was the solution. I forgot to add the stylesheet.

**Comment by cinder92** [comment]
@QuentinChevance this should come with npm install

**Comment by edowado** [comment]
same issue with npm install

**Comment by edowado** [comment]
Can we re-open this?
