### ISSUE TITLE
leaflet.css

### ISSUE THREAD

**Issue by Raju10100** [PaulLeCam/react-leaflet#619]
Installed both react-leaflet and it's dependency leaflet.

In the index.html file I gave references for both leaflet.css and leaflet.js from ..node_modules/leaflet/dist/

When I load maps page It was loaded broken into several pieces.
![image](https://user-images.githubusercontent.com/33671734/65468733-9ddcd980-de2a-11e9-9493-576cd485a8f6.png)

Then I replaced leaflet.css using a CDN:       
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />

It works fine.
![image](https://user-images.githubusercontent.com/33671734/65468775-c4027980-de2a-11e9-88fc-e269565751d5.png)

Looks like there was a problem with compiled leaflet.css in dist folder.

Versions:
Leaflet: 1.5.1
ReactLeaflet: 2.4.0

**Comment by qas612820704** [comment]
I got the same problem, and it's solved as you said.

Thanks!

```html
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""
/>
```
