### ISSUE TITLE
Updating marker updates popup

### ISSUE THREAD

**Issue by JLTe-ch** [PaulLeCam/react-leaflet#621]
## Bug report in v2

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [x] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

I am looking at having the Popup not auto close when the marker is updated.

### Actual behavior

When the marker is update the Popup closes.

### Steps to reproduce

I have markers that are colored based on events that come in.  When the event comes in, I would like the popup that is open to stay open and update the popup marker.  Is there any guidance you can give on this situation?

Thank you!

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
