### ISSUE TITLE
How can I upload .kml file / shp file?

### ISSUE THREAD

**Issue by esersasmaz** [PaulLeCam/react-leaflet#631]
I want to upload kml file and shp file to react-leaflet. How can I do that?

I would appreciate it if you have sample code.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
