### ISSUE TITLE
Send custom header in wms requests

### ISSUE THREAD

**Issue by hadiranjbar25** [PaulLeCam/react-leaflet#632]
It would be great to have a feature to send custom headers (jwt token) with wms tile requests.
There is a plugin to have this when using leaflet:
leaflet-wms-header
May we have this feature in react-leaflet too?

**Comment by PaulLeCam** [comment]
Hi, please refer to the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.

**Comment by matheust3** [comment]
@PaulLeCam This page is broken

**Comment by Mathijs003** [comment]
Indeed, page is broken, any solution somewhere?
