### ISSUE TITLE
FeatureGroup fails when passing in react-style shapes: TypeError: layer.onAdd is not a function

### ISSUE THREAD

**Issue by marcello3d** [PaulLeCam/react-leaflet#64]
I realize FeatureGroups aren't documented/tested yet, but I've tested them and hitting an error: `TypeError: layer.onAdd is not a function`.

I made a test case here: https://github.com/PaulLeCam/react-leaflet/compare/master...marcello3d:broken-featuregroup-example

Key bit is:
```html
      <FeatureGroup layers={[
          <Circle center={center} radius={200} fillColor='blue' />,
          <CircleMarker center={[51.51, -0.12]} radius={20} color='red'>
            <Popup>
              <span>Popup in CircleMarker</span>
            </Popup>
          </CircleMarker>,
          <Polyline positions={polyline} color='lime' />
      ]}/> 
```

Although it seems like it'd be better if the API were:
```html
      <FeatureGroup>
          <Circle center={center} radius={200} fillColor='blue' />,
          <CircleMarker center={[51.51, -0.12]} radius={20} color='red'>
            <Popup>
              <span>Popup in CircleMarker</span>
            </Popup>
          </CircleMarker>,
          <Polyline positions={polyline} color='lime' />
      </FeatureGroup>
```

I haven't quite wrapped my head around the voodoo this project is doing to make a PR. :-)

**Comment by PaulLeCam** [comment]
Hi,

The `layers` value is simply passed to the `L.featureGroup` function, so it's expecting Leaflet classes, not React components.

The API you're suggesting for it would be much better indeed, but I don't have time to implement it with all the use/test cases, if you feel like it you're more than welcome to send a PR :+1:
