### ISSUE TITLE
Overzealous shouldUpdateCenter check

### ISSUE THREAD

**Issue by zwade** [PaulLeCam/react-leaflet#641]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

I had implemented a basic "go to current location" using `react-leaflet`. It used the `geolocation` api to get the user's current location and then used it to update the react component's state with the new center. When it is clicked, it is expected that the map will recenter to the current user's location.

### Actual behavior

Instead, it recenters the map for the first time it is clicked, but upon all subsequent clicks the action is ignored. This is because of the check performed [here](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L162). The `shouldUpdateCenter` check returns false because the center has not changed between subsequent rerenders. However, this behaviour is suspect because the value stored in the center props is not in accordance with the actual center stored in the map.

The standard way to handle this in react land would be to ensure that the prop's center always corresponds with the actual map's center, but looking through the examples, I didn't see any good way to do this. It seems like either I'm missing a way to ensure correspondence between the map's internal center state and it's props, or there is no current mechanism for repeatedly returning to the same location.

### Steps to reproduce

Have a map with a user action that sets the center to a fixed location. Multiple interactions with this will not recenter the map.

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/gzVmGw).

Example shown here:  [https://codepen.io/zwade/pen/ZEEPgML?editors=1111#anon-login](https://codepen.io/zwade/pen/ZEEPgML?editors=1111#anon-login)

We would expect the button to recenter us because it triggers a rerender, but instead nothing happens

I was able to work around this in my code by doing: 

```tsx
() => {
    let [focus, setFocus] = React.useState({ longLat: [0, 0] as [number, number], zoom: 13 });
    let mapRef = React.useRef(null);
    let onSearch = (f: { longLat: [number, number], zoom: number }) => {
		setFocus(f);
		if (mapRef.current) {
			let map = mapRef.current as any;
			map.leafletElement.setView([f.longLat[1], f.longLat[0]], f.zoom);
		}
	};

    return (
        <>
            <CurrentLocationButton onClick={onSearch}/>
            <Map
                ref={mapRef}
                center={[focus.longLat[1], focus.longLat[0]]}
                zoom={focus.zoom}
            >
            { /* map code */ }
            </Map>
        </>
    );
}
```

But this seems suboptimal

**Comment by PaulLeCam** [comment]
I agree this is a possibly unexpected behavior in your case, it's mostly the case for legacy reasons, as the first versions of this library behaved as expected (re-center when changed), but various issues were opened by people not understanding this and wanting to prevent this behavior, so it became the default.
This would be a breaking change to revert to the original behavior now so it's not going to happen in a v2.x but should be the case in v3. In the meantime, you could use the `viewport` prop as described in the [`Map` component docs](https://react-leaflet.js.org/docs/en/components#map), it contains an example that should match the behavior you need.
