### ISSUE TITLE
Offline map using react-leaflet

### ISSUE THREAD

**Issue by SergeyMelnyk** [PaulLeCam/react-leaflet#642]
Can I create offline map using react-leaflet, also i have exported .osm file with my area, maybe can i use she?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
