### ISSUE TITLE
How can I mock react-leaflet module on jest?

### ISSUE THREAD

**Issue by iamgbayer** [PaulLeCam/react-leaflet#644]
I'm trying to test a component that uses [GeoJSON](https://react-leaflet.js.org/docs/en/components#geojson) and running the tests, jest reports the following error because I'm using SVG elements on the `pointToLayer` markers.

```
Error: Uncaught [TypeError: Cannot read property 'addLayer' of undefined]
```

I see react-leaflet tests are using a mock of the leaflet, but I didn't understand if I should mock the react-leaflet or leaflet.

**Comment by PaulLeCam** [comment]
Really depends on your needs, it might be simpler to mock React-Leaflet itself if you don't use any Leaflet API directly.
