### ISSUE TITLE
Unable to get property 'MapControl' of undefined or null reference

### ISSUE THREAD

**Issue by Charmatzis** [PaulLeCam/react-leaflet#645]
Hello, I am trying to use React-Leaflet with GarsbyJS. It seems that eventhough there are few issues it works.

But, I am also I am trying to develop few new react-leaflet components using MapControl.

I am writing a simple MapControl which uses leaflet-geosearch

```
var provider = new EsriProvider();
class Search extends MapControl {

  createLeafletElement() {
      
    return GeoSearchControl({
      provider:  provider,
      style: 'bar',
      showMarker: true,
      showPopup: false,
      autoClose: true,
      retainZoomLevel: false,
      animateZoom: true,
      keepResult: false,
      searchLabel: 'search'
    });
  }
}
export default withLeaflet(Search);
```

```
return (
            <Map
                className="map-surface"
                center={[39, -104]}
                zoom={5}
                minZoom={2}
                ref="map"
            >
                <Search />

                <TileLayer
            attribution="&amp;copy <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
            </Map>
        );
```

when I am debugging the application everything works great, but when I am trying to bundle it and going to production using `gatsby build` I get everytime this error

```
Unable to get property 'MapControl' of undefined or null reference
```

It is something that has to do with react-leaflet and MapControl class, or I am missing smthing?

Thx, for your time and for the great library.

Christos

**Comment by r3mi** [comment]
Hello,
I have a similar issue, using the same setting.
I am using React-Leaflet within GatsbyJS (with the help of https://github.com/dweirich/gatsby-plugin-react-leaflet ).
I am extending GridLayer (`class MyGridLayer extends GridLayer ...`). Everything is fine in development mode (`gatsby develop`). However, when I try to build (`gatsby build`), I get:
```
  WebpackError: TypeError: Class extends value undefined is not a constructor or null
```
on `GridLayer`.

Thanks,

**Comment by r3mi** [comment]
After some investigation, I found the problem in https://github.com/dweirich/gatsby-plugin-react-leaflet/blob/master/src/gatsby-node.js
It is excluding `leaflet` from the SSR build (which is fine, because it relies on `window`). But is also exclude `react-leaftlet`, which cause the problems above. 
By patching `gatsby-plugin-react-leaflet` to only exclude `leaftlet`, I managed to build successfully. 
I don't know is there was a real reason to exclude `react-leaflet` ? I will raise an issue there.

**Comment by Charmatzis** [comment]
@r3mi great feedback.
My hack is to use react hooks and `useLeaflet()` where there is no need to extend the `MapControl` class.

Here is an example
https://github.com/TA-Geoforce/react-leaflet-geosearch/blob/master/src/GeoSearchControl.js
