### ISSUE TITLE
Crash empty Polyline when updating color

### ISSUE THREAD

**Issue by r3mi** [PaulLeCam/react-leaflet#650]
## Bug report

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Change `color` on a `<Polyline>` component, with empty `positions` (i.e. `[]`), and a `weight` set.
Should not crash (and nothing should be displayed as polyline is empty).

### Actual behavior

crash application

### Steps to reproduce

https://codepen.io/r3mix/pen/ZEYJxGq

click on `CLICK ME` button to change the color and crash the map.

Note that it does not crash if the `weight` attribute is not set.

**Comment by PaulLeCam** [comment]
Providing an empty array of `positions` is not supported, it's up to your application logic.

**Comment by Nate-Wessel** [comment]
I think the problem here is that empty positions _seem_ to be supported (i.e. don't produce any errors) except under pretty specific conditions. I spent quite a bit of time trying to figure out what was wrong with the way I was setting the weight, since that was the only thing that changed to produce the crash.
