### ISSUE TITLE
No way to trigger an 'onFocus' handler when focusing on a marker.

### ISSUE THREAD

**Issue by rickymcgeehan** [PaulLeCam/react-leaflet#651]
I would like to add an 'onFocus' handler to a marker which will trigger when the marker comes into focus. I've tried adding a property in the same fashion as 'onClick' but this doesn't work.

My application uses the 'tab' key to alter which marker is selected. As such I need to know whether a marker is currently in-focus and/or be able to attach onFocus and OnBlur handlers to each marker.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
