### ISSUE TITLE
TileLayer allows indefinite zooming if maxZoom not specified

### ISSUE THREAD

**Issue by AlliterativeAlice** [PaulLeCam/react-leaflet#654]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

When no maxZoom is passed as a prop for a TileLayer, the Leaflet default of 18 is used.

### Actual behavior

When no maxZoom is passed as a prop for a TileLayer, the map allows the user to zoom in indefinitely. When using OSM tiles, this causes the map to become blank when zoom level 20 or higher is reached.

### Steps to reproduce

Can be observed on the default codepen: https://codepen.io/PaulLeCam/pen/gzVmGw

1. Open the codepen.
2. Zoom in until you reach zoom level 20 or higher.
3. The map is unable to load tiles because OSM does not provide tiles at zoom level 20 or higher. Requests for tiles result in 404 responses.

It appears this bug was introduced in version 2.0.1

**Comment by AlliterativeAlice** [comment]
Actually, this happens even if a maxZoom is passed as a prop to the tileLayer. Only specifying a maxZoom prop for the map prevents it.

**Comment by PaulLeCam** [comment]
Should be fixed in [v2.6.2](https://github.com/PaulLeCam/react-leaflet/releases/tag/v2.6.2), please try it out!
