### ISSUE TITLE
iOS safari: Navigating away from a leaflet map and coming back, will disable panning.

### ISSUE THREAD

**Issue by Metroxe** [PaulLeCam/react-leaflet#657]
## Bug report

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior
While using safari on iOS. Visiting a website with react-leaflet, and then navigating to another url after an <a> tag has been pressed, then coming back (via the safari back button) will allow a user to use the map with panning.

### Actual behavior
While using safari on iOS. Visiting a website with react-leaflet, and then navigating to a different website after an <a> tag has been pressed, then coming back (via the safari back button) will not allow the user to pan.

### Steps to reproduce

1. Open Safari on iOS _(this can be done on the Mac iPhone Simulator or hardware. Safari desktop will not produce the bug)_
2. Navigate to the codepen example [https://codepen.io/PaulLeCam/pen/gzVmGw](https://codepen.io/PaulLeCam/pen/gzVmGw)
3. Press the <a> tag for open street map link _(can be any href though, just this is the most realistic example)_
3. Navigate to any URL _(I use [https://www.google.ca/](https://www.google.ca/))_ 
4. Press the back button on Safari after it loads
5. Panning will now be disabled on the map

I made a video showing this, with a second example included
[https://www.dropbox.com/s/6ypg83tmxetfzw9/Screen%20Recording%202020-01-31%20at%209.20.45%20PM.mov?dl=0](https://www.dropbox.com/s/6ypg83tmxetfzw9/Screen%20Recording%202020-01-31%20at%209.20.45%20PM.mov?dl=0) _- I had mentioned the number of API calls affecting this, I don't believe it is a quantity issue, but something to do with simply trying to navigate away. I am unable to replicate this on any other browser besides safari on iOS._

**Comment by PaulLeCam** [comment]
There is no logic specific to iOS Safari or any other mobile browser in this library so it's most likely an issue coming from Leaflet or Safari itself, so you should use their bug tracker rather than this one.
