### ISSUE TITLE
FeatureGroup with actual FeatureGroup override

### ISSUE THREAD

**Issue by colbyfayock** [PaulLeCam/react-leaflet#659]
I have a use case where I'm trying to utilize a FeatureGroup between the ones created using the component FeatureGroup with Draw functions (wrapping it is a requirement) but also where I'm dynamically adding layers to the group after a search function.

My issue is - I'm currently utilizing a `ref` to achieve this, where I forward it to the component, and have access through the lifted component that I can use as I please throughout the tree, but I'm running into a case where if I search too soon and try to create the layers to that group, it's not available, as the component with the actual FeatureGroup component isn't rendered yet.

🤯

Some pseudocode to see if this helps:
```
const TopLevel = () => {
  const featureRef = createRef();

  useEffect(() => {
    const { current } = featureRef;
    const { leafletElement } = current;
    leafletElement.addLayer(...);
  }, [])

  return (
    <>
      <Map>
        <MapDraw forwardedRef={featureRef} />
      </Map>
    </>
  )
}

const MapDraw = ({featureRef}) => {
  return (
    <FeatureGroup ref={forwardedRef}>
        <EditControl .../>
    </FeatureGroup>
  )
}
```
That's pnot going to work "as is" but hopefully it illustrates the gist.

 I figured out a solution that creates a new FeatureGroup component, but instead of using a `ref`, I'm overriding the components local `layerGroup` with a prop if it's available, that way I can create the feature group itself from a higher level and use that for my purposes. 

```
import L from 'leaflet';
import { MapLayer, withLeaflet } from 'react-leaflet';

// Recreates react-leaflet's FeatureGroup with the ability to pass in custom FeatureGroup
// via https://github.com/PaulLeCam/react-leaflet/blob/master/src/FeatureGroup.js

class FeatureGroup extends MapLayer {
  createLeafletElement (props) {
    let el = this.props.featureGroup;

    if (!this.props.featureGroup) {
      el = new L.FeatureGroup(this.getOptions(props));
    }

    this.contextValue = {
      ...props.leaflet,
      layerContainer: el,
      popupContainer: el
    };

    return el;
  }
}

export default withLeaflet(FeatureGroup);
```

First of all - I'm wondering if I'm looking at this the wrong way? 

Otherwise, is this something you'd be interested in me adding to the component by default? Maybe it's an issue of `react-leaflet-draw` being tightly coupled with the component, but wondering if this might be useful for other use cases.

**Comment by PaulLeCam** [comment]
Seems like what you're trying to do is create a custom component, you can read about it in the [creating custom components](https://react-leaflet.js.org/docs/en/custom-components.html) section of the documentation.
