### ISSUE TITLE
Support for new Leaflet Version 1?

### ISSUE THREAD

**Issue by afilp** [PaulLeCam/react-leaflet#66]
Hello Paul,

Is react-leaflet 100% compatible with the enhanced new version of leaflet (1.0)? I know it is on beta status, but as it is now the preferred development branch (on 'master') with many new features I cannot resist not to use it:

https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md

P.S. It would be great if there was a branch for extending react-leaflet with the new features of leaflet.

Thanks!

**Comment by PaulLeCam** [comment]
Hello,

No it's not at all made compatible with Leaflet 1.0 beta, and it will probably not be until Leaflet 1.0 is released as stable.
Being in beta means the API can still change and I don't have time to track all the changes upstream to update this lib, I'll probably adapt it once Leaflet 1.0 hits a RC but not before.

Good idea for the new branch, I'll add one in case you or anybody else has the chance to start adapting it.

**Comment by hannesj** [comment]
I'm currently using react-leaflet with the Leaflet beta and haven't seen any issues yet. The only broken things have been due to changed z-indexes in Leaflet's CSS, which doesn't have anything to do with the actual components.

**Comment by netsgnut** [comment]
I am also trying `react-leaflet` 0.7.0 with `Leafet` 1.0.0-beta.1. In the project here there are not much plugins and it seems to work straight out of box.

For anyone interested in testing it out, you may want to point your local `package.json` to my testing branch at `"react-leaflet": "netsgnut/react-leaflet#v0.7.0-with-leaflet-1.0b1"`. I have just only changed `package.json` there; everything else is identical with v0.7.0 release.

**Comment by PatrickKing** [comment]
I just submitted [a PR](https://github.com/PaulLeCam/react-leaflet/pull/117) for Leaflet 1.0, based on some small changes to make Popups work.

React-leaflet seems to just work, but I haven't exhaustively tried all its features.

**Comment by kofronpi** [comment]
Leaflet 1.0.0-rc.1 has been released so its new API should be stable now :+1:

**Comment by tjwebb** [comment]
> Being in beta means the API can still change

That's not what beta means. A new major version number would indicate an incompatible API change. beta just means there will be more bugs than usual.

**Comment by nqbao** [comment]
+1 for Leaflet 1.0 support

**Comment by lkolek** [comment]
+1

**Comment by PaulLeCam** [comment]
+1 noise is completely useless, but pull requests are welcome!

**Comment by ballwood** [comment]
Its working reasonably well with 1.0 for the things we've been using it with. One error I did have was with the zoom control but fixed it by doing this if anyone was interested.

import { ZoomControl } from 'react-leaflet';

export default class FixedZoomControl extends ZoomControl {
  componentWillUnmount() {
    this.leafletElement.remove();
  }
}

**Comment by PaulLeCam** [comment]
[First beta released](https://github.com/PaulLeCam/react-leaflet/releases/tag/v1.0.0-beta.1), you can install it from npm using `npm install react-leaflet@next`.

**Comment by Alappin** [comment]
What is the approximate timeline for the first stable release of this library to support leaflet version 1.x?

**Comment by PaulLeCam** [comment]
No timeline for a stable release, please use the RCs in the meantime if you need Leaflet v1 support.

**Comment by PaulLeCam** [comment]
Now released
