### ISSUE TITLE
How to use SVGOverlay?

### ISSUE THREAD

**Issue by maLikiz** [PaulLeCam/react-leaflet#660]
I tried using the `html-react-parser` to parse svg string from the request. But if look at elements in Chrome Inspector, then two svg elements (svg in svg) are created there, and the zoom map don't work.

I also tried using leaflet without react-leaflet using official documentation, and there were no problems

**Comment by PaulLeCam** [comment]
The `svg` element is created by the `SVGOverlay` component.
You can have a look at the [provided SVG Overlay example](https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/svg-overlay.js).
