### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Oscar-Raygoza** [PaulLeCam/react-leaflet#661]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [X] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [ ] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

#### init map component

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/gzVmGw).

**Comment by MatthewAnstey** [comment]
Looks like there's an issue with the title request to https://{s}.tile.osm.org/{z}/{x}/{y}.png.

It works fine if you change it too

https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

Looks like there have been a few recent changes to open street map DNS. Maybe related, maybe not. 

See working code pen here: 

https://codepen.io/matta/pen/ExjjVjo

**Comment by Oscar-Raygoza** [comment]
Thanks, it worked  @MatthewAnstey
