### ISSUE TITLE
moving marker and leaving behind it a line traced 

### ISSUE THREAD

**Issue by Anoirwork** [PaulLeCam/react-leaflet#663]
Hi there;
Hope everyone doing great in this begin of a week;
So as the title describer the issue i need this maker that moves when i get the Geolocation data from outside api this marker starts moving as i get the data and leaving behind it a line like  in the screen below.
Thanks in advance for you help. Have a nice day. :) Keep smiling.
![iec9g](https://user-images.githubusercontent.com/57225309/74648847-bb666300-517e-11ea-8e5d-628edfd74782.jpg)

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
