### ISSUE TITLE
SVGOverlay is not displayed when zoom is 16 or more

### ISSUE THREAD

**Issue by kamal951** [PaulLeCam/react-leaflet#664]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x ] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [ x ] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [ x ] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ x ] The issue has not already been reported.
- [ x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

See the SVGOverlay when the zoom is 16 or more

### Actual behavior

When we zoom on the map, if the zoom is 16 or more, the SVGOverlay disapear.

### Steps to reproduce

You can see it on [this CodePen](https://codepen.io/kamal95190/pen/yLNMPdq). When you zoom out you see the SVGOverlay, but when the zoom is 16 or more, you can't see it.

**Comment by eric-burel** [comment]
Hijacking your issue with another one on SVGOverlay: it does not fire interactive layer events, you can try it by adding an "onClick" on either the overlay or the rect.

I will probably use an alternative or manually call Leaflet functions to bypass this without using SVGOverlay, I'll let you know.

**Comment by eric-burel** [comment]
Ok I've solved my own issue by adding `interactive: true`, for some reason I never found any doc on it except this commit "https://github.com/Leaflet/Leaflet/commit/4ec26a5b69c3cb9f483be57a95f98c6bda6a9d67"

Your issue seems related to `transform` property, it is wrong when the zoom level increase so your rect is here but in the wrong place because of the CSS.
