### ISSUE TITLE
styling to .leaflet-control-zoom not applied on mobile device.

### ISSUE THREAD

**Issue by laurencefass** [PaulLeCam/react-leaflet#667]
## Bug report

checklist:

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x ] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x ] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x ] The issue has not already been reported.
- [x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

Accessing the site from desktop browser and mobile should have consistent styling. I can changes see on desktop browser but not on mobile.

### Actual behavior

I can apply styling to .leaflet-container but to not to .leaflet-control-zoom.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/gzVmGw).

i've forked your example here (using desktop Chrome latest) and Android phone. i cant see the red border around the zoom control on the mobile display.

https://codepen.io/laurencefass/pen/zYGwqKB

thanks

**Comment by PaulLeCam** [comment]
There is no specific logic in this library regarding mobile devices so it's most likely an issue you should report to Leaflet's bug tracker.
