### ISSUE TITLE
How to change label color for city/country names?

### ISSUE THREAD

**Issue by AdityaAnand1** [PaulLeCam/react-leaflet#669]
![image](https://user-images.githubusercontent.com/13274079/75515476-25ed8d80-5a20-11ea-9b41-2fef4bfeb4c4.png)

**Comment by AdityaAnand1** [comment]
![image](https://user-images.githubusercontent.com/13274079/75515938-4538ea80-5a21-11ea-8ce1-b75dc1cf251e.png)

The text is stuck behind the panes, I'm guessing the answer will solve both of these.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
