### ISSUE TITLE
Polyline - updating properties other than positions does not trigger React reconciliation

### ISSUE THREAD

**Issue by marcinlichwala** [PaulLeCam/react-leaflet#67]
Is there any reason why the code below does not take into account the changes made on properties such as: color, weight, opacity etc?

```javascript
// Polyline.js
componentDidUpdate(prevProps) {
    if (this.props.positions !== prevProps.positions) {
      this.leafletElement.setLatLngs(this.props.positions);
    }
}
```

At the moment the only way to cause the polyline to update is to change 'key' property of the component which is a bit of a hack.

It would be nice to have the remaining properties explicitly included. I can make a proper PR if needed.

Great library, btw! :)

**Comment by luqmaan** [comment]
Another approach is to subclass Polyline and make custom changes in `componentDidUpdate`.

**Comment by marcinlichwala** [comment]
The class hierarchy is already quite deep and this is a feature that probably many library users would benefit from. At the moment it is not very intuitive that only one Polyline property makes the component update - it made me dive deep into the lib code to understand why things aren't working the way I would normally expect them to do. I would like to understand if there is any architectural motivation behind not including these properties in update.

**Comment by PaulLeCam** [comment]
Hi, it's now supported in v0.7, for Polyline and other vector layers extending the added Path class.
