### ISSUE TITLE
How to refresh style prop on GeoJSON component?

### ISSUE THREAD

**Issue by AdityaAnand1** [PaulLeCam/react-leaflet#672]
Depending on where the user is (GPS) I'm highlighting their countries map pane. What I'd like to do is to be able to let the user select another country, which would then be highlighted itself.

```
  function style(feature) {
    return {
      fillColor: getColor(feature.properties.name),
      weight: 1,
      opacity: 1,
      color: 'white',
      dashArray: '3',
      fillOpacity: 0.7
    };
  }
```

So, to do that, I need to somehow tell GeoJSON that "Hey you need to run `style()` for all map panes again". Is there a way to do this?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
