### ISSUE TITLE
TileLayer.maxZoom not working

### ISSUE THREAD

**Issue by codler** [PaulLeCam/react-leaflet#675]
## Bug report

MaxZoom option are not working in TileLayer https://leafletjs.com/reference-1.6.0.html#tilelayer-maxzoom.
react-leaftlet 2.6.1
leaflet 1.6.0

### Expected behavior

Should stop at 8 zoom

### Actual behavior

It continues to zoom

### Steps to reproduce

    <TileLayer maxZoom={8} />

**Comment by codler** [comment]
I did some debugging. and it seems if we remove the whole `getOptions`-method in GridLayer.js maxZoom will work again, but I don't understand why.

**Comment by codler** [comment]
a workaround is to set maxZoom on Map instead. 

    <Map maxZoom={8} />

**Comment by PaulLeCam** [comment]
Should be fixed in [v2.6.2](https://github.com/PaulLeCam/react-leaflet/releases/tag/v2.6.2), please try it out!

**Comment by chaitanya1248** [comment]
FYI, maxZoom prop on <Map /> is breaking the app after v2.6.2 update

**Comment by PaulLeCam** [comment]
👍 should be fixed with v2.6.3
