### ISSUE TITLE
Wrap Marker or allow custom HTML props

### ISSUE THREAD

**Issue by justrealmilk** [PaulLeCam/react-leaflet#676]
Helloooo

I have a map with some animated markers and works great until I can drag the map or similar causing some markers to re-render.

Why do they re-render? Because they made by a function. Why are they made by a function? To inject custom HTML props i.e. `data-attributes`.

I've tried wrapping the markers in JSX Divs but they're unwrapped before the hit the DOM and only the Markers themselves make it. I've tried adding props to Markers but they're not included in the final HTML element that wraps my `L.divIcon`

Some code...

Here's the function that creates the icons, adding in some custom attributes for other business

```js
export const iconForge = (tooltip = {}, classNames = []) => {
  const html = (
    <div className='wrapper'>
      <div className='forge tooltip' data-hash={tooltip.hash} data-playlist={tooltip.playlist} data-table={tooltip.table}>
        <div className='dial' />
        <div className='frame' />
        <div className='logo' />
      </div>
    </div>
  );

  return L.divIcon({
    className: ['icon-marker', 'native'].concat(classNames).join(' '),
    html: ReactDOMServer.renderToString(html)
  });
};
```

Here's the Marker

```js
  const icon = marker.iconForge({ hash: node.activityHash, playlist: node.playlistHash, table: 'ATable' }, []);

  <Marker key={i} position={[offsetY, offsetX]} icon={icon} zIndexOffset='-1000' />;
```

What I want to avoid: declaring every variation before runtime.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
