### ISSUE TITLE
event handlers function onload and onLocationfound are not being loaded [question]

### ISSUE THREAD

**Issue by kyle-sun-asterisk** [PaulLeCam/react-leaflet#680]
I'm trying to get the current user location with the following code:
`const OSMap: React.FC = () => {
  const handleLocationFound = (event) => {
    console.log('test', event.latLng)
  }

  const handleLoad = ()  => {
    console.log('test', event.latLng)
  }

  return (
    <Map
      center={[mapState.lat, mapState.lng]}
      onload={handleLoad}
      onLocationfound={handleLocationFound}
      zoom={mapState.zoom}
    >
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
    </Map>
  )
}
`
handleLocationFound or handleLoad are not being called what am I'm doing wrong?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
