### ISSUE TITLE
checked property 

### ISSUE THREAD

**Issue by pcpatfire** [PaulLeCam/react-leaflet#681]
### Actual behavior

The `checked` property of  `LayersControl.BaseLayer` / `LayersControl.Overlay` doesn't work when set to `false`. 
Actually it works just writing `checked`, without any value. Is it correct?

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.

**Comment by frafra** [comment]
It works by using `checked={false}`.
