### ISSUE TITLE
Popup react-leaflet component inside onEachFeachure function.

### ISSUE THREAD

**Issue by astricus** [PaulLeCam/react-leaflet#682]
I want to use react components inside a leaflet popup for every GeoJSON feature, e.g. to fire a reactstrap `<Modal>` with objects information from features.properties or another component. But `onEachFeachure` function uses leaflet's `bindPopup` function with html instead of react-leaflet `<Popup>` component. So how to be able to use `<Popup>` component inside of `onEachFeachure` function? Thank you!

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by barbalex** [comment]
see here: https://gis.stackexchange.com/a/356513/13491
