### ISSUE TITLE
After updating from 2.6.1 to 2.6.3 I got "TypeError: Cannot read property 'addLayer' of undefined" error

### ISSUE THREAD

**Issue by Kbdq** [PaulLeCam/react-leaflet#683]
All components (leaflet, react, etc) are latest.

Call stack displays:

1. setState([my variables for map content like markers, etc.])

2. [internal react calls]

3. Fall in MapLayer.js:40 at line
    this.layerContainer.addLayer(this.leafletElement);

When I downgrade back to to 2.6.1, everything works fine.

Don't know what else I can add to description. Project is huge enought and I cannot extract minimal code to reproduce.

**Comment by PaulLeCam** [comment]
Please provide a simple example to reproduce the issue, this is not enough information to investigate.

**Comment by Kbdq** [comment]
I think I narrowed down the problem. Look like changes between 2.6.1 and 2.6.3 are incompatible with react-leaflet-google-v2 module (https://github.com/TA-Geoforce/react-leaflet-google-v2)

**Comment by PaulLeCam** [comment]
Thanks for the details.
It seems to be an issue with react-leaflet-google-v2 then, that should be raised in their repository rather than here.

Please feel free to reopen the issue if you can reproduce it with only the components provided by react-leaflet.

**Comment by nrakochy** [comment]
I am seeing the same issue on 2.6.3, except I am using only `react-leaflet` to create a customComponent. It appears that the `LayersControl.Overlay` is not receiving the inherited props from `LayersControl`- 

```
    <LayersControl.Overlay checked={showOnLoad} name={layerName}>
      <FeatureGroup ref={groupRef}>
         ...implementation...
      </FeatureGroup>
    </LayersControl.Overlay>
  );
```

which yields this - 

![missing_controlled_layer_props](https://user-images.githubusercontent.com/3740177/78835039-1f561c80-79b5-11ea-9af2-f3bfb92f5312.png)


You can see on line `16182` that `addLayer` is undefined on the object returned from `ControlledLayer`. Somehow the inherited class is not being applied?  

I don't have easy access to data, which makes this webpack debugging a bit dicey. If you have ideas of why this might be happening, would be happy to investigate further.
