### ISSUE TITLE
popup content

### ISSUE THREAD

**Issue by pcpatfire** [PaulLeCam/react-leaflet#685]
Is there, for the `Marker `/ `Popup `classes, a function corresponding to `marker._popup.setContent('something else')` to update the content of a popup?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
