### ISSUE TITLE
Map doesn't loading correctly

### ISSUE THREAD

**Issue by AliYmn** [PaulLeCam/react-leaflet#688]
## Bug report

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [X] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior
Maps doesn't loading correctly. Some area are empty.

### Actual behavior
I want to show basic map.

### Steps to reproduce
 [this CodePen](https://codesandbox.io/s/react-leaft-my-example-6ef2p).

**Comment by PaulLeCam** [comment]
Before ticking the boxes please actually do what is described.

**Comment by AliYmn** [comment]
@PaulLeCam I think you are right. I can't do step 3. How to find about step 3 on document?

**Comment by PaulLeCam** [comment]
You should start with Leaflet's quick start guide: https://leafletjs.com/examples/quick-start/

**Comment by AliYmn** [comment]
Hi again, i used as your example in https://github.com/PaulLeCam/react-leaflet/blob/master/example/index.html#L10.
And then, i included this file css ; 
              `<link rel="stylesheet" href="//unpkg.com/leaflet@1.6.0/dist/leaflet.css" />`
But i can't see any thing or maps.
My example updated ; https://codesandbox.io/s/react-leaft-my-example-6ef2p

I think everything is correct based on document and your example. I can't find my problem :(

**Comment by AliYmn** [comment]
@PaulLeCam Sorry i fixed my problem;

    .leaflet-container {
    height: 400px;
    width: 100%;
    }
