### ISSUE TITLE
className for Marker

### ISSUE THREAD

**Issue by iKethavel** [PaulLeCam/react-leaflet#689]
Hello, what do you think about passing className and maybe other props to Marker component?

**Comment by stebogit** [comment]
Yeah, I was wondering why you can't add a class to the Marker component... 🤔 
Is there a specific way you can target and style a particular marker?

**Comment by iKethavel** [comment]
@stebogit, yeah, used Math and css [nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) property.
But it would be better to pass className. @PaulLeCam what do you think about it?

**Comment by iKethavel** [comment]
@stebogit I've found solution via custom icons.
For more info looks [here](https://github.com/PaulLeCam/react-leaflet/issues/691)
or #691

**Comment by PaulLeCam** [comment]
Props are used as options to create Leaflet element, as `className` is not an option in Leaflet's Marker, it's not supported by React Leaflet.
