### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by dougajmcdonald** [PaulLeCam/react-leaflet#69]
Hi there,

When I include the react-leaflet library I seem to get "ReferenceError: window is not defined".

This comes from leaflet-src.js as far as I can see, any ideas? Seems like I'm including something incorrectly.

ReferenceError: window is not defined
    at Object.<anonymous> (C:\Applications\Nexus\Nexus\node_modules\leaflet\dist
\leaflet-src.js:9163:3)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Applications\
Nexus\Nexus\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:
214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Applications\Nexus\Nexus\node_modules\react-leafle
t\lib\index.js:9:16)
    at Module._compile (module.js:460:26)
14 Sep 11:44:46 - [nodemon] app crashed - waiting for file changes before starti
ng...

**Comment by PaulLeCam** [comment]
Hi,

Please refer to https://github.com/PaulLeCam/react-leaflet/issues/45 for more information.

**Comment by mhacxermood914** [comment]
This worked for me
1-i've installed jsdom-global using npm manager...

2-I've replaced window object by global object

**Comment by bertho-zero** [comment]
Or use https://www.npmjs.com/package/@react-leaflet/universal-leaflet

https://github.com/PaulLeCam/react-leaflet/blob/85d68d114d6080ff8d292fc866cae01e2780cdfd/packages/universal-leaflet/index.js#L1

**Comment by amr8644** [comment]
> Or use https://www.npmjs.com/package/@react-leaflet/universal-leaflet
> 
> https://github.com/PaulLeCam/react-leaflet/blob/85d68d114d6080ff8d292fc866cae01e2780cdfd/packages/universal-leaflet/index.js#L1

I still shows an error.

**Comment by amr8644** [comment]
It still shows an error.

**Comment by a0m0rajab** [comment]
This could hlep:
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by SheikhRashed** [comment]
> This could hlep: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
Thank you, It's work for me

**Comment by EthanDebnath** [comment]
what is the /header.js file?

**Comment by kleenkanteen** [comment]
> This could hlep: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

If you are using the app router, make sure to change the docs to app router version. and make sure you put the leaflet map in a separate component and dynamically import it.

**Comment by JeanKouss** [comment]
I encounter this issue with Next.js. This article was a proper solution for me.

https://medium.com/@tomisinabiodun/displaying-a-leaflet-map-in-nextjs-85f86fccc10c

**Comment by bloodykheeng** [comment]
in next 15 jsut import ur component like this 
i mean the component that holds ur map

```
import dynamic from 'next/dynamic'

const ViewMapButtonDialog = dynamic(() => import('./ViewMapButtonDialog'), {
    ssr: false,
})

```
