### ISSUE TITLE
Map rendering problem

### ISSUE THREAD

**Issue by fborghi** [PaulLeCam/react-leaflet#690]
**_"react-leaflet": "^2.6.3"
 "leaflet": "^1.6.0"_**

Hi everyone, hi have a problem with the map in my react project.

I insert the Map as described in the documentation and for a first moment it worked.
Now this is the result:
![asd](https://user-images.githubusercontent.com/24275113/77883906-51080e80-7264-11ea-8313-16c2aed80f66.png)

I don't know what to do.
```
export const Container = styled.div`
  flex: 0 0 100%;
  max-width: 100%;
  height: 250px;
`

<Container>
        <Map
          style={{ width: '100%', height: '100%' }}
          scrollWheelZoom={false}
          center={centerPosition} zoom={9}>
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
            url='https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png'
          />
          {positions.length && <Polyline positions={positions} />}
          <Marker icon={myIcon} key='lastPosition' position={lastPosition}>
            <Popup>
              <span>Popup</span>
            </Popup>
          </Marker>
        </Map>
      </Container>
```
HELP.

**Comment by INGCRENGIFO** [comment]
Hello, how did you solve it?

**Comment by julianklumpers** [comment]
i have the same probleem.
leaflet: 1.6.0
react-leaflet: 2.6.3

**Comment by fborghi** [comment]
I solved adding the leaflet.css to my React map component.

**Comment by devrchancay** [comment]
`import "leaflet/dist/leaflet.css"`

**Comment by 0xorial** [comment]
having same problem, but after I added css, nothing is rendered at al...
