### ISSUE TITLE
CircleMarker with label

### ISSUE THREAD

**Issue by himalayantechies** [PaulLeCam/react-leaflet#691]
Is there any way to produce circle marker with the label on it? Not the tooltip or popup. just a integer within the circle marker

**Comment by iKethavel** [comment]
Hi @himalayantechies! 
I've found solution, not a perfect but a quick one:
```          <Marker
            icon={L.icon({
              iconUrl: `https://ui-avatars.com/api/?name=${idx}&rounded=true`,
              iconSize: [30, 30],
              className: 'my-class-name'
            })}
            key={marker.id}
            position={marker.position}
          >
```
but this service supports only two digits numbers

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
