### ISSUE TITLE
Popup does not update state of props passed in

### ISSUE THREAD

**Issue by louisnow** [PaulLeCam/react-leaflet#694]
## Bug report

- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior
Popup is created with autoPan set to false, change state of autoPan to true. Must now autoPan to popup on rerender of map.

### Actual behavior
Popup is created with autoPan set to false, change state of autoPan to true. Does not autoPan to popup on rerender of map.
Toggling the autopan state has no effect, it behaves like the value you give it on first render.

### Steps to reproduce

[Codepen](https://codepen.io/louis9171/pen/WNvVwEa)

If autoPan is initially true, open popup and pan far away and hit the rerender button, popup will come back into view. The opposite happens if it's initially false. 
However, the toggle button has no effect.

**Comment by louisnow** [comment]
I extended the DivOverlay abstract class and copy/pasted the bulk of the code from [Popup.js](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Popup.js#L33) but I think this change can go into the library instead. 
The only thing which needs to be done is change `updateLeafletElement` to

```
updateLeafletElement(fromProps, toProps) {
  if (toProps.position !== fromProps.position) {
    this.leafletElement.setLatLng(toProps.position);
  }
  if (toProps.autoPan !== fromProps.autoPan) {
    this.leafletElement.options.autoPan = Boolean(toProps.autoPan);
  }
}
```

**Comment by PaulLeCam** [comment]
Leaflet doesn't provide a public method to change this, so it's not supported by React Leaflet.
