### ISSUE TITLE
Problem with Circle radius

### ISSUE THREAD

**Issue by imshmen** [PaulLeCam/react-leaflet#696]
<Circle center={some coordinates} radius={some value}>

No matter what value I assign to 'radius', circle comes as a dot on the map.

**Comment by LongJohnSilver1504** [comment]
Hello @imshmen  try:
<Circle center={some coordinates} radius={ParseInt(yourRadius,10)}>
if the radius is string the circle as show as dot

**Comment by imshmen** [comment]
@LongJohnSilver1504 
Thanks for suggesting a way. But sorry, it didn't work.

Although if I add,
`<Map crs={CRS.Simple}>`
the radius of the <Circle> component works fine. But the map comes with 3 grey quarters saying, "Map data isn't available."

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
