### ISSUE TITLE
Invariant Violation when unmounting popup

### ISSUE THREAD

**Issue by scttnlsn** [PaulLeCam/react-leaflet#70]
I'm getting the following error when a component is unmounted that makes use of `Popup`:

```
Uncaught Error: Invariant Violation: unmountComponentAtNode(...): Target container is not a DOM element.
```

Any ideas?  I'm using React 0.14.0-rc1 with version 0.8.0-rc.1 of react-leaflet.

**Comment by PaulLeCam** [comment]
Hi, thanks for reporting this.

I pushed a change in RC2 that should address this issue, could you try with it?
If the problem persists, could you please add an example code to reproduce the issue? Thanks.

**Comment by scttnlsn** [comment]
RC2 is working great.  Thanks!
