### ISSUE TITLE
curly braces on top of the map

### ISSUE THREAD

**Issue by vtarelkin-comprehend** [PaulLeCam/react-leaflet#700]
![image](https://user-images.githubusercontent.com/46703134/80206845-c2559a00-8635-11ea-9fa8-3dfcff9d5d24.png)

good day. Is it possible to remove those braces?

**Comment by vtarelkin-comprehend** [comment]
@PaulLeCam

**Comment by vtarelkin-comprehend** [comment]
@PaulLeCam why do you close this?

**Comment by PaulLeCam** [comment]
See the [contributing guidelines](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md)
