### ISSUE TITLE
require bounds property to accept empty array

### ISSUE THREAD

**Issue by vtarelkin-comprehend** [PaulLeCam/react-leaflet#701]
good day,

if we' re not providing bounds for the map yet - why not to allow pass an empty array? just show the whole planet. 
instead I am forced to do strange constructions to check if my array provided to bounds is not empty and if is - put some data in it. 
```

        <LeafMap
            bounds={allCoordinates.length > 0 ? allCoordinates : ifSelectedTestsEmptyCoordinates}
```

**Comment by PaulLeCam** [comment]
This is the expected behavior, please refer to Leaflet's documentation.
