### ISSUE TITLE
react-leaflet is not extendable

### ISSUE THREAD

**Issue by uniphil** [PaulLeCam/react-leaflet#71]
When I `npm install --save react-leaflet`, I get a compiled version that does not include the `src/` directory.

I'm using babel in my own project, so it would be nice to be able to do

```js
import { Marker } from 'react-leaflet';

export default MyCustomizedMarker extends Marker {
  ...
}
```

---

**My current solution is to add a github tarbal to `package.json` manually**:
```json
  "dependencies": {
    "react-leaflet": "https://github.com/PaulLeCam/react-leaflet/archive/v0.7.0"
  }
```

and then import like
```js
import Marker from 'react-leaflet/src/Marker'
```

however, it would be nice to be able to do this with a normal npm install.

**Comment by PaulLeCam** [comment]
This is an issue with your compilation process, not this lib.
See the [babel-loader usage documentation](https://github.com/babel/babel-loader#usage) for example if you are using Webpack, it explicitly excludes `node_modules`.

**Comment by uniphil** [comment]
No, the problem is that the `src/` directory is not included on `npm install`.

![react-leaflet-no-src](https://cloud.githubusercontent.com/assets/205128/10044468/491d03e8-61c9-11e5-82e8-0452c8cbf366.png)

**Comment by PaulLeCam** [comment]
This is not a problem, it is intended.
The modules made to be consumed are in `lib` and are exposed by the public API.

**Comment by uniphil** [comment]
So to be clear, `react-leaflet` is not extendable by design, and

```jsx
class CustomizedMarker extends Marker {
```

is not allowed.

If this is true, then react-leaflet is not for us. Just want to be clear before forking.

**Comment by PaulLeCam** [comment]
No, to be clear, there is nothing preventing you from extending the components as they are already exposed. It's just JavaScript.

**Comment by uniphil** [comment]
Hey, sorry for the tone of my previous messages. This library is an awesome step toward making great map apps, so thank you! I shouldn't jump on github issues before I have my morning coffee :smile:

The problem I was having with extending the components distributed in `lib/` was.... I forgot to put `lib/` in the import path haha.

I still want to make the case for one more reason to considering distributing with the `src/` directory: when extending `react-leaflet` components, stack traces that lead into the `react-leaflet` uncompiled source are much nicer do dig through. Similar to how leaflet distributes `leaflet-src.js`. Any chance of it?

**Comment by PaulLeCam** [comment]
Hey, no problem.
Sure, I'll publish the `src` folder as well in future npm releases.

**Comment by uniphil** [comment]
Awesome, thanks! :cake:

**Comment by PaulLeCam** [comment]
Added in RC3 :)
