### ISSUE TITLE
react-leaflet give an error with "the experimental syntax 'flow' isn't currently enabled" 

### ISSUE THREAD

**Issue by IBunDem** [PaulLeCam/react-leaflet#710]
`SyntaxError: D:\Development\JS\SnapServiceClient\snap_service_client\node_modules\react-leaflet\src\index.js: Support for the experimental syntax 'flow' isn't currently enabled (10:8):

   8 | } from './context'
   9 | 
> 10 | export type {
     |        ^
  11 |   LeafletContext,
  12 |   LatLng,
  13 |   LatLngBounds,

Add @babel/plugin-transform-flow-strip-types (https://git.io/vb49g) to the 'plugins' section of your Babel config to enable transformation.`

![изображение](https://user-images.githubusercontent.com/13468375/81779536-b7947380-9516-11ea-8fbb-9057be84922a.png)

I tried to add"@babel/plugin-transform-flow-strip-types to the 'plugins'" in react-leaflet .babelrc, but nothing changed. Please help, how to enable necessary plugin?

**Comment by PaulLeCam** [comment]
The `src` folder contains the source files, you shouldn't import from there unless you know what you're doing. The `lib` and `es` folders should be used instead.
