### ISSUE TITLE
Using zoomOffset in TileLayer as value rather than expresssion results in bad requests

### ISSUE THREAD

**Issue by Eightquake** [PaulLeCam/react-leaflet#711]
## Bug report

I noticed a problem when I was upgrading to a newer version of Mapbox using react-leaflet to render everything - the [upgrade guide from Mapbox](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/#leaflet-implementations) mentioned that the tiles are now larger and zoomOffset needs to be added. I added it as an value, `zoomOffset="-1"`, but that didn't work.

Of course, there is a way around this: using an expression, `let zO = -1; [...] zoomOffset={zO}`, will ensure it's used as an number rather than a string. 

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

When using zoomOffset as a value in the TileLayer component, values are calculated correctly and requests are sent with the correct zoom, latitude and longitude parameters.

Expected request URL: `https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/2/2/1?access_token=` gets 200 OK

### Actual behavior

When using zoomOffset as a value in the TileLayer component, values are appended as strings and requests results in a 404.

Actual request URL: `https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/3-1/2/1?access_token=` gets 404 Not Found

### Steps to reproduce

From a working map, add `zoomOffset="-1"` to the TileLayer component and all requests for tiles will fail.

[Here is a CodePen demonstrating this](https://codepen.io/dvdssn/pen/wvKxdov)

**Comment by ShogunRoss** [comment]
Leaflet's docs state that zoomOffset should be _Number_ (https://leafletjs.com/reference-1.6.0.html#tilelayer-zoomoffset).

Your zoomOffset's input is _String_ so it will make url become "3-1"

**Comment by ShogunRoss** [comment]
As Leaflet's docs state that zoomOffset should be _Number_ (https://leafletjs.com/reference-1.6.0.html#tilelayer-zoomoffset)

I think this be should the work for Leaflet library side.

However, when I insert zoomOffset, the initial position seem like to be in wrong position in comparision with when I don't insert zoomOffset at all.
