### ISSUE TITLE
react-leaflet v2 map synchronization

### ISSUE THREAD

**Issue by nunomferreira** [PaulLeCam/react-leaflet#713]
Hi,

I have searched for a way to have two maps side by side with zoom and pan synchronized and couldn't find a solution that would work with react-leaflet v2.6.3. I'm using react v16.13.1

Is there somthing i might have missed or isn't it possible?

Thanks in advance,
Nuno Ferreira

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
