### ISSUE TITLE
Strange behavior when reverse() over coordinates and filtering elements

### ISSUE THREAD

**Issue by cesargdm** [PaulLeCam/react-leaflet#714]
## Bug report

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

In an array of objects with the property coordinates [Float,Float], and calling reverse() over that coordinates to render the elements correctly.

When filtering that array I expect to render the elements being returned by the map function, and when removing the filter I expect to have all elements being rendered.

Object example
```js
const intialPositions = [
  { id: '0', position:  [-0.09, 51.505] },
  { id: '1', position:  [-0.09, 51.51] },
  { id: '2', position:  [-0.09, 51.495] },
  { id: '3', position:  [-0.09, 51.5] },
]
```

### Actual behavior

In the first case all the elements in the array are correctly rendered, when filtering once the first element is correctly rendered, but when clicking for a second time the expected behavior is to have all elements being rendered again but that single element keeps being the only one rendered; on the third click that element persists and on the fourth click all elements are rendered. Maybe my videos will explain myself better.

### Steps to reproduce

Codepen example:
https://codepen.io/cesargdm/pen/VwvJdOJ

Gif:
![May-28-2020 20-14-20](https://user-images.githubusercontent.com/10179494/83210711-2d0c6080-a121-11ea-89fd-83f730495792.gif)

I got my case to work by reversing the coordinates while doing `[coordinates[1],coordinates[0]]` but it's really strange why reverse outputs that behavior.

**Comment by alecananian** [comment]
Hi @cesargdm, the issue you're encountering doesn't really have anything to do with `react-leaflet`, it's a result of the way the JavaScript Array prototype's `reverse()` function works.  Please see the documentation here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse

The `reverse()` function not only returns the reversed array, but it also _mutates the array in place_.  You'll get unexpected behavior by mutating the parameter of the `map` function as you're doing now:

    fileredPositions.map(({ position, id }, index) => {
      const reversedCoordinates = position.reverse()
      return <Circle key={id} color={colors[index]} radius={30} center={reversedCoordinates} />
    }

Instead, you should make a copy of the array and reverse the copy in place:

    fileredPositions.map(({ position, id }, index) => {
      const coordinates = [...position]
      coordinates.reverse()
      return <Circle key={id} color={colors[index]} radius={30} center={coordinates} />
    }

**Comment by cesargdm** [comment]
Thanks @alecananian didn't now that reverse mutated the array, makes sense that it will cause that unexpected behavior in React, thanks for the tip. Closing.
