### ISSUE TITLE
LineString GeoJSON rendering causes Invalid LatLng error

### ISSUE THREAD

**Issue by furyozo** [PaulLeCam/react-leaflet#720]
Rendering the following GejJSON object using the GeoJSON class causes an invalid LatLng error:

```
{
    "type": "LineString",
    "coordinates": [
        [18.26741130000005, 49.7588141],
        [18.281350299999986, 49.84900529999999]
    ]
}
```

![Capture](https://user-images.githubusercontent.com/20482304/84799316-663b4080-affc-11ea-98ab-491460d5285c.PNG)

![Capture](https://user-images.githubusercontent.com/20482304/84799499-a13d7400-affc-11ea-9909-593aa984475b.PNG)

**Comment by alecananian** [comment]
The JSON and console output you provided don't match. In your console output, your `coordinates` array is nested twice (an array with 1 value containing an array with 2 values, each an array with two values):

    coordinates: [[
      [18.26741130000005, 49.7588141],
      [18.281350299999986, 49.84900529999999]
    ]]

It should only be nested once, as shown in the sample JSON you provided. I took that JSON and drew it with the `GeoJSON` component as expected, so once you fix the data structure it should be good to go.
