### ISSUE TITLE
Custom component extended from MapLayer merging previous and current props.

### ISSUE THREAD

**Issue by joeynimu** [PaulLeCam/react-leaflet#721]
Hi!,

I am implementing a route plan using [leaflet routing machine](https://github.com/perliedman/leaflet-routing-machine) along with React Leaflet. 

But I have this situation whereby the component I implemented seems to merging previous `props` with the next/current `props`.  I am extending `MapLayer` class component and passing it `props` that are used to build the route (coordinate). Below is my implementation.

```js
import { MapLayer, withLeaflet } from "react-leaflet";
import L from "leaflet";
import "leaflet-routing-machine";
import "leaflet-routing-machine/dist/leaflet-routing-machine.css";
const { REACT_APP_MAPBOX_TOKEN: access_token } = process.env;

class Routing extends MapLayer {
  createLeafletElement() {
    const { map, orders } = this.props;
    const coords = orders.map(({ shop }) => [shop.latitude, shop.longitude]);
    const leafletElement = L.Routing.control({
      waypoints: coords.map(([lat, lng]) => L.latLng(lat, lng)),
      lineOptions: {
        addWaypoints: false,
        styles: [
          { color: "rgba( 42, 159, 255, 0.6)", opacity: 1, weight: 6 },
          { color: "white", opacity: 0.8, weight: 6 },
          { color: "rgba( 42, 159, 255, 1)", opacity: 0.5, weight: 5 }
        ]
      },
      waypointMode: "connect", // connect or snap,
      router: L.Routing.mapbox(access_token, {
        profile: "mapbox/cycling"
      }),
      routeWhileDragging: false
    }).addTo(map.leafletElement);
    return leafletElement.getPlan();
  }
}
export default withLeaflet(Routing);

```

The below image shows the first render, which renders fine.  Notice the makers.
<img width="1177" alt="first render" src="https://user-images.githubusercontent.com/1195863/85270933-bbef6d00-b482-11ea-9c3d-95e6c9b58e5d.png">

<img width="1064" alt="Screen Shot 2020-06-22 at 12 16 20 PM" src="https://user-images.githubusercontent.com/1195863/85270985-d0cc0080-b482-11ea-9b99-fef42ce51f15.png">

The above shows the second render where it retains the path on the first render yet the props have changed. Notice one of the paths has no markers (which I don't want to render). Is there a way that I can make the custom component not merge previous props with current ones?

**Comment by PaulLeCam** [comment]
Hi,

There is no logic merging props between renders, but the element returned by [`createLeafletElement`](https://github.com/PaulLeCam/react-leaflet/blob/fd68fd52d97ab6f005e9766beac970ab5dfaf4d9/src/MapLayer.js#L19) will be [added to its container](https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapLayer.js#L34), so that may be the behavior you're seeing.
