### ISSUE TITLE
React Leaflet - How to render custom image using Circle Markers

### ISSUE THREAD

**Issue by FatehAK** [PaulLeCam/react-leaflet#725]
I am trying to generate a custom image for my CircleMarkers. I am not sure how to do it. I am using CircleMarkers here because I have almost 20K+ markers and need them for performance. I can't quite figure out how to pass a custom image to the CircleMarker. Any help on this is much appreciated.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by FatehAK** [comment]
I did a post on stack but didn't receive any feasible solution. Could you help me on this?
