### ISSUE TITLE
map bounds when using multiple markers, 

### ISSUE THREAD

**Issue by rodri595** [PaulLeCam/react-leaflet#728]
hi, im  just having problems resolving the bounds from the mao,

i have multple markers from my api and mos times it would change, how do i set up the bounds i can setup a static version but not one that actually generetas regarding to the markers shown?

**Comment by rodri595** [comment]
![image](https://user-images.githubusercontent.com/16696513/87252101-6117b880-c425-11ea-895f-d8a02ab5d18a.png)
 i need to create one that actually generetes depending on ther markers or polygons to show, i read some of the fitbounds( ) method of pure leaflet but cant seem to implement it quite exactly

thanks in advance and sorry for the post

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
