### ISSUE TITLE
V3 - LayersControl losing context of added layers

### ISSUE THREAD

**Issue by industrylol** [PaulLeCam/react-leaflet#734]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

The layers control should maintain the list of added layers and their current visibility

### Actual behavior

The layer control is empty after several re-renders, and checking the context on the layers control component in react dev tools, has the _layers property on the control as just an empty array.

### Steps to reproduce

You may need to adjust the effect that is causing the re-renders to see it, but mousing over the layers control should cause it to be blank.  This example is a bit contrived, but it shows the problem that I am running into in the simplest way I can think of.

(this is a codepen using v3.0.0-beta.1)
https://codepen.io/industrylol/pen/oNbmbvX

![emptylayercontrol](https://user-images.githubusercontent.com/12126346/88114772-dd22a680-cb71-11ea-9168-6958a551da73.gif)

**Comment by PaulLeCam** [comment]
Thanks for reporting the issue, it should be fixed in beta 2, please try it out!

**Comment by industrylol** [comment]
Confirming this fixed the issue on my simple and more complex use case!  Thanks!  Closing.
