### ISSUE TITLE
V3 Website - Get Started button 404

### ISSUE THREAD

**Issue by slutske22** [PaulLeCam/react-leaflet#742]
The "Get Started" button at https://react-leaflet-v3.now.sh/ goes nowhere.  It links to https://react-leaflet-v3.now.sh/docs/installation, which is a 404.  I think you meant for it to go to https://react-leaflet-v3.now.sh/docs/start-installation?  Just a heads up.

**Comment by PaulLeCam** [comment]
Thanks for reporting this, it will be fixed in the next push of the website

**Comment by slutske22** [comment]
I see this is fixed so I'm closing it.
