### ISSUE TITLE
[Feature Request] v3 - referenceable behavior for components with children

### ISSUE THREAD

**Issue by slutske22** [PaulLeCam/react-leaflet#746]
Hi Paul, thanks for this great library, its my favorite :relaxed:

I am having an issue with getting a `ref` from a child component that has its own children.  My particular case is with trying to use `<LayersControl>`, but I imagine one would have the same issue with a `<FeatureLayer>` or `<LayerGroup>`.  

Looking at this example:

````javascript
class MyComponent extends React.Component {

  componentDidMount(){
    console.log(this.controlRef)
    console.log(this.controlRef._container)
  }

  render(){
    return (
       <LayersControl ref={controlRef => this.controlRef = controlRef}>
         {this.props.children}
       </LayersControl>
    )
  }

}
````
Then you can imagine that this component is used elsewhere, with `LayersControl.BaseLayer` or `LayersControl.Overlay` as the children, which in turn have their own children that may be a `TileLayer`, or `FeatureLayer`, or what have you.

The issue is that in getting the ref from the top level element, the `LayersConrol`, the ref is not really complete at the time of `componentDidMount`.  For example, getting the `this.controlRef` returns an object, but the `this.controlRef._container` is not yet defined at the time of `componentDidMount`.  My guess it that this is because the underlying leaflet `L.control.layers` is not complete until all the children of `LayersControl` render, call their leaflet handlers, and update the `L.control.layers` object.

I tried digging through the `LayersControl.tsx` and `control.ts` files to undertand what's going on there, but as I am not (yet) a typescript ninja, I'm stuggling to grasp it.  I posted a [posted a question on SO](https://stackoverflow.com/questions/63361702/get-ref-once-all-descendants-are-finished-rendering), and there's a bit of discussion there about adding an `onLayersReady()` callback, which would fire once all the children are done rendering.  I'm not sure how feasible that is, or if its already built in to RL and I'm just not seeing it.  Perhaps this is a feature that can be added, or if it already exists, better documented in the 'Referenceable Behavior' section?

Thanks again

**Comment by PaulLeCam** [comment]
Hey, thanks!

I'm not sure I understand exactly the specifics of your issue, but the scope for v3 is the same as previous versions: simply to provider bindings between React and Leaflet, no additional logic.

So in your case I think it's best you wrap the components you need with the additional logic necessary for your use case.

**Comment by slutske22** [comment]
After some more thought, I realize this is more of an issue with how react behaves, and not an issue with react-leaflet.  To better explain, I'll write out a quick example.  Taking a look at a simple `LayerControl` with one `BaseLayer`,:

````javascript
<LayersControl>
   <LayersControl.BaseLayer name="Some Layer">
      <TileLayer url=" ... " />
   </LayersControl.BaseLayer>
</LayersControl>
````

Its tempting to think that this translates to the following leaflet logic: 

````javascript
L.control.layers({
   "Some Layer": L.tileLayer({
      url: " ..." })
   })
   .addTo(map);`
````

**But** its not.  Its actually closer to this:

1. `LayersControl` mounts and renders, calling `L.control.layers().addTo(map)` with no arguments
2. In the `componentDidMount` of my component, the `ref` is referring to the empty `L.control.layers`
3. The children of `LayersControl` render, calling the leaflet `addBaseLayer` or `addOverlay` method, which adds the layer to the control

So that is my issue.  I'm trying to access my `ref` before the children have had a chance to apply the crucial leaflet logic to that `ref`.  I feel like this is addressed with the [supporting children](https://react-leaflet-v3.now.sh/docs/core-architecture#supporting-children) section of the docs, so I'll have to chew on it a bit more. 

Thanks again
