### ISSUE TITLE
o.withLeaflet is not a function 

### ISSUE THREAD

**Issue by nduka-junior** [PaulLeCam/react-leaflet#749]
I was using react leaflet for a project on my localhost it working fine but when I deploy to netlify i gives me this error o.wtihLeaflet is not a function and unable to load leaflet.css 
![159739807715641304284324044705](https://user-images.githubusercontent.com/63047742/90236506-c0992780-de1a-11ea-992a-5db7dc66bad4.jpg)

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
