### ISSUE TITLE
Add Leaflet CSS as a requirement

### ISSUE THREAD

**Issue by ericsoco** [PaulLeCam/react-leaflet#75]
It's probably worth mentioning in your README.md that `leaflet.css` is a requirement for this component, e.g. `<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.5/leaflet.css">`. Experienced users of Leaflet will figure this out easily; others may not.

**Comment by PaulLeCam** [comment]
Good idea, I added it to the readme.

**Comment by samcorcos** [comment]
@PaulLeCam Just out of curiosity, is there a reason the CSS is not included automatically? Since it's a requirement, perhaps it should come with the package? I can put together the PR if you think it's a good idea.

**Comment by PaulLeCam** [comment]
It's a dependency of Leaflet, which is a dependency of React-Leaflet. It's up to your build process to handle these kind of requirements, not this library.

**Comment by txs** [comment]
Still having the rendering issue even when include the css file
