### ISSUE TITLE
The map does not start with the correct position - Ionic with React

### ISSUE THREAD

**Issue by 3runoDesign** [PaulLeCam/react-leaflet#755]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

mount the map with the correct position.

### Actual behavior

The map is mounted with the wrong position even using the `invalidateSize()` method.

### Steps to reproduce

https://codesandbox.io/s/ionic-react-forked-fbz51?file=/src/Home.tsx:619-633

**Comment by 3runoDesign** [comment]
my only solution was:

```tsx
//...
const startMap = useCallback(() => {
    refMap.current?.leafletElement.invalidateSize();
    setTimeout(() => {
        setLoading(false);
    }, 250);
}, []);

useEffect(() => {
    document.addEventListener('deviceready', startMap, false);
    window.addEventListener('load', startMap, false);
});
// ...
```

**Comment by micheal-w-wells** [comment]
I had to do something very similar (also in an ionic react app):  https://gist.github.com/micheal-w-wells/5d3f14b9cd75926975b3a86075a3119a

If there is a 'more correct' way to do it (preferably without a timeout) I would be interested in how to go about it.

**Comment by 3runoDesign** [comment]
> I had to do something very similar (also in an ionic react app): https://gist.github.com/micheal-w-wells/5d3f14b9cd75926975b3a86075a3119a
> 
> If there is a 'more correct' way to do it (preferably without a timeout) I would be interested in how to go about it.

That bothers me a lot. (timeout)

**Comment by Pomaio** [comment]
It`s good that you closed issue, but ..... What about solution without timeout(💩)?
