### ISSUE TITLE
React Leaflet Map not rendering on Safari

### ISSUE THREAD

**Issue by KayleighJoy** [PaulLeCam/react-leaflet#756]
- [X ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X ] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [X ] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [ X] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X ] The issue has not already been reported.
- [ X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- X[ ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

The react leaflet map to render on Safari

### Actual behavior

The map does not render on Safari

### Steps to reproduce

Html: 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
   <script src="https://unpkg.com/react-leaflet@2.7.0/dist/react-leaflet.js"></script>

    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet-src.js"></script>

    <script src="https://unpkg.com/react-dom@16.13.0/umd/react-dom.development.js"></script>

    <script src="https://unpkg.com/react@16.13.0/umd/react.development.js"></script>

    <script src="https://unpkg.com/es6-promise@4.0.5/dist/es6-promise.min.js"></script>

    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
      crossorigin=""
    />
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="container"></div>
    
  </body>
</html>

CSS:
.map-container {
  width: 100%;
  flex-grow: 1;
}

.leaflet-container {
  height: 100%;
  width: 100%;
  margin: 0 auto;
  z-index: -1;
}

Component:
import React, { useState } from "react";
import { Map as LeafletMap, TileLayer, ZoomControl } from "react-leaflet";
import { useSelector, useDispatch } from "react-redux";

import "./Map.css";
import "leaflet/dist/leaflet.css";

export default function Map({ children }) {
  const [tilesLoaded, setTilesLoaded] = useState(false);
  const [tileDetails, setTileDetails] = useState({
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    attribution:
      'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
  });
  const [bounds, setBounds] = useState ({
    southWest: [-34.833333, 16.466667],
    northEast: [-22.133333, 32.883333],
  })

  function onload() {
    var map = document.getElementsByClassName("leaflet-container");
    map[0].style.zIndex = "auto";
    setTilesLoaded(true);
  }

  function tileError() {
    setTileDetails(Config.secondaryTileDetails);
  }

  return (
    <div className="map-container">
      <LeafletMap
        bounds={[bounds.southWest, bounds.northEast]}
        zoomControl={false}
        preferCanvas={true}
        ref={React.createRef()}
      >
        <TileLayer
          url={tileDetails.url}
          attribution={tileDetails.attribution}
          onLoad={onload}
          onTileError={tileError}
        />
        <ZoomControl position="bottomright" />
        {tilesLoaded ? children : null}
      </LeafletMap>
    </div>
  );
}

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
