### ISSUE TITLE
GeoJson Layers rendering old data

### ISSUE THREAD

**Issue by Bhavi-2** [PaulLeCam/react-leaflet#758]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.8.0 minimum).
- [x] Using the supported version of Leaflet (v1.6.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

When Multiple GeoJSON layers are present and particular geojson data is removed, it shouldn't render the data of that geojson object.

### Actual behavior

From multiple GeoJson layers, when one geojson is dynamically removed it still renders it's data and instead removes the last layer added (Stack behaviour)

Please describe.

I've used the GeoJson component to dynamically render a set of datasets that are chosen by the user, my custom component is successfully passing this data to the leaflet map's geojson component.
However, when I use the code as below:

{props.file &&
          props.file.map((file, index) => ( 
            <>
              < GeoJSON  key={index}  data={file} pointToLayer={pointToLayer.bind(this)} style={polystyle(index)} />
</>
))}

It renders the data correctly when adding new datasets, but when the user removes a dataset, the geojson renders all the datasets except the last one that was added.
For instance, user selects : Dataset1 , Dataset2 and then Dataset3 (in order), and then removes Dataset2 from the selection, GeoJson renders Dataset1 and Dataset2 , instead of Dataset1 and Dataset3.

When I don't use the file.map, and pass all the datasets as one array of geojson objects, this issue doesn't seem to happen. But I need this mapping since I need to show different colours for each dataset.

I hope I've added all the required details for this issue.

Any help in the interim will be very helpful!!

Thank you!

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by Bhavi-2** [comment]
Hi Paul,
This was not actually a question regarding the usage. I do think it’s an issue in the library, and hence, reported it.

Please let me know if you think otherwise.

Regards,
Bhavi Mehta

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
