### ISSUE TITLE
Improve the Getting started guide

### ISSUE THREAD

**Issue by mariusGundersen** [PaulLeCam/react-leaflet#759]
The getting started guide isn't very clear for impatient developers. There are several things that aren't mentioned explicitly that would make it much simpler to set up react-leaflet. I think it would be a good idea to show how to set up react-leaflet with create-react-app, since that covers setting it up in a new project and how to set it up with babel and webpack, which I think many people use. The guide would then be 

1. Create a react app
```
npx create-react-app my-map-app
cd my-map-app
npm start
```
2. Install react-leaflet and leaflet 
  * leaflet is a peer dependency of react-leaflet, so it needs to be installed too.
```
npm i react-leaflet leaflet
```
3. Import react-leaflet components and the leaflet css in the app. 
  * The css is needed for the map to be presented correctly. This assumes you are using webpack.
```jsx
// App.jsx

import React from "react";
import "leaflet/dist/leaflet.css";
import { Map, TileLayer } from "react-leaflet";
```
4. Show the map in the app
  * Make sure to include `zoom` and `center` props.
  * Make sure the containing div has a height and width
```jsx
// App.jsx

import React from "react";
import "leaflet/dist/leaflet.css";
import { Map, TileLayer } from "react-leaflet";

export default function App() {
  return (
    <div style={{height:  '400px', width: '400px'}}>
      <Map zoom={1} center={[0, 0]}>
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
      </Map>
    </div>
  );
}
```

This covers several of the problems I had when trying react-leaflet: 
* leaflet is a peer-dependency
* The css needs to be included someway. 
* The props zoom and center (or viewport) must be included
* The containing div needs a height

**Comment by PaulLeCam** [comment]
Leaflet and React Leaflet docs already describe all of this.
React Leaflet is just a library, it doesn't make assumptions about your build tools and environment.
