### ISSUE TITLE
V3 plugins page / column?

### ISSUE THREAD

**Issue by slutske22** [PaulLeCam/react-leaflet#760]
Thanks for this amazing library.  

I've built my first plugin that is native to V3: [react-esri-leaflet](https://github.com/slutske22/react-esri-leaflet) (and I've got some other plugins that have a V3-compatible version ready to go).

Is there a 3rd party plugins page for V3?  Will you be making one?  For now, can I put in a PR to create a 'Compatible with V3' column in the plugins table for the current site?

**Comment by PaulLeCam** [comment]
Thanks!
I added a page in the docs stating to use the `react-leaflet-v3` tag on npm: https://react-leaflet-v3.now.sh/docs/extra-plugins
