### ISSUE TITLE
SVGOverlay rotation

### ISSUE THREAD

**Issue by MatiasManevi** [PaulLeCam/react-leaflet#761]
Hi. I didn't find nothing related to this in StackOverflow nor in the issues list. So it is more like a feature request.

Currently `SVGOverlay` component does not provide a rotation property. You can rotate what ever your SVGOverlay contains but not the SVGOverlay itself. I'm using SVGOverlay to contain a single piece of svg on my map (I'm not using a complete map size SVGOverlay, should I?)

I'm applying rotation to the inner section now but it feels hacky and it doesn't work well, meaning, sometimes the "thing" I'm rendering inside the SVGOverlay gets cutted.

It would be very nice to pass a property like this. 

`<SVGOverlay bounds={bounds} transform={rotate(${degree})} viewBox={box}>`  

So the [SVGOverlay.js](https://github.com/PaulLeCam/react-leaflet/blob/master/src/ImageOverlay.js) would be doing something like this
```
   setAttribute(container, 'xmlns', 'http://www.w3.org/2000/svg')
   setAttribute(container, 'preserveAspectRatio', props.preserveAspectRatio)
   setAttribute(container, 'viewBox', props.viewBox)
   // new prop
   setAttribute(container, 'transform', props.transform)
   
   ...
   
   // Also should be handled on  updateLeafletElement method
```

Questions:
1 - How much possible is this to be implemented as a built-in property option?
2 - Is it possible to address this with custom component? (I can't find SVGOverlay in components hierarchy)

Thanks in advance.

**Comment by MatiasManevi** [comment]
After a few days trying to workaround I ended up solving my problem using the `className` attr of SVGOverlay component.

I passed a class that contain the following css
`overflow: overlay`

**Comment by PaulLeCam** [comment]
Using `className` seems like a good option, or alternatively a custom component gives you the most flexibility. `SVGOverlay` extends `MapComponent` as you can see in the source: https://github.com/PaulLeCam/react-leaflet/blob/master/src/SVGOverlay.js#L21
