### ISSUE TITLE
Wrong property name

### ISSUE THREAD

**Issue by fabian-st** [PaulLeCam/react-leaflet#764]
https://github.com/PaulLeCam/react-leaflet/blob/f56a1ab72752e70b9b277269379cea4a16e2b490/example/components/draggable-marker.js#L56

I believe that `onDragend` should be replaced by `ondragend` here, at least Typescript throws an error when using the first variant.

**Comment by PaulLeCam** [comment]
Both `onDragend` and `ondragend` are valid as far as the library logic is concerned. The TypeScript definitions are provided by a third-party so it's something that should be addressed where relevant.
