### ISSUE TITLE
my image is rendered multiple times

### ISSUE THREAD

**Issue by swaroooo** [PaulLeCam/react-leaflet#769]
![Screenshot from 2020-10-11 17-19-07](https://user-images.githubusercontent.com/70526703/95677830-e60d9c00-0be5-11eb-91f0-3944633513dd.png)
i have imported css file also
here is my code
`import React, { useEffect, useState } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Dialog from '@material-ui/core/Dialog';
import DialogContent from '@material-ui/core/DialogContent';
import AppBar from '@material-ui/core/AppBar';
import Toolbar from '@material-ui/core/Toolbar';
import IconButton from '@material-ui/core/IconButton';
import CloseIcon from '@material-ui/icons/Close';
import { Map, TileLayer, Marker, Popup } from 'react-leaflet';
// import L from 'leaflet'
let Leaflet = require('leaflet');

const useStyles = makeStyles((theme) => ({
  root: {
    height: '85vh',
  }
}));
function MarkOnPlan(props) {
  const classes = useStyles();
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (props.open) {
      setOpen(true);
    }
  }, [props.open]);

  const handleClose = () => {
    setOpen(false);
    props.close();
  };

  return (
    <div className={classes.root}>
    <Map className={classes.root} center={[51,0]} zoom={1}>
             <TileLayer
              attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
              url={props.file}
              // url='https://www.openstreetmap.org/#map=14/19.2007/73.0051'
            />
            <Marker position={[1, -1]}>
              <Popup>
                A pretty CSS3 popup. <br /> Easily customizable.
              </Popup>
            </Marker>
          </Map>
    </div>
  );
}

export default React.memo(MarkOnPlan);`

**Comment by swaroooo** [comment]
**<Map className={classes.root} center={[51,0]} zoom={1}>
            <TileLayer
              attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
              url={props.file}
              // url='https://www.openstreetmap.org/#map=14/19.2007/73.0051'
            />
            <Marker position={[1, -1]}>
              <Popup>
                A pretty CSS3 popup. <br /> Easily customizable.
              </Popup>
            </Marker>
          </Map>**
leaflet code

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
