### ISSUE TITLE
Markers always re-rendered?

### ISSUE THREAD

**Issue by hunterc** [PaulLeCam/react-leaflet#77]
I've got a Map with multiple markers on it. When the map is dragged I make an api call to get a list of new markers. 

I want to leave markers that exist in the new marker list. I figured setting a `key`prop with the item's `id` on the marker would allow react to leave it, but all markers seem to be getting removed.

Ideas?

**Comment by radnor** [comment]
If all your markers are receiving new props that cause them to re-render you can add a `shouldComponentUpdate(nextProps)` function inside `src/Marker.js` to determine whether or not the marker should continue on and trigger `componentDidUpdate()`.

**Comment by hunterc** [comment]
@radnor currently I'm creating the markers in the render function each time. If the loop creates a marker with the same props as the previous time, shouldn't the `key` be used to see if it needs to be removed/re-rendered?
```
render() {
  let markers = this.props.options.map((item, idx) => {
    let ref = 'marker-' + idx;

    return (
      <Marker key={item.id} ref={ref} position={item.location}>
          <Popup>
            {item.name}
          </Popup>
      </Marker>
    );
  });

  return (
      <div>
        <Map
          accessToken={accessToken}
          center={[lat, lng]}
          minZoom={14}
          zoom={14}
          zoomControl={false}
          ref="map"
        >
          <LayerGroup>
            {markers}
          </LayerGroup>
      </Map>
    </div>
  );
}
```

**Comment by hunterc** [comment]
Closing this as it turned out to be an error in a wrapping library.

**Comment by harlequin516** [comment]
I think I am experiencing this same problem with 4.2.0.  Is this fixed?  What wa sthe resolution?
