### ISSUE TITLE
<Circle/> does not support <Popup/> - Not working.

### ISSUE THREAD

**Issue by rufat** [PaulLeCam/react-leaflet#775]
## Bug report

This kind of usage of Popup with Circle is not working. But, I can use it in the same way with Polyline (and it will work).
`<Circle> <Popup> Test </Popup> </Circle>`

### Expected behavior

Expected to see the Popup balloon when I click on Circle.

### Actual behavior

Popup does not show up.

### Steps to reproduce

As I mentioned above, you can try this code snippet with the requires props: `<Circle> <Popup> Test </Popup> </Circle>`

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.

**Comment by rufat** [comment]
> Please follow the issue template and make sure all the boxes are checked before posting an issue.

I have updated the issue. Thank you.

**Comment by PaulLeCam** [comment]
Please provide an example reproducing the issue using this codepen: https://codepen.io/PaulLeCam/pen/XVPmmj

**Comment by rufat** [comment]
> Please provide an example reproducing the issue using this codepen: https://codepen.io/PaulLeCam/pen/XVPmmj

I'm sorry for wasting your time here. I now see that I had to put the Circle component on the end of the other markers because of the z-index priority. If anyone has this issue, simply put the Circle component after other map components to render it last. The Popup now will show up.

![image](https://user-images.githubusercontent.com/5330471/97716906-9ed84400-1add-11eb-96f4-427d1d882d11.png)
