### ISSUE TITLE
Nothing is working with typescript

### ISSUE THREAD

**Issue by cargallo** [PaulLeCam/react-leaflet#778]
Hi I'm new with react-leaflet, I'm working on typescript and everything I tried seems to fail, the documentation is not clear about working with typescript, despite of the fact that the library seems to be coded in ts. I'll apreciate if someone could help me to get it working with typescript. Tnx in advance!

**Comment by cargallo** [comment]
![image](https://user-images.githubusercontent.com/13320290/97831000-8cad0000-1cad-11eb-8179-50a37b427309.png)
![image](https://user-images.githubusercontent.com/13320290/97831017-9d5d7600-1cad-11eb-9737-255b9da838f0.png)

**Comment by mcpgza** [comment]
Same here

**Comment by PaulLeCam** [comment]
React Leaflet provides type definitions directly in the installed package but Leaflet does not, you need to install them as needed: `yarn add -D @types/leaflet`.

**Comment by mcpgza** [comment]
Sorry, another question, how can I define event hendlers on the components?

eg:
![image](https://user-images.githubusercontent.com/50031926/97855495-1b943980-1cfb-11eb-8438-2328817501d6.png)

**Comment by cargallo** [comment]
> React Leaflet provides type definitions directly in the installed package but Leaflet does not, you need to install them as needed: `yarn add -D @types/leaflet`.

Tnx @PaulLeCam it worked! 

It might be worth adding some clarification in the documentation on installing with typescript. I would add a PR to the readme but the documentation is separate. Greetings from Argentina and thanks for the quick response!

**Comment by PaulLeCam** [comment]
Yes I added a section to the installation docs: https://react-leaflet.js.org/docs/start-installation#using-typescript

**Comment by molinto** [comment]
> Yes I added a section to the installation docs: https://react-leaflet.js.org/docs/start-installation#using-typescript

Link: https://react-leaflet.js.org/docs/start-installation/#typescript-support
