### ISSUE TITLE
Not able to use with Typescript 2.4.2 in SPFX

### ISSUE THREAD

**Issue by spoman007** [PaulLeCam/react-leaflet#780]
I am trying to use reac-leaflet in SPFX (Which may not be usual scenario). I am using SPFX version 1.4 and Typescript 2.4.2
When I import anything from react-leaflet I get following error.

![image](https://user-images.githubusercontent.com/8514338/98034521-6b682300-1e17-11eb-86ca-ef0922f9a103.png)

I have tried downloading the type files but it did not help.

Maybe this is simple and I am missing something obvious.
Thanks in advance!!

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
