### ISSUE TITLE
<Pane> tag is not working, new Panes are not created/styles are not applied

### ISSUE THREAD

**Issue by Lorthiz** [PaulLeCam/react-leaflet#782]
## Bug report in v3

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior
When using <Pane> with different name new Pane is created containing it's children.

### Actual behavior
This simple chunk of code should creates 100 markers and splits them beetween 2 panes. One with grayedout/semitransparent markers, second one without styles. Current result is that no matter what name or pane I use they are always placed on 'leaflet-pane leaflet-marker-pane'.

There is not much documentation on using panes except that they should have different names while 'pane' property is not even documented. Also this was working in version 2.x of React Leaflet

### Steps to reproduce
https://codepen.io/costarikamangaulamika/pen/yLJqjYm?editors=1111

### Additional info
Okay I checked it a little deeper. 
Here is example with what I ended up with: https://codepen.io/costarikamangaulamika/pen/bGejJLJ?editors=1010
One thing that I observed is if I use 'pane' property from leaflet marker in codepen It works, and it's because even if pane is empty it is created:
![image](https://user-images.githubusercontent.com/31590000/98308134-a741ea80-1fc7-11eb-80f3-d4dafaabdb70.png)

Localy no pane is created if I do not specify any children, but if I do the empty `<div>` is created BELOW the leaflet-map-pane:
![image](https://user-images.githubusercontent.com/31590000/98308897-8084b380-1fc9-11eb-90f6-518cb24ac4e7.png)
![image](https://user-images.githubusercontent.com/31590000/98308985-a5792680-1fc9-11eb-9eac-3b2fce57d55e.png)
And what is the most suprising the components tab shows that my markers are created 'inside' ContextProvider, but it's children inside props are just an empty div:
![image](https://user-images.githubusercontent.com/31590000/98309223-3b14b600-1fca-11eb-8011-8de310150843.png)
![image](https://user-images.githubusercontent.com/31590000/98309236-41a32d80-1fca-11eb-828d-c8d025386311.png)
Truth be told I don't know what to make of it, but I felt it might be important. Also the third empty pane is also present here:
![image](https://user-images.githubusercontent.com/31590000/98310138-88922280-1fcc-11eb-8360-094c2c757c8d.png)

Anyway if I tried to use the approach from the codepen on my enviroment it did not created any div panes inside 'leaflet-map-pane' and this line:  `this.getPane().appendChild(this._icon);` inside function `initIcon` is throwing error: `Uncaught TypeError: Cannot read property 'appendChild' of undefined`

![image](https://user-images.githubusercontent.com/31590000/98309914-fee25500-1fcb-11eb-9ed7-ff4410e864bb.png)

Here is full stackTrace:
main.js:8806 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at NewClass._initIcon (main.js:8806)
    at NewClass.onAdd (main.js:8658)
    at NewClass._layerAdd (main.js:7770)
    at NewClass.whenReady (main.js:5631)
    at NewClass.addLayer (main.js:7832)
    at addLayer (0.299e78ac4d315f262f24.hot-update.js:4125)
    at fk (main.js:28059)
    at exports.unstable_runWithPriority (main.js:28131)
    at gg (main.js:27919)
    at Oj (main.js:28058)

**Comment by PaulLeCam** [comment]
Indeed there was an issue with handling the panes, it should be fixed in v3.0.1 but please let me know if it doesn't work in your case.

**Comment by Lorthiz** [comment]
There is still problem.
![image](https://user-images.githubusercontent.com/31590000/98447467-45979280-2125-11eb-946c-7f7fc713af0a.png)
   
```
return <>
        <Pane name={"otherLayersPane"} style={{opacity: 0.5, filter: "grayscale(100%)"}}>
            {otherLayersMarkers}
        </Pane>
        <Pane name={"currentLayer"}>
            {currentLayerMarkers}
        </Pane>
    </>
```

The same problem. <divs> are rendered below the 'leaflet-map-pane'.
I tried upgrading to 3.0.1, invalidating IDE caches and restarting app. It should get the new changes by now.

**Comment by PaulLeCam** [comment]
I pushed v3.0.2 with changes to the panes creation logic, hopefully that fixes common issues. The [Pane example](https://react-leaflet.js.org/docs/example-panes/) works as expected with this logic.

**Comment by Lorthiz** [comment]
Checked it just now. Works like a charm! 👍
Thank you for quick fixes!
