### ISSUE TITLE
useLeaflet is not exported from "react-leaflet"

### ISSUE THREAD

**Issue by gynekolog** [PaulLeCam/react-leaflet#783]
## Bug report in v3

- [ x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x  ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [ x ] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [ x ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ x ] The issue has not already been reported.
- [ x ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Actual behavior

Attempted import error: 'useLeaflet' is not exported from 'react-leaflet'.

**Comment by PaulLeCam** [comment]
The `useLeaflet` hook exists in v2 but not v3 that exports [other hooks](https://react-leaflet.js.org/docs/api-map#hooks).
