### ISSUE TITLE
Is there a prop for different map skins?

### ISSUE THREAD

**Issue by iamwillow** [PaulLeCam/react-leaflet#786]
After looking through [the documentation](https://react-leaflet.js.org/docs/api-map), I don't see any props listed for the different leaflet map skins. 

Is this included with react-leaflet?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
