### ISSUE TITLE
GeoJSON Component-based Popup

### ISSUE THREAD

**Issue by BuffaloDeveloper** [PaulLeCam/react-leaflet#787]
Is it possible to render a **component** for a popup when using GeoJSON's onEachFeature prop?

The problem is described in more detail here: https://stackoverflow.com/questions/64630603/react-leaflet-using-a-component-as-a-popup-on-a-geojson-feature

Currently doing this below, which just renders basic HTML that doesn't have any JS interactivity.  I would like to add a button with an onClick event handler to the popup.

```
 function onEachFeature(feature, layer) {
        const popupOptions = {
            minWidth: 200,
            maxWidth: 250,
            className: "popup-classname",
            closeButton: false
        };

            layer.bindPopup(()=>{
                return ReactDOMServer.renderToString(<MyPopupComponent feature={feature} />);
            }, popupOptions);
    }
```

```
<GeoJSON
                key={1234}
                data={props.data}
                onEachFeature={onEachFeature}
            />
```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
