### ISSUE TITLE
Popup issue on Safari

### ISSUE THREAD

**Issue by mariellekatharina** [PaulLeCam/react-leaflet#790]
## Bug report in v3

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [X] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Popup appears in Safari after click or touch event on a marker is fired.

### Actual behavior

Popup is not appearing in Safari after click or touch event on a marker is fired.
It's only not working in Safari, other Browsers working as expected for me. I’m using Safari 14.0. The problem appears also on demo sites (e.g. https://react-leaflet.js.org).

### Steps to reproduce
The problem also exists in this codepen: 
Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by PaulLeCam** [comment]
This seems to be a known issue in Leaflet: https://github.com/Leaflet/Leaflet/issues/7331
Please use the upstream issue to keep track of it.
