### ISSUE TITLE
Search at the documentation page is broken

### ISSUE THREAD

**Issue by matkoniecz** [PaulLeCam/react-leaflet#793]
Open https://react-leaflet.js.org/

Type "Circle" in search form at top right

Select https://react-leaflet.js.org/docs/en/components#circle (first result)

Get "Page Not Found We could not find what you were looking for. Please contact the owner of the site that linked you to the original URL and let them know their link is broken."

**Comment by PaulLeCam** [comment]
It seems the index still references the previous version of the docs so I disabled the search bar.
