### ISSUE TITLE
Bug With centering

### ISSUE THREAD

**Issue by shah1012** [PaulLeCam/react-leaflet#796]
Hi,

i was watching following a youtube video that was using react-leaflet and i followed everything in the youtube video but for some reason the map does not center when i update it here is my code

```
import React from "react";
import {
  MapContainer as LeafletMap,
  Marker,
  TileLayer,
  Popup,
} from "react-leaflet";
import "./Map.css";

const position = [13.1667, -59.5333];
function Map({ ctr, zm }) {
  return (
    <div className="map">
      <LeafletMap center={ctr} zoom={zm} scrollWheelZoom={false}>
        <TileLayer
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
      </LeafletMap>
    </div>
  );
}

export default Map;
```

and here is my state that centers the map

```
setMapCenter([data.countryInfo.lat, data.countryInfo.long]);
`setMapZoom(4);`
<Map ctr={mapCenter} zm={mapZoom} />
```

**Comment by lucax88x** [comment]
reproducible:

[version with 2.8.0 (working)](https://codesandbox.io/s/react-leaflet-forked-blck6?file=/src/index.js)
[version with 3.0.2 (not working)[(https://codesandbox.io/s/great-wind-fxvqn?file=/src/App.js)

**Comment by anajavi** [comment]
[According to documentation:](https://react-leaflet.js.org/docs/api-map#mapcontainer)
> Except for its children, MapContainer props are immutable: changing them after they have been set a first time will have no effect on the Map instance or its container.


You could try something like this:
```jsx
const Centerer = ({ center }) => {
  const map = useMap();

  useEffect(() => {
    map.setView(center);
  }, [center, map]);

  return null;
};

const MyMap = ({ center }) => {
  return (
    <MapContainer>
      <Centerer center={center} />
    </MapContainer>
  )
}
```

**Comment by PaulLeCam** [comment]
As replied above, it's the expected behavior.

**Comment by meetDeveloper** [comment]
@PaulLeCam Won't that make MapContainer an impure component? As it does not follow the rule that same input always give same output?
