### ISSUE TITLE
Indonesian cities are under water at some point of zoom.

### ISSUE THREAD

**Issue by mearajali** [PaulLeCam/react-leaflet#797]
## Bug report in v3

<img width="794" alt="Screenshot 2020-12-03 at 4 03 28 AM" src="https://user-images.githubusercontent.com/20181787/100939701-bd868c00-351c-11eb-8856-4b0e80cf68e2.png">
<img width="800" alt="Screenshot 2020-12-03 at 4 03 18 AM" src="https://user-images.githubusercontent.com/20181787/100939705-bfe8e600-351c-11eb-92f8-262be53d2be7.png">

Some of the cities from Indonesia doesn't have lands e.g. Sumatra, in map it is showing underwater. I have checked this issue in leaflet.js as well, i think it is inherited from parent library. Any idea how to fix this?

Position - [0, 118]
Zoom - 4

**Comment by PaulLeCam** [comment]
This is up to you tiles server, not this library.
