### ISSUE TITLE
Build Failing Due to TypeScript Error

### ISSUE THREAD

**Issue by lauchness** [PaulLeCam/react-leaflet#798]
### Expected behavior

As a developer I would expect a working TypeScript app in development to build successfully

### Actual behavior

Build fails with error message:
```
Failed to compile.
--
11:57:02.643 | /vercel/workpath0/node_modules/@react-leaflet/core/types/index.d.ts
11:57:02.643 | TypeScript error in /vercel/workpath0/node_modules/@react-leaflet/core/types/index.d.ts(3,1):
11:57:02.643 | Declaration or statement expected.  TS1128
11:57:02.643 | 1 \| export { useAttribution } from './attribution';
11:57:02.643 | 2 \| export { updateCircle } from './circle';
11:57:02.643 | > 3 \| export type { CircleMarkerProps } from './circle';
11:57:02.643 | \| ^
11:57:02.643 | 4 \| export { createContainerComponent, createDivOverlayComponent, createLeafComponent, } from './component';
11:57:02.643 | 5 \| export { CONTEXT_VERSION, LeafletContext, LeafletProvider, useLeafletContext, } from './context';
11:57:02.643 | 6 \| export type { LeafletContextInterface } from './context';
11:57:02.674 | error Command failed with exit code 1.

```

### Steps to reproduce

You can use the CodeSandbox here: [https://codesandbox.io/s/fervent-perlman-ll6so](https://codesandbox.io/s/fervent-perlman-ll6so)

If you fork this sandbox, and attempt to build using Vercel, the CRA Scripts will run, and fail at the `yarn build` step.

This is built using the React-Typescript template in CodeSandbox, utilitizing Create-React-App with the default typescript setup.

The types for both react-leaflet and leaflet are installed as dev-dependencies. As a reference, the package.json is here: [package.json](https://codesandbox.io/s/fervent-perlman-ll6so?file=/package.json)

**Comment by anajavi** [comment]
You are using typescript v3.7.5. [The export/import type was introduced in typescript 3.8.0.](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html)

**Comment by lauchness** [comment]
Thanks @anajavi, you're absolutely correct. Closing the issue.
