### ISSUE TITLE
changing bounds does not change bounds of the map anymore (did in v2)

### ISSUE THREAD

**Issue by barbalex** [PaulLeCam/react-leaflet#799]
## Bug report in v3

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Changing bounds via state should change the bounds of the map.

### Actual behavior

The map does not change it's bounds.
I updated my working app from v2 to v3. This worked in v2 but not any more in v3.

### Steps to reproduce

See here: https://codepen.io/barbalex/pen/XWjKroo

Instructions:

1. open link
1. open console
1. click on "Run"
1. watch bounds being changed via state after 3 seconds
1. see that map seems to redraw - but with unchanged bounds

Could maybe be related to https://github.com/PaulLeCam/react-leaflet/issues/796

**Comment by PaulLeCam** [comment]
This is the expected behavior in v3, `<MapContainer>` does not behave like `<Map>` used to.

**Comment by barbalex** [comment]
So how would I change the bounds?

**Comment by barbalex** [comment]
Oh, I finally got it: `map.fitBounds` as explained here: https://react-leaflet.js.org/docs/example-view-bounds
