### ISSUE TITLE
Popups not working as expected

### ISSUE THREAD

**Issue by stevenmason** [PaulLeCam/react-leaflet#80]
Changing a popups content does not update until the popup is closed and then opened again. I am also getting the following warning: "Failed propType: Invalid prop `popupContainer` supplied to `Popup`, expected a ReactNode. Check the render method of `Marker`."

**Comment by PaulLeCam** [comment]
What version of React and the lib are you using?
How can this issue be reproduced?

**Comment by stevenmason** [comment]
Cheers for the quick reply version 0.7.0. I'll make a demo project.

**Comment by PaulLeCam** [comment]
v0.7 does not support dynamic rendering of Popups, it's been added to v0.8.

**Comment by stevenmason** [comment]
Okay awesome thank you, I'll update to v0.8.
