### ISSUE TITLE
Changing MapContainer className prop removes internally set classes

### ISSUE THREAD

**Issue by fdev** [PaulLeCam/react-leaflet#804]
## Bug report in v3

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
    **Yes and no. It was [fixed in v2](https://github.com/PaulLeCam/react-leaflet/issues/531) but is back in v3.**
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

When the `className` passed to `MapContainer` changes, the default Leaflet classes are kept.

### Actual behavior

Only the passed `className` remains.

### Steps to reproduce

https://codepen.io/fdev-nl/pen/jOMVVRy (push the button and watch it break)

**Comment by PaulLeCam** [comment]
`<MapContainer>` does not support changing other props than its `children`.

**Comment by ToastHawaii** [comment]
For people looking for a solution. This works for me: 

```typescript
export function ClassName({ classList }: { classList: string[] }) {
  const map = useMap();
  const [currentClassList, setCurrentClassList] = useState(classList);

  useEffect(() => {
    map.getContainer().classList.remove(...currentClassList);
    map.getContainer().classList.add(...classList);
    setCurrentClassList(classList);
  }, [classList.join(" ")]);

  return null;
}
```

Usage:

  ```tsx
 <MapContainer>
     ...
     <ClassName classList={["focus-ring", ...(props.error ? ["focus-ring-danger", "is-invalid"] : [])]} />
   </MapContainer>
```
