### ISSUE TITLE
eventHandlers property of MapContainer is ignored

### ISSUE THREAD

**Issue by zdila** [PaulLeCam/react-leaflet#805]
Property `eventHandlers` of `MapContainer` is ignored. Leaflet's `Map` knows nothing about `eventHandlers` in its options.

**Comment by fdev** [comment]
You can use the following code in a component that is a child of `MapContainer`:

```jsx
import { useMapEvent } from 'react-leaflet'

...

useMapEvent('click', () => {
  ...
})
```

This approach makes more sense to me, as a child component (for example a Route) can specify the map events as needed for that component.

**Comment by zdila** [comment]
@fdev I am not telling that I can't work around this problem. I am reporting issue that `MapContainer` TypeScript definition tells that it supports `eventHandlers` but that is not true.

**Comment by PaulLeCam** [comment]
Yes it's an error that the TypeScript definition contains `eventHandlers`, it should be fixed in the latest version.
