### ISSUE TITLE
Accessing the Map via a Ref

### ISSUE THREAD

**Issue by colbyfayock** [PaulLeCam/react-leaflet#806]
### Expected behavior

Being able to access the map instance via a ref

### Actual behavior

Ref is no longer available

### Steps to reproduce

In v2, I was able to access the map via a ref that allowed me to forward that ref from outside of the map and trigger functionality. That ref is no longer available it seems in v3

https://github.com/colbyfayock/gatsby-starter-leaflet/blob/master/src/pages/index.js
https://gatsby-starter-leaflet.netlify.app/

I've been trying to think about how to do this and I was hoping you could provide guidance with the new API or if a Ref is something you'd entertain including back in as an option.

It seems I would be able to include a child component from the outside where I would then have access to useMap, but that component wouldn't really be a component, it would be a shell for a useMap function, which seems a little less ideal than the current setup I have with useRef

Was curious if you have any suggestions or ideas?

**Comment by PaulLeCam** [comment]
Yes having a child component with `useMap` is the best option, using `ref` on `<Map>` has always been problematic so `<MapContainer>` doesn't support it.

**Comment by colbyfayock** [comment]
Got it. thanks

**Comment by colbyfayock** [comment]
For those finding this thread, here's an example of how I handled this: https://github.com/colbyfayock/gatsby-starter-leaflet/blob/master/src/pages/index.js#L100
