### ISSUE TITLE
Map <Marker> image does not appear on Next.js

### ISSUE THREAD

**Issue by MathisBarre** [PaulLeCam/react-leaflet#808]
### Expected behavior

When I import my leaflet map in react with dynamic import (required with Next.js), I want the marker images to be display.

### Actual behavior

Instead of expected behavior, the marker icon doesn't appear.
When I inspect the images with devtools here is the src I get for the image :
`http://localhost:3000/_next/static/media/marker-icon.2b3e1faf89f94a4835397e7a43b4f77d.png")marker-icon.png`

Here is my actuel dependencies:
```json
 "dependencies": {
    "@mdx-js/loader": "^1.6.21",
    "@next/mdx": "^10.0.2",
    "@tailwindcss/typography": "^0.3.1",
    "ackee-tracker": "^4.2.0",
    "autoprefixer": "^10.0.2",
    "dayjs": "^1.9.6",
    "leaflet": "^1.7.1",
    "next": "10.0.3",
    "postcss": "^8.1.9",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-preset-env": "^6.7.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-leaflet": "^3.0.4",
    "react-select": "^3.1.1",
    "sass": "^1.29.0",
    "tailwindcss": "^2.0.2"
  },
```

I've tried this fix found in another old github issue :
```jsx
import L from 'leaflet';

delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});
```

But unfortunately, it result to a compile error :
```
./node_modules/leaflet/dist/images/marker-shadow.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

### Steps to reproduce

You can clone this repository to reproduce the issue easily : https://github.com/MathisBarre/leaflet-icon-issue
Otherwise you just need to dynamically import a leaflet map in nextjs

**Comment by kud** [comment]
Same here.

**Comment by kunKun-tx** [comment]
https://github.com/ghybs/leaflet-defaulticon-compatibility
this one seems fix the issue for me.

**Comment by kud** [comment]
Interesting, thanks

For the moment I did this:

```js
<Marker
          position={[51.505, -0.09]}
          icon={L.divIcon({
            iconSize: [size, size],
            iconAnchor: [size / 2, size + 9],
            className: "mymarker",
            html: "😁",
          })}
        >
```

**Comment by MathisBarre** [comment]
> https://github.com/ghybs/leaflet-defaulticon-compatibility
> this one seems fix the issue for me.

Looks like it's working well ! Thanks !

**Comment by antoinerousseau** [comment]
Simply create a PNG icon (64x64px in my case), put it in `/public`, and then create an [icon](https://leafletjs.com/reference-1.7.1.html#icon) instance:

```js
const ICON = L.icon({
  iconUrl: "/marker.png",
  iconSize: [32, 32],
})
```

and use it like this:

```jsx
<Marker icon={ICON} position={...} />
```

**Comment by kud** [comment]
Yessssss, this is better than using the global variable `L`

**Comment by silviuburceadev** [comment]
The workarounds are nice, but for default behavior, i.e. showing the default Leaflet marker icon, it should work out of the box. Since we're talking about React here, which most of us use with webpack (via CRA), it should work to just import the CSS from app code, not imported from a CDN ([as in the setup guide code](https://github.com/PaulLeCam/react-leaflet/blob/gh-pages/docs/start-setup/index.html#L9)) or at least put a warning in the docs, saying that Leaflet CSS doesn't play nice with webpack and you have to do this and that.

**Comment by antoinerousseau** [comment]
I just `import "leaflet/dist/leaflet.css"` but yeah for the marker a working default would be nice

**Comment by jhackett1** [comment]
this seems to still be broken :(

**Comment by MathisBarre** [comment]
> this seems to still be broken :(

That's true but the workaround are still valid

**Comment by kud** [comment]
Yeah https://github.com/PaulLeCam/react-leaflet/issues/808#issuecomment-747719927 is really cool. :)

You can create an intermediary component which injects this `ICON`.

**Comment by meglio** [comment]
> Yeah [#808 (comment)](https://github.com/PaulLeCam/react-leaflet/issues/808#issuecomment-747719927) is really cool. :)
> 
> You can create an intermediary component which injects this `ICON`.

I tried to create an intermediary component:

```
import {divIcon, Marker} from 'leaflet';

const ICON = divIcon();

export default function DivIconMarker(props) {

    return <Marker icon={ICON} {...props} />
}
```

Loading this component dynamically into a Next.js page component produces an error:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/282177/123187644-b5eafc80-d4d9-11eb-84f4-2c66085b1924.png">

**Comment by ted-piotrowski** [comment]
If you're using `create-react-app`, this will fix the default icon behaviour:

```
import L from 'leaflet';
import markerIcon2x from 'leaflet/dist/images/marker-icon-2x.png';
import markerIcon from 'leaflet/dist/images/marker-icon.png';
import markerShadow from 'leaflet/dist/images/marker-shadow.png';

delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
    iconUrl: markerIcon,
    iconRetinaUrl: markerIcon2x,
    shadowUrl: markerShadow,
})
```

The reason the fix at the start of this thread did not work is because the Webpack `file-loader` configuration for `create-react-app` does not allow using `require()` for loading files.

**Comment by DarkSuniuM** [comment]
> If you're using `create-react-app`, this will fix broken Marker images:
> 
> ```
> import L from 'leaflet';
> import markerIcon2x from 'leaflet/dist/images/marker-icon-2x.png';
> import markerIcon from 'leaflet/dist/images/marker-icon.png';
> import markerShadow from 'leaflet/dist/images/marker-shadow.png';
> 
> delete L.Icon.Default.prototype._getIconUrl;
> L.Icon.Default.mergeOptions({
>     iconUrl: markerIcon,
>     iconRetinaUrl: markerIcon2x,
>     shadowUrl: markerShadow,
> })
> ```
> 
> If you're curious why the old fix at the start of this thread does not work, it is because the default Webpack `file-loader` [configuration](https://v4.webpack.js.org/loaders/file-loader/#esmodule) (which is used by `create-react-app`) does not allow using `require()` for loading files.
> 
> > I've tried this fix found in another old github issue :
> > ```js
> > import L from 'leaflet';
> > 
> > delete L.Icon.Default.prototype._getIconUrl;
> > 
> > L.Icon.Default.mergeOptions({
> >     iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
> >     iconUrl: require('leaflet/dist/images/marker-icon.png'),
> >     shadowUrl: require('leaflet/dist/images/marker-shadow.png')
> > });
> > ```

Awesome, using NextJS and `create-next-app` and it works perfectly fine,
Only needs the src of the imported images instead of the object.


```js
import L from 'leaflet';
import markerIcon2x from 'leaflet/dist/images/marker-icon-2x.png';
import markerIcon from 'leaflet/dist/images/marker-icon.png';
import markerShadow from 'leaflet/dist/images/marker-shadow.png';

delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
    iconUrl: markerIcon.src,
    iconRetinaUrl: markerIcon2x.src,
    shadowUrl: markerShadow.src,
})
```

**Comment by fasiha** [comment]
> Awesome, using NextJS and `create-next-app` and it works perfectly fine

Hmm, @DarkSuniuM's solution didn't work for me, using Next.js: browser was getting 404 on `http://localhost:3000/[object Module]`. I'm not sure if Next or Leaftlet (or npm or something else) is breaking it.

My solution was, instead of any code changes, just to put the files it's looking for in a place where Next can find them: `mkdir public && cp node_modules/leaflet/dist/images/* public`.

**Comment by BranislavLazic** [comment]
> No need for extra libs!
> 
> Simply create a PNG icon (64x64px in my case), put it in `/public`, and then create an [icon](https://leafletjs.com/reference-1.7.1.html#icon) instance:
> 
> ```js
> import { icon } from "leaflet"
> 
> const ICON = icon({
>   iconUrl: "/marker.png",
>   iconSize: [32, 32],
> })
> ```
> 
> and use it like this:
> 
> ```js
> <Marker icon={ICON} position={...} />
> ```

Yes, there is. Although this seems like a good solution, I noticed that the marker doesn't stay pinned in the same location as I zoom in or zoom out the map.

**Comment by CodePhilanthropist** [comment]
Hello gorgeous people of the internet,

I found this issue and was able to fix it by customizing the marker icon to point to the correct URL. 

Here is the code I used:

```
import { MapContainer, TileLayer, Marker, Popup, Circle, ZoomControl } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import markerIcon from "leaflet/dist/images/marker-icon.png";
import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
import markerShadow from "leaflet/dist/images/marker-shadow.png";

const customMarkerIcon = L.icon({
  iconUrl: markerIcon,
  iconRetinaUrl: markerIcon2x,
  shadowUrl: markerShadow,
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  tooltipAnchor: [16, -28],
  shadowSize: [41, 41],
});

const Map = () => {
  return (
    <MapContainer
      className="mapContainer"
      center={[51.505, -0.09]}
      zoom={16}
      scrollWheelZoom={false}
      zoomControl={false}
    >
      <TileLayer
        className="map"
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <Marker position={[51.505, -0.09]} icon={customMarkerIcon}>
      
      </Marker>
      <Circle
        center={[51.505, -0.09]}
        pathOptions={{ color: "#50C878", fillColor: "#72FE9F" }}
        radius={200}
      />
    
    </MapContainer>
  );
};

export default Map;

```

I hope this helps!

**Comment by Abbosbek-cloud** [comment]
> Hello gorgeous people of the internet,
> 
> I found this issue and was able to fix it by customizing the marker icon to point to the correct URL.
> 
> Here is the code I used:
> 
> ```
> import { MapContainer, TileLayer, Marker, Popup, Circle, ZoomControl } from "react-leaflet";
> import "leaflet/dist/leaflet.css";
> import L from "leaflet";
> import markerIcon from "leaflet/dist/images/marker-icon.png";
> import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
> import markerShadow from "leaflet/dist/images/marker-shadow.png";
> 
> const customMarkerIcon = L.icon({
>   iconUrl: markerIcon,
>   iconRetinaUrl: markerIcon2x,
>   shadowUrl: markerShadow,
>   iconSize: [25, 41],
>   iconAnchor: [12, 41],
>   popupAnchor: [1, -34],
>   tooltipAnchor: [16, -28],
>   shadowSize: [41, 41],
> });
> 
> const Map = () => {
>   return (
>     <MapContainer
>       className="mapContainer"
>       center={[51.505, -0.09]}
>       zoom={16}
>       scrollWheelZoom={false}
>       zoomControl={false}
>     >
>       <TileLayer
>         className="map"
>         attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
>         url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
>       />
>       <Marker position={[51.505, -0.09]} icon={customMarkerIcon}>
>       
>       </Marker>
>       <Circle
>         center={[51.505, -0.09]}
>         pathOptions={{ color: "#50C878", fillColor: "#72FE9F" }}
>         radius={200}
>       />
>     
>     </MapContainer>
>   );
> };
> 
> export default Map;
> ```
> 
> I hope this helps!

Hello @CodePhilanthropist!

I can set it as you did. But I need to change the marker icon of the react-leaflet-geoman-v2.

**Comment by Lodimup** [comment]
> > No need for extra libs!
> > Simply create a PNG icon (64x64px in my case), put it in `/public`, and then create an [icon](https://leafletjs.com/reference-1.7.1.html#icon) instance:
> > ```js
> > import { icon } from "leaflet"
> > 
> > const ICON = icon({
> >   iconUrl: "/marker.png",
> >   iconSize: [32, 32],
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and use it like this:
> > ```js
> > <Marker icon={ICON} position={...} />
> > ```
> 
> Yes, there is. Although this seems like a good solution, I noticed that the marker doesn't stay pinned in the same location as I zoom in or zoom out the map. https://github.com/ghybs/leaflet-defaulticon-compatibility fixes this issue.

I'm using this lib https://github.com/holytrips/react-leaflet-marker to use react component as marker. I got the same problem, when zoomed marker just move around. The repo doesn't fix my problem. I wonder if I'm doing something wrong. Does react-leaflet-marker  work on yours?

**Comment by catalin-axsys-FE** [comment]
In nextJs 14.1.0 I have managed to add a custom marker image by doing the follwoing:
`import MapMarkerIcon from "./_assets/some_icon.png";

const customIcon = new L.Icon({
  iconUrl: MapMarkerIcon.src,
  iconSize: [15, 15],
});

.
..
...
<Marker
              key={id}
              icon={customIcon} />
`

**Comment by Nnenna-udefi** [comment]
This worked for me. I'm using creact react app and typescript

(delete (L.Icon.Default.prototype as any)._getIconUrl);

(L.Icon.Default.prototype as any)._getIconUrl = function (name: string): string {
    return require('leaflet/dist/images/' + (name === 'icon' ? 'marker-icon' : 'marker-shadow') + '.png');
};

**Comment by DIEGOHORVATTI** [comment]
### Custom Marker Icon

```ts
 const sizeMarkerIcon = 50

const IconMarker = icon({
    iconUrl: `data:image/svg+xml;utf8,${encodeURIComponent(`<?xml version="1.0" encoding="iso-8859-1"?>
    <svg xmlns="http://www.w3.org/2000/svg" width="0.67em" height="1em" viewBox="0 0 1024 1536">
      <path fill="${theme.palette.primary.main}" d="M768 512q0-106-75-181t-181-75t-181 75t-75 181t75 181t181 75t181-75t75-181m256 0q0 109-33 179l-364 774q-16 33-47.5 52t-67.5 19t-67.5-19t-46.5-52L33 691Q0 621 0 512q0-212 150-362T512 0t362 150t150 362" />
    </svg>  
  `)}`,
    iconSize: [sizeMarkerIcon, sizeMarkerIcon],
    iconAnchor: [sizeMarkerIcon / 2, sizeMarkerIcon],
    popupAnchor: [0, -sizeMarkerIcon]
  })
```

```ts
<Marker icon={IconMarker} position={position} draggable={false}>
   <Popup>{descriptionCurrentPosition}</Popup>
</Marker>
```

<img width="965" alt="image" src="https://github.com/PaulLeCam/react-leaflet/assets/72998710/3e9bf932-79a3-480e-b38a-ada0743c0351">

**Comment by nwatab** [comment]
overriding default, mergeOptions, customIcon, none of them works on Next.js15

**Comment by sovetski** [comment]
In my case I just downloaded theses:

https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png
https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png

And put it inside `public` folder and that's all
