### ISSUE TITLE
Controls Position

### ISSUE THREAD

**Issue by RobinMalfait** [PaulLeCam/react-leaflet#81]
Hey

How can I change the position of the controls on the map element?
Currently the zoom buttons are at the top left, is there a way to change it?

Thanks

**Comment by PaulLeCam** [comment]
Hi,

This is purely Leaflet behavior, as per their [documentation](http://leafletjs.com/reference.html#map-zoomcontrol), it is possible to hide it but not set its position directly in the map properties.

I think you best option is to hide it from the map, `<Map zoomControl={false} ...>` should work but please let me know if it doesn't, and add the [zoom control](http://leafletjs.com/reference.html#control-zoom) to the map yourself, as this library does not provide components for controls.

**Comment by RobinMalfait** [comment]
Hey

I'll try this asap, thing is I used a hack :p
I saw that it had the .left class, so I did something like

```css
.left {
    right: 0!important; 
}
```
But this is probably better, thanks!

**Comment by web2style** [comment]
There is controls position option: http://leafletjs.com/reference.html#control-positions

Did it appear recently or I misunderstand smth?

**Comment by PaulLeCam** [comment]
As I wrote in my previous message, it's possible to set this in the control options, not the map ones.

**Comment by PaulLeCam** [comment]
Hi,

The `ZoomControl` as been added to v0.9.

**Comment by RobinMalfait** [comment]
Hey @PaulLeCam thank you very much!

**Comment by jayenashar** [comment]
hi @PaulLeCam i've disabled the zoom control with `zoomControl={false}` as above added a `<ZoomControl>` component with `position`.  it works as i expect, but I don't see the `zoomControl` prop in the https://react-leaflet.js.org/docs/en/components.html#map docs.

**Comment by purveshmakode24** [comment]
How can i set position other than topright, topleft, bottomleft, bottomright??
