### ISSUE TITLE
Sorry to ask it there...

### ISSUE THREAD

**Issue by fredleput** [PaulLeCam/react-leaflet#811]
Je suppose peut-être mal Paul mais je suppose que tu es Français (avec des origines Bretonnes sans doute).
Moi-même je suis de Paimpol et je commence tout juste React / et react-leaftleft. J'arrive à faire la plupart des choses simples mais j'aurai une question à te poser sur "les contextes", en gros comment garder dans le contexte une référence à 1 map que l'on peut manipuler comme on veut par la suite...

 Je n'ai pas trouvé comment te contacter directement sur Git mais c'est sans doute voulu ! Je te serai très reconnaissant de répondre à ce message quand tu auras le temps !

PS1 : Super boulot 👍 

PS2 : I' am able to speak English too if i was mistaken about your nationality !

Thx in advance,

Frédéric Le Put
Brittany, (Paimpol)
France.

**Comment by PaulLeCam** [comment]
Oui je suis Français mais désolé je ne fais pas de support individuel.
Il est possible d'accéder à la référence crée en utilisant [`useMap()`](https://react-leaflet.js.org/docs/api-map#usemap) par example comme indiqué dans la documentation.
