### ISSUE TITLE
Missing documentation v2

### ISSUE THREAD

**Issue by stebogit** [PaulLeCam/react-leaflet#812]
Looks like the [documentation for v2](https://react-leaflet.js.org/legacy) is not found, is there maybe an error in the url?

![Screen Shot 2020-12-14 at 1 56 56 PM](https://user-images.githubusercontent.com/12717225/102140597-51593180-3e14-11eb-8ef0-31a118048fc8.png)

Also, it is quite tricky to get the link to the docs of the old version, would it be possible (best?) to add the link to the main readme?

**Comment by govind-xebia** [comment]
@stebogit  - do you have access to version 2.8 docs? It really would help me! Thanks in advance!

**Comment by stebogit** [comment]
@govind-xebia No I don't, that's why I opened the issue 😅

**Comment by govind-xebia** [comment]
@stebogit - There is way you can get the documentation for v2.8 now if its urgent. You can download [this](https://github.com/PaulLeCam/react-leaflet/tree/3c216dc50839837f1a728ed5782bfbc3b2c0150a) commit and go into the docs directory and run the contents on your localhost.

**Comment by vitoorgomes** [comment]
I don't know if I'm dumb or blind, but I cant seem to find the onClick event on the marker, so I could open a popup, ou even onMouseHover to enable the tooltip, is there something that I'm missing?

```
mapPoints.map((point) => (
<Marker
	key={Math.random() * 999}
	position={[ point['geo']['lat'], point['geo']['lng'] ]}
	onClick={() => setActivePoint(point)}
/>
))
```

I was reading/watching few tutorials, from few months back and all of them have the event, was it removed?

**Comment by PaulLeCam** [comment]
Documentation for previous versions is available in the repository, such as [here for v2](https://github.com/PaulLeCam/react-leaflet/tree/v2/docs)

**Comment by stebogit** [comment]
For anybody interested, I published the old docs [here](https://react-leaflet-v2-docs.netlify.app):
Ref: https://github.com/PaulLeCam/react-leaflet/pull/813#issuecomment-766627824

**Comment by Will-Copeland** [comment]
> Documentation for previous versions is available in the repository, such as [here for v2](https://github.com/PaulLeCam/react-leaflet/tree/v2/docs)

https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/other-layers.js

Missing 404

**Comment by Will-Copeland** [comment]
> For anybody interested, I published the old docs [here](https://react-leaflet-v2-docs.netlify.app):
> Ref: [#813 (comment)](https://github.com/PaulLeCam/react-leaflet/pull/813#issuecomment-766627824)

https://react-leaflet-v2-docs.netlify.app/docs/en/prop-types.html

Also 404. 


:(

**Comment by stebogit** [comment]
@Will-Copeland for as mentioned above ☝🏻 I published the docs at [react-leaflet-v2-docs.netlify.app](https://react-leaflet-v2-docs.netlify.app).
You should see the example of your interest [here](https://github.com/stebogit/react-leaflet/blob/docs-v2/example/components/other-layers.js)
