### ISSUE TITLE
Custom controls overlap with builtin controls

### ISSUE THREAD

**Issue by MasterEric** [PaulLeCam/react-leaflet#816]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

When a custom control (the process for creating this is described [at this official documentation example](https://react-leaflet.js.org/docs/example-react-control) and in issue #706), the default controls (such as ZoomControl and AttributionControl) should be displayed inline with any custom controls which are provided. This functioned as expected in react-leaflet before migrating to v3.

### Actual behavior

The custom control will be rendered in a separate DOM element, and thus these elements will overlap with default style controls if placed in the same corner.

### Steps to reproduce

This fork of the CodeSandbox shown in #706 demonstrates the issue.

https://codesandbox.io/s/layer-control-fork-o9hk4

**Comment by PaulLeCam** [comment]
The example you're referencing is about implementing a custom control in React, not using a Leaflet-provided control. It's up to you to use either depending on your needs considering the associated constraints.

**Comment by MasterEric** [comment]
@PaulLeCam Please load the included example and inspect the DOM of the React control and the Leaflet-provided control.

The issue is that custom React controls are not being rendered in the proper DOM element, resulting in annoying workarounds being necessary to ensure they do not overlap with existing controls.

**Comment by PaulLeCam** [comment]
Again this is an **example** of one way you can implement custom behavior, there is no specific logic in React Leaflet to handle this, it's all up to your custom logic.
