### ISSUE TITLE
Updated 3.0.5 and MapLayer is not exported from 'react-leaflet' (it was 1.7.0)

### ISSUE THREAD

**Issue by umitduran** [PaulLeCam/react-leaflet#818]
## MapLayer Not Found
Hi,

I updated the my react-leaflet library from 1.7.0 to 3.0.5 

In my project i am using HeatMapLayer extends from MapLayer. After updating i am getting this error **'Attempted import error: 'MapLayer' is not exported from 'react-leaflet'.**
Below my code block here
`export default class HeatMapLayer extends MapLayer {
  createLeafletElement() {
    return null;
  }
  componentDidMount() {}
...
}`
What should i do ?

**Comment by silviuburceadev** [comment]
3.x is a breaking change, no MapLayer anymore.

**Comment by umitduran** [comment]
instead of the MapLayer what i will use ?

**Comment by umitduran** [comment]
> 3.x is a breaking change, no MapLayer anymore.

Instead of the MapLayer what i should use ? Do you have any idea ?

**Comment by anajavi** [comment]
> > 3.x is a breaking change, no MapLayer anymore.
> 
> Instead of the MapLayer what i should use ? Do you have any idea ?

Probably you should rewrite it with hooks. Something like this:
```js
const HeatLayer = (props: Props) => {
  const map = useMap();

  useEffect(() => {
    const { data, ...options } = props;

    const heatLayer = Leaflet.heatLayer(data, options);
    map.addLayer(heatLayer);
    return () => {
      map.removeLayer(heatLayer);
    };
  }, [map, props]);
};
export default HeatLayer;
```
