### ISSUE TITLE
LayerControl doesn't disable HexbinLayer

### ISSUE THREAD

**Issue by YasminBaba** [PaulLeCam/react-leaflet#821]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [ ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by YasminBaba** [comment]
I am attempting to use LayerControl to toggle between two different hexbin layers but have run into an issue I can't solve. 
When I select a layer, it successfully appears on the map; however, when I deselect it, it does not disappear. This means if I select another layer, the previous layer remains on the map. Any help would be very appreciated, I have been stuck on this for ages!

I'm using the following package versions:
  "leaflet": "^1.7.1",
  "react": "^17.0.1",
  "react-dom": "^17.0.1",
  "react-leaflet": "^2.1.4",
  "react-leaflet-d3": "^2.0.0"

And here is my simple code:

`
import '../App.css';
import React, { Component } from "react";
import { Map, TileLayer, LayersControl, withLeaflet, MapControl} from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { HexbinLayer } from 'react-leaflet-d3';
import data_postive from "../data/testing_dict_positive.json";
import data_negative from "../data/testing_dict_negative.json";

const WrappedHexbinLayer = withLeaflet(HexbinLayer);
const {Overlay} = LayersControl;

class MapDeltaTransaction extends Component{
  render() {

    const options_postive = {
        colorScaleExtent: [ 1, undefined ],
        radiusScaleExtent: [ 1, undefined ],
        colorRange: [ '#b2d8b2', '#008000' ],
        radiusRange: [ 5, 12 ],
        pointerEvents: ['none'],
    };

    const options_negative = {
        colorScaleExtent: [ 1, undefined ],
        radiusScaleExtent: [ 1, undefined ],
        colorRange: [ '#ffcccc', '#FF0000' ],
        radiusRange: [ 5, 12 ],
        pointerEvents: ['none'],
    };

    return (
      <>

        <Map center={[54, -3]} zoom={5} scrollWheelZoom={false}>
            <TileLayer
                attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            <LayersControl position="topleft">
                <Overlay name="Layer 1"> 
                     <WrappedHexbinLayer data={data_postive} {...options_postive} onEachFeature={onEachFeature} />
                </Overlay>
                <Overlay name="Layer 2"> 
                    <WrappedHexbinLayer data={data_negative} {...options_negative} />
                </Overlay>
             </LayersControl>
        </Map> 
      </>
    );
  }
}
export default MapDeltaTransaction;`

**Comment by PaulLeCam** [comment]
v2 is no longer maintained, v3 is the current version.
