### ISSUE TITLE
WMSTileLayer flickers on re-render

### ISSUE THREAD

**Issue by atlefren** [PaulLeCam/react-leaflet#825]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

WMSTileLayer should not flicker (i.e be re-drawn) unless parameters are changed.

That is, WMSTileLayer should behave the way TileLayer does

### Actual behavior
WMSTileLayer flickers (i.e is re-drawn) when a re-render of the parent is triggered, even if no parameters are changed.

Please describe.

### Steps to reproduce

See https://codepen.io/atlefren/pen/yLaEyNp

Try clicking the button at the bottom, and see that the map flickers

(tested in Opera and Firefox)

### Likely cause:
The updateWMSTileLayer function in WMSTileLayer uses ```!==``` to compare ```props.params``` and ```prevProps.params```

This will return true, even if the params have equal contents, object comparison uses object references. 

https://github.com/PaulLeCam/react-leaflet/blob/e2e36643150c04f190944ec638a5f267358a9ff4/packages/react-leaflet/src/WMSTileLayer.tsx#L30

**Comment by PaulLeCam** [comment]
This is the expected behavior that props comparison is made by reference, it's up to you to keep track of these references rather than creating new objects in every render as you need.

**Comment by atlefren** [comment]
Ok, that is a fair explaination and point. 

However, since I am using a state management library (recoil) to hold a list of WMS-layers, and then render them, I don't think I am able to get the same reference each time. 

Could you add something to the documantation about this?

**Comment by PaulLeCam** [comment]
This is simply how JS works, and how React works, so I'm not really up for having to explicitly document this kind of behavior. If you want to memoize objects, that's what the [`useMemo` hook](https://reactjs.org/docs/hooks-reference.html#usememo) is for.
