### ISSUE TITLE
Documentation v2 still not found ?

### ISSUE THREAD

**Issue by asepkh** [PaulLeCam/react-leaflet#826]
https://react-leaflet.js.org/legacy, please documentation v2 still not found, i want to use react-leaflet-canvas-markers which only supports React-Leaflet v2

**Comment by Lorthiz** [comment]
@asepkh For now I think you can just check documentation on earlier branch here: https://github.com/PaulLeCam/react-leaflet/tree/v2/website/versioned_docs/version-v2
I don't know about that feature so I won't link any specific file. Hope it will help until legacy docs are up.

**Comment by PaulLeCam** [comment]
Yes please use the docs from GitHub, the legacy URL was just temporary for the v3 release.

**Comment by stebogit** [comment]
@asepkh @Lorthiz see https://github.com/PaulLeCam/react-leaflet/pull/813#issuecomment-766627824
