### ISSUE TITLE
Updating className on Tooltip-component does not update underlying class

### ISSUE THREAD

**Issue by karl-run** [PaulLeCam/react-leaflet#828]
## Bug report

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [X] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [-] The issue has not already been reported.
- - Seems to have been a bug a couple of years ago as well, but two major versions ago, #458
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Changing the `className`-prop on the `<Tooltip>`-component should update the underlying DOM-class.

### Actual behavior

The underlying class remains unchanged.

### Steps to reproduce

1. Open CodePen https://codepen.io/karl-run/pen/jOMvGoQ
2. Click `Toggle style`-button
3. Observe that class on tooltip doesn't change.

**Comment by PaulLeCam** [comment]
`className` is not a mutable prop on `Tooltip`, please refer to the the [relevant docs](https://react-leaflet.js.org/docs/api-components#tooltip)

**Comment by impsdc** [comment]
@PaulLeCam Why are you planning to do make the `className` mutable ? Is there a workaround to dynamically apply style ? I do think this would be a useful feature.
