### ISSUE TITLE
Custom component is fully recreated when updating.

### ISSUE THREAD

**Issue by MasterEric** [PaulLeCam/react-leaflet#830]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

When creating a custom map component (using the `createPathComponent` function provided by react-leaflet), two functions are passed, one for creating the element and one for updating the element.

It is expected that when the props of the custom map component are modified, only the update function will be called. This allows any necessary updates to be performed on the layer, and by preventing the create function from being called again, you avoid potentially expensive setup. 

### Actual behavior

However, when updating the props for a custom map component, both the create and update functions will be called.

### Steps to reproduce

1. Use `createPathComponent` to create a custom component.
2. Add print calls to the create and update functions to see when each are called.
3. Use that component in a map.
4. Add a prop to the component which you can easily update (for example, input from a text box).
5. Start the app, and update the prop.
6. Note how both the create and update functions are called.

I have minimally reproduced this issue in the following CodeSandbox:

https://codesandbox.io/s/react-leaflet-forked-fjzt6?file=/src/NewLine.js

**Comment by PaulLeCam** [comment]
Your logic is re-creating the `MapContainer` and all its children every time your `textInput` state changes, that's how React works, it's not specific to using custom components.

**Comment by clementallen** [comment]
Hi @PaulLeCam 

Thanks for looking into this but I still don't think it's working properly.

Here is a code sandbox that has been updated to have no state changes in the `index.js` file where the `MapContainer` is created, yet the custom component still appears to be recreated every time: https://codesandbox.io/s/react-leaflet-forked-hps8j?file=/src/index.js

**Comment by MasterEric** [comment]
> Your logic is re-creating the `MapContainer` and all its children every time your `textInput` state changes, that's how React works, it's not specific to using custom components.

If this is true, than what even is the point to having an `updateElement` argument in the first place?

**Comment by PaulLeCam** [comment]
> Here is a code sandbox that has been updated to have no state changes in the `index.js` file where the `MapContainer` is created, yet the custom component still appears to be recreated every time: https://codesandbox.io/s/react-leaflet-forked-hps8j?file=/src/index.js

The fact the create function is called doesn't mean the result is used, if there is an existing reference it is used instead.

> If this is true, than what even is the point to having an `updateElement` argument in the first place?

None if you decide to re-render your entire map every time anything change in your app, but if you only want to update what is relevant that becomes useful.

**Comment by clementallen** [comment]
@PaulLeCam even if it is not used, a new instance of the underlying leaflet plugin would still be created which is surely inefficient?

**Comment by PaulLeCam** [comment]
Inefficient compared to what? Function calls happen everywhere when rendering React components.
If you're rendering more than necessary that's more likely an issue with the logic of you app.

If you want to use Leaflet in the most efficient way possible, you shouldn't use React Leaflet in the first place. It's meant as an abstraction on top of Leaflet and as such comes with additional cost.

**Comment by nemosmithasf** [comment]
@PaulLeCam To further this issue; can you clarify what the `createPathComponent` does?

I'm running into the same trouble trying to implement the Antpath plugin. The `createElement` function is called every time I pan the map (which triggers a state update). But if I implement the plugin manually using `useEffect`, this problem is solved.

Having read the "core architecture" section of the docs, I'm under the impression that `createElement` was a convenience function for being wrapped in `useEffect`. But there's clearly some misunderstanding.

Can you comment on what I'm misunderstanding?

**Comment by PaulLeCam** [comment]
`createPathComponent` is just a high-level wrapper over these calls: https://github.com/PaulLeCam/react-leaflet/blob/master/packages/core/src/generic.ts#L78-L80.
You can think of the `createElement` call as similar to [React's `createElement`](https://reactjs.org/docs/react-api.html#createelement) that gets called in every render, but that doesn't mean the created element is going to be used/attached to the DOM.
