### ISSUE TITLE
How to reverse  coordinates?

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [PaulLeCam/react-leaflet#835]
a third-party api returns an inverse coordinate to that used by the leaflet.

how to display coordinates correctly?

URL API: https://servicodados.ibge.gov.br/api/v2/malhas/?formato=application/vnd.geo+json

**result** 
![image](https://user-images.githubusercontent.com/9791364/105648361-cd21b180-5e89-11eb-960c-df6e34c02310.png)

the map of brazil should appear

source

import React, { useState, useEffect } from 'react';
import { MapContainer, TileLayer, Marker, Popup, Polygon} from 'react-leaflet';
import L from 'leaflet';
import ReactLeafletGoogleLayer from 'react-leaflet-google-layer';

const defaultLatLng = [-24.89, -51.55];
const zoom = 8;
const purpleOptions = { color: 'purple' }
const multiPolygons = [
  [
    [51.51, -0.12],
    [51.51, -0.13],
    [51.53, -0.13],
  ],
  [
    [51.51, -0.05],
    [51.51, -0.07],
    [51.53, -0.07],
  ],
]
const polygons = async () => {
  let BR = 'https://servicodados.ibge.gov.br/api/v2/malhas/?formato=application/vnd.geo+json'
  let PR = 'https://servicodados.ibge.gov.br/api/v3/malhas/estados/PR?formato=application/vnd.geo+json'
  let response = await fetch(BR)    
  let polygons = await response.json()  

  const geoJsonData = polygons.features[0].geometry
  
  return polygons.features[0].geometry.coordinates
  
}
const Leaflet = () => { 
 const [multiPolygon, setMultiPolygon] = useState(multiPolygons); 
 useEffect(async () => {    // Atualiza o titulo do documento usando a API do browser     
  setMultiPolygon(await polygons())
 }, []); 
 
 console.log(multiPolygon)
 return (
       <div id="mapid">
          <MapContainer center={defaultLatLng} zoom={zoom} scrollWheelZoom={true} l>
        
          <Marker position={defaultLatLng}>
            <Popup>
              A pretty CSS3 popup. <br /> Easily customizable.
            </Popup>
          </Marker>
          <ReactLeafletGoogleLayer apiKey='AIzaSyBReiW....0S2BfTQIGzaY' type={'satellite'} />
          <Polygon pathOptions={purpleOptions} positions={multiPolygon} />
        </MapContainer>
        </div>
   )
}

export default Leaflet;

**Comment by Lorthiz** [comment]
For my knowledge there is no build in solution for that. You can use simple mapping function for that. Even something like this:

```const reversedMultiPolygons = multiPolygons.map(polygon => polygon.map(v => [v[1], v[0]]))```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
