### ISSUE TITLE
Dynamically making tooltip interactive and changing polygon key causes error.

### ISSUE THREAD

**Issue by zdila** [PaulLeCam/react-leaflet#842]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

No error

### Actual behavior

Error:
```
Uncaught TypeError: this._map is null
    removeInteractiveTarget Layer.js:87
    closeTooltip Tooltip.js:352
    unbindTooltip Tooltip.js:296
    removeTooltip react-leaflet.js:891
    React 14
```

### Steps to reproduce

https://codepen.io/zdila/pen/ExNyxMQ

**Comment by PaulLeCam** [comment]
Should be fixed in v3.2, please try it out!
