### ISSUE TITLE
Make more (all) component properties mutable

### ISSUE THREAD

**Issue by zdila** [PaulLeCam/react-leaflet#843]
After migrating from v2 to v3 many properties in react-leaflet are immutable. I think that this goes against React design where all properties are per default treated as mutable. Now in our code we must now compute component `key` from all _immutable_ properties which could mutate to be applied. For example it is common to change interactivity (property `interactive`) dynamically.

Now the only option is to also change key of the component to force it's re-creation wich makes it flash on the screen.

(see also https://stackoverflow.com/questions/65854184/reason-of-making-properties-immutable-in-react-leaflet-v3)

**Comment by PaulLeCam** [comment]
As far as I know there are not more immutable properties in v3 than in previous versions, do you have specific examples please?

This behavior has been since the very first version of this library and is simply based on Leaflet's APIs. 
You can create custom components if you want to implement a different behavior.

**Comment by zdila** [comment]
One example may be property `interactive`.

**Comment by PaulLeCam** [comment]
On the `MapContainer` component? If so, it works differently from `Map` and it shouldn't get re-rendered as much as possible, instead v3 provides [hooks to interact with the map](https://react-leaflet.js.org/docs/api-map#hooks) that should be used instead.

**Comment by zdila** [comment]
No. On `Polyline`, `Polygon` and `Marker`.

**Comment by PaulLeCam** [comment]
As far as I can tell `interactive` has never been a mutable prop in these components in previous versions either, at least it was not documented as such.

**Comment by zdila** [comment]
Then for some reason it worked. In v3 I have to change the `key` to apply `interactive` property change. I will try to prepate a testcase.

**Comment by PaulLeCam** [comment]
If you're relying on undocumented/unexpected behavior from v2 it's not a regression that it's not supported in v3, but rather the expected behavior.

**Comment by tirli** [comment]
@PaulLeCam One more example: `style` property of GeoJSON.  https://codepen.io/tirl95/pen/rNWPWgE
It was mutable in v2, and now you need to use the key to change the style...

**Comment by zdila** [comment]
@PaulLeCam I created a testcase with react-leaflet v2 regarding `interactive` and it doesn't work there too. So finally I think I was wrong and it worked in our app before migrating to v3 for some other reason.

Feel free to close this issue, but maybe first check https://github.com/PaulLeCam/react-leaflet/issues/843#issuecomment-797525847 which may be legit.

Thank you!

**Comment by deadman2000** [comment]
className of MapContainer is no longer mutable. All object's className must be mutable.

I had to create my own classes for this...
Example of Polyline with mutable className:

```jsx
import {createPathComponent} from "@react-leaflet/core";
import {Polyline as LeafletPolyline} from "leaflet";

export const PolylineExt = createPathComponent(
    ({ positions, ...options }, ctx) => {
        const instance = new LeafletPolyline(positions, options)
        return { instance, context: { ...ctx, overlayContainer: instance } }
    },
    (layer, props, prevProps) => {
        if (props.positions !== prevProps.positions) {
            layer.setLatLngs(props.positions)
        }
        if (props.className !== prevProps.className) {
            if (prevProps.className) {
                prevProps.className.split(' ').forEach(c => c && layer.getElement().classList.remove(c))
            }
            if (props.className) {
                props.className.split(' ').forEach(c => c && layer.getElement().classList.add(c))
            }
        }
    }
)
```

**Comment by stephent** [comment]
@PaulLeCam I'm finding this is indeed an issue in moving from v2.8.0 to v3.2.5. Property changes that previously would re-render a component (e.g. `fill` or `fillColor` on `<Circle>`) no longer result in any visible change. Hacking a `key` from these properties fixes the issue.
