### ISSUE TITLE
Pass User-Defined Props to Markers

### ISSUE THREAD

**Issue by athenawisdoms** [PaulLeCam/react-leaflet#845]
Hello, is it possible to pass user-defined properties to the `Marker` component in a TypeScript-friendly way? 

```js
<Marker
    position={[marker.lat, marker.lon]} 
    key={index}
    count={marker.count}    // <==== user-defined prop
/>
```

I like to retrieve these user-defined properties (such as `count` in the above example) inside a function passed into the `iconCreateFunction` prop of the [MarkerClusterGroup component](https://github.com/yuzhva/react-leaflet-markercluster), achieving something similar to https://github.com/Leaflet/Leaflet.markercluster/issues/901#issuecomment-610723716

```js
iconCreateFunction: function (cluster) {
  const childMarkers = cluster.getAllChildMarkers();
  let myCustomCount = 0;
  for (const childMarker of childMarkers) {
    myCustomCount += childMarker.count;               // <=== using the user-defined prop
  }
  return L.divIcon({ html: '<b>' + myCustomCount + '</b>' });
}
```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
