### ISSUE TITLE
<MapContainer> ref not backward compatible with <Map> ref

### ISSUE THREAD

**Issue by laurencefass** [PaulLeCam/react-leaflet#846]
## Bug report

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x ] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ x] The issue has not already been reported.
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

I have recently upgraded React Leaflet to replace the <Mao> with the <MapContainer> and refs are no longer working because it appears that Map was a class component and MapContainer is a function component. However I have a lot of code where I need to access the ref.current.LeafletElement which means (currently) I cant upgrade. 

Errors are in accord with official React docs which states "You may not use the ref attribute on function components because they don’t have instances". See https://reactjs.org/docs/refs-and-the-dom.html 

It also states: "If you want to allow people to take a ref to your function component, you can use forwardRef (possibly in conjunction with useImperativeHandle), or you can convert the component to a class."

I have a lot of code accessing the leafletmap directly but this no longer appears possible. How do i get the leafletmap?
 
Previous version (working code)

```
constructor() {
    this.refmap = createRef();
}
ComponentDidMount() {
   let myMap = this.refmap.current.leafletElement;
   myMap.getZoom() // works
}
render() {
   <Map ref={this.refmap}>
}

```
### Actual behavior

I've replaced the <Map> with <MapContainer> and the program fails

TypeError: Cannot read property 'leafletElement' of null InteractiveMapClass.componentDidMount
  error: let myMap = this.refmap.current.leafletElement;

### Steps to reproduce
Here's a working version with RL 2.1 
https://codesandbox.io/s/react-leaflet-21-useref-u3bb4?file=/src/index.js

Please provide the simplest example possible to reproduce the issue:
Here's the exact same code with RL 3.1 and latest React/Leaflet using <MapContainer>
https://codesandbox.io/s/react-leaflet-31-useref-ztnli?file=/src/index.js

**Comment by Rennzie** [comment]
hi @laurencefass, 

A ref for the map is no longer available in version three. Please have a look at these issues for background: https://github.com/PaulLeCam/react-leaflet/issues/806, https://github.com/PaulLeCam/react-leaflet/issues/841 . 

In your case I suggest you either use a similar approach my example in https://github.com/PaulLeCam/react-leaflet/issues/841 or consider a custom child component that uses `useMap` to access the map instance.

I can't tell exactly what you are using the zoom value for when your component mounts but something like this could work:

```javascript

function GetZoom(){
  const mapInstance = useMap()

  useEffect(() => {
    const zoom = mapInstance.getZoom()
    // do something with zoom
  },[])

  return null
}

// then render <GetZoom/> inside the MapContainer

```

I hope that helps.

**Comment by laurencefass** [comment]
thanks for info i have a bit of restructuring to upgrade but all makes sense.
