### ISSUE TITLE
Extend MapContainerProps for options from Leaflet.loading addInitHook

### ISSUE THREAD

**Issue by davetapley** [PaulLeCam/react-leaflet#847]
Leaflet's [`addInitHook`](https://leafletjs.com/examples/extending/extending-3-controls.html) permits additional parameters to be passed in with `props` here:
https://github.com/PaulLeCam/react-leaflet/blob/85d68d114d6080ff8d292fc866cae01e2780cdfd/packages/react-leaflet/src/MapContainer.tsx#L38

You can see an example of this in [Leaflet.loading](https://github.com/ebrelsford/Leaflet.loading)'s `loadingControl` [here](https://github.com/ebrelsford/Leaflet.loading/blob/7b22aff19a5a8fa9534fb2dcd48e06c6dc84b2ed/examples/simple.html#L23-L30).

---

However `props` is given as ⬇️ , thus it's not possible to pass `loadingControl` in without a type error.
https://github.com/PaulLeCam/react-leaflet/blob/85d68d114d6080ff8d292fc866cae01e2780cdfd/packages/react-leaflet/src/MapContainer.tsx#L18

This can be avoided with [`@ts-ignore`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments), but:
Would a PR be accepted to allow an `extends MapContainerProps` to be given?

---

See https://github.com/ebrelsford/Leaflet.loading/issues/48 for the other side of this 😊

**Comment by PaulLeCam** [comment]
> Would a PR be accepted to allow an `extends MapContainerProps` to be given?

Do you have a simple example of what that would change please?
I don't want to add properties specific to a given plugin but if you have a generic solution that would work for your case yes please open a PR!

**Comment by davetapley** [comment]
I have tried it, but I _assume_ that [Generic Type Definitions with Type Parameter Defaults](https://mariusschulz.com/blog/generic-parameter-defaults-in-typescript#generic-type-definitions-with-type-parameter-defaults) could be allowed to keep existing behavior, but allow for things like:

```js
interface MapContainerWithPluginsProps extends MapContainerProps {
  myExtraOption: string
}

const MapContainerWithPlugins = MapContainer<MapContainerWithPluginsProps>

return (
  <MapContainerWithPlugins zoom={13} myExtraOption="value"> ...
```

And not end up with a type error in TypeScript.

**Comment by PaulLeCam** [comment]
Sounds good, yes please feel free to open a PR to make that change if you want 👍

**Comment by devgioele** [comment]
It looks like this PR was never made
