### ISSUE TITLE
ImageOverlay fails to update bounds when they are an array

### ISSUE THREAD

**Issue by liwp** [PaulLeCam/react-leaflet#849]
The react-leaflet [documentation](https://react-leaflet.js.org/docs/api-components#mediaoverlay-behavior) claims that updates to the `bounds` prop of an `ImageOverlay` are passed to the underlying leaflet element.

But this does not happen if the bounds are described as an array rather than a leaflet `LatLngBounds` object - eg

```js
// does not work
[
  [49.3974648, -10.9672241],
  [59.603405, 2.7442017],
]
```

vs

```js
// works
latLngBounds([
  [49.3974648, -10.9672241],
  [59.603405, 2.7442017],
])
```

I think [this](https://github.com/PaulLeCam/react-leaflet/blob/master/packages/core/src/media-overlay.ts#L23) is the culprit.

The workaround is to convert array bounds to `L.LatLngBounds` instances before passing them to `<ImageOverlay .../>`, which is fine, but the documentation remain misleading.

**Comment by justrealmilk** [comment]
This is still an issue and the above work around works well!

**Comment by PaulLeCam** [comment]
Indeed the docs were incorrect, it should be fixed now.
