### ISSUE TITLE
Changing the Marker styling options

### ISSUE THREAD

**Issue by aauberg** [PaulLeCam/react-leaflet#85]
Is there a method for changing the marker styling options?
The Marker tag picksup the 'position' attribute, does it also pickup 'color' or something like that?

**Comment by bradsimantel** [comment]
Leaflet markers don't have a `color` option, but they do have an `icon` option, and React-Leaflet will update your map when the value of that option changes. You can read more about Leaflet's `icon` here: http://leafletjs.com/reference.html#icon.

**Comment by aauberg** [comment]
I wondered about that, thanks @PaulLeCam !
