### ISSUE TITLE
pathOptions can take a function but it's not documented

### ISSUE THREAD

**Issue by Rennzie** [PaulLeCam/react-leaflet#851]
## Missing Documentation

I've managed to use `pathOptions` in a `GeoJSON` component as a function. The function is passed a feature as an argument and is called once for each feature in a `FeatureCollection`. The behaviour is similar to the `onEachFeature` except there is no `layer` argument as a second param. 

I'm not sure if this is expected or not but either way I've found it very valuable and would like to get it documented. Even better would be if the `layer` argument could also be passed in this case?

To illustrate:

```javascript

<GeoJSON
  data={fooFeatureCollection}
  pathOptions={ feature => {
      // do something with feature
  }}
/>

``` 

I'm not sure if this works on anything other than a `FeatureCollection`

**Comment by PaulLeCam** [comment]
I don't know why you're seeing this behavior, it might be something specific Leaflet does but it's not expected as far as React Leaflet's logic is concerned, so I wouldn't recommend to rely on it.

**Comment by Rennzie** [comment]
Ok thanks @PaulLeCam. I tried to find it in leaflets documentation but came up empty too.
