### ISSUE TITLE
Uncaught TypeError: mapEvent.setCenter is not a function

### ISSUE THREAD

**Issue by dancesWithCycles** [PaulLeCam/react-leaflet#856]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Hi folks, following the documentation on the website I wanted to use the ```useMapEvent``` hook to set the center location of the map using the ```setCenter``` call. I expected a log message and the map to center on the respective location.

### Actual behavior

The browser dev tools responded with the following error message.
```Uncaught TypeError: mapEvent.setCenter is not a function```
The map did not center on the respective location.

### Steps to reproduce

Here is my map function:
```
import React from 'react';  
// map is invisible without the following CSS
import './map.css';
import  {MapContainer,TileLayer} from 'react-leaflet';
// map is BROKEN without zoom attribute
import 'leaflet/dist/leaflet.css';
import TestMapComponent from './testMapComponent';

const Map=()=>
{
    return(
	//create Leaflet Map instance and provide it to its child components
            <MapContainer
	id="map"
        className="map"
        // map is invisible without center attribute
        center={[0,0]}
        // map is invisible without zoom attribute
        zoom={2}>
                
            <TileLayer
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            attribution="&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
            />

	<TestMapComponent/>
        </MapContainer>
        ); 
}
export default Map;
```

Here is my map child component:
```
import {useMap} from 'react-leaflet';
import {useMapEvents} from 'react-leaflet';
import {useMapEvent} from 'react-leaflet';

function TestMapComponent(){
    
    const map=useMap()
    console.log('center: '+map.getCenter())

    const mapEvent=useMapEvent('click',()=>{
	console.log('set center')
	mapEvent.setCenter([50.5, 30.5])
    })
    return null
}
export default TestMapComponent
```

I would be very thankful for any advice.

Cheers!

**Comment by silviuburceadev** [comment]
Maybe a typo? (`map.setCenter` instead of `mapEvent.setCenter`)

**Comment by PaulLeCam** [comment]
Please provide a simple example of the issue using [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP)

**Comment by ucin3d** [comment]
Not a typo. Tried both.  Any thoughts?
