### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dgodglue** [PaulLeCam/react-leaflet#859]
I used this example

```
Copied wrong example code, read below
```

and my website is blank

**Comment by tirli** [comment]
@dgodglue 
- [ ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).


That checklist in the issue creation template is there for a reason. And there is a bright yellow notice in [docs](https://react-leaflet.js.org/docs/start-installation#leaflet-prerequisites) that mentions what you need to do.

**Comment by dgodglue** [comment]
Yes I checked all these steps and my map is working but when I want to extends with hooks like example doesn't work. Weird.

**Comment by tirli** [comment]
@dgodglue https://codepen.io/tirl95/pen/NWbodjE it works

**Comment by dgodglue** [comment]
Damn I am so sorry, i copied the wrong example

i meant this:

`function MyComponent() {
  const map = useMap()
  console.log('map center:', map.getCenter())
  return null
}

function MyMapComponent() {
  return (
    <MapContainer center={[50.5, 30.5]} zoom={13}>
      <MyComponent />
    </MapContainer>
  )
}`

**Comment by tirli** [comment]
Works anyway :) https://codepen.io/tirl95/pen/OJbdWwa

Make a reproducible example in code pen. If you cannot - then the problem is 99% on your side
