### ISSUE TITLE
Reactangle didn't unmount if it is inside LayersControl

### ISSUE THREAD

**Issue by tirli** [PaulLeCam/react-leaflet#860]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported. **Maybe related to https://github.com/PaulLeCam/react-leaflet/issues/832**
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Rectangle disappears when LayersControl (its parent) disappears

### Actual behavior

Rectangle remains on a map without the possibility to remove it.

### Steps to reproduce

https://codepen.io/tirl95/pen/dyOaORP

**Comment by PaulLeCam** [comment]
Should be fixed in v3.2, please try it out!

**Comment by vsevolod-masterdelivery** [comment]
not fixed.

**Comment by klizogubova** [comment]
@vsevolod-masterdelivery it is fixed. I tried to change the version in my codepen to 3.2, and Rectangle disappeared as expected.
