### ISSUE TITLE
update Marker map in defaultValue

### ISSUE THREAD

**Issue by hosseindelara** [PaulLeCam/react-leaflet#861]
At the time of update Marker The user has entered the profile Received from the server.
  It is set based on the following code But it does not move when the user wants to move on the map
This problem in browsers google chrome and mozilla windows
Is, but not in mobile mode

`import { memo, useCallback, useEffect, useMemo, useState } from 'react';

import { MapContainer, TileLayer, Marker, Popup, useMapEvents } from 'react-leaflet';
import "leaflet-defaulticon-compatibility";

import 'leaflet/dist/leaflet.css'
import "leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.css";

const LocaconoUser = ({ defaultValue, handelValue, name }) => {

    function LocationMarker() {
        const [position, setPosition] = useState(defaultValue ? defaultValue : null)
        const map = useMapEvents({
            click: (e) => {
                console.log(e);
                setPosition(e.latlng)
                map.locate()
                handelValue(name, { lat: e.latlng.lat, lng: e.latlng.lng })
                map.getCenter()
                console.log(map.getCenter());

            },

        })

        return position === null ? null : (
            <Marker position={position}>

            </Marker>
        )
    }

    return (
        <>
            {
                defaultValue ?
                    <MapContainer
                        style={{ width: '100%', height: 'auto', minHeight: '300px', borderRadius: '20px' }}
                        center={defaultValue}
                        zoom={18}
                        scrollWheelZoom={false}
                        openSearchOnLoad={true}

                    >
                        <TileLayer
                            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        />
                        <LocationMarker />

                    </MapContainer>
                    :
                    <MapContainer
                        style={{ width: '100%', height: 'auto', minHeight: '300px', borderRadius: '20px' }}
                        center={{ lat: 35.7023643, lng: 51.4467067 }}
                        zoom={15}
                        scrollWheelZoom={false}
                        openSearchOnLoad={true}

                    >
                        <TileLayer
                            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
                            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        />
                        <LocationMarker />

                    </MapContainer>
            }
        </>

    )

}

export default memo(LocaconoUser)`

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
