### ISSUE TITLE
[SvgRenderer/CanvasRender - same issue] Support to render circleMarker on top of polylines. Polylines should not cross over circle markers.

### ISSUE THREAD

**Issue by vissharm** [PaulLeCam/react-leaflet#863]
As we cannot have interaction in multiple canvas/map-panes. One layer will block others. I don't want to go into the workarounds here. But at least can we have support to draw circle markers later than polylines. So click on the circle markers should not fire clicks on polylines.
Also what about supporting drag on circle marker? Is there any way?

This issue exists with the SVG renderer also. CircleMarkers will be rendered first and then polylines. The canvas I want circle-markers to painted last to stay on top of polylines. This is a very genuine problem especially when the interaction between canvas layers is an issue.

![Screenshot 2021-03-25 at 2 26 47 AM](https://user-images.githubusercontent.com/21159071/112392057-d8c11580-8d1e-11eb-9cf9-943486c7a8cb.png)

**Comment by vissharm** [comment]
This is the case with both canvas and SVG renderer. I don't want multiple panes to increase my complexity of interaction.

I want interaction on polyline but you can see the polyline is rendered on top of circle-marker. So the line got clicked instead of the circle marker. Let me know if I am still bad at explanation. Please open the issue I verified it both with canvas and svg renderer.

Polylines and CircleMarkers rendered in the same leaflet layer and what I can see from rendering behaviour is that polylines are always rendered on top of circle marker. I am using react-leaflet and passing all the items at once. It just a wrapper around it so this must be something that is missing at leaflet i.e. to support user-defined order between polylines, circle-markers and other kinds of elements that exist at the same layer..

**Comment by vissharm** [comment]
@PaulLeCam I am creating an array of circle markers and then the array of polylines and contacting both arrays and passing it as a child to the leaflet map node. something like this

<LeafletMap
   ...
>
    {Array containing polylines and circle-markers}
</LeafletMap>

**Comment by vissharm** [comment]
@PaulLeCam - I am not sure what mistake I am doing.... if I do an example and rendering a polylines first and then circle marker within leaflet map it draws items on the canvas in same order ie. circle marker at top.
But when I pass polylines array and circle markers array as children to leaflet map... it always renders polylines on top of it irrespective of which array I place first as children. What silly mistake I am doing....I tried every debugging.....

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
