### ISSUE TITLE
Performance issues - initial loading is too slow with many geojsons

### ISSUE THREAD

**Issue by AndrejGajdos** [PaulLeCam/react-leaflet#865]
If you try to render ~40K [GeoJSONs](https://react-leaflet.js.org/docs/api-components/#geojson) in canvas mode, initial rendering is too slow. It takes ~30 seconds (~60 seconds in codesandbox) when map renders.

If you use Leaflet's [GeoJSON](https://react-leaflet.js.org/docs/api-components/#geojson), instead of react-leaflet  [GeoJSONs](https://react-leaflet.js.org/docs/api-components/#geojson), initial rendering takes few seconds.

### Steps to reproduce

1.) Allow [CORS](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf) in your browser. I created a basic web service deployed on Heroku, which returns ~40k objects.

2.) Open [codesandbox](https://codesandbox.io/s/elastic-murdock-o02n6?file=/src/MarkerClusterContainer.js)

**Comment by PaulLeCam** [comment]
Using React and React Leaflet are additional abstractions so it is expected the performance would be lower than using Leaflet directly.

**Comment by AndrejGajdos** [comment]
@PaulLeCam how is this expected, based on what, your experience?

Wouldn't it be a good idea to mention it somewhere? In Readme or documentation?
