### ISSUE TITLE
Custom controls do not block MapContainer propagation

### ISSUE THREAD

**Issue by Lorthiz** [PaulLeCam/react-leaflet#866]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Somekind of Element/mechanism that will allow blocking popagation for custom controls.
```
<CustomMapControl>
     <YOUR_JSX>
</CustomMapControl/>
```

### Actual behavior

Custom controls created using public API are just a React elements. There is no way to prevent event propagation since MapEvents are fired first. 

### Steps to reproduce

1) Open CodePen example: https://codepen.io/PaulLeCam/pen/xxOgovP
2) Replace js code:

```
const { MapContainer, TileLayer, Marker, Popup, useMapEvents, useMap} = ReactLeaflet;
const {useState} = React;

  const style = {
    backgroundColor: "black",
    padding: "2em",
    color: "white"
  };

function MapClickEvent({ setPosition }) {
  useMapEvents({
    click: (e) => {
      const newPos = {
        lat: e.latlng.lat.toFixed(2),
        lng: e.latlng.lng.toFixed(2)
      }
      console.log(`MAP CLICK - setting new position to:\t\tlat:${newPos.lat} lng:${newPos.lng}`);
      setPosition(newPos);
    },
    contextmenu: () => {}
  });

  return null;
}

function MoveToPositionControlButton({ postion }) {
  const map = useMap();


  const onClick = () => {
    console.log(`BUTTON CLICK moving to position:\t\t\tlat:${postion.lat} lng:${postion.lng}`);
    map.panTo(postion);
  };

  return (
    <div className="leaflet-top leaflet-right">
      <div className="leaflet-control leaflet-bar">
        <div className="button-control" onClick={onClick} style={style}>
          PAN TO MARKER POSITION
        </div>
      </div>
    </div>
  );
}

function ReactControlExample() {
  const [lastClickPosition, setLastClickPosition] = useState({
    lat: 51.505,
    lng: -0.09
  });
  
  return (
    <MapContainer center={[51.505, -0.09]} zoom={6}>
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <Marker position={lastClickPosition} />
      <MoveToPositionControlButton postion={lastClickPosition} />
      <MapClickEvent setPosition={setLastClickPosition}/>
    </MapContainer>
  );
}

ReactDOM.render(<ReactControlExample />, document.getElementById("container"));
```

3) Click on zoom control in left-upper corner to see that events are blocked and marker position is not changed.
4) Click around the map to see that marker position is changed with each click.
5) Click on custom control to see that marker is moved there and after that panning is executed.
6) Check console to confirm that events executed this order: MapEvents => OnClick assigned to button that is supposed to be above map

Or I can just be stupid af... and I don't see any other tutorial/documentation on how we are supposed to create custom controls other than this one: https://react-leaflet.js.org/docs/example-react-control

**Comment by ted-piotrowski** [comment]
This worked to stop click/drag events from propagating through to the map:

```
const MyControl = () => {
  const ref = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (ref.current) {
            L.DomEvent.disableClickPropagation(ref.current);
        }
    });

  return (
    <div ref={ref}>
       ... YOUR JSX
    </div>
  )
};

**Comment by Lorthiz** [comment]
Wow! Very clean solution! I used one I found here: https://github.com/LiveBy/react-leaflet-control/issues/44
I think I will rewrite my component to your solution for easier maintnance, Thanks! :)

**Comment by alivtar** [comment]
@ted-piotrowski  Assigning `ref` to the element that I wanted to stop the propagation from, did the job. Thanks a lot;

**Comment by Lokolin** [comment]
@ted-piotrowski thanks for solution

**Comment by charlieforward9** [comment]
> This worked to stop click/drag events from propagating through to the map:
> 
> ```
> const MyControl = () => {
>   const ref = useRef<HTMLDivElement>(null);
> 
>     useEffect(() => {
>         if (ref.current) {
>             L.DomEvent.disableClickPropagation(ref.current);
>         }
>     });
> 
>   return (
>     <div ref={ref}>
>        ... YOUR JSX
>     </div>
>   )
> };
> ```

This does not work with ReactSlider package. I am unable to use the slider component when this useEffect method is included.
