### ISSUE TITLE
Shape properties does not update in Next js

### ISSUE THREAD

**Issue by joms** [PaulLeCam/react-leaflet#871]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [X] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

When changing the property like color of a shape (e.g. `CircleMarker` or `PolyLine`), the view would update accordingly (shape changes color) whilst in developer mode and mechanics like HMR are enabled.

When programmatically changing the property of a a shape (.e.g `CircleMarker` or PolyLine`), by for instance updating the color. The shape should update accordingly with the new color.

### Actual behavior

Color or property remains unchanged until a complete refresh is done.

### Steps to reproduce

Example: https://codesandbox.io/s/leafletjs-with-nextjs-forked-1lenk?file=/component/map.jsx
(forked and modified from https://dev.to/tsaxena4k/integrating-next-js-with-leaflet-js-mapbox-1351)

In this example, the black circle should change color to pink on hover. I have implemented this using Create React App, and it worked like a charm. However, when implementing it using Next, it does not seem to work the same way.

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by joms** [comment]
Hi! Thanks for your reply.

> Please only use GitHub issues to report possible bugs in the library.

Could you elaborate on why you don't think this is a bug in the library?

As an update I can also confirm that I'm experiencing the exact same issue in Remix. However changing the objects size works, so I have a feeling there's a bug concerning the updating of colors.
I tried looking into the source to check if I was able to debug it, but I didn't really get a grasp on it.

**Comment by PaulLeCam** [comment]
These props are not mutable, you should use `pathOptions` instead.
