### ISSUE TITLE
[Question] Fullscreen support

### ISSUE THREAD

**Issue by dngconsulting** [PaulLeCam/react-leaflet#872]
Hello,
Thanks for this great react wrapper.
Do you have any fullscreen support ? How can I use the MapContainer component or any third party plugin to add a fullscreen control ?
Thanks
Sami

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.

**Comment by dngconsulting** [comment]
Thanks a lot @elangobharathi , this is exactly what I was looking for. You rock 👍
