### ISSUE TITLE
Marker eventHandler mouseover bug

### ISSUE THREAD

**Issue by JaviCodess** [PaulLeCam/react-leaflet#873]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [ x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [ x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ x] The issue has not already been reported.
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

When i put the mouse over the circle it shows a circle showing the area of the marker, and when i put the mouse out of the marker the circle should disappear.

### Actual behavior

If i put the mouse over the marker the circle appears, but if the mouse is out, the circle is still there, unless i put the mouse over other marker.

### Steps to reproduce

This bug only happens when there is a setter(setRangeData in this case) inside the mouseover, if its not it works propperly.
```
             {bts.map((b, index) => {
                  let redIcon = new L.AwesomeMarkers.icon({
                    icon: renderToStaticMarkup(
                      <i className=" fa fa-broadcast-tower fa-3x" />
                    ),
                    prefix: "fas",
                  });
                  
                  return (
                    <>
                      {BT ? (
                        <>
                          <Marker
                            key={b.id}
                            icon={redIcon}
                            position={[b.lat, b.lon]}
                            eventHandlers={{
                              mouseover: (e) => {
                                console.log("mouseover");
                                setRangeData([b.lat, b.lon, b.range_bts]);
                             
                              },
                              mouseout: (e) => {
                                console.log("mouseout");
                                setRangeData([0, 0, 0]); //i set 0 to make the circle disappear
                              },
                            }}
                          >
                            <Popup>
                              <h4>Lat: {b.lat}</h4>
                              <h4>Lon: {b.lon}</h4>
                              <h4>Range: {b.range_bts}</h4>
                              <h4>Network: {b.network_name}</h4>
                            </Popup>
                            <RangeSpec /> //this is the const where i apply the rangeData to create the circle
                          </Marker>
                        </>
                      ) : null}
                      {range ? (
                        <Circle
                          key={b.id}
                          center={[b.lat, b.lon]}
                          radius={b.range_bts}
                        ></Circle>
                      ) : null}
                    </>
                  );
                })}
```

**Comment by PaulLeCam** [comment]
Please provide a simple example of the issue using [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP)

**Comment by JaviCodess** [comment]
Done. But is still not working.

**Comment by PaulLeCam** [comment]
If you don't provide a link to a CodePen showing the issue I won't start looking into it.

**Comment by JaviCodess** [comment]
Sorry, i thought it was in the link you send before, i never used codepen before. Here it is. https://codepen.io/javicodess/pen/vYxXVVY

**Comment by PaulLeCam** [comment]
Your codepen example doesn't run.
