### ISSUE TITLE
Make quick-start guide a no-brainer

### ISSUE THREAD

**Issue by vovayartsev** [PaulLeCam/react-leaflet#875]
## Feature request

This is largely a duplicate of https://github.com/PaulLeCam/react-leaflet/issues/859, but I've created a separate issue just because I'm willing to make a contribution PR if my suggestion is approved.

### Steps to reproduce

1. Create a fresh React app using [Create React App](https://reactjs.org/docs/create-a-new-react-app.html)
2. Skip the big orange banner 🤷
3. Follow steps from [Getting Started](https://react-leaflet.js.org/docs/start-installation) and copy-paste the `<MapContainer...` snippet into the fresh `App.js`
4. Received a "broken" map because CSS was not loaded:
![image](https://user-images.githubusercontent.com/204231/117975351-a6579000-b33f-11eb-9293-77f7148a7798.png)
5. Added CSS and got an empty map, because the container's height was `0`

### Issue I had

My confusion happened from the fact that this line below makes an impression that `leaflet` is there already:

```
npm install react react-dom leaflet
```

Yes I've noticed the big orange banner and read through [Leaflet's Quick Start Guide](https://leafletjs.com/examples/quick-start/) - but I thought that it's a bit irrelevant as it suggests adding CSS and JS via `<script>` and `<link>` tags... while I'm adding leaflet via `npm`.

Also using CDN version of `leaflet.css` + NPM version of `leaflet.js` sounds like decoupling things that should be bundled together.

### Proposal

1. Update the [Getting Started](https://react-leaflet.js.org/docs/start-installation) guide to rely on `leaflet.css` from NPM rather than from CDN
2. Update the snippet to include height on `<MapContainer>`
3. Drop the orange banner - it's not required anymore
 
Here's the minimalistic `App.js` which worked for me:

```
import './App.css';
import { MapContainer, TileLayer} from 'react-leaflet'

import "leaflet/dist/leaflet.css"     // <----- using NPM version, not the CDN one

function App() {
  return (
    <MapContainer center={[51.505, -0.09]} zoom={13} style={{height: 400}}>
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
    </MapContainer>
  );
}

export default App;
```

**Comment by PaulLeCam** [comment]
Don't skip the big orange banner
