### ISSUE TITLE
Is there anyone who tried to implement proj4leaflet plugin?

### ISSUE THREAD

**Issue by sabit990928** [PaulLeCam/react-leaflet#878]
Hello guys! Thanks for the good library
I raised project in Next JS. Most of functionality works fine, I used lat/long to display element and for coordinate system in general.
Then business said that it's important to take data ed-50/utm 32N coordinate system, it's the one called Cartesian coordinate system. After some research I found that there's a plugin in leaflet official page to achieve it. I'm actually a bit stucked by that problem, it seems not that hard and even there's examples in docs. 

Is there anyone who tried to implement [proj4leaflet](https://github.com/kartena/Proj4Leaflet)?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
