### ISSUE TITLE
Hooks version of L.Routing.control

### ISSUE THREAD

**Issue by ebisLab** [PaulLeCam/react-leaflet#884]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x ] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [ x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x ] The issue has not already been reported.
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Please describe.
It seem that there's no access to L.Routing over version 3 and up. 

### Actual behavior

Please describe.
It erroring out.
Keep getting 

```TypeError
Super expression must either be null or a function
```

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).
Downgrade react-leaflet version to anything under 3.0

https://codesandbox.io/s/react-leaflet-routing-machine-update-yr6zx?file=/src/RoutingMachine.js

**Comment by PaulLeCam** [comment]
v3 APIs are different from v2, that why it's a major version change.
