### ISSUE TITLE
Popup content is not refreshed

### ISSUE THREAD

**Issue by ShardanaSoft** [PaulLeCam/react-leaflet#894]
### Expected behavior

Once the marker is clicked, popup open correctly, but its content never change. For example it show a timestamp generated when popup open. When I close and re open the same popup, timestamp is not re-generated.

### Actual behavior

Popup content don't change

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

js code 
`const { MapContainer, TileLayer, Marker, Popup } = ReactLeaflet

function SimpleExample(props) {
  return (
    <MapContainer center={props.position} zoom={13}>
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url='https://{s}.tile.osm.org/{z}/{x}/{y}.png'
        />
      <Marker 
        position={props.position}>
        <Popup
          onOpen={()=>console.log('this is called onOpen')}>
          {console.log('this is called only once')}
          A pretty CSS3 popup. <br/> Easily customizable.
        </Popup>
      </Marker>
    </MapContainer>
  )
}
ReactDOM.render(<SimpleExample position={{ lat: 51.505, lng: -0.09 }} />, document.getElementById('container'))`

**Comment by arigon** [comment]
Are there any news on this? It shouldn't be that hard to implement it because Popup has an update method which will rerender the content of the Popup. Only react-leaflet is missing this, yet.

**Comment by ShardanaSoft** [comment]
Hi @arigon , I've solved this by wrapping the Popup component inside another custom component. Inside onCLose event listener I call a function that modify a state

```
const MyPopup = ({ place }: MyPopupProps) => {
  const [, setCount] = useState(0);

  return (
    <Popup
      autoClose={true}
      onOpen={() => {}}
      onClose={() => {
        setCount((prev) => prev + 1);
      }}
      maxWidth={3000}
      closeButton={false}
      className={getColorByPlaceType(place.type)}
    >
      <PopupContent place={place} />
    </Popup>
  );
};
```
"It ain't much, but it's honest work"
At the moment, no bug revealed, and I'm using it with 500.
