### ISSUE TITLE
[v3.2.0] Markers aren't unmounting

### ISSUE THREAD

**Issue by TurtIeSocks** [PaulLeCam/react-leaflet#898]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior
Markers unmount when navigating off screen and remount when navigating back to their position

### Actual behavior
Markers stay mounted and continue to mount additional clones of the markers, notably without their popup info. See below screenshots. While the screenshots depict this behavior using DivIcons since it was much more apparent what was happening, this also happens while using a standard Leaflet Icon class as shown in the code examples.

### Steps to reproduce

Basic code:

Component:
```js
        <Marker
          position={[item.lat, item.lon]}
          icon={(basicMarker(iconUrl, size)}
        >
          <Popup position={[item.lat, item.lon]}>
            <PopupContent
              item={item}
              iconUrl={iconUrl}
              userSettings={userSettings}
            />
          </Popup>
        </Marker>
```

`basicMarker return`:
```js
  return new Icon({
    iconUrl,
    iconSize: [size, size],
    iconAnchor: [size / 2, size / 2],
    popupAnchor: [0, size * -0.6],
    className: 'marker',
  })
```
Expected:
<img width="61" alt="Screen Shot 2021-07-07 at 4 23 06 PM" src="https://user-images.githubusercontent.com/58572875/124824328-3846d800-df40-11eb-9ff8-5eb4b980907b.png">

Examples of not unmounting:
<img width="109" alt="Screen Shot 2021-07-07 at 4 22 43 PM" src="https://user-images.githubusercontent.com/58572875/124824349-4268d680-df40-11eb-9a38-8cfef46e1530.png">

With React Clustering for better visibility:
<img width="209" alt="Screen Shot 2021-07-07 at 4 22 27 PM" src="https://user-images.githubusercontent.com/58572875/124824348-4268d680-df40-11eb-8da7-c64c9f70be00.png">

**Comment by ShardanaSoft** [comment]
Hi, possible duplicate #832 ? See my answer, for now, it solved for me

**Comment by TurtIeSocks** [comment]
Sounds like a similar issue but might be notable to Paul that this issue wasn't present (for me at least) with `react-leaflet v3.1.0/core@1.0.2` and became an issue when I attempted to update to `react-leaflet v3.2.0/core@1.1.0`.
