### ISSUE TITLE
Popup's `renderPopupContent` isn't called with leaflet v1.0.0-beta2

### ISSUE THREAD

**Issue by alendit** [PaulLeCam/react-leaflet#90]
Hi, the popups are rendered empty with the newest leaflet beta. 

On a related note: since you've made plans to port `react-leaflet` maybe it would make sense to release a very early alpha version which would specify the newest beta in it's dependencies to encourage testing. In my experience `react-leaflet` mostly works with the newest version, with minor exceptions.

**Comment by PaulLeCam** [comment]
Hi,

Leaflet v1 is not supported by this lib.
Its API is not stable yet and there are still features of v0.7 that are not implemented in this lib, so this is my main focus until Leaflet v1 is stable.
