### ISSUE TITLE
React-leaflet map fails to start

### ISSUE THREAD

**Issue by AbolfazlHeidarpour** [PaulLeCam/react-leaflet#900]
## Bug report
I created a react app with create-react-app, I installed leaflet, leaflet-draw, react-leaflet, react-leaflet-draw. I run following code with npm start but got error...

```
import React, { useState } from 'react';
import { MapContainer, TileLayer } from 'react-leaflet';
import { EditControl } from 'react-leaflet-draw';

const App = () => {
  const [center] = useState({lat: 50, lng: 40});
  return (
    <MapContainer center={center} zoom={12}>
        <EditControl
          draw={{
            circle: true,
            rectangle: false,
            circlemarker: false,
            polygon: {allowIntersection: false},
            polyline: {allowIntersection: false}
          }}
        />
        <TileLayer
          noWrap={true}
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
    </MapContainer>
  );
}
export default App;
```

when I use `npm start` command I got following error:

```
./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;
```

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [ ] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [ ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ ] The issue has not already been reported.
- [ ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by PedroSouza157998** [comment]
Same here

**Comment by brienna** [comment]
Same problem.

**Comment by AbolfazlHeidarpour** [comment]
Thank you very mush brienna
