### ISSUE TITLE
Map displays mostly gray

### ISSUE THREAD

**Issue by tilnea** [PaulLeCam/react-leaflet#902]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Map not having a gray area

### Actual behavior

Map gets a gray area
![Screenshot 2021-07-14 at 10 52 34](https://user-images.githubusercontent.com/3692320/125593702-a256a761-1ea1-4499-9fa6-6ba89d21ccac.png)

### Steps to reproduce
just adding the steps here https://react-leaflet.js.org/docs/start-setup
and adding `style={{height: 90}}` to MapContainer

**Comment by Juliapp** [comment]
I've got the same issue, the map is mostly not rendering right. It looks like some random squared  map images all around the MapContainer. 
<img width="781" alt="rendering failing" src="https://user-images.githubusercontent.com/34479004/126372933-2b73fa17-71aa-49a2-924f-c6d6eecdf8c2.png">

**Comment by jezaman** [comment]
You have to call map.invalidateSize() after the map has completed rendering.
You would think this can easily be done in the whenCreated callback, but that seems to be called before the actual leaflet map finished loading.
I can't believe a widely downloaded package such as this doesn't have a clean solution for this. Using a setTimeout seems to be the only way to do it now... like seriously?

**Comment by thienhophu** [comment]
@jezaman Thanks.
