### ISSUE TITLE
Marker icon renders twice

### ISSUE THREAD

**Issue by alechko** [PaulLeCam/react-leaflet#903]
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Marker icon should only display once.

Please describe.

When using [this example](https://react-leaflet.js.org/docs/example-popup-marker) the marker icon should render once.

![image](https://user-images.githubusercontent.com/1391846/125742509-364890eb-9624-4af1-a5e8-b5dd6e6cef67.png)

### Actual behavior

Please describe.

Rendering a map component like this results in duplicate marker icon:
```
import React, { useEffect } from "react";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";

const position = [51.505, -0.09];
const position2 = [51.51, -0.095];

const Map = () => {
	useEffect(() => {
		console.log("render");
	}, []);
	return (
		<MapContainer center={position} zoom={13} scrollWheelZoom={false}>
			<TileLayer
				attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
				url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
			/>
			<Marker position={position}>
				<Popup>
					A pretty CSS3 popup. <br /> Easily customizable.
				</Popup>
			</Marker>
			<Marker position={position2}>
				<Popup>
					A pretty CSS3 popup. <br /> Easily customizable.
				</Popup>
			</Marker>
		</MapContainer>
	);
};
export default Map;

```
Added `useEffect` hook to make sure that we are rendering the component once:
 
![image](https://user-images.githubusercontent.com/1391846/125742145-30a47df2-ff93-4701-b2bb-acd9ec7d3676.png)

When inspecting the DOM:

![image](https://user-images.githubusercontent.com/1391846/125742258-33856c74-ce97-48ac-85d9-0260822a7c14.png)

### Steps to reproduce

package.json:

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@babel/preset-react": "^7.13.13",
        "autoprefixer": "^10.2.6",
        "axios": "^0.21",
        "bootstrap": "^4.6.0",
        "browser-sync": "^2.27.4",
        "browser-sync-webpack-plugin": "^2.3.0",
        "jquery": "^3.6",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "popper.js": "^1.16.1",
        "postcss": "^8.3.5",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.32.11",
        "sass-loader": "^11.0.1",
        "tailwindcss": "^2.2.4",
        "webpack-livereload-plugin": "1"
    },
    "dependencies": {
        "@tailwindcss/forms": "^0.3.3",
        "leaflet": "^1.7.1",
        "react-leaflet": "^3.2.0",
        "react-router-dom": "^5.2.0"
    }
}

```

webpack.mix.js:
```
const mix = require("laravel-mix");

mix
	.js("resources/js/app.js", "public/js")
	.react()
	// .sass('resources/sass/app.scss', 'public/css');
	.postCss("resources/css/app.css", "public/css", [require("tailwindcss")])
	.browserSync("friendly-laravel.ddev.site");
```

tailwind.config.js:
```
module.exports = {
  purge: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.vue',
  ],
  darkMode: 'media', // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}
```

**Comment by alechko** [comment]
Small followup, I've used a custom marker icon and the issue is not happening, seems to be only with the default icon:

![image](https://user-images.githubusercontent.com/1391846/125756311-6976feca-1516-4390-b022-06f48702b370.png)

**Comment by ShardanaSoft** [comment]
Hi

> Added useEffect hook to make sure that we are rendering the component once:

this mean that the code inside useEffect is called once, not that the component is rendered once.
Use console.log outside useEffect to see how many time component is rendered.

Check issue  #832, might be related.

**Comment by alechko** [comment]
hi @ShardanaSoft, thanks for the tip, I've moved console.log outside of the hook to make sure that everything renders once, but the issue is still there only for the default icon:

![image](https://user-images.githubusercontent.com/1391846/126024755-2c8a7a81-38ff-4fce-9893-7bc4554c8613.png)

I don't use the marker-cluster package and the tooltips work fine, it's just the weird default icon rendering...

**Comment by ShardanaSoft** [comment]
provide minimum working code, I can give a look. github, codesandbox, or, as suggested by repo owner,

> Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by alechko** [comment]
I've provided the code in the issue description, I had no success replicating this in a codepen sandbox.

I've created a codesandbox.io project: https://codesandbox.io/s/nameless-haze-1q68p?file=/src/App.js
For some reason the markers icons themselves are not loading there but you can see the multiple image placeholders.

**Comment by alechko** [comment]
I've replicated the issue and resolved it.

My problem was that I was importing local leaflet.css from the leaflet package like:

`https://unpkg.com/leaflet@1.7.1/dist/leaflet.css`

Once changed to importing the css globally from the html with the `<link>` tag the icons are rendering properly:

`<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""/>`

**Comment by ShardanaSoft** [comment]
> hi @ShardanaSoft, thanks for the tip, I've moved console.log outside of the hook to make sure that everything renders once, but the issue is still there only for the default icon:
> 
> ![image](https://user-images.githubusercontent.com/1391846/126024755-2c8a7a81-38ff-4fce-9893-7bc4554c8613.png)
> 
> I don't use the marker-cluster package and the tooltips work fine, it's just the weird default icon rendering...

Well done, did not notice the "clone" pin was stretched (css related for sure). 

happy code

**Comment by alechko** [comment]
just worth mentioning that besides this specific issue with the default icon there was no other things I've encountered in the maps rendering, so if anyone needs to use the local css provided with the `leaflet` package, make sure you replace the icon with a custom one, like:

```
import { Icon } from "leaflet";
...

<Marker
  position={position}
  icon={
	  new Icon({
		  iconUrl: 'imgurlhere',
		  iconSize: [42, 42],
	  })
  }
  >
  ...
```
