### ISSUE TITLE
Render array of the components twice does not render it

### ISSUE THREAD

**Issue by vsevolod-masterdelivery** [PaulLeCam/react-leaflet#904]
## Bug report

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Render array of any component (e.x. Marker) with uniq key twice with new link to array but same values does not render component.

### Actual behavior

Render array of any component (e.x. Marker) with uniq key twice with new link to array but same values render component.

### Steps to reproduce

using selectors(useSelector react-redux with shallowEqual) and fetch data for render component from server twice

**Comment by PaulLeCam** [comment]
Please provide a codepen to reproduce the issue without a third-party library.
