### ISSUE TITLE
onMoveEnd event removed in 3.0

### ISSUE THREAD

**Issue by vitalif** [PaulLeCam/react-leaflet#911]
Hi, is it true that react-leaflet 3.0 doesn't have map event handlers anymore? Like onMoveEnd.
What's the replacement for them?

**Comment by ulken** [comment]
> Hi, is it true that react-leaflet 3.0 doesn't have map event handlers anymore? Like onMoveEnd.

There's no prop like that on `<MapContainer>`, no.

> What's the replacement for them?

See [useMapEvent(s)](https://react-leaflet.js.org/docs/api-map/#usemapevents) and [Map Events](https://leafletjs.com/reference-1.7.1.html#map-event).

**Comment by vitalif** [comment]
I don't like hooks. I ended up with using MapConsumer and then manually setting an event handler via leaflet.

**Comment by ulken** [comment]
Whatever works for you. I just mentioned the official replacement.

You can quite easily wrap `MapContainer` and expose desired event handlers as props.

**Comment by ulken** [comment]
If you found an answer to your question, can this issue be closed?
