### ISSUE TITLE
React peerDependency excludes v16

### ISSUE THREAD

**Issue by MartinSoderholm** [PaulLeCam/react-leaflet#912]
At the moment the React peerDependency version is set to `^17.0.1`. My app uses `16.14`, and as I have the react-leaflet dependency in one of my workspaces, npm 7 auto-installs React 17 locally, resulting in the [Invalid Hook Call Warning](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) due to multiple instances of React. If I try to install it globally I of course get the npm “*unable to resolve dependency tree*” error.

AFAIK these is no reason to not include v16, as version 17 was [a “stepping stone” release](https://reactjs.org/blog/2020/08/10/react-v17-rc.html) with **“No New Features”**. All our other dependencies that require React all have inclusive versions so they work for both 16 and 17.

Thanks for your time and the work on this lib 👍

**Comment by PaulLeCam** [comment]
You can use React-Leaflet v2 if you use React v16, v3 is only tested for React v17.
