### ISSUE TITLE
URLs on react-leaflet.js.org need updated

### ISSUE THREAD

**Issue by dweisberg3** [PaulLeCam/react-leaflet#925]
The url to the docs page at leaftlet is now  leafletjs.com/reference.html . 

Previously was leafletjs.com/reference-1.7.1.html   . They took out "-1.7.1"  . The links should be updated on react-leaflet.js.org . Currently they are dead links.

**Comment by PaulLeCam** [comment]
Thanks for reporting this, should be fixed now!

**Comment by val089** [comment]
Hi PaulLeCam, Do you know when PR (**Set build target to es2015**) will be merged?
