### ISSUE TITLE
how can I expose some useful map methods?

### ISSUE THREAD

**Issue by cocodrino** [PaulLeCam/react-leaflet#93]
Hi, I've  a little problem, I need access to some methods: map.fitBounds, map. map.scrollWheelZoom.disable();
map.boxZoom.disable();
map.keyboard.disable();

maybe you could pass a callback function to map for call map methods

```js
const mapOptions = (map)=>{
  map.boxZoom.disable()
  map.scrollWheelZoom.disable()
}

<Map   zoom={11} style={{'min-height' : 250}}
           mapOptions={mapOptions}

>


```

not sure if it could be an option...

**Comment by gryzzly** [comment]
One way to get a reference to Leaflet map object is to `ref` the react-leaflet `Map` component and access its `leafletElement` property. You could make your own `Map` component that would be wrapping `react-leaflet`:
```js
import react from 'react';
import {Map} from 'react-leaflet';

export default react.createClass({
  displayName: 'Map',
  componentDidMount() {
    this.mapApi = this.refs.map.leafletElement; // <= this is the Leaflet Map object
  },
  fitBounds() {
    this.mapApi.fitBounds();// you can access Leaflet methods
  },
  render() {
    return <div>
      <Map ref="map" {...this.props} />
    </div>;
  }
});
```

**Comment by PaulLeCam** [comment]
Hi,
As answered by @gryzzly, you can access the `leafletElement` property or any created element after it is mounted.

In your case though, I think you could simply pass add these properties when creating the map, as they are passed to the `Leaflet.map()` factory. See [Leaflet's documentation for the available options](http://leafletjs.com/reference.html#map-options).

Ex in your case:
```js
<Map ... scrollWheelZoom={false} boxZoom={false} keyboard={false}>...
```

**Comment by cocodrino** [comment]
thanks @PaulLeCam  sorry for not answer before, this works nice...
