### ISSUE TITLE
Tooltip position glitch on first render

### ISSUE THREAD

**Issue by CiaccoDavide** [PaulLeCam/react-leaflet#931]
## Bug report

https://user-images.githubusercontent.com/3226096/143834847-1c53fd4b-e880-4994-9bd3-9bec1e76b8a9.mp4

### Expected behavior

The tooltip should not flash like that.
When the cursor hovers the marker the tooltip's position should not change once it becomes visible.

### Actual behavior

When the cursor hovers a marker for the first time, its tooltip's position glitches (you can see it in the video).
Subsequent hoverings aren't affected.
If the `sticky` parameter is set to `true` the tooltip renders just fine (its position doesn't flash and is correctly fixed to the cursor position), when the `sticky` parameter is set to `false` (default behaviour) this bug occurs.

### Steps to reproduce

Example on codepen: https://codepen.io/ciaccodavide/pen/ZEXzNGq

This bug can be reproduced also directly in the [tooltip's section of the React-Leaflet v3 documentation](https://react-leaflet.js.org/docs/example-tooltips/).

**Comment by PaulLeCam** [comment]
That's the expected behavior, the layout is updated once the content is rendered.
