### ISSUE TITLE
Popup does not open on iOS Chrome

### ISSUE THREAD

**Issue by kimifoud** [PaulLeCam/react-leaflet#932]
## Bug report

Popup markers do not open consistently in Chrome on iOS. The problem can be reproduced when browsing the official documentation  https://react-leaflet.js.org/docs/example-popup-marker/

### Expected behavior

Popups open consistently.

### Actual behavior

The popup flashes but does not open.

https://user-images.githubusercontent.com/1176169/144057998-3722e4c7-3788-45ac-8dee-6fbce85bf8f9.mov

### Steps to reproduce

The bug is not 100% consistent but can be easily reproduced with the minimal example.

1. Using Chrome on iOS, open https://react-leaflet.js.org/docs/example-popup-marker/
2. Click the marker.
3. The popup flashes but does not open.

**Comment by ntishkevich** [comment]
Faced with the same problem, that react-leaflet doesn't work on iOS Safari.
The script fails during the bootstrap with `SyntaxError` on the [line 21 of the file layer.ts](https://github.com/PaulLeCam/react-leaflet/blob/ae961ccf34162fd0badf2487f0e1aa55da856957/packages/core/src/layer.ts#L21).

**Comment by PaulLeCam** [comment]
This is a known issue in Leaflet: https://github.com/Leaflet/Leaflet/issues/7255
