### ISSUE TITLE
window is not defined 

### ISSUE THREAD

**Issue by marma4l** [PaulLeCam/react-leaflet#933]
### Expected behavior

Render map

### Actual behavior
**'window is not defined error'**

### Steps to reproduce
installed "react-leaflet": "^3.2.2",
"leaflet": "^1.7.1",
and then in code created this component..

import { Map, TileLayer } from 'react-leaflet';
function CBandMap() {

    return (
        <div className="App">
            <Map center={[0, 0]} zoom={4}>
                <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="&copy; <a href=&quot;https://www.openstreetmap.org/copyright&quot;>OpenStreetMap</a> contributors" />
            </Map>
        </div>
    );
}

export default CBandMap;

**Comment by chrislicodes** [comment]
I have the same issue with

"leaflet": "^1.7.1",
"next": "12.0.7",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-leaflet": "^3.2.2"

**Comment by Marc-Klein** [comment]
This is issue is not resolved, I got the same deps as @chrislicodes, and it doesn't work.
