### ISSUE TITLE
hi，I executed npm installe leaflet react-leaflet, and then executed npm start, I got this error. how to resolve it

### ISSUE THREAD

**Issue by CalvinP-Cai** [PaulLeCam/react-leaflet#937]
./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;

**Comment by CalvinP-Cai** [comment]
i see,  due to lower react version

**Comment by dmasters19** [comment]
https://stackoverflow.com/a/67574280

**Comment by CalvinP-Cai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
