### ISSUE TITLE
marker 点击事件会触发两次

### ISSUE THREAD

**Issue by CalvinP-Cai** [PaulLeCam/react-leaflet#938]
![image](https://user-images.githubusercontent.com/37281618/147814057-c89f121c-5bd3-467b-8932-51c90e712f15.png)
![image](https://user-images.githubusercontent.com/37281618/147814072-7e56b612-582f-4754-a20e-89afc3e1b5f8.png)

`{
          data.map(item => (
            <Marker 
              key={item.id}
              position={item.coordinates}
              icon={L.icon({
                iconUrl: item.icon,
                iconSize: [231 / 3,  78 / 3],
                iconAnchor: [0, 0],
            })}  
            eventHandlers={{
              click: () => {
                handleClickMarker(item)
              },
            }}
            >
            </Marker>
          ))
        }`

但我，在线上测试没复现
，本地测试却复现
https://codesandbox.io/s/serene-nightingale-u8npi?file=/src/App.js

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
