### ISSUE TITLE
Tooltips for Rectangles and Polygons are displaced on mount

### ISSUE THREAD

**Issue by ShreyasRP** [PaulLeCam/react-leaflet#940]
## Bug report

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior
![image](https://user-images.githubusercontent.com/34506519/148397291-fbc463c9-a0ae-425e-82fb-436c541cd3ae.png)

Tooltips for Rectangles and Polygons should be placed on the respective areas.

### Actual behavior
![image](https://user-images.githubusercontent.com/34506519/148397212-8e36fd1d-294e-43aa-98f0-98fa9449cb1b.png)

Tooltips for Rectangles and Polygons are placed far away from their actual areas. They are placed properly once the component is re-rendered (when the state or props changes).
They work perfectly fine for Circles though.

CodePen Link: https://codepen.io/srp888/pen/wvrELZr

I have attached the JS file below in case the above link does not work.
[example.txt](https://github.com/PaulLeCam/react-leaflet/files/7838626/example.txt)

**Comment by PaulLeCam** [comment]
Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by ShreyasRP** [comment]
I have updated my bug report to include the CodePen link: https://codepen.io/srp888/pen/wvrELZr

I have observed that this issue is present when the zoom value of MapContainer is a low value like 2. The Tooltip moves closer and closer to the Polygon/Rectangle as the zoom value is increased.

**Comment by PaulLeCam** [comment]
There is no specific logic about this in React Leaflet and the positions seem accurate when the zoom level is higher so I won't investigate this myself, but if you figure out the source of the issue is actually in React Leaflet (based on a working example using Leaflet directly) please feel free to open PR.
