### ISSUE TITLE
WMSTileLayer event handler does not works

### ISSUE THREAD

**Issue by md-amir** [PaulLeCam/react-leaflet#942]
<WMSTileLayer
                        layers={ 'banbeis:division' }
                        url={ `http://localhost:8080/geoserver/banbeis/wms` }
                        maxZoom={ 18 }
                        transparent={ true }
                        format='image/png'
                        opacity={ 0.5 }
                        eventHandlers={ {
                            click: () =>
                            {
                                console.log( 'layer clicked' ); <------------------------- does not work
                            },
                        } }
        
                    />

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
