### ISSUE TITLE
Question (not an issue) - Base Layers Grouping

### ISSUE THREAD

**Issue by rehovicova** [PaulLeCam/react-leaflet#944]
I am rewriting my coworkers code and he is using [this plugin](https://www.npmjs.com/package/leaflet.styledlayercontrol) to group base layers. Is it possible to achieve something like this with react-leaflet? For example:

```
<MapContainer ref={this.state.myRef} center={defaultLocation} zoom={MapConfig.zoom}>
        <LayersControl position="topright">
            <LayerGroup name="Online Maps">
                {layers}
            </LayerGroup>
            <LayerGroup name="WMS">
                {wmsLayers}
            </LayerGroup>
        </LayersControl>
</MapContainer>
```

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
