### ISSUE TITLE
Error code when rendering geojson layer

### ISSUE THREAD

**Issue by cubecleveland** [PaulLeCam/react-leaflet#949]
i have the follwing code:

const Layer = (props) => {
  const layerRef = React.createRef(null);

  const { setSelectedLayer } = useOverview();

  const [selected, setSelected] = React.useState();

  React.useEffect(() => {
    
  }, [layerRef]);

  return (
    <GeoJSON
      ref={layerRef}
      data={props.data}
      //key={currentSiteItems?.data?.data?.[0].geojson}
      eventHandlers={{
        click: (e) => {
          setSelectedLayer(e.layer);
        },
        mouseover: (e) => {
          d3.select(e.layer._path)
            .transition()
            .duration(500)
            .style("fill", "lightBlue")
            .style("stroke", "white");
        },
        mouseout: (e) => {
          d3.select(e.layer._path)
            .transition()
            .duration(500)
            .style("fill", e.layer.feature.properties.fillColor)
            .style("stroke", e.layer.feature.properties.stroke);
        },
      }}
      style={(feature) => {
        if (feature)
          return {
            //   fillColor: color || feature?.properties?.fillColor || "red",
            color: feature?.properties?.color || "orange",
            borderColor: feature?.properties?.borderColor || "red",
            fillOpacity: feature?.properties?.fillOpacity || 0.4,
            weight: feature?.properties?.weight || 1,
            fillColor: feature?.properties?.fillColor,
            dashArray: selected ? "5" : "1",
          };
      }}
      pointToLayer={function (feature, latlng) {
        {
          /* return L.marker(latlng, {
              icon: L.divIcon({
                iconSize: "auto",
                html: "<b>" + "aa" + "</b>",
              }),
            }); */
        }
        //do not return pointers
        return null;
      }}
    ></GeoJSON>

Im getting this error everytime the GeoJson is being rendered

![image](https://user-images.githubusercontent.com/51701990/150841448-3276daae-7161-4c39-93cb-6b80dc4b0afb.png)
 
i see no specific issue but any idea why this error is showing ?

**Comment by bastiion** [comment]
@cubecleveland Please do not use GitHub-Issues for support as mentioned in the https://github.com/PaulLeCam/react-leaflet#support

Ask the question on [StackOverflow](https://stackoverflow.com/) using the [`react-leaflet` tag](https://stackoverflow.com/questions/tagged/react-leaflet) and create a minimal example like https://codesandbox.io/s/geojson-sqtkl to show you're case.
