### ISSUE TITLE
Adding/removing polyline 

### ISSUE THREAD

**Issue by ayozebarrera** [PaulLeCam/react-leaflet#95]
Hi

I'm having some perfomance problems and it happens when I render a polyline in my map.
I noticed that when there isn't polyline, the .leaflet-overlay div is empty, and when I render a Polyline, it's append a svg of the line on this div.

BUT when I remove it. I saw that the svg is still there, translating when I move the map.. so.. shouldn't be that div empty?

Good job!

**Comment by PaulLeCam** [comment]
Hi,

Would you have a code example to reproduce the issue please?
Also, have you checked the behavior using Leaflet only (not this lib), as it may be the default Leaflet behavior and not something due to this lib?

**Comment by ayozebarrera** [comment]
I was thinking maybe its a Leaflet thing... but I haven't tried yet

About the code example.. you just have to add a polyline, remove it from the map and then check the div .leaflet-overlay. 
If there is a empty svg, that is what I'm talking about.

I'll try asap

**Comment by ayozebarrera** [comment]
Ok, Its a Leaflet thing. Sorry for the issue

**Comment by PaulLeCam** [comment]
No problem, I hope you sorted it out.
