### ISSUE TITLE
How to show only one country?

### ISSUE THREAD

**Issue by neysidev** [PaulLeCam/react-leaflet#951]
I want to show only one country and **delete the rest or hide**.

Someone has solved this problem but unfortunately it's not for React. Do you know how to turn this into a react code or how can I solve this problem in react-leaflet?

[LeafletJs only show one country](https://stackoverflow.com/questions/46643086/leafletjs-only-show-one-country)

_One such thing:_
![PantoHealth Map](https://i.ibb.co/t2ZvRv5/Group-1056.png)

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
