### ISSUE TITLE
Typescript definition for LeafletElement too strict

### ISSUE THREAD

**Issue by ksummerlin** [PaulLeCam/react-leaflet#953]
https://github.com/PaulLeCam/react-leaflet/blob/ca1e765ed3289cb2f79804f1fe61a972b17845dd/packages/core/src/element.ts#L5-L9

In the above definition, the context property is required. But the actual usage of `LeafletElement<Evented>` elsewhere -- say in the examples demonstrating `useEventHandlers` seem to indicate that `context` is optional as in the usage:

`useEventHandlers({ instance: parentMap } }, handlers)` from the [React Control](https://react-leaflet.js.org/docs/example-react-control/) example.

I believe this is the problem referenced in this [SO issue](https://stackoverflow.com/questions/70730390/property-context-is-missing-in-type-instance-any-but-required-in-type).

**Comment by PaulLeCam** [comment]
The type definition is correct, the context should always be provided for internal logic.
The example is for JS code and a specific case where the context is not needed.

**Comment by mauriciabad** [comment]
Hi, IMO this is not solved. **Either the type definition or the example is wrong.** That the code "is JS", is not a justification to ignore the type definitions. The examples should be impeccable, and having a lint error, makes it a bad example.
If some handlers need the context, just make it required for them, not all.
