### ISSUE TITLE
Sending an onClick event using renderToString method in bindPopup method

### ISSUE THREAD

**Issue by RinorJahaj** [PaulLeCam/react-leaflet#955]
Hi guys, I want to use a React FC as marker's popup, but to bind this popup, we should use renderToString to match its type requirements, doing so, onClick event of Popup component doesn't go through since renderToString returns plain HTML. Is there a way to make this happen? Thanks.

React version: 17.0.2

<img width="826" alt="image" src="https://user-images.githubusercontent.com/52374991/155098042-c49b4a9d-fb00-43a4-8966-7ed69382a4ec.png">

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
