### ISSUE TITLE
Error: window not defined

### ISSUE THREAD

**Issue by BraydenTW** [PaulLeCam/react-leaflet#956]
### Expected behavior

When using the starter example in my NextJS app from (https://react-leaflet.js.org/docs/example-popup-marker/), it should show up just fine.

### Actual behavior

It returns an error of:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/47185402/156280287-deff5e49-36dc-46bf-9514-5a46182f5a9f.png">

### Steps to reproduce

1. Create a new NextJS app
2. Follow the quickstart and install guide for `react-leaflet`.
3. Try this demo (https://react-leaflet.js.org/docs/example-popup-marker/)

**Comment by LeonidShatilo** [comment]
Hi, @BraydenTW! For Next.js you need to dynamically import a component with the Leaflet map in the `index.js` file.

`components/MapComponent/MapComponent.js`

```js
import React from 'react';
import { MapContainer, Marker, TileLayer, Popup } from 'react-leaflet';

const Map = () => (
  <MapContainer center={[51.505, -0.09]} zoom={13}>
    <TileLayer
      attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    />
    <Marker position={[51.505, -0.09]}>
      <Popup>
        A pretty CSS3 popup. <br /> Easily customizable.
      </Popup>
    </Marker>
  </MapContainer>
);

export default Map;
```

`components/MapComponent/index.js`

```js
import dynamic from 'next/dynamic';

const MapComponent = dynamic(() => import('./MapComponent'), {
  ssr: false,
});

export { MapComponent };
```

Now you can import the `MapComponent` wherever you want and avoid the error.

I hope this helps you!

**Comment by nikitakhutorni** [comment]
@LeonidShatilo I have the same issue. Did exactly what you recommended, but the problem remains.

**Comment by BraydenTW** [comment]
@LeonidShatilo, I did that and it removed the error, however I am getting this real messed up map.

https://www.loom.com/share/237be89a67c74f0fbea8f568fc184dff

(I am scrolling and zooming in and out on the map during the recording)

**Comment by ShyykoSerhiy** [comment]
@BraydenTW It seems like you might be missing css for the leaflet.
Create (if not yet created) `pages/_document.tsx` file and add

```tsx
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    return (
        <Html>
            <Head>
                <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
                    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
                    crossOrigin="" />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}
```

to it.

**Comment by BraydenTW** [comment]
@ShyykoSerhiy, thanks. I added it and it is still giving me the same issue.

```js
// Map.tsx
import dynamic from 'next/dynamic'
import MapComponent from './MapComponent'

const Map = dynamic(() => import('./MapComponent'), {
  ssr: false,
})

export default Map
```

```js
// MapComponent.tsx

**Comment by JoueBien** [comment]
This is what I'm doing to import the map and it's comps. Noting that you should do it at the library level and not the level of your own components (you'll have to do both if you are managing state externally - ie useMap in a context)
```
export const MapContainer = memo(
  dynamic<MapContainerProps>(() => import('react-leaflet').then((mod) => mod.MapContainer), { ssr: false }),
);
export const TileLayer = dynamic<TileLayerProps>(() => import('react-leaflet').then((mod) => mod.TileLayer), { ssr: false });
export const Polygon = dynamic<PolygonProps>(() => import('react-leaflet').then((mod) => mod.Polygon), { ssr: false });
export const Marker = dynamic<MarkerProps>(() => import('react-leaflet').then((mod) => mod.Marker), { ssr: false });
```

If you are dynamically swapping out layers, markers or polygons you need to wrap the map in memo because otherwise react will redraw the entire map every time a parent updates.

**Comment by Mubashir-rehma** [comment]
I am using react-leaflet in my nextjs project. The project works perfect on dev mode but when I try to build it it gives ReferenceError: window is not defined. I am also using ssr as false in dynamic but still gives the same error. Here is the code for further reference. any help would be highly appreciated. Thank you.

  Index.js

    `import dynamic from 'next/dynamic'

     export default dynamic(() => import("./map"), { ssr: false });

     // const  OpenStreetMap = dynamic(() => import('./map'), {
        //   ssr: false
     // })

     // const index = () => {
         //   return (
            //     <>
              //       <OpenStreetMap />
           //     </>
      //   )
     // }

     // export default index`


 map.js

     `import React, { useState, useRef, useEffect, useMemo } from 'react'
      import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet'
      import L from 'leaflet'
      import 'leaflet/dist/leaflet.css'

      const OpenStreetMap = () => {

         const [center, setCenter] = useState({ lat: 43.64701, lng: -79.39425 })
         const ZOOM_LEVEL = 5
         const mapRef = useRef()

          return (
             <MapContainer center={center} zoom={ZOOM_LEVEL} ref={mapRef} style={{ flex: 2, 
                 height: '100%', width: '100%' }}>
             

                <Marker  position={position} icon={icon}  eventHandlers={{ click: () => handleMarkerClick(marker) }} />
         </MapContainer>
       )
     }

    export default OpenStreetMap`


 Error

      `info  - Collecting page data ..ReferenceError: window is not defined
      at D:\logistics-crm\logistics-crm\node_modules\leaflet\dist\leaflet-src.js:230:19
      at D:\logistics-crm\logistics-crm\node_modules\leaflet\dist\leaflet-src.js:7:66
      at Object.<anonymous> (D:\logistics-crm\logistics-crm\node_modules\leaflet\dist\leaflet-src.js:10:3)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
      node:internal/process/promises:288
        triggerUncaughtException(err, true /* fromPromise */);
        ^

       ReferenceError: window is not defined
       at D:\logistics-crm\logistics-crm\node_modules\leaflet\dist\leaflet-src.js:230:19
       at D:\logistics-crm\logistics-crm\node_modules\leaflet\dist\leaflet-src.js:7:66
        at Object.<anonymous> (D:\logistics-crm\logistics-crm\node_modules\leaflet\dist\leaflet-src.js:10:3)
       at Module._compile (node:internal/modules/cjs/loader:1256:14)
       at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
       at Module.load (node:internal/modules/cjs/loader:1119:32)
       at Module._load (node:internal/modules/cjs/loader:960:12)
       at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
       > Build error occurred
       Error: Failed to collect page data for /apps/map/map
       at D:\logistics-crm\logistics- crm\node_modules\next\dist\build\utils.js:1152:15 {
       type: 'Error'
        }
        info  - Creating an optimized production build .info  - Collecting page data .`

**Comment by bdmostafa** [comment]
@Mubashir-rehma 
I answered your question here about how I solved today the same issue. Please take a look 
https://stackoverflow.com/questions/77658930/having-referenceerror-window-is-not-defined-error-for-react-leaflet-during-buil/77664865#77664865

**Comment by Jee-vim** [comment]
> [@Mubashir-rehma](https://github.com/Mubashir-rehma) I answered your question here about how I solved today the same issue. Please take a look https://stackoverflow.com/questions/77658930/having-referenceerror-window-is-not-defined-error-for-react-leaflet-during-buil/77664865#77664865

sadly im still facing the error, im using appDir
