### ISSUE TITLE
Support for right to left  ? 

### ISSUE THREAD

**Issue by doryanB** [PaulLeCam/react-leaflet#957]
Hi, 
would like to know if the right to left will be handled ? 
for instance, when i switch languages from a left to right lang  to right to left lang , all the tiles are miss positioned and the markers  go in the center of the map while zooming  out 
any tips for that ? 
thank you for your work anyway ! it's awesome

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
