### ISSUE TITLE
react-leaflet v3 custom controls

### ISSUE THREAD

**Issue by pcpatfire** [PaulLeCam/react-leaflet#960]
There are very good examples of how to create react-leaflet v3 custom constrols and wrappers using native leaflet function, but I could not find any example of how to create a custom control  from a regular react component, as for instance the following one:

```
const Sidebar = (props) {
  const [state, setState] = useState({
    collapsed: true,
    selected: 'home'
  })

  function onSidebarClose() {
    setState({collapsed: true})
   }
  
  function onSidebarOpen(id) {
    setState({
      collapsed: false,
      selected: id
    })
  
  return ( ... )
}
```
With the previous version of react-leaflet it was possible to use `MapComponent` as follows:

`class Sidebar extends MapComponent { ... }`

I think it would be very useful to give a simple example of how to replace MapComponent using the current version of react-leaflet.
Thanks a lot.

**Comment by PaulLeCam** [comment]
There is an example for using a React-based control on the [documentation website](https://react-leaflet.js.org/docs/example-react-control/).
