### ISSUE TITLE
Add support for React 18 Strict Effects

### ISSUE THREAD

**Issue by sarimarton** [PaulLeCam/react-leaflet#963]
## Bug report

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

In React 18 Strict Mode, it works as usual.

### Actual behavior

In React 18 Strict Mode, it throws an `Uncaught Error: Map container is already initialized.` The reason is that React 18 simulates an extra unmount+mount cycle when a component is first mounted to make sure it complies with complicated concurrency features. It's described at https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

### Steps to reproduce

The minimal example is sufficient to test, but change react's version to ^18.0.0 (currently react@rc and react-dom@rc), use the createRoot API with Strict Mode:

```tsx
createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    {/* ... */}
  <React.StrictMode>
)
```

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by sarimarton** [comment]
I've created a pull request with the fix: https://github.com/PaulLeCam/react-leaflet/pull/964

**Comment by PaulLeCam** [comment]
v3 doesn't support React concurrent mode, please use v4.

**Comment by sarimarton** [comment]
Can't use v4, because react-leaflet-markercluster doesn't work with that.
