### ISSUE TITLE
Marker image src corrupted

### ISSUE THREAD

**Issue by Req** [PaulLeCam/react-leaflet#967]
I can't find an existing issue for this. 

Brand new project. `<Marker>` renders `<img src="data:image/png;base64,iVBOR.--..K5CYII=&quot;)marker-icon-2x.png" ...>`

When I manually remove the ending part; `&quot;)marker-icon-2x.png` - the icon starts to work.

--- 
```
    "leaflet": "^1.7.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-leaflet": "^3.2.5",
    "react-scripts": "^5.0.0"
```

:yellow_heart: :blue_heart:

**Comment by AlexeyPogorelov** [comment]
The same for me.
🇺🇦

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.

**Comment by MysteryPancake** [comment]
@Req @AlexeyPogorelov I had the same issue, found a solution on #808:
```
import L from "leaflet";
import markerIcon from "leaflet/dist/images/marker-icon.png";
import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
import markerShadow from "leaflet/dist/images/marker-shadow.png";

delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
	iconUrl: markerIcon,
	iconRetinaUrl: markerIcon2x,
	shadowUrl: markerShadow,
});
```

**Comment by fasiha** [comment]
@PaulLeCam I wanted to thank you for your stewardship of this project and for all the labor that you've put into it. I am sure everyone using open-source is acutely aware of the problems of maintainer [burnout](https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/) and self-[entitled](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9) users. This project rocks.

**Comment by antoniocaporrini** [comment]
Hello everyone! Just to let you know, in my case i fixed by removing the .src suffix at the end of each property, thanks @MysteryPancake for the solution 👍 

```
'use client';

import L from 'leaflet';
import { MapContainer, Marker, TileLayer } from 'react-leaflet';

import 'leaflet/dist/leaflet.css';
import markerIcon2x from 'leaflet/dist/images/marker-icon-2x.png';
import markerIcon from 'leaflet/dist/images/marker-icon.png';
import markerShadow from 'leaflet/dist/images/marker-shadow.png';

// @ts-ignore
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconUrl: markerIcon, // .src removed
  iconRetinaUrl: markerIcon2x, // .src removed
  shadowUrl: markerShadow, // .src removed
});

```
