### ISSUE TITLE
React Leaflet with iOS 15.4

### ISSUE THREAD

**Issue by TurtIeSocks** [PaulLeCam/react-leaflet#968]
## Bug report

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [X] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

A user should be able to navigate the map without top layers/leaflet controls being hidden behind map tiles.

### Actual behavior

When panning and/or zooming around the map, if a marker goes on and off screen, sometimes additional divs or leaflet controls that are on top of the map tiles will disappear/flicker. Sometimes they come back, sometimes they're permanently stuck behind the map tiles until a refresh.

- I've experienced this with the built in zoom controls, the external ones, and Mui components that are layered on the map. 
- iOS/iPadOS 15.4 are the only problematic devices. 
- [Webkit Release Notes](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/)
- This only happens when using the Marker component.
- If all markers stay visible during the pan/zoom, it doesn't occur.

### Steps to reproduce

1. Open the map (example repo provided below)
2. Zoom in until at least some of the 10 markers are off screen
3. Pan/zoom around, the leaflet zoom controls will flicker and eventually disappear

### Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

This basic repo demonstrates the issue when opened with an iOS 15.4 device.
https://github.com/TurtIeSocks/React-Leaflet-Example

**Comment by carlo711** [comment]
I am having the same issue, ZoomControl and LayerControl are disappearing/flickering while dragging the map. Sometimes the reappear with further dragging.

**Comment by carlo711** [comment]
Issue with leaflet: https://github.com/Leaflet/Leaflet/issues/8068

**Comment by PaulLeCam** [comment]
If it's an upstream issue please track it there.
