### ISSUE TITLE
MapContainer doesnt support eventHandlers Prop and useMapEvents means having to define children just to pass state up the component tree.

### ISSUE THREAD

**Issue by laurencefass** [PaulLeCam/react-leaflet#972]
MapContainer children have a eventHandlersProp which allows callbacks to be defined at the same level as a rendered component.

The eventHandlers prop doesnt seem to work for the MapContainer object. Is that right?

I can access the MapContainer  events using the useMapEvents hook but I am having to define a <MapContainer> child component to do so which has no meaningful render. It also means that I have to pass map state back up the tree if i want to use it at the same level as the map.

e.g. 

```
function Subscriber( { setUsefulThings } ) {
   // useMapEvents only works in a child component of MapContainer
  // i need to pass data
    const map = useMapEvents({
        zoomend: function(e) {
            setUsefulThings(e.target.value.something);
        }
    })
    return <p>nothing to see here</p>
}

function SimpleExample(props) {
  return (
    <MapContainer 
      center={props.position} 
      zoom={13}
      // eventHandler props dont work on MapContainers only on children
      // eventHandlers={{
      //     zoomend : onZoomEnd,
      // }}
   > 
      <Subscriber/> // i had to create this to handle MapContainer events because 
  <MapContainer />

```

I can see the merits of useMapEvents but it adds complexity if I want to process events and map state at the same level as the <MapContainer/> object.

Would it be useful to add the eventHandler prop on the MapContainer component to allow events to be handled at the MapContainer level without having to pass items up from a child?

Thanks

**Comment by PaulLeCam** [comment]
This is intentional, if you set state from the map at the same level as the `MapContainer`, you'll re-render the map.
