### ISSUE TITLE
whenCreated event removed in v4

### ISSUE THREAD

**Issue by mariush2** [PaulLeCam/react-leaflet#974]
Hi!

Been using this library for a while and really enjoy using it. I recently, like many others, updated to React 18 and therefore also to the v4 beta version of react-leaflet. After updating I see that the MapContainer component doesn't have the `whenCreated` event anymore (which used to return the leaflet map).

Is there any other way for me to access the leaflet map that is connected with the MapContainer component?

**Comment by mariush2** [comment]
So after trying some more this morning I figured out that it is possible to use the ref property to achieve the same results as I wanted, was this the intention when removing the whenCreated prop from the MapContainer?

**Comment by PaulLeCam** [comment]
Yes exactly, providing a callback `ref` in v4 supports the use-case for which `whenCreated` exists in v3.

**Comment by mariush2** [comment]
Got it, thanks for the quick reply. Closing this as it's been resolved.

**Comment by bonesoul** [comment]
is there a quick example of achieving the same functionality of callback refs?

**Comment by ciruz** [comment]
Hey @bonesoul ,

my solution, I created an component used inside ``MapContainer`` for this:

```
      <MapContainer>
        <ZoomToMarker bounds={bounds} />
      </MapContainer>
```

Inside this child component from ``MapContainer`` you can use the ``useMap();`` Hook to fit the bounds.

**Comment by bonesoul** [comment]
can you show an example implementation of your component if possible?

**Comment by michielglibert** [comment]
For anyone who needs an example, this should work:

```tsx
  const handleMapCreated = (map: Map | null) => {
    if (map) {
      map.haveFun();
    }
  };
```

**Comment by vardhan03** [comment]
@mariush2, can you please let me know how to use the ref in v4 for the map graying out the issue as I mentioned here i.e. https://github.com/PaulLeCam/react-leaflet/issues/1074.

We fixed the map graying out issue on redrawing using the whenCreated event, as the now event is removed, I am in a bit confused about how to resolve this in the newer version.
@PaulLeCam

**Comment by mariush2** [comment]
@vardhan03 The comment from @michielglibert is the same as what I did.

**Comment by bloodykheeng** [comment]
use ref

ie
```
 //================== set current location ===============
  const [map, setMap] = useState<Map | null>(null); 

return ( <MapContainer
          ref={setMap} >)
```
