### ISSUE TITLE
GeoJSON props is missing className

### ISSUE THREAD

**Issue by JoueBien** [PaulLeCam/react-leaflet#975]
## Bug report
GeoJSON supports a class name but the type defs omit the className. 

To get this to work I have to specify a custom definition which I can assign because I'm dynamically importing in nextjs but that isn't going to work for everyone. 

```
interface GeoJSONPropsWithClassName extends GeoJSONProps {
  className?: string
}
```

- [ ./] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [./ ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [ ./] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [./ ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ ./] The issue has not already been reported.
- [ ./] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ ./] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior
I can assign a class name
```
<GeoJSON
    key={`slat-${slat?.id}`}
    className={'timeline-layer-slats'}
    data={slat?.mpoly as GeoJsonObject}
  />
```
and the def `GeoJSONProps` has a member ` className?: string`

### Actual behavior
Unable to use Class names when building in a react type script project
This is what VS code tells me:
```
(property) className: string
No overload matches this call.
  Overload 1 of 2, '(props: GeoJSONProps, context?: any): ReactElement<any, any> | Component<GeoJSONProps, any, any> | null', gave the following error.
    Type '{ key: string; className: string; data: GeoJsonObject; }' is not assignable to type 'IntrinsicAttributes & GeoJSONProps'.
      Property 'className' does not exist on type 'IntrinsicAttributes & GeoJSONProps'.
  Overload 2 of 2, '(props: PropsWithChildren<GeoJSONProps>, context?: any): ReactElement<any, any> | Component<GeoJSONProps, any, any> | null', gave the following error.
    Type '{ key: string; className: string; data: GeoJsonObject; }' is not assignable to type 'IntrinsicAttributes & GeoJSONProps & { children?: ReactNode; }'.
      Property 'className' does not exist on type 'IntrinsicAttributes & GeoJSONProps & { children?: ReactNode; }'.ts(2769)
```
### Steps to reproduce
Copy paste this into a react leflet map container in a TS react or nextjs TS project 
```
        <GeoJSON
          key={`slat`}
          className={'timeline-layer-slats'}
          data={[] as GeoJsonObject}
        />
```
With next you'll also need to dynamic import to resolve issues with the jank running in the import or window being called during SSR. 
```
export const GeoJSON = dynamic<GeoJSONProps>(() => import('react-leaflet').then((mod) => mod.GeoJSON as any), { ssr: false });
export const MapContainer = dynamic<MapContainerProps>(() => import('react-leaflet').then((mod) => mod.MapContainer), { ssr: false });

```

**Comment by PaulLeCam** [comment]
You need to use the `style` prop, not `className`, cf Leaflet's docs.
