### ISSUE TITLE
useMap not exposing additional functions added to leaflet map by a leaflet plugin and no ref.current to access the Leaflet object in 3.+

### ISSUE THREAD

**Issue by laurencefass** [PaulLeCam/react-leaflet#976]
Ive read some text somewhere saying you cant/wont support third party pluins but this issue isnt about a plugin more about how React-Leaflet exposes functionality added by plugins. I hope its relevant.

Im trying to use a plugin which adds rotate function to leaflet map but i cant access its functions and properties with react-leaflet 3 nor can i access the leaflet map directly as a ref as I could in previous versions. Im not sure if this is a specific issue for this plugin or a general one concerned with exposing plugin functions and properties through react-leaflet 3+. In version 2 i could access the leaflet object directly.

[Here is a sandbox](https://codesandbox.io/s/react-leaflet-forked-me1he5?file=/src/index.js) comparing a fully function rotatable pure HTML leaflet map and a react-leaflet map. The React Leaflet map does nothing more than expose the map object through useMap to demonstrate that the rotate functionality is not present which can be seen by inspection of the map object in the console window.

Specific question is: is there a way to access the modified leaflet object and expose the rotate functionality when using react-leaflet?

More general question: is there a best practice for exposing additional functionality to maps and child objects introduced by plugins?

Thanks

**Comment by JoueBien** [comment]
You should use `useMap`
if you need functionality externally (in components that are parents to the map) you need to set up a context.
You can access the instantiated leflet object from useMap with components that are children to the map container

```
export const MapControllerContext = createContext<MapControllerContextValues>({
  // State
  map: null,
   setMap: function (state) {},
})

export const _MapControllerProvider: React.FC<MapControllerProviderProps> = ({ 
  children, startCenterOn, missionSlug
}) => {
   const [map, setMap] = useAsyncSetState<Map | null>(null)
  return <MapControllerContext.Provider value={{
    // Values
    map, setMap,

  }}>
    {children}
  </MapControllerContext.Provider>
}


export const _MapInitController: React.FC<MapInitControllerProps> = (props) => {
  // Global State 
  const {
    setMap
  } = useContext(MapControllerContext)

  // On Mount
  useEffect(() => {
    setMap(map)
  }, [])
  return <></>
}

```
Then use it like so
```
<MapControllerProvider>
    {/* State avalible to children to manipulate */}
    <MapContainer>
       {/* you can use useMap in here in any children to the map*/}
        <MapInitController />
    </MapContainer>
</MapControllerProvider>
```

**Comment by laurencefass** [comment]
@JoueBien thanks for your input. useMap is not exposing the additional functions provided by the third party plugin so I dont think contexts will fix that. My question relates to whether/how react-leaflet can expose additional functionality which is avaiable on the leaflet object or whether it will only expose the base leaflet object.

**Comment by PaulLeCam** [comment]
There's nothing specific in React Leaflet about Leaflet plugins, it's up to your setup.
