### ISSUE TITLE
Popup changes position when moving the map

### ISSUE THREAD

**Issue by manudevcode** [PaulLeCam/react-leaflet#979]
### Expected behavior

When a popup is active, when navigating on the map it must maintain the position with its marker

### Actual behavior

If I activate a marker and move around the map the marker changes position away from its marker (as in the video)

### Steps to reproduce

Create a list of markers and generate them through a .map using the `CircleMarker` component inside the  `LayerGroup` component.
I can't reproduce the bug in the codepen because I use a rather large external dataset.

https://user-images.githubusercontent.com/11260098/162771058-3582cb9e-f254-431a-89c1-deecd88aea70.mov

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
