### ISSUE TITLE
MapControl

### ISSUE THREAD

**Issue by ayozebarrera** [PaulLeCam/react-leaflet#98]
I saw you have MapControl component at README and in master branch but I've updated the package and I don't see it

If this is ok, maybe you should put it on the documentation that will be available on future versions, and if not is ok.. you know :)

**Comment by PaulLeCam** [comment]
I use master as the main development branch so it matches more the next release than the current one, but I understand it might be confusing so I'll keep it matching the latest release instead.

**Comment by ayozebarrera** [comment]
Great, thanks
