### ISSUE TITLE
Issues with loading and viewing openstreetmap tiles of Basic Map Layer : Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by raphael10-collab** [PaulLeCam/react-leaflet#980]
As you can see from here: https://github.com/Leaflet/Leaflet/issues/8142
I reported an issue about loading and viewing `openstreetmap tiles` of `Basic Map Layer` on the `Leaflet` Github repo.
This is the answer received: https://github.com/Leaflet/Leaflet/issues/8142#issuecomment-1100304133

So, I'm here to ask help.

As I described in this `StackOverflow` questions :
- https://stackoverflow.com/questions/71861153/leaflet-suddenly-im-getting-this-error-message-failed-to-load-resource-the?noredirect=1#comment126988321_71861153

- https://stackoverflow.com/questions/71887095/issues-with-loading-and-viewing-openstreetmap-tiles-failed-to-load-resource-t

I'm experiencing issues with loading and viewing `openstreetmap tiles`  : 

`Failed to load resource: the server responded with a status of 403 ()`

Based on the info here : https://operations.osmfoundation.org/policies/tiles/ the following are the requirements for the `openstreetmap` tiles usage: 

    Requirements
    
        Heavy use (e.g. distributing an app that uses tiles from openstreetmap.org) is forbidden without prior permission from the [Operations Working Group](https://wiki.osmfoundation.org/wiki/Operations_Working_Group). See below for alternatives.
        Clearly display [license](https://wiki.openstreetmap.org/wiki/License) attribution.
        Do not actively or passively encourage copyright infringement.
        Calls to /cgi-bin/export may only be triggered by direct end-user action. (For example: “click here to export”.) The export call is an expensive (CPU+RAM) function to run and will frequently reject when server is under high load.
        Recommended: Do not hardcode any URL at tile.openstreetmap.org as doing so will limit your ability to react quickly if the service is disrupted or blocked.
        Recommended: add a link to https://www.openstreetmap.org/fixthemap to allow your users to report and fix problems in our data.
    
    Technical Usage Requirements
    
        Valid [HTTP User-Agent](http://en.wikipedia.org/wiki/en:User_agent) identifying application. Faking another app’s User-Agent WILL get you blocked.
        If known, a valid [HTTP Referer](http://en.wikipedia.org/wiki/en:HTTP_Referer).
        DO NOT send no-cache headers. (“Cache-Control: no-cache”, “Pragma: no-cache” etc.)
        Cache Tile downloads locally according to HTTP Expiry Header, alternatively a minimum of 7 days.
        Maximum of 2 download threads. (Unmodified web browsers’ download thread limits are acceptable.)
    
    Note: modern web browsers in standard configuration generally pass all the above technical requirements.

As far as I understand, I do respect all of them

Here you can find a `reproducible live test case`:  https://github.com/raphael10-collab/LeafletElectronPlaying

Steps to reproduce:

1) git clone https://github.com/raphael10-collab/LeafletElectronPlaying.git
2) cd LeafletElectronPlaying
3) yarn
4) in one screen: yarn type-check
5) in another screen: yarn start

An Electron Window will open 

What perplex me is that this happens only for the `Basic Map Layer`:

        <LayersControl position="topleft">
          <LayersControl.BaseLayer checked name="Basic Map">
            <TileLayer
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
          </LayersControl.BaseLayer>

![FailedToLoadResources](https://user-images.githubusercontent.com/70313067/163602118-4028cb84-284f-4c18-baf0-5d2b8f70433d.jpg)

![FailedToLoadResources2](https://user-images.githubusercontent.com/70313067/163677528-80439a06-7cc8-432f-905a-5176e583910c.jpg)

For example, it fails to load this tile:

https://b.tile.openstreetmap.org/13/4094/2723.png

![FailedToLoadResources3](https://user-images.githubusercontent.com/70313067/163678845-f224ceef-b87c-4dd8-8035-9e5c78342efa.jpg)

Error message: `Access Denied See: https://operations.osmfoundation.org/policies/tiles/ ` 

With the `Topo Map Layer` the visualization seems fine : 

          <LayersControl.BaseLayer name="Topo Map">
            <TileLayer
              attribution='Map data: &copy; <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
              url="https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"
            />
          </LayersControl.BaseLayer>

![FailedToLoadResourcesTopoMapLayer](https://user-images.githubusercontent.com/70313067/163602126-ef98a496-9ce1-49b2-8bc1-6d0ca8d6966e.jpg)

How to solve the issue?
Looking forward to your kind help

**Comment by PaulLeCam** [comment]
This is not an issue with this library but your setup with your tile provider, you should contact them if you think it's an issue on their end.
