### ISSUE TITLE
Marker move event arguments type are missing oldLatLng and latlng

### ISSUE THREAD

**Issue by zdila** [PaulLeCam/react-leaflet#981]
According to https://leafletjs.com/SlavaUkraini/reference.html#marker-move Marker's move event should contain `oldLatLng` and `latlng` properties but type defined in react-leaflet doesn't contain it. Note that also `drag` event contains these properties even that Leaflet 1.8 documentation doesn't mention it.

**Comment by PaulLeCam** [comment]
React Leaflet uses the types from `@types/leaflet`, if there's an issue with them please report it in the relevant project.
