### ISSUE TITLE
@react-leaflet/core_ module not found 

### ISSUE THREAD

**Issue by FredChauviere** [PaulLeCam/react-leaflet#983]
I got a weird one:
My original project worked fine with `leaflet@1.8.0`, `react-leaflet@3.2.5`, `react@17.0.2`, `react-dom@17.0.2`.

But as soon as I migrate to `react@18.0.0`, I got some _Module not found: Error: Can't resolve '@react-leaflet/core'_ errors, and I can see that I don't have a _@react-leaflet/core_ module defined in my _node_modules_ folder. 
I've tried several combinations of _react-leaflet_ and _react-dom_ versions, including of course `react-leaflet@4.0.0`, and `react-dom@18.0.0`, but I got that error as soon as I use `react@18.0.0`, that's the only constant.

Anybody else got a similar issue?

**Comment by PaulLeCam** [comment]
Please follow the issue template and make sure all the boxes are checked before posting an issue.
