### ISSUE TITLE
Having problem with react V-18

### ISSUE THREAD

**Issue by Enx-dev** [PaulLeCam/react-leaflet#985]
Please update peer dependency

**Comment by mildlyadequate** [comment]
> I'm having the same issue, here is a reproduction of the bug: https://codesandbox.io/s/solitary-meadow-cpntxn?file=/src/App.js

It turns out we just forgot to add something. You need to import the leaflet CSS file either globally or as a module where your map is like so:

` import 'leaflet/dist/leaflet.css'`

This fixed it for me

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
