### ISSUE TITLE
Tilt Feature

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [PaulLeCam/react-leaflet#988]
Is it possible to embed 3D Buildings?

Like: https://github.com/wrld3d/wrld.js

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
