### ISSUE TITLE
Side by side comparison

### ISSUE THREAD

**Issue by edsilv** [PaulLeCam/react-leaflet#989]
Hi,

I've been given a brief for a project that wants to use https://github.com/digidem/leaflet-side-by-side

I'd prefer to use react to implement this if possible, and was wondering if something like this might be achievable with react-leaflet?

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
