### ISSUE TITLE
Polyline zIndex

### ISSUE THREAD

**Issue by ayozebarrera** [PaulLeCam/react-leaflet#99]
Hi

I have 5 polylines in the map and I'm trying to change the zIndex of one. I tried to change the order that I render the lines, and adding zIndex prop to Polyline component but have no luck.

Also, searching in the repo, I only saw zIndex at Marker component..

So.. how can I change the order?

**Comment by PaulLeCam** [comment]
Hi,

`zIndex` is not a Path option handled by Leaflet: http://leafletjs.com/reference.html#path-options

Regarding your issue, you should check with Leaflet's documentation / tutorials, this lib does not do anything related to rendering, it just passes the properties to Leaflet.
