### ISSUE TITLE
Map does not render in a Next.js app on iOS 12

### ISSUE THREAD

**Issue by mattbbc** [PaulLeCam/react-leaflet#990]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

The map should render in a Next.js app running in Safari on an iOS 12 device.

### Actual behavior

The map does not render, unless testing on iOS 13+. When testing in iOS 12, very occasionally (in the actual production app we are building that I can't share) I see the following error printed directly to the DOM (not the console):

```
<p>Unexpected token '?'<br>eval@[native code]./node_modules/@react-leaflet/core/esm/pane.js@http://localhost:3000/_next/static/chunks/components_Map_index_tsx.js:172:5factory@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:640:35__webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:37:37eval codeeval@[native code]./node_modules/@react-leaflet/core/esm/div-overlay.js@http://localhost:3000/_next/static/chunks/components_Map_index_tsx.js:73:5factory@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:640:35__webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:37:37eval codeeval@[native code]./node_modules/@react-leaflet/core/esm/index.js@http://localhost:3000/_next/static/chunks/components_Map_index_tsx.js:139:5factory@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:640:35__webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:37:37eval codeeval@[native code]./node_modules/react-leaflet/esm/hooks.js@http://localhost:3000/_next/static/chunks/components_Map_index_tsx.js:793:5factory@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:640:35__webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:37:37eval codeeval@[native code]./node_modules/react-leaflet/esm/index.js@http://localhost:3000/_next/static/chunks/components_Map_index_tsx.js:804:5factory@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:640:35__webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:37:37eval codeeval@[native code]./components/Map/index.tsx@http://localhost:3000/_next/static/chunks/components_Map_index_tsx.js:355:5factory@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:640:35__webpack_require__@http://localhost:3000/_next/static/chunks/webpack.js?ts=1652108803590:37:37fn@[native code]promiseReactionJob@[native code]</p>
```

The map component in question is not server-side rendered. I have tried changing Next.js to using Babel instead of SWC but it makes no difference. We are building a substantial app that uses `react-leaflet` that will reach a wide audience and if possible we would like to support iOS 12 devices for our users that are elderly or otherwise unable to get a newer device.

### Steps to reproduce

[Clone this scaffolded Next.js app](https://github.com/mattbbc/maptest) that just has a map component in it. Run `npm install` and then `npm run dev` to start locally and view `localhost:3000` in an iOS simulator running iOS 12 and another on iOS 13.

![Screenshot 2022-05-13 at 18 00 58](https://user-images.githubusercontent.com/55093072/168333545-5e7fd8dd-7a0d-46a3-aefc-5ab114075b16.png)

**Comment by FranciscoKloganB** [comment]
Hello @mattbbc, I am not a maintainer, however `React-Leaflet` disclaims that it is not ready for SSR.

> https://react-leaflet.js.org/docs/start-introduction/#limitations

Therefore, my suggestion is to render your maps on the client-side. Here is a simple working example.

Maps page at `~/pages/maps`
```javascript
export default function Maps() {
  const Map = useMemo(
    () =>
      dynamic(() => import("~/components/map-providers/leaflet/Map"), {
        loading: () => <AppSpinner />,
        ssr: false
      }),
    []
  );

  return (
    <AppLayout>
      <div className="flex content-center justify-center">
        <Map />
      </div>
    </AppLayout>
  );
}
```

Map Component at `~/components/map-providers/leaflet/Map`
```javascript
import React from "react";
import {
  MapContainer as LeafletMapContainer,
  TileLayer,
  Popup,
  defaultTileLayer,
  attribution
} from "./config";
import "leaflet/dist/leaflet.css";
import PlacesAutocomplete from "./PlacesAutocomplete";
import LocationMarker from "./LocationMarker";
import { MapContainer } from "../styled";

export default function Map({
  children,
  lat = 38.70083420014407,
  lng = -9.30168323054906,
  zoom = 20,
  tileUrl = defaultTileLayer,
  withSearchControl = true
}) {
  const [position, setPosition] = React.useState({ lat, lng });

  function handleSelect(place) {
    setPosition(place.coordinates);
  }

  // https://react-leaflet.js.org/docs/api-map/
  // https://leafletjs.com/reference.html#map-l-map
  return (
    <MapContainer>
      {withSearchControl && <PlacesAutocomplete onSelect={handleSelect} />}
      <LeafletMapContainer
        // TODO: center can be an object of shape { lat: 51.505, lng: -2.09 }
        className="w-2/3 h-screen-2/3"
        center={position}
        scrollWheelZoom={false}
        zoom={zoom}
        zoomControl={false}
      >
        <TileLayer attribution={attribution} url={tileUrl} />
        <LocationMarker onLocationFound={setPosition} position={position}>
          {children && <Popup className="pb-5">{children}</Popup>}
        </LocationMarker>
      </LeafletMapContainer>
    </MapContainer>
  );
}
```

**Comment by rjackson** [comment]
I don't think this is a react-leaflet issue. Playing around with various local projects of mine, I am seeing a docusaurus project suffer the same issue, and also set up a [create-react-app recreation](https://github.com/rjackson/ios-12-map-test-cra).

Safari on iOS 12 seems unhappy that the built code includes ES6 features such as null coalescing (`??`) and optional chaining (`?.`) – which makes sense, as iOS 12 does not support ES6.

I _believe_ the fix would be to create a `.babelrc` and specify a custom `browserslist`. This does solve the problem on my create-react-app recreation (https://github.com/rjackson/ios-12-map-test-cra/commit/a5373a9c507dd3bc5ee0157c4a76c56de5dd14da), but I cannot figure out how to do the same with a Next.js project – I don't think my custom browserslist is ever being picked up by Next.js.

I'd suggest raising this issue with [vercel/next.js](https://github.com/vercel/next.js) for further guidance / investigation.

**Comment by mattbbc** [comment]
> Hello @mattbbc, I am not a maintainer, however `React-Leaflet` disclaims that it is not ready for SSR.

Thanks for your reply @FranciscoKloganB, but as I was saying in the report I'm not rendering the map with SSR, and the code repo I linked to does what you're suggesting already.

**Comment by mattbbc** [comment]
> I'd suggest raising this issue with [vercel/next.js](https://github.com/vercel/next.js) for further guidance / investigation.

It looks like I might have to do that ultimately - I'd hate to have to use Babel in Next.js and lose their most recent features though.

**Comment by ashley-christensen** [comment]
I ran into this issue on MacOS and solved it with the following: seems the docs are off a bit

-Adding INLINE styling to the MapContainer component Directly
-Adding an ACTUAL height to this Component [in pixels or otherwise]
-Importing the StyleSheet -- import "leaflet/dist/leaflet.css";

Others were having issues trying to add styling to the div, as per the documentation. This did not work for me until I tried:

< MapContainer
style={{ width: '100%', height: '600px' }}
center={position}
zoom={13} >

Hope this helps!

**Comment by PaulLeCam** [comment]
iOS 12 is not supported.

**Comment by yogithesymbian** [comment]
i have same issue . . 🔥 but on prouction only

**Comment by yogithesymbian** [comment]
> Hello @mattbbc, I am not a maintainer, however `React-Leaflet` disclaims that it is not ready for SSR.
> 
> > https://react-leaflet.js.org/docs/start-introduction/#limitations
> 
> Therefore, my suggestion is to render your maps on the client-side. Here is a simple working example.
> 
> Maps page at `~/pages/maps`
> 
> ```js
> export default function Maps() {
>   const Map = useMemo(
>     () =>
>       dynamic(() => import("~/components/map-providers/leaflet/Map"), {
>         loading: () => <AppSpinner />,
>         ssr: false
>       }),
>     []
>   );
> 
>   return (
>     <AppLayout>
>       <div className="flex content-center justify-center">
>         <Map />
>       </div>
>     </AppLayout>
>   );
> }
> ```
> 
> Map Component at `~/components/map-providers/leaflet/Map`
> 
> ```js
> import React from "react";
> import {
>   MapContainer as LeafletMapContainer,
>   TileLayer,
>   Popup,
>   defaultTileLayer,
>   attribution
> } from "./config";
> import "leaflet/dist/leaflet.css";
> import PlacesAutocomplete from "./PlacesAutocomplete";
> import LocationMarker from "./LocationMarker";
> import { MapContainer } from "../styled";
> 
> export default function Map({
>   children,
>   lat = 38.70083420014407,
>   lng = -9.30168323054906,
>   zoom = 20,
>   tileUrl = defaultTileLayer,
>   withSearchControl = true
> }) {
>   const [position, setPosition] = React.useState({ lat, lng });
> 
>   function handleSelect(place) {
>     setPosition(place.coordinates);
>   }
> 
>   return (
>     <MapContainer>
>       {withSearchControl && <PlacesAutocomplete onSelect={handleSelect} />}
>       <LeafletMapContainer
>         className="w-2/3 h-screen-2/3"
>         center={position}
>         scrollWheelZoom={false}
>         zoom={zoom}
>         zoomControl={false}
>       >
>         <TileLayer attribution={attribution} url={tileUrl} />
>         <LocationMarker onLocationFound={setPosition} position={position}>
>           {children && <Popup className="pb-5">{children}</Popup>}
>         </LocationMarker>
>       </LeafletMapContainer>
>     </MapContainer>
>   );
> }
> ```

sir ,, can you show file for `./config` ?
