### ISSUE TITLE
Ability to add Cloud Optimised Geotiff layers

### ISSUE THREAD

**Issue by staffordsmith83** [PaulLeCam/react-leaflet#992]
Is it possible to create a new custom component for react-leaflet to display COGs ?
Somehow using https://github.com/GeoTIFF/georaster-layer-for-leaflet?

With a few pointers in the right direction I would be happy to contribute!

**Comment by PaulLeCam** [comment]
You can use the Core package to create custom components, see https://react-leaflet.js.org/docs/core-introduction/

**Comment by staffordsmith83** [comment]
Great, thanks @PaulLeCam
