### ISSUE TITLE
Module '"react-leaflet"' has no exported member 'withLeaflet'

### ISSUE THREAD

**Issue by omateusamaral** [PaulLeCam/react-leaflet#993]
Hi I'm trying to import withLeaflet from react-leaflet but not exists. I'm using the version: "react-leaflet": "^3.2.5". any sugestion/help to solve this?

**Comment by FranciscoKloganB** [comment]
`withLeaflet` is used to be a High Order Component, to use with class-based React. Two things to take note of:

1. `react-leaflet` v3 is no longer maintained. See [here](https://react-leaflet.js.org/docs/v3/start-setup/)
2. If you absolutely need to use v3, then, High Order Components are no longer available. Use their hooks instead!
   a. I believe [useMap](https://react-leaflet.js.org/docs/api-map/#usemap) is the hook you are looking for.

**Comment by omateusamaral** [comment]
yeah I founded this: https://github.com/PaulLeCam/react-leaflet/issues/862#issuecomment-846603024 and was what I needed just some adjustment to my component.

**Comment by Medmly20208** [comment]
Hi @FranciscoKloganB, I am using react-leaflet@4.2.1 but I still got this error 
```
The requested module '/node_modules/.vite/deps/react-leaflet.js?v=d7daadaf' does not provide an export named 'withLeaflet'
```
