### ISSUE TITLE
ImageOverlay updating bounds in realtime

### ISSUE THREAD

**Issue by johnfrades** [PaulLeCam/react-leaflet#995]
Hello, just want to ask, currently i have an <ImageOverlay>

`<ImageOverlay className="object-fit-cover" url={props.image} bounds={props.availableBounds} />`

as you can see, the bounds is based on the `props.availableBounds` now this value will be updated in realtime, what happens is, the map will instantiate, then the image will be placed on the map, but everytime i update the value of `availableBounds`, the ImageOverlay is not moving.
The hack that i did was, to reinstantiate the MapContainer for me to be able to see the updated ImageOverlay bounds.

Is there a way to update the ImageOverlay bounds freely? without reinstantiating the MapContainer? Thanks!

**Comment by PaulLeCam** [comment]
Hi,
Please only use GitHub issues to report possible bugs in the library.
You can use [the `react-leaflet` tag in StackOverflow](https://stackoverflow.com/questions/tagged/react-leaflet) for questions related to using it.
