### ISSUE TITLE
MapContainer does not work correctly without a center point 

### ISSUE THREAD

**Issue by SalahAdDin** [PaulLeCam/react-leaflet#999]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [X] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [X] Using the latest version of React and ReactDOM v18.
- [X] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [X] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [X] The issue has not already been reported.
- [X] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [X] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior
Looking at **MapContainer** properties' types we check `center` to be optional, so, if we don't put a center to the map, 
it should a show a random location.

### Actual behavior
The map is totally gray, not showing anything.
<img width="1728" alt="Screen Shot 2022-06-19 at 16 49 51" src="https://user-images.githubusercontent.com/5034215/174484377-c3e06281-83e9-49dc-9b12-4bddc4b1d5ae.png">

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/OJxEbBW).

Just remove the center from the map.

What's the problem?

Thank you

**Comment by PaulLeCam** [comment]
This is the expected behavior.

**Comment by SalahAdDin** [comment]
> This is the expected behavior.

If it is the expected behavior, why is center an optional property?

**Comment by PaulLeCam** [comment]
Because you can set `bounds` instead.

**Comment by SalahAdDin** [comment]
> Because you can set `bounds` instead.

Unfortunately, I could not find anything about it on the **react-leaflet** documentation. That's why I thought it was a bug.

**Comment by sahin52** [comment]
Giving an error indicating that problem could be a nice approach
